// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

// Bench targets are not public API: `criterion_group!` expands to a `pub fn`,
// which would otherwise trip the workspace `missing_docs` lint.
#![allow(missing_docs)]

//! Profiling harness for index construction and ranked retrieval.
//!
//! Wall-clock samples from a shared development host are not acceptance
//! evidence, and nothing here asserts one. The crate's test suite is what fixes
//! behaviour: scores are exact fixed-point values compared against literal
//! `xsd:decimal` strings, and the bounded-heap path is proved to agree with the
//! full sort row for row across a spread of ceilings. This target exists to
//! collect allocation and profile data on a controlled host, and it measures
//! rather than concludes.
//!
//! Six paths are covered, because they have genuinely different shapes:
//!
//! * building the index, which analyzes every literal and sorts the dictionary;
//! * a ranked search with **no** ceiling, which scores every candidate and sorts
//!   the whole candidate list;
//! * the same search **with** a ceiling, which routes the same candidates
//!   through a binary heap bounded at the ceiling instead of sorting the tail;
//! * a term-occurrence lookup, which is a dictionary binary search plus a
//!   partition-span slice and touches no arithmetic at all;
//! * and the two halves of the **bound-document** path over a multi-partition
//!   corpus — one ranking every partition and one ranking only the partitions
//!   the bound subject appears in.
//!
//! # Why the last pair exists
//!
//! The evaluator drives a property function once per left row, so a pattern that
//! binds the document position opens the relation once for every candidate
//! document. A bound document is filtered *after* ranking, so no ceiling is
//! offered to the ranker on that path (see `TextSearchRelation::open`) — which
//! left every one of those invocations ranking the whole index and then
//! discarding all but one row's worth of it.
//!
//! `search_bound_doc_every_partition` is that shape and
//! `search_bound_doc_pushed_down` is the shape after
//! `TextIndex::partitions_holding_subject` narrows the filter to the partitions
//! the subject actually occupies. Both are measured here rather than argued
//! about, and neither asserts a number: the reduction is a complexity claim —
//! `O(all partitions)` becomes `O(that subject's partitions)` — and it is the
//! test suite, not this file, that proves the two produce the same rows.
//!
//! # The corpus is generated, not sampled
//!
//! Every document is produced by [`SplitMix64`] from one fixed seed, so the
//! corpus is a pure function of the constants below: the same documents, the
//! same dictionary, the same document frequencies on every run, every host and
//! every target. No random-number crate and no clock is consulted, which is the
//! same rule the crate itself follows — a benchmark whose corpus drifted between
//! runs would be reporting the corpus rather than the code.
//!
//! Term choice is deliberately skewed. Each token takes the smallest of several
//! draws over the vocabulary, so low-numbered terms appear in many documents and
//! high-numbered ones in few. A uniform corpus would give every term nearly the
//! same document frequency, which would make every inverse document frequency
//! nearly equal and every candidate list nearly the same length — the retrieval
//! shape that stresses the ranker least.

use std::sync::Arc;

use criterion::{Criterion, Throughput, black_box, criterion_group, criterion_main};
use purrdf_core::{RdfDataset, RdfDatasetBuilder, RdfLiteral, TermValue};
use purrdf_text::{
    Analyzer, GraphSelector, PartitionFilter, PartitionKey, TextIndex, TextIndexConfig, select,
};

/// The one predicate the corpus hangs its text off.
const NOTE: &str = "https://example.org/note";
/// How many documents the corpus holds.
const DOCUMENTS: u32 = 4096;
/// How many tokens each document holds.
const TOKENS_PER_DOCUMENT: u32 = 32;
/// How many distinct terms the generator draws from.
const VOCABULARY: u64 = 1024;
/// How many uniform draws each token takes the smallest of. Sets the skew.
const DRAWS: u32 = 4;
/// The generator's seed. Fixed, so the corpus is reproducible.
const SEED: u64 = 0x5EED_0000_1234_ABCD;
/// The ceiling the bounded-heap measurement uses.
const CEILING: u64 = 10;

/// SplitMix64 — a deterministic integer generator, seeded once.
///
/// Chosen because it is four lines of `wrapping_*` arithmetic with no state
/// beyond a `u64`, so the corpus can be regenerated by hand from the constants
/// above rather than depending on a crate whose stream could change between
/// versions.
struct SplitMix64 {
    /// The generator's running state.
    state: u64,
}

impl SplitMix64 {
    /// A generator seeded at `seed`.
    const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// The next value in the stream.
    fn next_value(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut word = self.state;
        word = (word ^ (word >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        word = (word ^ (word >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        word ^ (word >> 31)
    }

    /// A vocabulary ordinal, skewed toward the low end.
    ///
    /// The smallest of [`DRAWS`] uniform draws. That makes the probability of
    /// ordinal `k` proportional to `(VOCABULARY - k)` cubed, so a term's document
    /// frequency falls off steeply across the vocabulary instead of being flat:
    /// `term0000` lands in a large fraction of the corpus and `term0800` in a
    /// handful of documents.
    fn skewed_term(&mut self) -> u64 {
        let mut smallest = VOCABULARY;
        for _ in 0..DRAWS {
            smallest = smallest.min(self.next_value() % VOCABULARY);
        }
        smallest
    }
}

/// The generated corpus, as one frozen dataset.
///
/// Every literal is untagged and in the default graph, so the index holds a
/// single `(graph, language)` partition and a ceiling therefore bounds one
/// heap rather than being split across several.
fn corpus() -> Arc<RdfDataset> {
    let mut generator = SplitMix64::new(SEED);
    let mut builder = RdfDatasetBuilder::new();
    let note = builder.intern_iri(NOTE);

    let mut text = String::new();
    for document in 0..DOCUMENTS {
        text.clear();
        for token in 0..TOKENS_PER_DOCUMENT {
            if token > 0 {
                text.push(' ');
            }
            text.push_str("term");
            // Fixed width, so the dictionary's sorted order is its numeric order
            // and the generated text is trivially readable in a profile.
            let ordinal = generator.skewed_term();
            for digit in (0..4).rev() {
                let place = 10_u64.pow(digit);
                let value = (ordinal / place) % 10;
                text.push(char::from(
                    b'0' + u8::try_from(value).expect("a digit is one byte"),
                ));
            }
        }
        let subject = builder.intern_iri(&format!("https://example.org/doc/{document:04}"));
        let literal = builder.intern_literal(RdfLiteral::simple(&text));
        builder.push_quad(subject, note, literal, None);
    }

    builder
        .freeze()
        .expect("the generated corpus must validate")
}

/// The language tags the multi-partition corpus spreads its documents across.
///
/// Eight, so the bound-document measurement has a meaningful ratio to report:
/// ranking every partition touches eight corpora where ranking the bound
/// subject's touches one.
const LANGUAGES: [&str; 8] = ["en", "fr", "de", "es", "it", "nl", "pt", "sv"];

/// The same generated text as [`corpus`], but with each document's literal
/// language-tagged so the index holds one partition per [`LANGUAGES`] entry.
///
/// The generator is re-seeded identically, so the two corpora hold the same
/// text and differ only in partitioning — which is what makes the bound-document
/// pair below a measurement of the partition walk rather than of two different
/// bodies of text.
fn partitioned_corpus() -> Arc<RdfDataset> {
    let mut generator = SplitMix64::new(SEED);
    let mut builder = RdfDatasetBuilder::new();
    let note = builder.intern_iri(NOTE);

    let mut text = String::new();
    for document in 0..DOCUMENTS {
        text.clear();
        for token in 0..TOKENS_PER_DOCUMENT {
            if token > 0 {
                text.push(' ');
            }
            text.push_str("term");
            let ordinal = generator.skewed_term();
            for digit in (0..4).rev() {
                let place = 10_u64.pow(digit);
                let value = (ordinal / place) % 10;
                text.push(char::from(
                    b'0' + u8::try_from(value).expect("a digit is one byte"),
                ));
            }
        }
        let subject = builder.intern_iri(&format!("https://example.org/doc/{document:04}"));
        let language = LANGUAGES[document as usize % LANGUAGES.len()];
        let literal = builder.intern_literal(RdfLiteral::language_tagged(&text, language));
        builder.push_quad(subject, note, literal, None);
    }

    builder
        .freeze()
        .expect("the generated corpus must validate")
}

/// The configuration every measurement here builds under.
fn configuration() -> TextIndexConfig {
    TextIndexConfig::new(vec![TermValue::iri(NOTE)], GraphSelector::Any)
        .expect("one IRI predicate is a well-formed configuration")
}

/// The analyzed needle for `text`, exactly as a query would supply it.
fn needle(text: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    Analyzer::new().analyze(text, &mut tokens);
    tokens
        .into_iter()
        .map(|token| token.text.into_owned())
        .collect()
}

fn benchmark(criterion: &mut Criterion) {
    let dataset = corpus();
    let config = configuration();
    let index = TextIndex::from_dataset(&*dataset, &config).expect("the corpus index must build");

    // A common term, a middling one and a rare one, so the three candidate lists
    // the ranker unions differ in length by orders of magnitude and the three
    // inverse document frequencies are genuinely far apart.
    let query = needle("term0000 term0512 term0800");
    let partition = PartitionKey::new(None, None);
    let filter = PartitionFilter::unconstrained();

    let mut group = criterion.benchmark_group("purrdf_text");
    group.throughput(Throughput::Elements(u64::from(DOCUMENTS)));

    group.bench_function("build_index", |bencher| {
        bencher.iter(|| {
            TextIndex::from_dataset(black_box(&*dataset), black_box(&config))
                .expect("the corpus index must build")
        });
    });

    group.bench_function("search_unbounded", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&index),
                black_box(&query),
                black_box(&filter),
                None,
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.bench_function("search_ceiling_10", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&index),
                black_box(&query),
                black_box(&filter),
                Some(CEILING),
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.bench_function("term_occurrences", |bencher| {
        bencher.iter(|| {
            index
                .postings(black_box(&partition), black_box("term0000"))
                .map(|(document, positions)| u64::from(document) + positions.len() as u64)
                .sum::<u64>()
        });
    });

    // ── the bound-document pair ─────────────────────────────────────────────
    //
    // One index, one needle, one bound subject; the only difference is whether
    // the filter names the partitions that subject occupies.
    let spread = partitioned_corpus();
    let spread_index =
        TextIndex::from_dataset(&*spread, &config).expect("the partitioned corpus must build");
    let subject = TermValue::iri("https://example.org/doc/0007");
    let narrowed = PartitionFilter::unconstrained()
        .restricted_to(spread_index.partitions_holding_subject(&subject));
    assert_eq!(
        narrowed.keys().map(<[_]>::len),
        Some(1),
        "the bound subject must occupy exactly one of the corpus's partitions, or the pair below \
         measures nothing"
    );

    group.bench_function("search_bound_doc_every_partition", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&spread_index),
                black_box(&query),
                black_box(&filter),
                None,
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.bench_function("search_bound_doc_pushed_down", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&spread_index),
                black_box(&query),
                black_box(&narrowed),
                None,
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.finish();
}

criterion_group!(benches, benchmark);
criterion_main!(benches);
