// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

// Bench targets are not public API: `criterion_group!` expands to a `pub fn`,
// which would otherwise trip the workspace `missing_docs` lint.
#![allow(missing_docs)]

//! Profiling harness for index construction and ranked retrieval.
//!
//! Wall-clock samples from a shared development host are not acceptance
//! evidence, and nothing here asserts one. The crate's test suite is what fixes
//! behaviour: scores are exact fixed-point values compared against literal
//! `xsd:decimal` strings, and the bounded-heap path is proved to agree with the
//! full sort row for row across a spread of ceilings. This target exists to
//! collect allocation and profile data on a controlled host, and it measures
//! rather than concludes.
//!
//! Four paths are covered, because they have genuinely different shapes:
//!
//! * building the index, which analyzes every literal and sorts the dictionary;
//! * a ranked search with **no** ceiling, which scores every candidate and sorts
//!   the whole candidate list;
//! * the same search **with** a ceiling, which routes the same candidates
//!   through a binary heap bounded at the ceiling instead of sorting the tail;
//! * a term-occurrence lookup, which is a dictionary binary search plus a
//!   partition-span slice and touches no arithmetic at all.
//!
//! # The corpus is generated, not sampled
//!
//! Every document is produced by [`SplitMix64`] from one fixed seed, so the
//! corpus is a pure function of the constants below: the same documents, the
//! same dictionary, the same document frequencies on every run, every host and
//! every target. No random-number crate and no clock is consulted, which is the
//! same rule the crate itself follows — a benchmark whose corpus drifted between
//! runs would be reporting the corpus rather than the code.
//!
//! Term choice is deliberately skewed. Each token takes the smallest of several
//! draws over the vocabulary, so low-numbered terms appear in many documents and
//! high-numbered ones in few. A uniform corpus would give every term nearly the
//! same document frequency, which would make every inverse document frequency
//! nearly equal and every candidate list nearly the same length — the retrieval
//! shape that stresses the ranker least.

use std::sync::Arc;

use criterion::{Criterion, Throughput, black_box, criterion_group, criterion_main};
use purrdf_core::{RdfDataset, RdfDatasetBuilder, RdfLiteral, TermValue};
use purrdf_text::{
    Analyzer, GraphSelector, PartitionFilter, PartitionKey, TextIndex, TextIndexConfig, select,
};

/// The one predicate the corpus hangs its text off.
const NOTE: &str = "https://example.org/note";
/// How many documents the corpus holds.
const DOCUMENTS: u32 = 4096;
/// How many tokens each document holds.
const TOKENS_PER_DOCUMENT: u32 = 32;
/// How many distinct terms the generator draws from.
const VOCABULARY: u64 = 1024;
/// How many uniform draws each token takes the smallest of. Sets the skew.
const DRAWS: u32 = 4;
/// The generator's seed. Fixed, so the corpus is reproducible.
const SEED: u64 = 0x5EED_0000_1234_ABCD;
/// The ceiling the bounded-heap measurement uses.
const CEILING: u64 = 10;

/// SplitMix64 — a deterministic integer generator, seeded once.
///
/// Chosen because it is four lines of `wrapping_*` arithmetic with no state
/// beyond a `u64`, so the corpus can be regenerated by hand from the constants
/// above rather than depending on a crate whose stream could change between
/// versions.
struct SplitMix64 {
    /// The generator's running state.
    state: u64,
}

impl SplitMix64 {
    /// A generator seeded at `seed`.
    const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// The next value in the stream.
    fn next_value(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut word = self.state;
        word = (word ^ (word >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        word = (word ^ (word >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        word ^ (word >> 31)
    }

    /// A vocabulary ordinal, skewed toward the low end.
    ///
    /// The smallest of [`DRAWS`] uniform draws. That makes the probability of
    /// ordinal `k` proportional to `(VOCABULARY - k)` cubed, so a term's document
    /// frequency falls off steeply across the vocabulary instead of being flat:
    /// `term0000` lands in a large fraction of the corpus and `term0800` in a
    /// handful of documents.
    fn skewed_term(&mut self) -> u64 {
        let mut smallest = VOCABULARY;
        for _ in 0..DRAWS {
            smallest = smallest.min(self.next_value() % VOCABULARY);
        }
        smallest
    }
}

/// The generated corpus, as one frozen dataset.
///
/// Every literal is untagged and in the default graph, so the index holds a
/// single `(graph, language)` partition and a ceiling therefore bounds one
/// heap rather than being split across several.
fn corpus() -> Arc<RdfDataset> {
    let mut generator = SplitMix64::new(SEED);
    let mut builder = RdfDatasetBuilder::new();
    let note = builder.intern_iri(NOTE);

    let mut text = String::new();
    for document in 0..DOCUMENTS {
        text.clear();
        for token in 0..TOKENS_PER_DOCUMENT {
            if token > 0 {
                text.push(' ');
            }
            text.push_str("term");
            // Fixed width, so the dictionary's sorted order is its numeric order
            // and the generated text is trivially readable in a profile.
            let ordinal = generator.skewed_term();
            for digit in (0..4).rev() {
                let place = 10_u64.pow(digit);
                let value = (ordinal / place) % 10;
                text.push(char::from(
                    b'0' + u8::try_from(value).expect("a digit is one byte"),
                ));
            }
        }
        let subject = builder.intern_iri(&format!("https://example.org/doc/{document:04}"));
        let literal = builder.intern_literal(RdfLiteral::simple(&text));
        builder.push_quad(subject, note, literal, None);
    }

    builder
        .freeze()
        .expect("the generated corpus must validate")
}

/// The configuration every measurement here builds under.
fn configuration() -> TextIndexConfig {
    TextIndexConfig::new(vec![TermValue::iri(NOTE)], GraphSelector::Any)
        .expect("one IRI predicate is a well-formed configuration")
}

/// The analyzed needle for `text`, exactly as a query would supply it.
fn needle(text: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    Analyzer::new().analyze(text, &mut tokens);
    tokens
        .into_iter()
        .map(|token| token.text.into_owned())
        .collect()
}

fn benchmark(criterion: &mut Criterion) {
    let dataset = corpus();
    let config = configuration();
    let index = TextIndex::from_dataset(&*dataset, &config).expect("the corpus index must build");

    // A common term, a middling one and a rare one, so the three candidate lists
    // the ranker unions differ in length by orders of magnitude and the three
    // inverse document frequencies are genuinely far apart.
    let query = needle("term0000 term0512 term0800");
    let partition = PartitionKey::new(None, None);
    let filter = PartitionFilter::unconstrained();

    let mut group = criterion.benchmark_group("purrdf_text");
    group.throughput(Throughput::Elements(u64::from(DOCUMENTS)));

    group.bench_function("build_index", |bencher| {
        bencher.iter(|| {
            TextIndex::from_dataset(black_box(&*dataset), black_box(&config))
                .expect("the corpus index must build")
        });
    });

    group.bench_function("search_unbounded", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&index),
                black_box(&query),
                black_box(&filter),
                None,
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.bench_function("search_ceiling_10", |bencher| {
        bencher.iter(|| {
            select(
                black_box(&index),
                black_box(&query),
                black_box(&filter),
                Some(CEILING),
                None,
            )
            .expect("a well-formed needle ranks")
        });
    });

    group.bench_function("term_occurrences", |bencher| {
        bencher.iter(|| {
            index
                .postings(black_box(&partition), black_box("term0000"))
                .map(|(document, positions)| u64::from(document) + positions.len() as u64)
                .sum::<u64>()
        });
    });

    group.finish();
}

criterion_group!(benches, benchmark);
criterion_main!(benches);
