// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

// Bench targets are not public API: `criterion_group!` expands to a `pub fn`,
// which would otherwise trip the workspace `missing_docs` lint.
#![allow(missing_docs)]

//! Profiling harness for the two costs a geometry predicate actually has.
//!
//! **Report-only, and never a gate.** Wall-clock samples from a shared
//! development host are not acceptance evidence, and nothing here asserts a
//! timing. Behaviour is fixed by the test suite; this file exists so that a
//! change to the exact-arithmetic core or to the noder can be *measured* rather
//! than argued about.
//!
//! Three paths, with three different shapes:
//!
//! * **Coordinate ingest.** Every row that reaches a `geof:` call parses a
//!   geometry literal first, and this crate parses coordinates into exact
//!   rationals rather than into floats. That is the price of determinism, and it
//!   is the one cost paid per row regardless of what the predicate then does.
//! * **Exact arithmetic.** The rational add/multiply/compare underneath every
//!   orientation test. Linear in the operand limb count, which is why the
//!   fixture sweeps coordinate precision rather than only coordinate count.
//! * **The relate itself.** The noder is quadratic in the segment count, so the
//!   fixture sweeps ring size: a predicate over two 8-vertex boxes and one over
//!   two 256-vertex rings are different questions and a single number for
//!   "relate" would hide which one moved.
//!
//! The corpus is **generated, not sampled, and generated deterministically** from
//! the constants below with a four-line SplitMix64 — no clock, no RNG crate, the
//! same rule the crate itself follows, so a run can be reproduced by hand from
//! this file alone.

use core::fmt::Write as _;

use criterion::{Criterion, Throughput, black_box, criterion_group, criterion_main};
use purrdf_geo::{Crs, GeometryLiteral, Rat, topology, wkt};

/// The number of coordinate literals in the ingest fixture.
const COORDINATES: u64 = 4096;
/// The fixed seed the deterministic corpus generator starts from.
const SEED: u64 = 0x5EED_0000_0197_0197;

/// A four-line SplitMix64, so the corpus can be regenerated by hand from the
/// constants in this file rather than depending on a crate whose stream could
/// change between versions.
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_value(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}

/// Decimal coordinate lexical forms of a fixed number of fraction digits.
fn coordinate_lexicals(count: u64, fraction_digits: u32) -> Vec<String> {
    let mut rng = SplitMix64::new(SEED);
    let scale = 10u64.pow(fraction_digits.min(18));
    (0..count)
        .map(|_| {
            let whole = rng.next_value() % 180;
            let fraction = rng.next_value() % scale;
            let width = fraction_digits.min(18) as usize;
            format!("-{whole}.{fraction:0width$}")
        })
        .collect()
}

fn benchmark(criterion: &mut Criterion) {
    let mut group = criterion.benchmark_group("purrdf_geo");
    group.throughput(Throughput::Elements(COORDINATES));

    // Coordinate ingest at three precisions. The point of the sweep is that the
    // exact representation's cost is a function of the DIGITS, not only of the
    // coordinate count — a fact a single-precision fixture would hide.
    for digits in [2u32, 9, 17] {
        let lexicals = coordinate_lexicals(COORDINATES, digits);
        group.bench_function(format!("parse_decimal_{digits}_digits"), |bencher| {
            bencher.iter(|| {
                for lexical in black_box(&lexicals) {
                    black_box(Rat::parse_decimal(black_box(lexical)));
                }
            });
        });
    }

    // The exact arithmetic underneath every orientation test: one multiply and
    // one subtract per operand pair, which is the shape of a cross product.
    let values: Vec<Rat> = coordinate_lexicals(256, 9)
        .iter()
        .filter_map(|lexical| Rat::parse_decimal(lexical))
        .collect();
    group.throughput(Throughput::Elements(values.len() as u64));
    group.bench_function("rational_cross_product_terms", |bencher| {
        bencher.iter(|| {
            let values = black_box(&values);
            let mut acc = Rat::zero();
            for window in values.windows(2) {
                acc = acc.add(&window[0].mul(&window[1]));
            }
            black_box(acc)
        });
    });

    // ---- the literal ingest path, end to end -----------------------------
    //
    // Every row that reaches a `geof:` call parses a geometry literal first, so
    // this is the one cost paid per row regardless of what the predicate does.
    let crs = Crs::new("http://example.org/crs/planar").expect("a non-empty IRI");
    for vertices in [8usize, 64, 256] {
        let lexical = ring_wkt(vertices, 0);
        group.throughput(Throughput::Elements(vertices as u64));
        group.bench_function(format!("parse_ring_{vertices}_vertices"), |bencher| {
            bencher.iter(|| {
                black_box(wkt::parse(black_box(&lexical), black_box(&crs)).expect("well formed"));
            });
        });
    }

    // ---- the relate itself ----------------------------------------------
    //
    // The noder compares every segment pair, so this is QUADRATIC in the
    // combined vertex count and the sweep is the point: a single number for
    // "relate" would hide which size moved. Two overlapping rings, so the noder
    // actually has intersections to find rather than short-circuiting on
    // disjoint bounding boxes.
    for vertices in [8usize, 32, 128] {
        let a = ring(&crs, vertices, 0);
        let b = ring(&crs, vertices, 1);
        group.throughput(Throughput::Elements((vertices * vertices) as u64));
        group.bench_function(format!("relate_two_rings_{vertices}_vertices"), |bencher| {
            bencher.iter(|| {
                black_box(topology::relate(
                    black_box(a.geometry()),
                    black_box(b.geometry()),
                ));
            });
        });
    }

    group.finish();
}

/// A closed convex ring of `vertices` positions on a lattice, offset by
/// `offset` so two of them overlap.
///
/// Lattice coordinates rather than a circle's, because a circle would need
/// transcendental functions and this crate has none — and because exact integer
/// vertices are the honest fixture for an exact predicate: a fixture whose
/// coordinates were already rounded would measure the rounding, not the noder.
fn ring_wkt(vertices: usize, offset: i64) -> String {
    let mut out = String::from("POLYGON((");
    let half = (vertices / 2) as i64;
    for index in 0..vertices {
        if index > 0 {
            out.push(',');
        }
        // A convex fan: x walks out and back, y follows, so the ring is simple
        // and its interior is non-degenerate at every size.
        let i = index as i64;
        let (x, y) = if i <= half {
            (i, i * i / 4)
        } else {
            (2 * half - i, (2 * half - i) * (2 * half - i) / 4 + 1)
        };
        let (x, y) = (x + offset, y + offset);
        write!(out, "{x} {y}").expect("writing to a String cannot fail");
    }
    write!(out, ",{offset} {offset}))").expect("writing to a String cannot fail");
    out
}

/// The parsed form of [`ring_wkt`].
fn ring(crs: &Crs, vertices: usize, offset: i64) -> GeometryLiteral {
    wkt::parse(&ring_wkt(vertices, offset), crs).expect("the generated ring is well formed")
}

criterion_group!(benches, benchmark);
criterion_main!(benches);
