// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

//! Standard vocabulary IRIs shared by every entailment engine.
//!
//! These are spec-supplied `rdf:`/`rdfs:`/`owl:`/`xsd:` IRIs from the RDF 1.2 Semantics /
//! OWL 2 calculus — PurRDF mints **none** of its own. Every engine (the RDFS/OWL-RL
//! chase, the OWL-Direct tableau, the RIF-Core evaluator) names its constant IRIs
//! through the flat aliases here, each of which is the workspace's one vocabulary
//! constant in `purrdf_iri::vocab` or `purrdf_xsd::datatype`.

pub(crate) use purrdf_iri::vocab::owl::{
    ALL_DIFFERENT as OWL_ALLDIFFERENT, ALL_DISJOINT_CLASSES as OWL_ALLDISJOINTCLASSES,
    ALL_DISJOINT_PROPERTIES as OWL_ALLDISJOINTPROPERTIES, ALL_VALUES_FROM as OWL_ALLVALUESFROM,
    ANNOTATED_PROPERTY as OWL_ANNOTATEDPROPERTY, ANNOTATED_SOURCE as OWL_ANNOTATEDSOURCE,
    ANNOTATED_TARGET as OWL_ANNOTATEDTARGET, ANNOTATION as OWL_ANNOTATION,
    ANNOTATION_PROPERTY as OWL_ANNOTATIONPROPERTY, ASSERTION_PROPERTY as OWL_ASSERTIONPROPERTY,
    ASYMMETRIC_PROPERTY as OWL_ASYMMETRICPROPERTY, AXIOM as OWL_AXIOM,
    BACKWARD_COMPATIBLE_WITH as OWL_BACKWARDCOMPATIBLEWITH,
    BOTTOM_DATA_PROPERTY as OWL_BOTTOMDATAPROPERTY,
    BOTTOM_OBJECT_PROPERTY as OWL_BOTTOMOBJECTPROPERTY, CARDINALITY as OWL_CARDINALITY,
    CLASS as OWL_CLASS, COMPLEMENT_OF as OWL_COMPLEMENTOF, DATA_RANGE as OWL_DATARANGE,
    DATATYPE_COMPLEMENT_OF as OWL_DATATYPECOMPLEMENTOF, DATATYPE_PROPERTY as OWL_DATATYPEPROPERTY,
    DEPRECATED as OWL_DEPRECATED, DIFFERENT_FROM as OWL_DIFFERENTFROM,
    DISJOINT_UNION_OF as OWL_DISJOINTUNIONOF, DISJOINT_WITH as OWL_DISJOINTWITH,
    DISTINCT_MEMBERS as OWL_DISTINCTMEMBERS, EQUIVALENT_CLASS as OWL_EQUIVALENTCLASS,
    EQUIVALENT_PROPERTY as OWL_EQUIVALENTPROPERTY, FUNCTIONAL_PROPERTY as OWL_FUNCTIONALPROPERTY,
    HAS_KEY as OWL_HASKEY, HAS_SELF as OWL_HASSELF, HAS_VALUE as OWL_HASVALUE,
    IMPORTS as OWL_IMPORTS, INCOMPATIBLE_WITH as OWL_INCOMPATIBLEWITH,
    INTERSECTION_OF as OWL_INTERSECTIONOF,
    INVERSE_FUNCTIONAL_PROPERTY as OWL_INVERSEFUNCTIONALPROPERTY, INVERSE_OF as OWL_INVERSEOF,
    IRREFLEXIVE_PROPERTY as OWL_IRREFLEXIVEPROPERTY, MAX_CARDINALITY as OWL_MAXCARDINALITY,
    MAX_QUALIFIED_CARDINALITY as OWL_MAXQUALIFIEDCARDINALITY, MEMBERS as OWL_MEMBERS,
    MIN_CARDINALITY as OWL_MINCARDINALITY,
    MIN_QUALIFIED_CARDINALITY as OWL_MINQUALIFIEDCARDINALITY,
    NAMED_INDIVIDUAL as OWL_NAMEDINDIVIDUAL,
    NEGATIVE_PROPERTY_ASSERTION as OWL_NEGATIVEPROPERTYASSERTION, NOTHING as OWL_NOTHING,
    OBJECT_PROPERTY as OWL_OBJECTPROPERTY, ON_CLASS as OWL_ONCLASS,
    ON_DATA_RANGE as OWL_ONDATARANGE, ON_DATATYPE as OWL_ONDATATYPE,
    ON_PROPERTIES as OWL_ONPROPERTIES, ON_PROPERTY as OWL_ONPROPERTY, ONE_OF as OWL_ONEOF,
    ONTOLOGY as OWL_ONTOLOGY, ONTOLOGY_PROPERTY as OWL_ONTOLOGYPROPERTY,
    PRIOR_VERSION as OWL_PRIORVERSION, PROPERTY_CHAIN_AXIOM as OWL_PROPERTYCHAINAXIOM,
    PROPERTY_DISJOINT_WITH as OWL_PROPERTYDISJOINTWITH,
    QUALIFIED_CARDINALITY as OWL_QUALIFIEDCARDINALITY, REFLEXIVE_PROPERTY as OWL_REFLEXIVEPROPERTY,
    RESTRICTION as OWL_RESTRICTION, SAME_AS as OWL_SAMEAS, SOME_VALUES_FROM as OWL_SOMEVALUESFROM,
    SOURCE_INDIVIDUAL as OWL_SOURCEINDIVIDUAL, SYMMETRIC_PROPERTY as OWL_SYMMETRICPROPERTY,
    TARGET_INDIVIDUAL as OWL_TARGETINDIVIDUAL, TARGET_VALUE as OWL_TARGETVALUE, THING as OWL_THING,
    TOP_DATA_PROPERTY as OWL_TOPDATAPROPERTY, TOP_OBJECT_PROPERTY as OWL_TOPOBJECTPROPERTY,
    TRANSITIVE_PROPERTY as OWL_TRANSITIVEPROPERTY, UNION_OF as OWL_UNIONOF,
    VERSION_INFO as OWL_VERSIONINFO, VERSION_IRI as OWL_VERSIONIRI,
    WITH_RESTRICTIONS as OWL_WITHRESTRICTIONS,
};
pub(crate) use purrdf_iri::vocab::rdf::{
    ALT as RDF_ALT, BAG as RDF_BAG, DIR_LANG_STRING as RDF_DIRLANGSTRING, FIRST as RDF_FIRST,
    LANG_RANGE as RDF_LANGRANGE, LANG_STRING as RDF_LANGSTRING, LIST as RDF_LIST, NIL as RDF_NIL,
    OBJECT as RDF_OBJECT, PLAIN_LITERAL as RDF_PLAINLITERAL, PREDICATE as RDF_PREDICATE,
    PROPERTY as RDF_PROPERTY, REIFIES as RDF_REIFIES, REST as RDF_REST, SEQ as RDF_SEQ,
    STATEMENT as RDF_STATEMENT, SUBJECT as RDF_SUBJECT, TYPE as RDF_TYPE, VALUE as RDF_VALUE,
    XML_LITERAL as RDF_XMLLITERAL,
};
pub(crate) use purrdf_iri::vocab::rdfs::{
    CLASS as RDFS_CLASS, COMMENT as RDFS_COMMENT, CONTAINER as RDFS_CONTAINER,
    CONTAINER_MEMBERSHIP_PROPERTY as RDFS_CONTAINERMEMBERSHIPPROPERTY, DATATYPE as RDFS_DATATYPE,
    DOMAIN as RDFS_DOMAIN, IS_DEFINED_BY as RDFS_ISDEFINEDBY, LABEL as RDFS_LABEL,
    LITERAL as RDFS_LITERAL, MEMBER as RDFS_MEMBER, PROPOSITION as RDFS_PROPOSITION,
    RANGE as RDFS_RANGE, RESOURCE as RDFS_RESOURCE, SEE_ALSO as RDFS_SEEALSO,
    SUB_CLASS_OF as RDFS_SUBCLASSOF, SUB_PROPERTY_OF as RDFS_SUBPROPERTYOF,
};
pub(crate) use purrdf_xsd::datatype::{
    OWL_RATIONAL, OWL_REAL, XSD_ANY_URI as XSD_ANYURI, XSD_BASE64_BINARY as XSD_BASE64BINARY,
    XSD_BOOLEAN, XSD_BYTE, XSD_DATE_TIME as XSD_DATETIME, XSD_DATE_TIME_STAMP as XSD_DATETIMESTAMP,
    XSD_DECIMAL, XSD_DOUBLE, XSD_FLOAT, XSD_HEX_BINARY as XSD_HEXBINARY, XSD_INT, XSD_INTEGER,
    XSD_LANGUAGE, XSD_LENGTH, XSD_LONG, XSD_MAX_EXCLUSIVE as XSD_MAXEXCLUSIVE,
    XSD_MAX_INCLUSIVE as XSD_MAXINCLUSIVE, XSD_MAX_LENGTH as XSD_MAXLENGTH,
    XSD_MIN_EXCLUSIVE as XSD_MINEXCLUSIVE, XSD_MIN_INCLUSIVE as XSD_MININCLUSIVE,
    XSD_MIN_LENGTH as XSD_MINLENGTH, XSD_NAME, XSD_NCNAME,
    XSD_NEGATIVE_INTEGER as XSD_NEGATIVEINTEGER, XSD_NMTOKEN,
    XSD_NON_NEGATIVE_INTEGER as XSD_NONNEGATIVEINTEGER,
    XSD_NON_POSITIVE_INTEGER as XSD_NONPOSITIVEINTEGER,
    XSD_NORMALIZED_STRING as XSD_NORMALIZEDSTRING, XSD_NS, XSD_PATTERN,
    XSD_POSITIVE_INTEGER as XSD_POSITIVEINTEGER, XSD_SHORT, XSD_STRING, XSD_TOKEN,
    XSD_UNSIGNED_BYTE as XSD_UNSIGNEDBYTE, XSD_UNSIGNED_INT as XSD_UNSIGNEDINT,
    XSD_UNSIGNED_LONG as XSD_UNSIGNEDLONG, XSD_UNSIGNED_SHORT as XSD_UNSIGNEDSHORT,
};
