#!/usr/bin/env -S uv run --script
# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0
# /// script
# requires-python = ">=3.11"
# dependencies = ["owlrl==7.1.4", "rdflib==7.6.0"]
# ///

"""Freeze the `owlrl` reference closure for every fixture in `owlrl-corpus/`.

This is the SECOND of the two regeneration steps documented in
`owlrl_oracle.rs`'s module comment; the first (`write_owlrl_corpus_inputs`, a Rust
`#[ignore]`d test) writes the canonical N-Triples input files this script reads. Run from
the repository root:

    cargo test -p purrdf-entail --test owlrl_oracle -- --ignored --exact write_owlrl_corpus_inputs
    uv run --with owlrl==7.1.4 --with rdflib==7.6.0 crates/entail/tests/regenerate_owlrl_goldens.py

(or, with `uv`'s inline script metadata above, simply
`uv run --script crates/entail/tests/regenerate_owlrl_goldens.py`.)

`owlrl` and `rdflib` are TEST DATA for this repository, never a runtime or even a
dev-dependency of any Rust crate: this script is the only place either package is
named, it is never imported by `cargo test`, and the committed `.owlrl.golden` files
under `owlrl-goldens/` are the only thing `owlrl_oracle.rs` ever reads at test time.

# Why `OWLRL_Semantics`, not the combined `RDFS_OWLRL_Semantics`

`owlrl` ships two closure classes. `RDFS_OWLRL_Semantics` always runs the full eighteen-
rule RDFS entailment alongside OWL 2 RL, which would type every subject and object
`rdfs:Resource` and identify `owl:Thing` with `rdfs:Resource` — neither of which OWL 2
Profiles §4.3 Tables 4-9 license, and neither of which PurRDF's `OWL-RL` regime computes
(that regime is exactly Tables 4-9 plus the three RDFS-shaped rules the profile itself
borrows: `rdfs6`, `rdfs8`, `rdfs10`). `OWLRL_Semantics` alone runs exactly that borrowed
set and nothing more, and is the closure class this script uses.

# Determinism

The corpus is deliberately blank-node-free (every `rdf:List` cell is a named
`example.org` IRI; see `owlrl_oracle.rs`'s module docs), so `owlrl`'s closure over it
contains no blank node either — `rdflib` mints fresh, unstable blank node LABELS on every
parse, and a golden frozen against one would not reproduce. `check_no_blank_nodes` below
is a hard assertion of that invariant, not a hope.
"""

from __future__ import annotations

import pathlib
import sys

import owlrl
import rdflib
from rdflib import BNode, Literal, URIRef

CORPUS_DIR = pathlib.Path(__file__).parent / "owlrl-corpus"
GOLDEN_DIR = pathlib.Path(__file__).parent / "owlrl-goldens"

HEADER = """# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# GOLDEN — generated by crates/entail/tests/regenerate_owlrl_goldens.py. Do not hand-edit.
#
# The `owlrl` reference closure (PyPI, pinned to 7.1.4; owlrl.OWLRL_Semantics,
# axiomatic_triples=False, datatype_axioms=False, rdfs_closure=False) of the fixture named
# below, over the canonical N-Triples input committed alongside it in
# tests/owlrl-corpus/{name}.nt.
#
# Regenerate deliberately with:
#   cargo test -p purrdf-entail --test owlrl_oracle -- --ignored --exact write_owlrl_corpus_inputs
#   uv run --script crates/entail/tests/regenerate_owlrl_goldens.py
#
# fixture: {name}
"""


def n3_escape(lexical: str) -> str:
    """Escape a literal's lexical form for canonical N-Triples."""
    out = []
    for ch in lexical:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return "".join(out)


def term_text(term: URIRef | Literal | BNode) -> str:
    """Render one RDF term in canonical N-Triples surface form.

    Matches `purrdf_core`'s own canonical-N-Quads writer
    (`crates/rdf-core/src/ir/canon.rs::write_term`) exactly: `xsd:string` is the implicit
    datatype for a literal with no language tag, so it is written BARE, with no `^^<…>`
    suffix. Every other datatype is written explicitly. Without this, every plain string
    literal would show up as a spurious "divergence" that is really just two renderers
    disagreeing about how to spell the same value.
    """
    if isinstance(term, URIRef):
        return f"<{term}>"
    if isinstance(term, Literal):
        lexical = f'"{n3_escape(str(term))}"'
        if term.language:
            return f"{lexical}@{term.language}"
        datatype = term.datatype or rdflib.XSD.string
        if str(datatype) == str(rdflib.XSD.string):
            return lexical
        return f"{lexical}^^<{datatype}>"
    raise TypeError(f"unexpected term kind for a blank-node-free corpus: {term!r}")


def check_no_blank_nodes(graph: rdflib.Graph, name: str) -> None:
    for s, _p, o in graph:
        if isinstance(s, BNode) or isinstance(o, BNode):
            raise AssertionError(
                f"{name}: owlrl's closure minted or read a blank node ({s!r}, {o!r}); "
                "the corpus is meant to stay blank-node-free — see owlrl_oracle.rs's "
                "module docs. Either the fixture regressed to using one, or owlrl's "
                "closure genuinely invents one and this script's determinism assumption "
                "needs revisiting before a golden can be frozen."
            )


def closure_lines(input_path: pathlib.Path, name: str) -> list[str]:
    graph = rdflib.Graph()
    graph.parse(str(input_path), format="nt")
    owlrl.DeductiveClosure(
        owlrl.OWLRL_Semantics,
        axiomatic_triples=False,
        datatype_axioms=False,
        rdfs_closure=False,
    ).expand(graph)
    check_no_blank_nodes(graph, name)
    lines = {f"{term_text(s)} {term_text(p)} {term_text(o)} ." for s, p, o in graph}
    return sorted(lines)


def main() -> int:
    if not CORPUS_DIR.is_dir():
        print(
            f"error: {CORPUS_DIR} does not exist. Run first:\n"
            "  cargo test -p purrdf-entail --test owlrl_oracle -- --ignored --exact "
            "write_owlrl_corpus_inputs",
            file=sys.stderr,
        )
        return 2

    GOLDEN_DIR.mkdir(exist_ok=True)
    inputs = sorted(CORPUS_DIR.glob("*.nt"))
    if not inputs:
        print(f"error: no *.nt files found under {CORPUS_DIR}", file=sys.stderr)
        return 2

    for input_path in inputs:
        name = input_path.stem
        lines = closure_lines(input_path, name)
        golden_path = GOLDEN_DIR / f"{name}.owlrl.golden"
        input_text = input_path.read_text(encoding="utf-8")
        with golden_path.open("w", encoding="utf-8") as f:
            f.write(HEADER.format(name=name))
            f.write("--- input ---\n")
            f.write(input_text)
            if not input_text.endswith("\n"):
                f.write("\n")
            f.write("--- owlrl closure ---\n")
            for line in lines:
                f.write(line)
                f.write("\n")
        print(f"wrote {golden_path} ({len(lines)} triples)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
