// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! @generated by `cargo run -p purrdf-core --example gen_unicode_blocks --locked`.
//! Do not hand-edit; `scripts/check-generated.sh` diffs this file against the
//! generator's stdout.
//!
//! Source: `crates/rdf-core/vendor/unicode/Blocks.txt`, Unicode Character
//! Database version 16.0.0 (pinned to match this workspace's locked
//! `regex-syntax` 0.8.11, whose embedded Unicode tables are also 16.0.0 --
//! see `Blocks.txt.license`).
//!
//! `UNICODE_BLOCKS` maps every XSD/XPath block-escape name (the `\p{IsX}`
//! form of XML Schema Part 2 Appendix G.4.2.3, normalized per that section:
//! "the string of characters formed by stripping out white space and
//! underbar characters from the block name ..., while retaining hyphens and
//! preserving case distinctions", prefixed with `Is`) to its inclusive
//! `[lo, hi]` Unicode codepoint range. Sorted ascending by `lo` and
//! non-overlapping -- enforced by the generator and re-checked by
//! `tests::table_is_sorted_and_non_overlapping` below.
//!
//! <https://www.w3.org/TR/xmlschema11-2/#cces-blockesc>

pub(crate) const UNICODE_BLOCKS: &[(&str, u32, u32)] = &[
    ("IsBasicLatin", 0x0000_0000, 0x0000_007F),
    ("IsLatin-1Supplement", 0x0000_0080, 0x0000_00FF),
    ("IsLatinExtended-A", 0x0000_0100, 0x0000_017F),
    ("IsLatinExtended-B", 0x0000_0180, 0x0000_024F),
    ("IsIPAExtensions", 0x0000_0250, 0x0000_02AF),
    ("IsSpacingModifierLetters", 0x0000_02B0, 0x0000_02FF),
    ("IsCombiningDiacriticalMarks", 0x0000_0300, 0x0000_036F),
    ("IsGreekandCoptic", 0x0000_0370, 0x0000_03FF),
    ("IsCyrillic", 0x0000_0400, 0x0000_04FF),
    ("IsCyrillicSupplement", 0x0000_0500, 0x0000_052F),
    ("IsArmenian", 0x0000_0530, 0x0000_058F),
    ("IsHebrew", 0x0000_0590, 0x0000_05FF),
    ("IsArabic", 0x0000_0600, 0x0000_06FF),
    ("IsSyriac", 0x0000_0700, 0x0000_074F),
    ("IsArabicSupplement", 0x0000_0750, 0x0000_077F),
    ("IsThaana", 0x0000_0780, 0x0000_07BF),
    ("IsNKo", 0x0000_07C0, 0x0000_07FF),
    ("IsSamaritan", 0x0000_0800, 0x0000_083F),
    ("IsMandaic", 0x0000_0840, 0x0000_085F),
    ("IsSyriacSupplement", 0x0000_0860, 0x0000_086F),
    ("IsArabicExtended-B", 0x0000_0870, 0x0000_089F),
    ("IsArabicExtended-A", 0x0000_08A0, 0x0000_08FF),
    ("IsDevanagari", 0x0000_0900, 0x0000_097F),
    ("IsBengali", 0x0000_0980, 0x0000_09FF),
    ("IsGurmukhi", 0x0000_0A00, 0x0000_0A7F),
    ("IsGujarati", 0x0000_0A80, 0x0000_0AFF),
    ("IsOriya", 0x0000_0B00, 0x0000_0B7F),
    ("IsTamil", 0x0000_0B80, 0x0000_0BFF),
    ("IsTelugu", 0x0000_0C00, 0x0000_0C7F),
    ("IsKannada", 0x0000_0C80, 0x0000_0CFF),
    ("IsMalayalam", 0x0000_0D00, 0x0000_0D7F),
    ("IsSinhala", 0x0000_0D80, 0x0000_0DFF),
    ("IsThai", 0x0000_0E00, 0x0000_0E7F),
    ("IsLao", 0x0000_0E80, 0x0000_0EFF),
    ("IsTibetan", 0x0000_0F00, 0x0000_0FFF),
    ("IsMyanmar", 0x0000_1000, 0x0000_109F),
    ("IsGeorgian", 0x0000_10A0, 0x0000_10FF),
    ("IsHangulJamo", 0x0000_1100, 0x0000_11FF),
    ("IsEthiopic", 0x0000_1200, 0x0000_137F),
    ("IsEthiopicSupplement", 0x0000_1380, 0x0000_139F),
    ("IsCherokee", 0x0000_13A0, 0x0000_13FF),
    (
        "IsUnifiedCanadianAboriginalSyllabics",
        0x0000_1400,
        0x0000_167F,
    ),
    ("IsOgham", 0x0000_1680, 0x0000_169F),
    ("IsRunic", 0x0000_16A0, 0x0000_16FF),
    ("IsTagalog", 0x0000_1700, 0x0000_171F),
    ("IsHanunoo", 0x0000_1720, 0x0000_173F),
    ("IsBuhid", 0x0000_1740, 0x0000_175F),
    ("IsTagbanwa", 0x0000_1760, 0x0000_177F),
    ("IsKhmer", 0x0000_1780, 0x0000_17FF),
    ("IsMongolian", 0x0000_1800, 0x0000_18AF),
    (
        "IsUnifiedCanadianAboriginalSyllabicsExtended",
        0x0000_18B0,
        0x0000_18FF,
    ),
    ("IsLimbu", 0x0000_1900, 0x0000_194F),
    ("IsTaiLe", 0x0000_1950, 0x0000_197F),
    ("IsNewTaiLue", 0x0000_1980, 0x0000_19DF),
    ("IsKhmerSymbols", 0x0000_19E0, 0x0000_19FF),
    ("IsBuginese", 0x0000_1A00, 0x0000_1A1F),
    ("IsTaiTham", 0x0000_1A20, 0x0000_1AAF),
    (
        "IsCombiningDiacriticalMarksExtended",
        0x0000_1AB0,
        0x0000_1AFF,
    ),
    ("IsBalinese", 0x0000_1B00, 0x0000_1B7F),
    ("IsSundanese", 0x0000_1B80, 0x0000_1BBF),
    ("IsBatak", 0x0000_1BC0, 0x0000_1BFF),
    ("IsLepcha", 0x0000_1C00, 0x0000_1C4F),
    ("IsOlChiki", 0x0000_1C50, 0x0000_1C7F),
    ("IsCyrillicExtended-C", 0x0000_1C80, 0x0000_1C8F),
    ("IsGeorgianExtended", 0x0000_1C90, 0x0000_1CBF),
    ("IsSundaneseSupplement", 0x0000_1CC0, 0x0000_1CCF),
    ("IsVedicExtensions", 0x0000_1CD0, 0x0000_1CFF),
    ("IsPhoneticExtensions", 0x0000_1D00, 0x0000_1D7F),
    ("IsPhoneticExtensionsSupplement", 0x0000_1D80, 0x0000_1DBF),
    (
        "IsCombiningDiacriticalMarksSupplement",
        0x0000_1DC0,
        0x0000_1DFF,
    ),
    ("IsLatinExtendedAdditional", 0x0000_1E00, 0x0000_1EFF),
    ("IsGreekExtended", 0x0000_1F00, 0x0000_1FFF),
    ("IsGeneralPunctuation", 0x0000_2000, 0x0000_206F),
    ("IsSuperscriptsandSubscripts", 0x0000_2070, 0x0000_209F),
    ("IsCurrencySymbols", 0x0000_20A0, 0x0000_20CF),
    (
        "IsCombiningDiacriticalMarksforSymbols",
        0x0000_20D0,
        0x0000_20FF,
    ),
    ("IsLetterlikeSymbols", 0x0000_2100, 0x0000_214F),
    ("IsNumberForms", 0x0000_2150, 0x0000_218F),
    ("IsArrows", 0x0000_2190, 0x0000_21FF),
    ("IsMathematicalOperators", 0x0000_2200, 0x0000_22FF),
    ("IsMiscellaneousTechnical", 0x0000_2300, 0x0000_23FF),
    ("IsControlPictures", 0x0000_2400, 0x0000_243F),
    ("IsOpticalCharacterRecognition", 0x0000_2440, 0x0000_245F),
    ("IsEnclosedAlphanumerics", 0x0000_2460, 0x0000_24FF),
    ("IsBoxDrawing", 0x0000_2500, 0x0000_257F),
    ("IsBlockElements", 0x0000_2580, 0x0000_259F),
    ("IsGeometricShapes", 0x0000_25A0, 0x0000_25FF),
    ("IsMiscellaneousSymbols", 0x0000_2600, 0x0000_26FF),
    ("IsDingbats", 0x0000_2700, 0x0000_27BF),
    (
        "IsMiscellaneousMathematicalSymbols-A",
        0x0000_27C0,
        0x0000_27EF,
    ),
    ("IsSupplementalArrows-A", 0x0000_27F0, 0x0000_27FF),
    ("IsBraillePatterns", 0x0000_2800, 0x0000_28FF),
    ("IsSupplementalArrows-B", 0x0000_2900, 0x0000_297F),
    (
        "IsMiscellaneousMathematicalSymbols-B",
        0x0000_2980,
        0x0000_29FF,
    ),
    (
        "IsSupplementalMathematicalOperators",
        0x0000_2A00,
        0x0000_2AFF,
    ),
    ("IsMiscellaneousSymbolsandArrows", 0x0000_2B00, 0x0000_2BFF),
    ("IsGlagolitic", 0x0000_2C00, 0x0000_2C5F),
    ("IsLatinExtended-C", 0x0000_2C60, 0x0000_2C7F),
    ("IsCoptic", 0x0000_2C80, 0x0000_2CFF),
    ("IsGeorgianSupplement", 0x0000_2D00, 0x0000_2D2F),
    ("IsTifinagh", 0x0000_2D30, 0x0000_2D7F),
    ("IsEthiopicExtended", 0x0000_2D80, 0x0000_2DDF),
    ("IsCyrillicExtended-A", 0x0000_2DE0, 0x0000_2DFF),
    ("IsSupplementalPunctuation", 0x0000_2E00, 0x0000_2E7F),
    ("IsCJKRadicalsSupplement", 0x0000_2E80, 0x0000_2EFF),
    ("IsKangxiRadicals", 0x0000_2F00, 0x0000_2FDF),
    (
        "IsIdeographicDescriptionCharacters",
        0x0000_2FF0,
        0x0000_2FFF,
    ),
    ("IsCJKSymbolsandPunctuation", 0x0000_3000, 0x0000_303F),
    ("IsHiragana", 0x0000_3040, 0x0000_309F),
    ("IsKatakana", 0x0000_30A0, 0x0000_30FF),
    ("IsBopomofo", 0x0000_3100, 0x0000_312F),
    ("IsHangulCompatibilityJamo", 0x0000_3130, 0x0000_318F),
    ("IsKanbun", 0x0000_3190, 0x0000_319F),
    ("IsBopomofoExtended", 0x0000_31A0, 0x0000_31BF),
    ("IsCJKStrokes", 0x0000_31C0, 0x0000_31EF),
    ("IsKatakanaPhoneticExtensions", 0x0000_31F0, 0x0000_31FF),
    ("IsEnclosedCJKLettersandMonths", 0x0000_3200, 0x0000_32FF),
    ("IsCJKCompatibility", 0x0000_3300, 0x0000_33FF),
    ("IsCJKUnifiedIdeographsExtensionA", 0x0000_3400, 0x0000_4DBF),
    ("IsYijingHexagramSymbols", 0x0000_4DC0, 0x0000_4DFF),
    ("IsCJKUnifiedIdeographs", 0x0000_4E00, 0x0000_9FFF),
    ("IsYiSyllables", 0x0000_A000, 0x0000_A48F),
    ("IsYiRadicals", 0x0000_A490, 0x0000_A4CF),
    ("IsLisu", 0x0000_A4D0, 0x0000_A4FF),
    ("IsVai", 0x0000_A500, 0x0000_A63F),
    ("IsCyrillicExtended-B", 0x0000_A640, 0x0000_A69F),
    ("IsBamum", 0x0000_A6A0, 0x0000_A6FF),
    ("IsModifierToneLetters", 0x0000_A700, 0x0000_A71F),
    ("IsLatinExtended-D", 0x0000_A720, 0x0000_A7FF),
    ("IsSylotiNagri", 0x0000_A800, 0x0000_A82F),
    ("IsCommonIndicNumberForms", 0x0000_A830, 0x0000_A83F),
    ("IsPhags-pa", 0x0000_A840, 0x0000_A87F),
    ("IsSaurashtra", 0x0000_A880, 0x0000_A8DF),
    ("IsDevanagariExtended", 0x0000_A8E0, 0x0000_A8FF),
    ("IsKayahLi", 0x0000_A900, 0x0000_A92F),
    ("IsRejang", 0x0000_A930, 0x0000_A95F),
    ("IsHangulJamoExtended-A", 0x0000_A960, 0x0000_A97F),
    ("IsJavanese", 0x0000_A980, 0x0000_A9DF),
    ("IsMyanmarExtended-B", 0x0000_A9E0, 0x0000_A9FF),
    ("IsCham", 0x0000_AA00, 0x0000_AA5F),
    ("IsMyanmarExtended-A", 0x0000_AA60, 0x0000_AA7F),
    ("IsTaiViet", 0x0000_AA80, 0x0000_AADF),
    ("IsMeeteiMayekExtensions", 0x0000_AAE0, 0x0000_AAFF),
    ("IsEthiopicExtended-A", 0x0000_AB00, 0x0000_AB2F),
    ("IsLatinExtended-E", 0x0000_AB30, 0x0000_AB6F),
    ("IsCherokeeSupplement", 0x0000_AB70, 0x0000_ABBF),
    ("IsMeeteiMayek", 0x0000_ABC0, 0x0000_ABFF),
    ("IsHangulSyllables", 0x0000_AC00, 0x0000_D7AF),
    ("IsHangulJamoExtended-B", 0x0000_D7B0, 0x0000_D7FF),
    ("IsHighSurrogates", 0x0000_D800, 0x0000_DB7F),
    ("IsHighPrivateUseSurrogates", 0x0000_DB80, 0x0000_DBFF),
    ("IsLowSurrogates", 0x0000_DC00, 0x0000_DFFF),
    ("IsPrivateUseArea", 0x0000_E000, 0x0000_F8FF),
    ("IsCJKCompatibilityIdeographs", 0x0000_F900, 0x0000_FAFF),
    ("IsAlphabeticPresentationForms", 0x0000_FB00, 0x0000_FB4F),
    ("IsArabicPresentationForms-A", 0x0000_FB50, 0x0000_FDFF),
    ("IsVariationSelectors", 0x0000_FE00, 0x0000_FE0F),
    ("IsVerticalForms", 0x0000_FE10, 0x0000_FE1F),
    ("IsCombiningHalfMarks", 0x0000_FE20, 0x0000_FE2F),
    ("IsCJKCompatibilityForms", 0x0000_FE30, 0x0000_FE4F),
    ("IsSmallFormVariants", 0x0000_FE50, 0x0000_FE6F),
    ("IsArabicPresentationForms-B", 0x0000_FE70, 0x0000_FEFF),
    ("IsHalfwidthandFullwidthForms", 0x0000_FF00, 0x0000_FFEF),
    ("IsSpecials", 0x0000_FFF0, 0x0000_FFFF),
    ("IsLinearBSyllabary", 0x0001_0000, 0x0001_007F),
    ("IsLinearBIdeograms", 0x0001_0080, 0x0001_00FF),
    ("IsAegeanNumbers", 0x0001_0100, 0x0001_013F),
    ("IsAncientGreekNumbers", 0x0001_0140, 0x0001_018F),
    ("IsAncientSymbols", 0x0001_0190, 0x0001_01CF),
    ("IsPhaistosDisc", 0x0001_01D0, 0x0001_01FF),
    ("IsLycian", 0x0001_0280, 0x0001_029F),
    ("IsCarian", 0x0001_02A0, 0x0001_02DF),
    ("IsCopticEpactNumbers", 0x0001_02E0, 0x0001_02FF),
    ("IsOldItalic", 0x0001_0300, 0x0001_032F),
    ("IsGothic", 0x0001_0330, 0x0001_034F),
    ("IsOldPermic", 0x0001_0350, 0x0001_037F),
    ("IsUgaritic", 0x0001_0380, 0x0001_039F),
    ("IsOldPersian", 0x0001_03A0, 0x0001_03DF),
    ("IsDeseret", 0x0001_0400, 0x0001_044F),
    ("IsShavian", 0x0001_0450, 0x0001_047F),
    ("IsOsmanya", 0x0001_0480, 0x0001_04AF),
    ("IsOsage", 0x0001_04B0, 0x0001_04FF),
    ("IsElbasan", 0x0001_0500, 0x0001_052F),
    ("IsCaucasianAlbanian", 0x0001_0530, 0x0001_056F),
    ("IsVithkuqi", 0x0001_0570, 0x0001_05BF),
    ("IsTodhri", 0x0001_05C0, 0x0001_05FF),
    ("IsLinearA", 0x0001_0600, 0x0001_077F),
    ("IsLatinExtended-F", 0x0001_0780, 0x0001_07BF),
    ("IsCypriotSyllabary", 0x0001_0800, 0x0001_083F),
    ("IsImperialAramaic", 0x0001_0840, 0x0001_085F),
    ("IsPalmyrene", 0x0001_0860, 0x0001_087F),
    ("IsNabataean", 0x0001_0880, 0x0001_08AF),
    ("IsHatran", 0x0001_08E0, 0x0001_08FF),
    ("IsPhoenician", 0x0001_0900, 0x0001_091F),
    ("IsLydian", 0x0001_0920, 0x0001_093F),
    ("IsMeroiticHieroglyphs", 0x0001_0980, 0x0001_099F),
    ("IsMeroiticCursive", 0x0001_09A0, 0x0001_09FF),
    ("IsKharoshthi", 0x0001_0A00, 0x0001_0A5F),
    ("IsOldSouthArabian", 0x0001_0A60, 0x0001_0A7F),
    ("IsOldNorthArabian", 0x0001_0A80, 0x0001_0A9F),
    ("IsManichaean", 0x0001_0AC0, 0x0001_0AFF),
    ("IsAvestan", 0x0001_0B00, 0x0001_0B3F),
    ("IsInscriptionalParthian", 0x0001_0B40, 0x0001_0B5F),
    ("IsInscriptionalPahlavi", 0x0001_0B60, 0x0001_0B7F),
    ("IsPsalterPahlavi", 0x0001_0B80, 0x0001_0BAF),
    ("IsOldTurkic", 0x0001_0C00, 0x0001_0C4F),
    ("IsOldHungarian", 0x0001_0C80, 0x0001_0CFF),
    ("IsHanifiRohingya", 0x0001_0D00, 0x0001_0D3F),
    ("IsGaray", 0x0001_0D40, 0x0001_0D8F),
    ("IsRumiNumeralSymbols", 0x0001_0E60, 0x0001_0E7F),
    ("IsYezidi", 0x0001_0E80, 0x0001_0EBF),
    ("IsArabicExtended-C", 0x0001_0EC0, 0x0001_0EFF),
    ("IsOldSogdian", 0x0001_0F00, 0x0001_0F2F),
    ("IsSogdian", 0x0001_0F30, 0x0001_0F6F),
    ("IsOldUyghur", 0x0001_0F70, 0x0001_0FAF),
    ("IsChorasmian", 0x0001_0FB0, 0x0001_0FDF),
    ("IsElymaic", 0x0001_0FE0, 0x0001_0FFF),
    ("IsBrahmi", 0x0001_1000, 0x0001_107F),
    ("IsKaithi", 0x0001_1080, 0x0001_10CF),
    ("IsSoraSompeng", 0x0001_10D0, 0x0001_10FF),
    ("IsChakma", 0x0001_1100, 0x0001_114F),
    ("IsMahajani", 0x0001_1150, 0x0001_117F),
    ("IsSharada", 0x0001_1180, 0x0001_11DF),
    ("IsSinhalaArchaicNumbers", 0x0001_11E0, 0x0001_11FF),
    ("IsKhojki", 0x0001_1200, 0x0001_124F),
    ("IsMultani", 0x0001_1280, 0x0001_12AF),
    ("IsKhudawadi", 0x0001_12B0, 0x0001_12FF),
    ("IsGrantha", 0x0001_1300, 0x0001_137F),
    ("IsTulu-Tigalari", 0x0001_1380, 0x0001_13FF),
    ("IsNewa", 0x0001_1400, 0x0001_147F),
    ("IsTirhuta", 0x0001_1480, 0x0001_14DF),
    ("IsSiddham", 0x0001_1580, 0x0001_15FF),
    ("IsModi", 0x0001_1600, 0x0001_165F),
    ("IsMongolianSupplement", 0x0001_1660, 0x0001_167F),
    ("IsTakri", 0x0001_1680, 0x0001_16CF),
    ("IsMyanmarExtended-C", 0x0001_16D0, 0x0001_16FF),
    ("IsAhom", 0x0001_1700, 0x0001_174F),
    ("IsDogra", 0x0001_1800, 0x0001_184F),
    ("IsWarangCiti", 0x0001_18A0, 0x0001_18FF),
    ("IsDivesAkuru", 0x0001_1900, 0x0001_195F),
    ("IsNandinagari", 0x0001_19A0, 0x0001_19FF),
    ("IsZanabazarSquare", 0x0001_1A00, 0x0001_1A4F),
    ("IsSoyombo", 0x0001_1A50, 0x0001_1AAF),
    (
        "IsUnifiedCanadianAboriginalSyllabicsExtended-A",
        0x0001_1AB0,
        0x0001_1ABF,
    ),
    ("IsPauCinHau", 0x0001_1AC0, 0x0001_1AFF),
    ("IsDevanagariExtended-A", 0x0001_1B00, 0x0001_1B5F),
    ("IsSunuwar", 0x0001_1BC0, 0x0001_1BFF),
    ("IsBhaiksuki", 0x0001_1C00, 0x0001_1C6F),
    ("IsMarchen", 0x0001_1C70, 0x0001_1CBF),
    ("IsMasaramGondi", 0x0001_1D00, 0x0001_1D5F),
    ("IsGunjalaGondi", 0x0001_1D60, 0x0001_1DAF),
    ("IsMakasar", 0x0001_1EE0, 0x0001_1EFF),
    ("IsKawi", 0x0001_1F00, 0x0001_1F5F),
    ("IsLisuSupplement", 0x0001_1FB0, 0x0001_1FBF),
    ("IsTamilSupplement", 0x0001_1FC0, 0x0001_1FFF),
    ("IsCuneiform", 0x0001_2000, 0x0001_23FF),
    ("IsCuneiformNumbersandPunctuation", 0x0001_2400, 0x0001_247F),
    ("IsEarlyDynasticCuneiform", 0x0001_2480, 0x0001_254F),
    ("IsCypro-Minoan", 0x0001_2F90, 0x0001_2FFF),
    ("IsEgyptianHieroglyphs", 0x0001_3000, 0x0001_342F),
    (
        "IsEgyptianHieroglyphFormatControls",
        0x0001_3430,
        0x0001_345F,
    ),
    ("IsEgyptianHieroglyphsExtended-A", 0x0001_3460, 0x0001_43FF),
    ("IsAnatolianHieroglyphs", 0x0001_4400, 0x0001_467F),
    ("IsGurungKhema", 0x0001_6100, 0x0001_613F),
    ("IsBamumSupplement", 0x0001_6800, 0x0001_6A3F),
    ("IsMro", 0x0001_6A40, 0x0001_6A6F),
    ("IsTangsa", 0x0001_6A70, 0x0001_6ACF),
    ("IsBassaVah", 0x0001_6AD0, 0x0001_6AFF),
    ("IsPahawhHmong", 0x0001_6B00, 0x0001_6B8F),
    ("IsKiratRai", 0x0001_6D40, 0x0001_6D7F),
    ("IsMedefaidrin", 0x0001_6E40, 0x0001_6E9F),
    ("IsMiao", 0x0001_6F00, 0x0001_6F9F),
    (
        "IsIdeographicSymbolsandPunctuation",
        0x0001_6FE0,
        0x0001_6FFF,
    ),
    ("IsTangut", 0x0001_7000, 0x0001_87FF),
    ("IsTangutComponents", 0x0001_8800, 0x0001_8AFF),
    ("IsKhitanSmallScript", 0x0001_8B00, 0x0001_8CFF),
    ("IsTangutSupplement", 0x0001_8D00, 0x0001_8D7F),
    ("IsKanaExtended-B", 0x0001_AFF0, 0x0001_AFFF),
    ("IsKanaSupplement", 0x0001_B000, 0x0001_B0FF),
    ("IsKanaExtended-A", 0x0001_B100, 0x0001_B12F),
    ("IsSmallKanaExtension", 0x0001_B130, 0x0001_B16F),
    ("IsNushu", 0x0001_B170, 0x0001_B2FF),
    ("IsDuployan", 0x0001_BC00, 0x0001_BC9F),
    ("IsShorthandFormatControls", 0x0001_BCA0, 0x0001_BCAF),
    (
        "IsSymbolsforLegacyComputingSupplement",
        0x0001_CC00,
        0x0001_CEBF,
    ),
    ("IsZnamennyMusicalNotation", 0x0001_CF00, 0x0001_CFCF),
    ("IsByzantineMusicalSymbols", 0x0001_D000, 0x0001_D0FF),
    ("IsMusicalSymbols", 0x0001_D100, 0x0001_D1FF),
    ("IsAncientGreekMusicalNotation", 0x0001_D200, 0x0001_D24F),
    ("IsKaktovikNumerals", 0x0001_D2C0, 0x0001_D2DF),
    ("IsMayanNumerals", 0x0001_D2E0, 0x0001_D2FF),
    ("IsTaiXuanJingSymbols", 0x0001_D300, 0x0001_D35F),
    ("IsCountingRodNumerals", 0x0001_D360, 0x0001_D37F),
    (
        "IsMathematicalAlphanumericSymbols",
        0x0001_D400,
        0x0001_D7FF,
    ),
    ("IsSuttonSignWriting", 0x0001_D800, 0x0001_DAAF),
    ("IsLatinExtended-G", 0x0001_DF00, 0x0001_DFFF),
    ("IsGlagoliticSupplement", 0x0001_E000, 0x0001_E02F),
    ("IsCyrillicExtended-D", 0x0001_E030, 0x0001_E08F),
    ("IsNyiakengPuachueHmong", 0x0001_E100, 0x0001_E14F),
    ("IsToto", 0x0001_E290, 0x0001_E2BF),
    ("IsWancho", 0x0001_E2C0, 0x0001_E2FF),
    ("IsNagMundari", 0x0001_E4D0, 0x0001_E4FF),
    ("IsOlOnal", 0x0001_E5D0, 0x0001_E5FF),
    ("IsEthiopicExtended-B", 0x0001_E7E0, 0x0001_E7FF),
    ("IsMendeKikakui", 0x0001_E800, 0x0001_E8DF),
    ("IsAdlam", 0x0001_E900, 0x0001_E95F),
    ("IsIndicSiyaqNumbers", 0x0001_EC70, 0x0001_ECBF),
    ("IsOttomanSiyaqNumbers", 0x0001_ED00, 0x0001_ED4F),
    (
        "IsArabicMathematicalAlphabeticSymbols",
        0x0001_EE00,
        0x0001_EEFF,
    ),
    ("IsMahjongTiles", 0x0001_F000, 0x0001_F02F),
    ("IsDominoTiles", 0x0001_F030, 0x0001_F09F),
    ("IsPlayingCards", 0x0001_F0A0, 0x0001_F0FF),
    ("IsEnclosedAlphanumericSupplement", 0x0001_F100, 0x0001_F1FF),
    ("IsEnclosedIdeographicSupplement", 0x0001_F200, 0x0001_F2FF),
    (
        "IsMiscellaneousSymbolsandPictographs",
        0x0001_F300,
        0x0001_F5FF,
    ),
    ("IsEmoticons", 0x0001_F600, 0x0001_F64F),
    ("IsOrnamentalDingbats", 0x0001_F650, 0x0001_F67F),
    ("IsTransportandMapSymbols", 0x0001_F680, 0x0001_F6FF),
    ("IsAlchemicalSymbols", 0x0001_F700, 0x0001_F77F),
    ("IsGeometricShapesExtended", 0x0001_F780, 0x0001_F7FF),
    ("IsSupplementalArrows-C", 0x0001_F800, 0x0001_F8FF),
    (
        "IsSupplementalSymbolsandPictographs",
        0x0001_F900,
        0x0001_F9FF,
    ),
    ("IsChessSymbols", 0x0001_FA00, 0x0001_FA6F),
    (
        "IsSymbolsandPictographsExtended-A",
        0x0001_FA70,
        0x0001_FAFF,
    ),
    ("IsSymbolsforLegacyComputing", 0x0001_FB00, 0x0001_FBFF),
    ("IsCJKUnifiedIdeographsExtensionB", 0x0002_0000, 0x0002_A6DF),
    ("IsCJKUnifiedIdeographsExtensionC", 0x0002_A700, 0x0002_B73F),
    ("IsCJKUnifiedIdeographsExtensionD", 0x0002_B740, 0x0002_B81F),
    ("IsCJKUnifiedIdeographsExtensionE", 0x0002_B820, 0x0002_CEAF),
    ("IsCJKUnifiedIdeographsExtensionF", 0x0002_CEB0, 0x0002_EBEF),
    ("IsCJKUnifiedIdeographsExtensionI", 0x0002_EBF0, 0x0002_EE5F),
    (
        "IsCJKCompatibilityIdeographsSupplement",
        0x0002_F800,
        0x0002_FA1F,
    ),
    ("IsCJKUnifiedIdeographsExtensionG", 0x0003_0000, 0x0003_134F),
    ("IsCJKUnifiedIdeographsExtensionH", 0x0003_1350, 0x0003_23AF),
    ("IsTags", 0x000E_0000, 0x000E_007F),
    ("IsVariationSelectorsSupplement", 0x000E_0100, 0x000E_01EF),
    ("IsSupplementaryPrivateUseArea-A", 0x000F_0000, 0x000F_FFFF),
    ("IsSupplementaryPrivateUseArea-B", 0x0010_0000, 0x0010_FFFF),
];

/// Looks up the inclusive `[lo, hi]` codepoint range for an XSD/XPath
/// block-escape name (e.g. `"IsBasicLatin"`), by linear scan over
/// [`UNICODE_BLOCKS`].
///
/// [`UNICODE_BLOCKS`] is sorted by codepoint (`lo`), not by name -- that is the
/// order that lets [`table_is_sorted_and_non_overlapping`] cheaply prove the
/// table is sorted ascending and non-overlapping (gaps between blocks are
/// legitimate and expected -- most of the Unicode codespace is unassigned --
/// so the test proves non-overlap, not the absence of gaps). A name-keyed
/// binary search would need a second, name-sorted view of the same
/// 338 rows; a linear scan is simpler (one array, ETHOS §S) and this runs at
/// most once per distinct `\p{IsX}`/`\P{IsX}` construct in a pattern being
/// *compiled*, never per matched character -- not a hot path.
///
/// Returns `None` if `name` is not a recognized block name. Per XML Schema
/// Part 2 §G.4.2.4, what an unrecognized block name should mean is a policy
/// decision for the caller (this crate does not implement that fallback here).
pub(crate) fn lookup(name: &str) -> Option<(u32, u32)> {
    UNICODE_BLOCKS
        .iter()
        .find_map(|(candidate, lo, hi)| (*candidate == name).then_some((*lo, *hi)))
}

#[cfg(test)]
mod tests {
    use super::{UNICODE_BLOCKS, lookup};

    #[test]
    fn table_is_sorted_and_non_overlapping() {
        for window in UNICODE_BLOCKS.windows(2) {
            let (_, _, prev_hi) = window[0];
            let (_, next_lo, _) = window[1];
            assert!(
                prev_hi < next_lo,
                "UNICODE_BLOCKS is not sorted-by-codepoint and non-overlapping: \
                 {:?} then {:?}",
                window[0],
                window[1],
            );
        }
    }

    #[test]
    fn known_block_ranges_match_unicode_16_0_0() {
        assert_eq!(lookup("IsBasicLatin"), Some((0x0000_0000, 0x0000_007F)));
        assert_eq!(
            lookup("IsLatin-1Supplement"),
            Some((0x0000_0080, 0x0000_00FF))
        );
        assert_eq!(lookup("IsGreekandCoptic"), Some((0x0000_0370, 0x0000_03FF)));
        assert_eq!(
            lookup("IsCJKUnifiedIdeographs"),
            Some((0x0000_4E00, 0x0000_9FFF))
        );
    }

    #[test]
    fn unknown_block_name_returns_none() {
        assert_eq!(lookup("IsNotARealUnicodeBlock"), None);
    }
}
