// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Shared mapping-DSL infrastructure for the surviving generated-artifact emitters.
//!
//! The four alignment dialects (SSSOM, FnO, EDOAL, SPARQL CONSTRUCT) are now
//! produced by the oxigraph-free `purrdf-logic-compile` correspondence lowerings. The
//! oxigraph-backed alignment rendering that used to live in this crate is gone, but
//! several still-live emitters and lints share a small kernel of infrastructure that
//! the alignment renderers used to host:
//!
//! * the curated [`PREFIX_REGISTRY`] (the single CURIE / prefix authority);
//! * the [`GENERATED_BANNER`] generated-artifact comment;
//! * the [`prefix_block`] SPARQL `PREFIX` emitter;
//! * the merged DSL dataset collector [`collect_dsl_store`] and the generic
//!   dataset helpers (`subjects_of_type`, [`object_literal`]);
//! * the language-retag helper [`retag_quad`].
//!
//! These are extracted verbatim so every surviving byte output is unchanged.

use std::collections::BTreeMap;
use std::path::Path;

use purrdf::{RdfQuad, RdfTerm};

use crate::artifact::ArtifactRole;
use crate::catalog::SliceCatalog;
use crate::error::SliceError;
use crate::rdf_query::{Dataset, DatasetAccumulator};
use crate::vocab::SliceVocab;

/// The generated-banner comment shared by every generated artifact.
pub(crate) const GENERATED_BANNER: &str =
    "GENERATED by `purrdf regenerate` (mappings) from mapping-dsl/ — DO NOT EDIT.";

/// The canonical prefix registry, in `config.PREFIXES` **insertion order**,
/// MINUS the consumer vocabulary entry: the caller's namespace is prepended at
/// runtime via [`effective_registry`] (its historical slot was first, so the
/// CURIE-shortening tie-break is unchanged for the original consumer).
///
/// This is the single authority for both CURIE-shortening (`_sssom_id` ∘ `curie`)
/// and the emitted `# curie_map:` block. It must mirror
/// `src/purrdf_tools/config.py::PREFIXES`, NOT the per-file `@prefix`
/// declarations — those use different prefix *names* for the same namespace
/// (e.g. a source declares `@prefix bf:` where the registry names it `bibframe`),
/// some registry prefixes are never declared in any source they shorten
/// (e.g. `mf` in the places set), and some source prefixes are absent from the
/// registry (e.g. `earl`, which is therefore left as a bare absolute URI). Using
/// `@prefix` declarations instead of this registry produces drift on the
/// committed corpus, so byte-parity demands the curated registry.
///
/// Insertion order is load-bearing: CURIE-shortening sorts by descending
/// namespace length with the *registry order* as the tie-break (mirroring
/// the compiler's stable sort keyed on descending namespace length over the
/// registry's insertion order. The block-comment groupings below follow `config.py`.
pub(crate) const PREFIX_REGISTRY: &[(&str, &str)] = &[
    ("logic", "https://blackcatinformatics.ca/logic/"),
    ("owl", "http://www.w3.org/2002/07/owl#"),
    ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
    ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
    ("xsd", "http://www.w3.org/2001/XMLSchema#"),
    ("skos", "http://www.w3.org/2004/02/skos/core#"),
    ("vs", "http://www.w3.org/2003/06/sw-vocab-status/ns#"),
    ("dcterms", "http://purl.org/dc/terms/"),
    ("dc", "http://purl.org/dc/elements/1.1/"),
    ("dcmitype", "http://purl.org/dc/dcmitype/"),
    ("vann", "http://purl.org/vocab/vann/"),
    ("void", "http://rdfs.org/ns/void#"),
    ("dcat", "http://www.w3.org/ns/dcat#"),
    ("dqv", "http://www.w3.org/ns/dqv#"),
    ("sssom", "https://w3id.org/sssom/"),
    ("semapv", "https://w3id.org/semapv/vocab/"),
    ("fno", "https://w3id.org/function/ontology#"),
    ("fnom", "https://w3id.org/function/vocabulary/mapping#"),
    ("edoal", "http://ns.inria.org/edoal/1.0/#"),
    ("align", "http://knowledgeweb.semanticweb.org/heterogeneity/alignment#"),
    ("gufo", "http://purl.org/nemo/gufo#"),
    ("umbel", "http://umbel.org/umbel#"),
    ("umbelrc", "http://umbel.org/umbel/rc/"),
    ("dul", "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#"),
    ("bfo", "http://purl.obolibrary.org/obo/"),
    ("sumo", "https://www.ontologyportal.org/SUMO.owl#"),
    ("cyc", "http://sw.opencyc.org/2012/05/10/concept/en/"),
    ("foaf", "http://xmlns.com/foaf/0.1/"),
    ("rel", "http://purl.org/vocab/relationship/"),
    ("doap", "http://usefulinc.com/ns/doap#"),
    ("prov", "http://www.w3.org/ns/prov#"),
    ("prof", "http://www.w3.org/ns/dx/prof/"),
    ("sosa", "http://www.w3.org/ns/sosa/"),
    ("ssn", "http://www.w3.org/ns/ssn/"),
    ("sweet", "http://sweetontology.net/"),
    ("om", "http://www.wurvoc.org/vocabularies/om-1.8/"),
    ("qb", "http://purl.org/linked-data/cube#"),
    ("mf", "http://www.opengis.net/ont/movingfeatures#"),
    ("sta", "http://www.opengis.net/def/ont/sensorthings/1.1/"),
    ("iso19156", "http://www.isotc211.org/iso19156/"),
    ("oboe", "http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#"),
    ("obi", "http://purl.obolibrary.org/obo/OBI_"),
    ("iao", "http://purl.obolibrary.org/obo/IAO_"),
    ("pato", "http://purl.obolibrary.org/obo/PATO_"),
    ("crmarc", "http://www.cidoc-crm.org/crmarchaeo/"),
    ("iptc", "http://iptc.org/std/NewsML-G2/"),
    ("bbc", "http://www.bbc.co.uk/ontologies/news/"),
    ("obscore", "http://www.ivoa.net/rdf/ObsCore#"),
    ("ppsr", "https://purl.org/ppsr/core#"),
    ("loinc", "http://loinc.org/rdf/"),
    ("snomed", "http://snomed.info/id/"),
    ("np", "http://www.nanopub.org/nschema#"),
    ("crm", "http://www.cidoc-crm.org/cidoc-crm/"),
    ("crmsci", "http://www.cidoc-crm.org/extensions/crmsci/"),
    ("crminf", "http://www.ics.forth.gr/isl/CRMinf/"),
    ("crmdig", "http://www.ics.forth.gr/isl/CRMdig/"),
    ("oa", "http://www.w3.org/ns/oa#"),
    ("exif", "http://www.w3.org/2003/12/exif/ns#"),
    ("iiif", "http://iiif.io/api/presentation/3#"),
    ("cito", "http://purl.org/spar/cito/"),
    ("credit", "https://credit.niso.org/contributor-roles/"),
    ("pav", "http://purl.org/pav/"),
    ("org", "http://www.w3.org/ns/org#"),
    ("moat", "http://moat-project.org/ns#"),
    ("tags", "http://www.holygoat.co.uk/owl/redwood/0.1/tags/"),
    ("time", "http://www.w3.org/2006/time#"),
    ("teo", "https://sbmi.uth.edu/bsdi/TEO_1.0.0.owl#"),
    ("pos", "http://purl.org/ieee1872-owl/pos#"),
    ("cora", "http://purl.org/ieee1872-owl/cora#"),
    ("knowrob", "http://knowrob.org/kb/knowrob.owl#"),
    ("soma", "http://www.ease-crc.org/ont/SOMA.owl#"),
    ("qudt", "http://qudt.org/schema/qudt/"),
    ("unit", "http://qudt.org/vocab/unit/"),
    ("edtf", "http://id.loc.gov/datatypes/edtf/"),
    ("periodo", "http://n2t.net/ark:/99152/"),
    ("gts", "http://resource.geosciml.org/ontology/timescale/gts#"),
    ("ivoa", "http://www.ivoa.net/rdf/"),
    ("crmgeo", "http://www.ics.forth.gr/isl/CRMgeo/"),
    ("lode", "http://linkedevents.org/ontology/"),
    ("sem", "http://semanticweb.cs.vu.nl/2009/11/sem/"),
    ("ical", "http://www.w3.org/2002/12/cal/icaltzd#"),
    ("schema", "https://schema.org/"),
    ("gedcom", "http://www.w3.org/2000/10/swap/pim/gedcom#"),
    ("vcard", "http://www.w3.org/2006/vcard/ns#"),
    ("mo", "http://purl.org/ontology/mo/"),
    ("mbz", "https://musicbrainz.org/"),
    ("discogs", "https://www.discogs.com/"),
    ("afo", "https://w3id.org/afo/onto/1.1#"),
    ("afv", "https://w3id.org/afo/vocab/1.1#"),
    ("jams", "http://w3id.org/polifonia/ontology/jams/"),
    ("pon", "https://w3id.org/polifonia/ontology/"),
    ("chord", "http://purl.org/ontology/chord/"),
    ("mimo", "http://www.mimo-db.eu/InstrumentsKeywords/"),
    ("pplan", "http://purl.org/net/p-plan#"),
    ("opmw", "https://www.opmw.org/ontology/"),
    ("bpmn", "http://www.omg.org/spec/BPMN/20100524/MODEL#"),
    ("ro_crate", "https://w3id.org/ro/crate/#"),
    ("brick", "https://brickschema.org/schema/Brick#"),
    ("bot", "https://w3id.org/bot#"),
    ("ifc", "http://www.buildingsmart-tech.org/ifcOWL/IFC4#"),
    ("vcardx", "https://blackcatinformatics.ca/vcard-ext/"),
    ("geo", "http://www.opengis.net/ont/geosparql#"),
    ("sf", "http://www.opengis.net/ont/sf#"),
    ("wgs84", "http://www.w3.org/2003/01/geo/wgs84_pos#"),
    ("gtfs", "http://vocab.gtfs.org/terms#"),
    ("tgn", "http://vocab.getty.edu/tgn/"),
    ("lgdo", "http://linkedgeodata.org/ontology/"),
    ("pleiades", "http://pleiades.stoa.org/places/vocab#"),
    ("whg", "https://whgazetteer.org/"),
    ("gvp", "http://vocab.getty.edu/ontology#"),
    ("mrg", "http://marineregions.org/ns/ontology#"),
    ("bibo", "http://purl.org/ontology/bibo/"),
    ("bibframe", "http://id.loc.gov/ontologies/bibframe/"),
    ("dpv", "https://w3id.org/dpv#"),
    ("frbr", "http://purl.org/vocab/frbr/core#"),
    ("fabio", "http://purl.org/spar/fabio/"),
    ("lrmoo", "http://iflastandards.info/ns/lrm/lrmoo/"),
    ("sioc", "http://rdfs.org/sioc/ns#"),
    ("as", "https://www.w3.org/ns/activitystreams#"),
    ("mads", "http://www.loc.gov/mads/rdf/v1#"),
    ("esco", "http://data.europa.eu/esco/model#"),
    ("esco-base", "http://data.europa.eu/esco/"),
    ("ceterms", "https://purl.org/ctdl/terms/"),
    ("ctdlasn", "https://credreg.net/ctdlasn/terms/"),
    ("onet", "https://www.onetcenter.org/"),
    ("nmo", "http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#"),
    ("wot", "http://xmlns.com/wot/0.1/"),
    ("vc", "https://www.w3.org/2018/credentials#"),
    ("did", "https://www.w3.org/ns/did#"),
    ("odrl", "http://www.w3.org/ns/odrl/2/"),
    ("cc", "http://creativecommons.org/ns#"),
    ("premis", "http://www.loc.gov/premis/rdf/v3/"),
    ("rstmt", "https://rightsstatements.org/vocab/"),
    ("ccpd", "https://creativecommons.org/publicdomain/"),
    ("spdx", "http://spdx.org/rdf/terms#"),
    ("spdxlic", "http://spdx.org/licenses/"),
    ("codemeta", "https://codemeta.github.io/terms/#"),
    ("forgefed", "https://forgefed.org/ns#"),
    ("swh", "https://www.softwareheritage.org/data-model/"),
    ("ma", "http://www.w3.org/ns/ma-ont#"),
    ("gsso", "http://purl.obolibrary.org/obo/GSSO_"),
    ("homosaurus", "https://homosaurus.org/v4/"),
    ("fhir", "http://hl7.org/fhir/"),
    ("bio", "http://purl.org/vocab/bio/0.1/"),
    ("gx", "http://gedcomx.org/"),
    ("gxv", "http://gedcomx.org/v1/"),
    ("gn", "http://www.geonames.org/ontology#"),
    ("wd", "http://www.wikidata.org/entity/"),
    ("wdt", "http://www.wikidata.org/prop/direct/"),
    ("wikibase", "http://wikiba.se/ontology#"),
    ("p", "http://www.wikidata.org/prop/"),
    ("ps", "http://www.wikidata.org/prop/statement/"),
    ("wds", "http://www.wikidata.org/entity/statement/"),
    ("lexvo", "http://lexvo.org/id/"),
    ("lvont", "http://lexvo.org/ontology#"),
    ("glottolog", "https://glottolog.org/resource/languoid/id/"),
    ("ontolex", "http://www.w3.org/ns/lemon/ontolex#"),
    ("lime", "http://www.w3.org/ns/lemon/lime#"),
    ("fibo-fnd-acc-cur", "https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/"),
    ("fibo-iso4217", "https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/ISO4217-CurrencyCodes/"),
    ("fibo-fnd-acc-ae", "https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/AccountingEquity/"),
    ("fibo-fnd-pas-ps", "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/"),
    ("fibo-fbc-fi-fi", "https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/"),
    ("fibo-fbc-pas-fpas", "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/"),
    ("mls", "http://www.w3.org/ns/mls#"),
    ("faldo", "http://biohackathon.org/resource/faldo#"),
    ("so", "http://purl.obolibrary.org/obo/SO_"),
    ("ladm", "http://www.opengis.net/ont/ladm#"),
    ("cp", "http://inspire.ec.europa.eu/ont/cp#"),
];

/// The effective prefix registry: the caller's `(prefix_name, ns)` entry first
/// (its historical insertion slot), then the curated static registry with any
/// entry shadowed by the caller's prefix name or namespace removed.
pub(crate) fn effective_registry(vocab: &SliceVocab) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> =
        vec![(vocab.prefix_name().to_owned(), vocab.ns().to_owned())];
    for (prefix, ns) in PREFIX_REGISTRY {
        if *prefix == vocab.prefix_name() || *ns == vocab.ns() {
            continue;
        }
        out.push(((*prefix).to_owned(), (*ns).to_owned()));
    }
    out
}

// ── Merged-store collection ──────────────────────────────────────────────────────

/// Build the merged DSL dataset: the shared `dsl/mappings/**/*.ttl` tree + the slice
/// `mappings/*.ttl` artifacts (the `load_dsl` source set, sorted-path insertion).
pub(crate) fn collect_dsl_store(root: &Path, vocab: &SliceVocab) -> Result<Dataset, SliceError> {
    let mut acc = DatasetAccumulator::new();
    let dsl_dir = root.join("dsl").join("mappings");
    let mut dsl_files: Vec<std::path::PathBuf> = Vec::new();
    collect_ttl_files(&dsl_dir, &mut dsl_files)?;
    dsl_files.sort();
    for path in &dsl_files {
        let bytes = std::fs::read(path).map_err(SliceError::Io)?;
        acc.add_turtle(&bytes, &path.display().to_string())?;
    }
    let slices_dir = root.join("slices");
    if slices_dir.is_dir() {
        let catalog = SliceCatalog::discover(&slices_dir, vocab.clone())?;
        let mut slice_mappings: Vec<(std::path::PathBuf, Vec<u8>)> = Vec::new();
        for record in catalog.records() {
            for artifact in &record.artifacts {
                if artifact.role == ArtifactRole::Mapping {
                    let path = record.slice_dir.join(&artifact.logical_path);
                    slice_mappings.push((path, artifact.content.clone()));
                }
            }
        }
        slice_mappings.sort_by(|a, b| a.0.cmp(&b.0));
        for (path, bytes) in &slice_mappings {
            acc.add_turtle(bytes, &path.display().to_string())?;
        }
    }
    acc.freeze()
}

fn collect_ttl_files(dir: &Path, out: &mut Vec<std::path::PathBuf>) -> Result<(), SliceError> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir).map_err(SliceError::Io)? {
        let entry = entry.map_err(SliceError::Io)?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(SliceError::Io)?;
        if file_type.is_dir() {
            collect_ttl_files(&path, out)?;
        } else if file_type.is_file() && path.extension().and_then(|e| e.to_str()) == Some("ttl") {
            out.push(path);
        }
    }
    Ok(())
}

// ── SPARQL PREFIX block ──────────────────────────────────────────────────────────

/// `_prefix_block`: the registry-ordered SPARQL `PREFIX` block for every prefix
/// token the body references. The caller's vocab entry is consulted first via
/// [`effective_registry`].
pub(crate) fn prefix_block(text: &str, vocab: &SliceVocab) -> String {
    // Strip `<...>` IRIs first.
    let search_text = strip_iris(text);
    let mut lines: Vec<String> = Vec::new();
    for (prefix, ns) in effective_registry(vocab) {
        if has_prefix_token(&search_text, &prefix) {
            lines.push(format!("PREFIX {prefix}: <{ns}>"));
        }
    }
    lines.join("\n")
}

/// Remove every `<...>` span (mirrors `re.sub(r"<[^>]*>", "", text)`).
fn strip_iris(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_iri = false;
    for c in text.chars() {
        if in_iri {
            if c == '>' {
                in_iri = false;
            }
            continue;
        }
        if c == '<' {
            in_iri = true;
            continue;
        }
        out.push(c);
    }
    out
}

/// Whether `text` contains `prefix:` at a position not preceded by a word char
/// (mirrors `re.search(rf"(?<!\w){prefix}:", text)`). `\w` = `[A-Za-z0-9_]`.
fn has_prefix_token(text: &str, prefix: &str) -> bool {
    let needle = format!("{prefix}:");
    let bytes = text.as_bytes();
    let nbytes = needle.as_bytes();
    let mut i = 0usize;
    while i + nbytes.len() <= bytes.len() {
        if &bytes[i..i + nbytes.len()] == nbytes {
            let ok = if i == 0 {
                true
            } else {
                let prev = bytes[i - 1];
                !(prev.is_ascii_alphanumeric() || prev == b'_')
            };
            if ok {
                return true;
            }
        }
        i += 1;
    }
    false
}

/// The CURIE prefix label the fixed query templates in this crate are authored
/// with. At assembly time every `purrdf:` token is renamed to the caller's
/// [`SliceVocab::prefix_name`] and bound to the caller's namespace by the
/// emitted `PREFIX` block, so the templates carry no namespace of their own.
const TEMPLATE_PREFIX: &str = "purrdf";

/// Rename `purrdf:` CURIE tokens (at a non-word-char boundary, mirroring
/// [`prefix_block`]'s token scan) to `{prefix}:`. A no-op when the caller's
/// prefix name is already the template label.
pub(crate) fn rename_template_prefix(text: &str, prefix: &str) -> String {
    if prefix == TEMPLATE_PREFIX {
        return text.to_owned();
    }
    let needle = format!("{TEMPLATE_PREFIX}:");
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(pos) = rest.find(needle.as_str()) {
        let boundary = pos == 0 || {
            let prev = rest.as_bytes()[pos - 1];
            !(prev.is_ascii_alphanumeric() || prev == b'_')
        };
        out.push_str(&rest[..pos]);
        if boundary {
            out.push_str(prefix);
            out.push(':');
        } else {
            out.push_str(&needle);
        }
        rest = &rest[pos + needle.len()..];
    }
    out.push_str(rest);
    out
}

// ── Dataset / term helpers ─────────────────────────────────────────────────────

pub(crate) fn subjects_of_type(store: &Dataset, type_iri: &str) -> Result<Vec<String>, SliceError> {
    store.subjects_of_type(type_iri)
}

pub(crate) fn object_literal(
    store: &Dataset,
    subject: &str,
    pred: &str,
) -> Result<Option<String>, SliceError> {
    store.object_literal(subject, pred)
}

// ── Language-tag retag ───────────────────────────────────────────────────────────

/// Retag a quad's language-tagged literal object through `tag_map` (a public tag —
/// no `x-purrdf-` mapping — passes through unchanged). Only the object can carry a
/// localizable literal in the FnO catalog.
pub(crate) fn retag_quad(mut quad: RdfQuad, tag_map: &BTreeMap<String, String>) -> RdfQuad {
    if let RdfTerm::Literal(lit) = &mut quad.object {
        if let Some(lang) = &lit.language {
            if let Some(ext) = tag_map.get(lang) {
                lit.language = Some(ext.clone());
            }
        }
    }
    quad
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prefix_token_respects_word_boundary() {
        assert!(has_prefix_token("foo purrdf:Place", "purrdf"));
        assert!(has_prefix_token("purrdf:Place", "purrdf"));
        assert!(!has_prefix_token("foo_ps:bar", "ps"));
        assert!(has_prefix_token("(ps:x)", "ps"));
    }
}
