// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Prefix-set projections (§2): the importable named prefix set
//! (`<vocab>CorePrefixes`) and the JSON-LD `@context` document — both *projections*
//! of the single prefix authority (the caller's [`SliceVocab`] entry plus
//! `crate::mapping_support::PREFIX_REGISTRY`).
//!
//! The article's §2 win is "generalize `sh:declare`": instead of every SHACL
//! shape / `.rq` author redeclaring the same prefixes, publish ONE named set,
//! importable by IRI, that consumers reference with `... sh:prefixes
//! <prefix>:CorePrefixes .`. The same registry also drives the JSON-LD `@context`,
//! which replaces the now-retired Python `jsonld_context.py` builder (Python
//! cull — the `@context` builder moves to Rust).
//!
//! Both artifacts are emitted as the `mappings` stage's projection family (they
//! are projections of the prefix authority, exactly like SSSOM / EDOAL / SPARQL),
//! so they ride the existing `generated/` drift gate and fold into `purrdf.gts`
//! with no new pipeline stage. The output is purely a function of the static
//! `PREFIX_REGISTRY`, so it is deterministic by construction (no blank-node
//! canonicalization, no wall-clock content).

use std::fmt::Write as _;

use crate::mapping_support::effective_registry;
use crate::vocab::SliceVocab;

/// Emit the importable SHACL prefix set `<prefix>:CorePrefixes` as canonical
/// Turtle.
///
/// One `sh:declare` blank node per registry entry (the caller's vocab entry
/// first, then the curated registry), in insertion order (load-bearing —
/// mirrors the CURIE-shortening tie-break). The node type is `owl:Ontology`
/// (the SHACL-spec convention for an `sh:prefixes` target); our own SHACL
/// reader (`purrdf_shacl` `prefix_header`) keys off `sh:declare` regardless of
/// the node's type. `sh:namespace` is the spec-typical `xsd:anyURI` literal.
///
/// The set's IRI is [`SliceVocab::core_prefixes_iri`]. For a fixed vocab the
/// output is byte-deterministic.
pub fn emit_core_prefixes(vocab: &SliceVocab) -> String {
    let registry = effective_registry(vocab);
    let prefix = vocab.prefix_name();
    let ns = vocab.ns();
    let ontology_iri = vocab.ontology_iri();
    let mut out = String::new();
    let _ = writeln!(out, "@prefix {prefix}: <{ns}> .");
    out.push_str("@prefix owl: <http://www.w3.org/2002/07/owl#> .\n");
    out.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
    out.push_str("@prefix sh: <http://www.w3.org/ns/shacl#> .\n");
    out.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n");
    out.push('\n');
    let _ = writeln!(out, "{prefix}:CorePrefixes a owl:Ontology ;");
    out.push_str("    rdfs:label \"PURRDF canonical prefix set\"@en ;\n");
    let _ = writeln!(
        out,
        "    rdfs:comment \"GENERATED by `purrdf regenerate` (mappings) from the \
         PREFIX_REGISTRY authority — DO NOT EDIT. The single importable PURRDF prefix \
         set; reference it from a SHACL shape with `sh:prefixes {prefix}:CorePrefixes`.\"@en ;"
    );
    let _ = writeln!(
        out,
        "    <http://purl.org/dc/terms/isPartOf> <{ontology_iri}> ;"
    );
    out.push_str("    sh:declare\n");
    let last = registry.len() - 1;
    for (i, (prefix, ns)) in registry.iter().enumerate() {
        let terminator = if i == last { " ." } else { " ," };
        let _ = writeln!(
            out,
            "        [ sh:prefix \"{prefix}\" ; sh:namespace \"{ns}\"^^xsd:anyURI ]{terminator}"
        );
    }
    out
}

/// Emit the JSON-LD `@context` document from the prefix authority.
///
/// Replaces `src/purrdf_tools/jsonld_context.py::build_context`. Shape:
/// `{"@context": {"@vocab": <vocab ns>, <prefix>: <namespace>, ...}}` with a
/// trailing newline, 2-space indent, registry insertion order preserved (the
/// caller's vocab entry first) — the same logical document the retired Python
/// builder produced.
pub fn emit_jsonld_context(vocab: &SliceVocab) -> String {
    let registry = effective_registry(vocab);
    let mut source = serde_json::Map::new();
    source.insert(
        "@vocab".to_owned(),
        serde_json::Value::String(vocab.ns().to_owned()),
    );
    for (prefix, namespace) in &registry {
        source.insert(prefix.clone(), serde_json::Value::String(namespace.clone()));
    }
    let compiled = purrdf::native_codecs::jsonld::CompiledJsonLdContext::compile(
        &serde_json::Value::Object(source),
        None,
    )
    .expect("validated slice prefix authority must compile as a JSON-LD context");
    let canonical = compiled
        .canonical_context()
        .as_object()
        .expect("compiled slice context is an object");
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"@context\": {\n");
    let canonical_vocab = canonical
        .get("@vocab")
        .and_then(serde_json::Value::as_str)
        .expect("compiled slice context retains @vocab");
    let _ = writeln!(out, "    \"@vocab\": {},", json_string(canonical_vocab));
    let last = registry.len() - 1;
    for (i, (prefix, _)) in registry.iter().enumerate() {
        let comma = if i == last { "" } else { "," };
        let namespace = canonical
            .get(prefix)
            .and_then(serde_json::Value::as_str)
            .expect("compiled slice context retains prefix mapping");
        let _ = writeln!(
            out,
            "    {}: {}{comma}",
            json_string(prefix),
            json_string(namespace)
        );
    }
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

/// Minimal JSON string escaping (the registry holds plain prefixes and URIs, but
/// escape defensively so a future entry with a quote/backslash cannot emit broken
/// JSON).
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pure fixtures use a caller-supplied example.org vocabulary with an
    /// explicit CURIE prefix name.
    fn vocab() -> SliceVocab {
        SliceVocab::for_namespace("https://example.org/vocab/").with_prefix_name("ex")
    }

    #[test]
    fn core_prefixes_is_well_formed_and_importable() {
        let vocab = vocab();
        let ttl = emit_core_prefixes(&vocab);
        // The importable node and the generalized sh:declare surface are present,
        // minted under the caller's vocabulary.
        assert!(ttl.contains("@prefix ex: <https://example.org/vocab/> ."));
        assert!(ttl.contains("ex:CorePrefixes a owl:Ontology"));
        assert!(ttl.contains("<http://purl.org/dc/terms/isPartOf> <https://example.org/vocab>"));
        assert!(ttl.contains("sh:declare"));
        // Every registry prefix appears exactly once as an sh:prefix declaration.
        let registry = effective_registry(&vocab);
        assert_eq!(
            registry[0],
            ("ex".to_owned(), "https://example.org/vocab/".to_owned())
        );
        for (prefix, ns) in &registry {
            let decl = format!("[ sh:prefix \"{prefix}\" ; sh:namespace \"{ns}\"^^xsd:anyURI ]");
            assert!(ttl.contains(&decl), "missing declaration for {prefix}");
        }
        // Exactly one statement terminator (the last declaration ends the triple).
        assert_eq!(
            ttl.matches("^^xsd:anyURI ] .").count(),
            1,
            "expected a single closing '.'"
        );
        assert_eq!(
            ttl.matches("^^xsd:anyURI ] ,").count(),
            registry.len() - 1,
            "every non-final declaration is comma-separated"
        );
    }

    #[test]
    fn jsonld_context_is_well_formed() {
        let vocab = vocab();
        let json = emit_jsonld_context(&vocab);
        // Structural shape: a single @context object with @vocab + every prefix.
        assert!(json.starts_with("{\n  \"@context\": {\n"));
        assert!(json.contains("\"@vocab\": \"https://example.org/vocab/\",\n"));
        let registry = effective_registry(&vocab);
        for (prefix, ns) in &registry {
            let entry = format!("\"{prefix}\": \"{ns}\"");
            assert!(
                json.contains(&entry),
                "context missing mapping for {prefix}"
            );
        }
        // Braces balance and the document ends with a single trailing newline.
        assert_eq!(json.matches('{').count(), json.matches('}').count());
        assert!(json.ends_with("}\n}\n"));
        // 4-space-indented mapping entries: @vocab + one line per registry prefix.
        let entry_lines = json.lines().filter(|l| l.starts_with("    \"")).count();
        assert_eq!(entry_lines, registry.len() + 1);
    }

    #[test]
    fn both_artifacts_are_deterministic() {
        let vocab = vocab();
        assert_eq!(emit_core_prefixes(&vocab), emit_core_prefixes(&vocab));
        assert_eq!(emit_jsonld_context(&vocab), emit_jsonld_context(&vocab));
    }
}
