// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Prefix-set projections (#1009 §2): the importable named prefix set
//! (`purrdf:CorePrefixes`) and the JSON-LD `@context` document — both *projections*
//! of the single prefix authority [`crate::mapping_support::PREFIX_REGISTRY`].
//!
//! The article's §2 win is "generalize `sh:declare`": instead of every SHACL
//! shape / `.rq` author redeclaring the same prefixes, publish ONE named set,
//! importable by IRI, that consumers reference with `... sh:prefixes
//! purrdf:CorePrefixes .`. The same registry also drives the JSON-LD `@context`,
//! which replaces the now-retired Python `jsonld_context.py` builder (#933 Python
//! cull — the `@context` builder moves to Rust).
//!
//! Both artifacts are emitted as the `mappings` stage's projection family (they
//! are projections of the prefix authority, exactly like SSSOM / EDOAL / SPARQL),
//! so they ride the existing `generated/` drift gate and fold into `purrdf.gts`
//! with no new pipeline stage. The output is purely a function of the static
//! `PREFIX_REGISTRY`, so it is deterministic by construction (no blank-node
//! canonicalization, no wall-clock content).

use crate::mapping_support::PREFIX_REGISTRY;

/// IRI of the importable named prefix set.
pub const CORE_PREFIXES_IRI: &str = "https://blackcatinformatics.ca/purrdf/CorePrefixes";

/// The PURRDF base namespace (the registry's `purrdf` entry; also the `@context`
/// `@vocab`). Asserted against `PREFIX_REGISTRY` at emit time, never duplicated.
const PURRDF_NS: &str = "https://blackcatinformatics.ca/purrdf/";

/// Emit the importable SHACL prefix set `purrdf:CorePrefixes` as canonical Turtle.
///
/// One `sh:declare` blank node per registry entry, in `PREFIX_REGISTRY` insertion
/// order (load-bearing — mirrors the CURIE-shortening tie-break). The node type is
/// `owl:Ontology` (the SHACL-spec convention for an `sh:prefixes` target); our own
/// SHACL reader (`purrdf_shacl` `prefix_header`) keys off `sh:declare` regardless of
/// the node's type. `sh:namespace` is the spec-typical `xsd:anyURI` literal.
pub fn emit_core_prefixes() -> String {
    // Single-source the set's identity from `CORE_PREFIXES_IRI`: derive the `purrdf:`
    // CURIE local name from the const rather than re-hardcoding the literal, so the
    // exported IRI authority and the emitted node can never drift apart.
    let local = CORE_PREFIXES_IRI
        .strip_prefix(PURRDF_NS)
        .expect("CORE_PREFIXES_IRI must live under the purrdf namespace");
    let mut out = String::new();
    out.push_str("@prefix purrdf: <https://blackcatinformatics.ca/purrdf/> .\n");
    out.push_str("@prefix owl: <http://www.w3.org/2002/07/owl#> .\n");
    out.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
    out.push_str("@prefix sh: <http://www.w3.org/ns/shacl#> .\n");
    out.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n");
    out.push('\n');
    out.push_str(&format!("purrdf:{local} a owl:Ontology ;\n"));
    out.push_str("    rdfs:label \"PURRDF canonical prefix set\"@en ;\n");
    out.push_str(
        "    rdfs:comment \"GENERATED by `purrdf regenerate` (mappings) from the \
         PREFIX_REGISTRY authority — DO NOT EDIT. The single importable PURRDF prefix \
         set; reference it from a SHACL shape with `sh:prefixes purrdf:CorePrefixes`.\"@en ;\n",
    );
    out.push_str(
        "    <http://purl.org/dc/terms/isPartOf> <https://blackcatinformatics.ca/purrdf> ;\n",
    );
    out.push_str("    sh:declare\n");
    let last = PREFIX_REGISTRY.len() - 1;
    for (i, (prefix, ns)) in PREFIX_REGISTRY.iter().enumerate() {
        let terminator = if i == last { " ." } else { " ," };
        out.push_str(&format!(
            "        [ sh:prefix \"{prefix}\" ; sh:namespace \"{ns}\"^^xsd:anyURI ]{terminator}\n"
        ));
    }
    out
}

/// Emit the JSON-LD `@context` document from the prefix authority.
///
/// Replaces `src/purrdf_tools/jsonld_context.py::build_context` (#933). Shape:
/// `{"@context": {"@vocab": <purrdf ns>, <prefix>: <namespace>, ...}}` with a
/// trailing newline, 2-space indent, registry insertion order preserved — the
/// same logical document the retired Python builder produced.
pub fn emit_jsonld_context() -> String {
    // Fail-fast in ALL build profiles (CONSTITUTION no-optionality): a release
    // build that silently skipped this would let a registry/`@vocab` drift ship.
    assert_eq!(
        registry_ns("purrdf"),
        Some(PURRDF_NS),
        "PREFIX_REGISTRY purrdf entry must match the @context @vocab"
    );
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"@context\": {\n");
    out.push_str(&format!("    \"@vocab\": {},\n", json_string(PURRDF_NS)));
    let last = PREFIX_REGISTRY.len() - 1;
    for (i, (prefix, ns)) in PREFIX_REGISTRY.iter().enumerate() {
        let comma = if i == last { "" } else { "," };
        out.push_str(&format!(
            "    {}: {}{comma}\n",
            json_string(prefix),
            json_string(ns)
        ));
    }
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

/// The namespace for a registry prefix, if present.
fn registry_ns(prefix: &str) -> Option<&'static str> {
    PREFIX_REGISTRY
        .iter()
        .find(|(p, _)| *p == prefix)
        .map(|(_, ns)| *ns)
}

/// Minimal JSON string escaping (the registry holds plain prefixes and URIs, but
/// escape defensively so a future entry with a quote/backslash cannot emit broken
/// JSON).
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn core_prefixes_is_well_formed_and_importable() {
        let ttl = emit_core_prefixes();
        // The importable node and the generalized sh:declare surface are present.
        assert!(ttl.contains("purrdf:CorePrefixes a owl:Ontology"));
        assert!(ttl.contains("sh:declare"));
        // Every registry prefix appears exactly once as an sh:prefix declaration.
        for (prefix, ns) in PREFIX_REGISTRY {
            let decl = format!("[ sh:prefix \"{prefix}\" ; sh:namespace \"{ns}\"^^xsd:anyURI ]");
            assert!(ttl.contains(&decl), "missing declaration for {prefix}");
        }
        // Exactly one statement terminator (the last declaration ends the triple).
        assert_eq!(
            ttl.matches("^^xsd:anyURI ] .").count(),
            1,
            "expected a single closing '.'"
        );
        assert_eq!(
            ttl.matches("^^xsd:anyURI ] ,").count(),
            PREFIX_REGISTRY.len() - 1,
            "every non-final declaration is comma-separated"
        );
    }

    #[test]
    fn jsonld_context_is_well_formed() {
        let json = emit_jsonld_context();
        // Structural shape: a single @context object with @vocab + every prefix.
        assert!(json.starts_with("{\n  \"@context\": {\n"));
        assert!(json.contains(&format!("\"@vocab\": \"{PURRDF_NS}\",\n")));
        for (prefix, ns) in PREFIX_REGISTRY {
            let entry = format!("\"{prefix}\": \"{ns}\"");
            assert!(
                json.contains(&entry),
                "context missing mapping for {prefix}"
            );
        }
        // Braces balance and the document ends with a single trailing newline.
        assert_eq!(json.matches('{').count(), json.matches('}').count());
        assert!(json.ends_with("}\n}\n"));
        // 4-space-indented mapping entries: @vocab + one line per registry prefix.
        let entry_lines = json.lines().filter(|l| l.starts_with("    \"")).count();
        assert_eq!(entry_lines, PREFIX_REGISTRY.len() + 1);
    }

    #[test]
    fn both_artifacts_are_deterministic() {
        assert_eq!(emit_core_prefixes(), emit_core_prefixes());
        assert_eq!(emit_jsonld_context(), emit_jsonld_context());
    }
}
