// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

//! @generated by `cargo run -p purrdf-lex --example gen_unicode_tables --locked -- xpath-dated-blocks`.
//! Do not hand-edit; `scripts/check-generated.sh` diffs this file against the
//! generator's stdout.
//!
//! The block names recognized by XML Schema Part 2 Second Edition.
//!
//! Appendix F.1.1 of the 28 October 2004 Recommendation lists, in its own
//! table, the block names every minimally conforming processor must recognize:
//! the Unicode 3.1 blocks current when that edition became a Recommendation.
//! Both dated XPath laws state that their syntax and semantics are those of
//! that edition with additions, so its table is part of each dated law. Three
//! names have no Unicode 17 counterpart (`Greek`, `CombiningMarksforSymbols`
//! and `PrivateUse`), and four ranges differ from their Unicode 17 extent.
//!
//! This is the Recommendation's table, not Unicode Character Database data:
//! `Specials` appears there twice, so it carries both of its listed ranges.
//! Rows are sorted by name for an exact binary search.
//!
//! Source: the Recommendation vendored verbatim as
//! `vectors/w3c-recs/REC-xmlschema-2-20041028.html`, read as the table that
//! follows its production \[36\] `IsBlock`, in the table's row order.
//!
//! <https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#charcter-classes>

/// `\p{IsX}` names of the XSD 1.0 Second Edition table, with their ranges.
pub(super) const XSD10_SECOND_EDITION: &[(&str, &[(u32, u32)])] = &[
    ("IsAlphabeticPresentationForms", &[(0xFB00, 0xFB4F)]),
    ("IsArabic", &[(0x0600, 0x06FF)]),
    ("IsArabicPresentationForms-A", &[(0xFB50, 0xFDFF)]),
    ("IsArabicPresentationForms-B", &[(0xFE70, 0xFEFE)]),
    ("IsArmenian", &[(0x0530, 0x058F)]),
    ("IsArrows", &[(0x2190, 0x21FF)]),
    ("IsBasicLatin", &[(0x0000, 0x007F)]),
    ("IsBengali", &[(0x0980, 0x09FF)]),
    ("IsBlockElements", &[(0x2580, 0x259F)]),
    ("IsBopomofo", &[(0x3100, 0x312F)]),
    ("IsBopomofoExtended", &[(0x31A0, 0x31BF)]),
    ("IsBoxDrawing", &[(0x2500, 0x257F)]),
    ("IsBraillePatterns", &[(0x2800, 0x28FF)]),
    ("IsCJKCompatibility", &[(0x3300, 0x33FF)]),
    ("IsCJKCompatibilityForms", &[(0xFE30, 0xFE4F)]),
    ("IsCJKCompatibilityIdeographs", &[(0xF900, 0xFAFF)]),
    ("IsCJKRadicalsSupplement", &[(0x2E80, 0x2EFF)]),
    ("IsCJKSymbolsandPunctuation", &[(0x3000, 0x303F)]),
    ("IsCJKUnifiedIdeographs", &[(0x4E00, 0x9FFF)]),
    ("IsCJKUnifiedIdeographsExtensionA", &[(0x3400, 0x4DB5)]),
    ("IsCherokee", &[(0x13A0, 0x13FF)]),
    ("IsCombiningDiacriticalMarks", &[(0x0300, 0x036F)]),
    ("IsCombiningHalfMarks", &[(0xFE20, 0xFE2F)]),
    ("IsCombiningMarksforSymbols", &[(0x20D0, 0x20FF)]),
    ("IsControlPictures", &[(0x2400, 0x243F)]),
    ("IsCurrencySymbols", &[(0x20A0, 0x20CF)]),
    ("IsCyrillic", &[(0x0400, 0x04FF)]),
    ("IsDevanagari", &[(0x0900, 0x097F)]),
    ("IsDingbats", &[(0x2700, 0x27BF)]),
    ("IsEnclosedAlphanumerics", &[(0x2460, 0x24FF)]),
    ("IsEnclosedCJKLettersandMonths", &[(0x3200, 0x32FF)]),
    ("IsEthiopic", &[(0x1200, 0x137F)]),
    ("IsGeneralPunctuation", &[(0x2000, 0x206F)]),
    ("IsGeometricShapes", &[(0x25A0, 0x25FF)]),
    ("IsGeorgian", &[(0x10A0, 0x10FF)]),
    ("IsGreek", &[(0x0370, 0x03FF)]),
    ("IsGreekExtended", &[(0x1F00, 0x1FFF)]),
    ("IsGujarati", &[(0x0A80, 0x0AFF)]),
    ("IsGurmukhi", &[(0x0A00, 0x0A7F)]),
    ("IsHalfwidthandFullwidthForms", &[(0xFF00, 0xFFEF)]),
    ("IsHangulCompatibilityJamo", &[(0x3130, 0x318F)]),
    ("IsHangulJamo", &[(0x1100, 0x11FF)]),
    ("IsHangulSyllables", &[(0xAC00, 0xD7A3)]),
    ("IsHebrew", &[(0x0590, 0x05FF)]),
    ("IsHiragana", &[(0x3040, 0x309F)]),
    ("IsIPAExtensions", &[(0x0250, 0x02AF)]),
    ("IsIdeographicDescriptionCharacters", &[(0x2FF0, 0x2FFF)]),
    ("IsKanbun", &[(0x3190, 0x319F)]),
    ("IsKangxiRadicals", &[(0x2F00, 0x2FDF)]),
    ("IsKannada", &[(0x0C80, 0x0CFF)]),
    ("IsKatakana", &[(0x30A0, 0x30FF)]),
    ("IsKhmer", &[(0x1780, 0x17FF)]),
    ("IsLao", &[(0x0E80, 0x0EFF)]),
    ("IsLatin-1Supplement", &[(0x0080, 0x00FF)]),
    ("IsLatinExtended-A", &[(0x0100, 0x017F)]),
    ("IsLatinExtended-B", &[(0x0180, 0x024F)]),
    ("IsLatinExtendedAdditional", &[(0x1E00, 0x1EFF)]),
    ("IsLetterlikeSymbols", &[(0x2100, 0x214F)]),
    ("IsMalayalam", &[(0x0D00, 0x0D7F)]),
    ("IsMathematicalOperators", &[(0x2200, 0x22FF)]),
    ("IsMiscellaneousSymbols", &[(0x2600, 0x26FF)]),
    ("IsMiscellaneousTechnical", &[(0x2300, 0x23FF)]),
    ("IsMongolian", &[(0x1800, 0x18AF)]),
    ("IsMyanmar", &[(0x1000, 0x109F)]),
    ("IsNumberForms", &[(0x2150, 0x218F)]),
    ("IsOgham", &[(0x1680, 0x169F)]),
    ("IsOpticalCharacterRecognition", &[(0x2440, 0x245F)]),
    ("IsOriya", &[(0x0B00, 0x0B7F)]),
    ("IsPrivateUse", &[(0xE000, 0xF8FF)]),
    ("IsRunic", &[(0x16A0, 0x16FF)]),
    ("IsSinhala", &[(0x0D80, 0x0DFF)]),
    ("IsSmallFormVariants", &[(0xFE50, 0xFE6F)]),
    ("IsSpacingModifierLetters", &[(0x02B0, 0x02FF)]),
    ("IsSpecials", &[(0xFEFF, 0xFEFF), (0xFFF0, 0xFFFD)]),
    ("IsSuperscriptsandSubscripts", &[(0x2070, 0x209F)]),
    ("IsSyriac", &[(0x0700, 0x074F)]),
    ("IsTamil", &[(0x0B80, 0x0BFF)]),
    ("IsTelugu", &[(0x0C00, 0x0C7F)]),
    ("IsThaana", &[(0x0780, 0x07BF)]),
    ("IsThai", &[(0x0E00, 0x0E7F)]),
    ("IsTibetan", &[(0x0F00, 0x0FFF)]),
    ("IsUnifiedCanadianAboriginalSyllabics", &[(0x1400, 0x167F)]),
    ("IsYiRadicals", &[(0xA490, 0xA4CF)]),
    ("IsYiSyllables", &[(0xA000, 0xA48F)]),
];

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::XSD10_SECOND_EDITION;

    #[test]
    fn dated_table_is_name_sorted_and_has_the_recommendations_rows() {
        assert!(
            XSD10_SECOND_EDITION
                .windows(2)
                .all(|pair| pair[0].0 < pair[1].0)
        );
        // 85 table rows; `Specials` occupies two of them.
        let rows: usize = XSD10_SECOND_EDITION
            .iter()
            .map(|(_, ranges)| ranges.len())
            .sum();
        assert_eq!((XSD10_SECOND_EDITION.len(), rows), (84, 85));
        for (name, ranges) in XSD10_SECOND_EDITION {
            assert!(name.starts_with("Is"), "{name}");
            assert!(
                ranges.iter().all(|&(lo, hi)| lo <= hi && hi <= 0xFFFD),
                "{name}"
            );
        }
    }
}
