# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0
SELECT ?s WHERE {
  ?s <http://example.org/v> ?a .
  OPTIONAL { ?s <http://example.org/w> ?b }
  FILTER NOT EXISTS { ?s <http://example.org/v> ?a . FILTER(?a > 10) }
}
