# Additional emitted-boundary repair proposals

Status: PROPOSALS ONLY. No Project/checkpoint implementation or compilation performed. Prior actual cost findings remain FAILED; final df2 artifacts must establish the result.

Project's existing eval_project_sequence is forced inline, but its outer map/collect emits an out-of-line standard-library SpecFromIter specialization. Proposed smallest change: replace only that outer collect with Vec::with_capacity(seq.rows.len()) and an explicit loop pushing the identical inner SmallVec column projection. This retains one traversal, row order, unbound cells, source lookups, schema/lift result and exact output capacity; empty input still allocates no output storage. Keep the sole shared projection home and inner cell conversion. Exact allocator samples and complete Project IR/assembly/drop paths must verify the result; loop syntax is not an erasure proof.

Forked Filter/Extend's added post-join boundaries are specifically RowCheckpoint::commit_rows, commit and commit_into. Existing for_rows/pass calls also occur in baseline and are not new blockers. Proposed smallest control is reasoned, tightly scoped inline(always) plus the specific clippy allowance on those three existing RowCheckpoint methods. Preserve all assertions, native buffer reuse, ordered conversion, governed replay/chunk accounting and continuations. Do not copy a fast path or touch ItemCheckpoint variants without an actual finding. The large governed body can expose another internal specialization; do not blanket-annotate callees or count shorter enclosing frames as proof. Final paired df2 emission must inspect sequential and forked calls/frames, worker captures, drop and source ordering.

The existing GRAPH helper repair likewise needs actual final erasure proof. One complete final source-bound paired emission campaign can cover all repaired homes; no per-function diagnostic ceremony or relaxed equality law. Main's intentional PreparedQuery/EvalCtx changes belong to both final sides by using the actual df2 baseline, not by normalizing measurements. ABI/frame/capture/drop/old-arm loop/numeric proof remains mandatory beyond 32 finite records.
