# Final selected evidence credential-policy first phase

2026-10-08. **First-phase scan COMPLETE; artifact packaging/capture/publication NOT performed.** The actual capture helper's unchanged CREDENTIAL expression was read from `/home/paudley/stage/stage-scripts/ghprsq-stage.py`. Standard rg scanned raw complete binary/plaintext bytes using precisely that expression; gzip/zstd/tar/unzip supplied decompressed/member streams. Only matching filenames/counts were reported, never matched credential text. No private Python checker, build, shipping source/index/forge mutation or capture operation was used.

## Exact inventory and terminals

All raw receipts are under `raw/final-credential-policy-scan-20261008/`. Selected-path inventory contains24,415 distinct regular nonsymlink paths: complete then-current selected Stage; proposed immutable-baseline85204 and candidate85330 top-level receipts/emitted/native/host selected artifacts; owning Rust/docs/generation/wheel/publication inputs; all164 rendered support artifacts; current tracked source paths; exact wheel and original baseline source.tar. Existing historical failures remain included. Before modes/sizes and SHA snapshots completed actual73557 exit0. The selected Stage portion is5,294files/5,781,464,175bytes with nine files over100,000,000bytes; its size is still a real packaging/publication constraint.

Raw scan21266 reported four matching paths with successful raw scanner admission0. Its later initial archive loop exited2 at the intentional traversal fixture; retained archive-errors/status identify the refused member path. The initial approach did not finish archive coverage and is not represented as a pass. Corrected89059 completed exit0 using output-only `tar -xOPf`, with no filesystem extraction; all26 archives have actual producer0 and matcher0/1, zero corrected error lines. This covers15 existing selected gzip archives, nine current tracked tar/gzip/zstd fixtures, one original baseline source.tar and one wheel. Every tar/zip member list is retained. Decompressed matching-archive inventory contains only the baseline source tar. No existing proof gzip or wheel member stream matched.

Nine nested archive members inside baseline source.tar were independently byte/hash matched against their current tracked originals, whose raw/decompressed streams were scanned. This establishes coverage of baseline nested compressed fixtures rather than treating outer tar bytes as decompressed nested content. Deliberate absolute/traversal/symlink/special-node test neighbors remain untouched; output-only absolute-name reads scan their data without accepting their extraction paths. The original traversal-parser error is retained separately from corrected zero-error policy coverage.

Source-member/count readback proves one match each in the two known baseline source members. Whole after modes/sizes/SHA inventory was also captured by36312. Its final diff returned1 because two live hosted-monitor reports changed during the scan: tasks/current-hosted-ed14/current-job-pages.json and run-watch.log. Full difference is retained. All other listed bytes—including every large historical/proposed artifact and source snapshot—remain identical. Those two concurrent report updates are not corruption or stable final capture; fresh final scan/freeze after evidence writers stop remains required. The later authorized editable proposal change is separately preserved/read back and rescanned, rather than misrepresented as original byte identity.

## Actual matches and ownership

Filename-only raw matches:

- `tasks/portfolio-final-evidence-packaging-proposal.md`: editable prose had literally restated a token prefix from the policy. This is a real helper-policy match, not evidence of a runtime credential. Root authorized replacement with the descriptive pointer to the actual helper.
- `crates/gts/src/openpgp.rs`: the owned armor parser's private-key marker string is public first-party code. Its actual match is not an authentication credential, but the current helper policy would still reject raw source copying.
- `vectors/openpgp/test_key.sec.asc`: tracked447-byte public frozen test-key fixture used by the owned transport/signing tests. It remains immutable; no key/source redaction was performed.
- `/opt/purrdf-454-native-cost-main-df2cec88/source.tar`: contains those two public source/fixture markers; matching member/count receipts confirm their attribution. Its original bytes and hash/readbacks remain outside selected publication.

Original rejected proposal bytes were preserved only under the exclusive private history directory named by proposal-private-history-root.txt. Actual preservation/cmp/SHA exit0. That original is not selected, compressed or published. No unchanged proof record was removed or concealed. Revised selected prose uses descriptive policy language and contains no matching literals. Source reconstructability uses canonical Git baseline df2/head audit ancestry plus exact tracked-path/hash manifests; raw full source tar and source copies will not enter selected Stage. This is root's explicit packaging decision, not a relaxed regex or source exclusion disguised as a scan pass.

After the authorized proposal correction and this report, actual current complete selected-Stage raw rescan exited0 with zero matching filenames and zero error lines; current-selected-stage-matches/errors retain that result. Revised proposal SHA is retained separately. This result is the current raw Stage policy checkpoint, not stable capture admission while other evidence writers remain active; prior unchanged decompressed proof streams retain their separately checked scope.

## Concrete next admission

The revised packaging proposal requires separate root admission before copying/compression. Preserve every historical record and all original large bytes. Measure canonical SHA/size groups and byte equality, then compress one representative per identity and retain reconstruction mappings for every role/path; do not trust the20% estimate. Actual deterministic gzip validation/full cmp/decompressed hash, all noncompressed copy readbacks, maximum stored blob and actual capture pack must fit conservative file limits and the2GiB single-push limit. Rendered164-member support data belongs in a lossless tar.gz with exact paths/modes/hash manifest, not new live Stage JavaScript files. No LFS, alternate repository, guard change or multi-push bypass is proposed.

Emitted analytical proof remains actual72fa/85330 against85204, applicable by reviewed test-only1905 delta; no fresh emission is implied. Final writer stop, current complete policy re-scan, artifact representation admission and supported capture preview are still pending. No large copy, new compression, relocation/removal, evidence capture, Git object/ref publication or forge operation occurred in this first phase.
