Task 1 core implementation is complete in signed commit e72660e8769af222387ecc4fd4f84ea9887e43a1 on `paudley/454-rdflib-shim-algebra-level-reassignment`, synchronized with current main 863c75e2.

The typed contextual preparation route now compiles graph context, actual returned domains, and initial bindings through the existing Rust algebra/evaluator/VM. It covers reassignment and alias collisions, lazy and nonlazy joins, OPTIONAL remembered retry and callback order, logical MINUS/DISTINCT/aggregate domains, grouped HAVING/ORDER, GRAPH context restoration, EXISTS projection/correlation, empty public projections, duplicate output columns, and ASK first accepted witnesses. Ordinary Rust and SHACL preparation retain their existing behavior and reject contextual IR at ordinary transformation admission.

Executed qualification includes all 241 frozen genuine rdflib 7.6.0 oracle cases, six additional BNODE identity controls, exhaustive group/ASK fuel cutoffs, production and iterative deep/proportional controls; 464 algebra and 1375 evaluator unit tests; 25 strict EXISTS and 16 current-base prebinding controls; 27 actual SHACL prebinding controls; five focused dependent visitor/admission controls; all 29 SPARQL 1.1 manifest groups, 25 relevant SPARQL 1.0 cases, and two SPARQL 1.2 grouping cases. Prepared execution's intended-profile 17 tests pass. Affected shipping code and selected release tests are warning-clean, supported-profile affected consumer test Clippy passes, structural/helper/layer checks pass, and affected target compilation passes. The unchanged debug-only memo-export failure in broad release-profile test selection is retained separately rather than misreported as a pass.

Independent implementation and native-cost reviews pass at the frozen source. New code is original first-party Rust with no copied upstream bodies/tables, second parser/evaluator, runtime rdflib import, dependency, or semantic feature. Native preservation was qualified logically through actual source operation sequences, layout/retained storage, paired untimed allocation/resource receipts, and attributable emitted native ABI/frame/tail-call evidence. No host timing benchmark was used.

Task 2 remains the authorized next task: actual Python compatibility wiring, the full available consumer differential matrix, and maintained documentation. Configured callback laws above execute through the shared Rust registry/VM; they do not claim that the preexisting Python custom-function surface executes callbacks. The issue is not yet complete.

