<!-- SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca> -->
<!-- SPDX-License-Identifier: CC-BY-4.0 -->

# Task 1 implementation and qualification

Status: SUCCESS. Task 1 implementation, qualification, independent reviews, signed normal-hook commit, push/OID readback, and authorized task issue update are complete. This is core-task completion, not issue completion or Python-surface qualification.

## Exact source and provenance

Worktree: `/home/paudley/Active/purrdf/.worktrees/454-rdflib-shim-algebra-level-reassignment`.
All paths below are relative to its Stage directory `.stage/rdflib-shim-algebra-level-reassignment` unless identified as shipping paths.

The synchronized base is `863c75e2c1e13001bcbe025820d257bd0ee49c4f`, tree `42cce1fededb04e9a7283bfa589b61e1ca34203c`. The original `18489a91cb452b1773c60b469d4c30dc33a9a4a4` receipts remain historical. `raw/t1-source-base-synchronization.log` records the exact task-owned stash, fast-forward, and clean application; unrelated sibling work was preserved. New-main's native VALUES/prebinding changes are retained. `raw/t1-final-source-identity.log`, `raw/t1-final-shipping-sha256.log`, and `raw/t1-final-shipping-tracked.diff` identify the final tracked delta and all three untracked shipping files. No shipping source changed during the final thin-Apply artifact build or subsequent final semantic gates.

Every new implementation body is original first-party Rust. Genuine rdflib 7.6.0 was inspected and executed only as the primary behavior oracle. No upstream implementation body, table, parser, evaluator, dependency, or runtime import was copied or added. The permanent JSON fixture retains oracle inputs and observable answers, not executable upstream code. The owned fixture freezer and untimed qualification probes are original Rust diagnostics under Stage, outside shipping source. There are no new semantic Cargo features, dependencies, tool credits, issue/PR/process references in shipping code, TODO/FIXME stubs, test deletions, new xfails, or deficiency/helper-ledger waivers.

Shipping files are the 34 tracked paths enumerated in the identity receipt plus `crates/sparql-eval/src/rdflib.rs`, `crates/sparql-eval/tests/rdflib_contextual.rs`, and `crates/sparql-eval/tests/fixtures/contextual-mappings.json`. Core homes are algebra/parser/walk/traits/validation and evaluator/compiler/engine/shared operator/governor/substitution/schema/extension seams. Explicit affected consumer arms and focused tests are in RDF dataset-description causes, slice ownership, shapes prebinding/SRL reads, and facade reasoning. No shipping Python wiring or documentation was edited in Task 1.

## Implemented laws and actual route

The single native parser has a static contextual admission mode. Ordinary parsing still refuses assignment collisions and retains native translation rules; contextual admission preserves group boundaries and source facts needed by the compiler. The single iterative compiler gives graph context C, actual returned domain R, and immutable initial bindings I distinct identities. Assignment aliases are disjoint, deterministic, and hygienic even against caller variables resembling generated names. Initial values remain typed RDF terms, including language, direction, blank, and triple-term identity. They are never stringified.

Expression forgetting uses actual R and I according to source facts; an empty logical domain thaws prior C before overlaying I. Relational expressions have the genuine empty `_vars` fact. Executable EXISTS root Filter retains its context exception. Project/EXISTS dependencies travel through preparation, caching, and deferred execution. A primary-oracle correction was required: EXISTS executable graph data does not carry the outer translation's lazy-Join annotation. The compiler explicitly treats these executable joins as nonlazy; strict ordinary native Join is unchanged. Actual oracle inputs/results for this correction are retained in the context, retry/EXISTS clause-fact, and volatile receipts, and permanent executable tests retain the resulting law.

One boxed typed Apply policy supplies declared correlation masks and operator modes. There is one existing evaluator dispatcher, expression VM, scratch/storage/governor home, and each operator's shared kernel. OPTIONAL remembers the incoming solution for retry, stores its RHS once, uses left precedence, and stops remembered retry at its first accepted row. Callback evaluation order follows each yielded row through BIND/Filter/projection and into Group accumulation; RHS, first-pass condition, and retry effects interleave correctly. Nonlazy Join and MINUS materialize the logical RHS once while consuming the left generator lazily. DISTINCT and COUNT(DISTINCT *) use actual logical returned rows; contextual REDUCED removes adjacent duplicates. GROUP handles explicit/implicit empty groups, group-only HAVING, clause-local ORDER aggregate sampling, distinct eligibility followed by accepted update reevaluation, and input/aggregate continuation. GRAPH restores the outer active graph before delivering to downstream consumers and does not fabricate a bound graph variable removed by inner projection.

The sealed `PreparedRdflibQuery` route prepares the compiled algebra through the shared internal preparation home and executes through the shared prepared-view engine. Ordinary `prepare_algebra` and `PreparedQuery::rewritten` reject contextual Apply directly and inside EXISTS using their existing validation traversal. SHACL's prebinding admission explicitly rejects it. Raw evaluator entry and the hidden fixture helper are technically public and are not claimed to reject arbitrary caller-built algebra; neither applies ordinary preparation transformations to the sealed contextual handle. Policy validation rejects all executed malformed mode/operand combinations. Optional conditions now reside in the ordinary RHS Filter, so all normal expression visitors see them.

Final public SELECT with empty actual projected domain suppresses iteration before I fallback; internal empty mappings remain valid, including true ASK of the unit mapping. Duplicate public column occurrences survive. ASK uses a contextual first-witness boundary and stops only after an accepted Filter witness. Query-labelled BNODE identity is shared across contextual rows; unlabelled BNODE is fresh per call. Ordinary native per-row labelled BNODE identity is separately preserved.

Governed Group enters and charges the actual Group node, treats incomplete grouped input as opaque, and withholds incomplete accumulators. Row transforms propagate truncated evidence through the existing Lift rather than discarding it. Latched trips stop subsequent callbacks and accumulator admission. Certain rows, aggregate answers, and true ASK answers are checked against actual complete answers/witness call counts across exhaustive small-fuel cutoffs.

## Proportional representation and work

The compiler uses the shared iterative work-list walkers for whole-query census, facts, compilation, expression/EXISTS mapping, clone, and drop. Each source node is summarized and compiled once; source child patterns are moved from a keyed result table, rather than cloned into both branches. Each OPTIONAL RHS and condition is retained once. Per-node domain/context work is bounded by the source's distinct variable width V; mapping/set operations add their ordered-map logarithmic factor. Thus node/context work is O(N V log V), plus source-term/name payload copying and generated alias spelling, and retained generated representation is O(N V). It does not multiply nested OPTIONAL subtrees or repeat whole-subtree variable census at each parent. The ordinary native parser/preparation path never invokes this compiler.

Permanent executed witnesses check optional depths 16/32/64/128, one RHS/condition per source optional, and independent node/variable grids (depth 8/16/32 and width 1/4/16). A private iterative compilation/clone/equality/drop witness runs depth 1024 on 128 KiB. A separate production typed-entry witness prepares and executes depth-32 nested EXISTS on an admitted stack. A stack-guard refusal is not counted as deep-support success.

## Permanent semantic evidence

The fixture asserts that all **241 genuine oracle cases** execute and compares exact ordered sequences or bags as appropriate, including duplicate columns and dataset distinction. Forty-seven capture flags denote callback-capable probes; four ASK controls make zero calls. Six additional BNODE oracle cases execute as typed identity controls, avoiding random-label string comparison. There are thirteen contextual integration tests in total; no skipped/stub operator or zero-case success.

The matrix covers nine original probes and all historical shapes, initialization/collision variants, graph-context/domain fallback, Project/EXISTS, OPTIONAL multiplicity/retry/volatility, all grouping/HAVING/ORDER/Slice laws, nonlazy duplicates, MINUS/DISTINCT, extension relations/SERVICE, SELECT/ASK/CONSTRUCT/DESCRIBE, and successive volatile assignments and aggregate continuations. Configured callback laws execute in Rust through the native registry/VM. The preexisting Python custom-function surface is not executing; these Rust controls do not claim Python callback availability.

The governed group sweeps examine 135/206/80/306 fuel cutoffs across four shapes, including actual computation trips (38/53 on callback shapes), and require Certain aggregate rows to equal complete aggregate rows. Fourteen ASK sweeps require a published Certain(true) to have exactly the number of calls needed for the first accepted witness (0/1/2 as captured); they also preserve false/empty and incomplete outcomes. The matrix, admission controls, RDF 1.2 terms, BNODE identities, proportional/deep controls, and governors are all in the permanent Rust home.

## Final-source commands and results

Commands were run from this isolated worktree with normal Stage cargo/rustc wrappers and `CARGO_BUILD_JOBS=2`. No timing benchmark was run. Cargo/libtest durations are unmodified tool output and are not performance acceptance measurements.

| Exact selected command | Actual result | Raw receipt |
|---|---|---|
| `cargo test --release -p purrdf-sparql-algebra -p purrdf-sparql-eval --lib --test iterative_traits --test rdflib_contextual --test prebound_grouping --test exists_sep0007` | PASS: algebra464, evaluator1375, iterative3, strict EXISTS25, prebound16, contextual13 | `t1-synchronized-final-core-controls.log` |
| `cargo test --release -p purrdf-rdf -p purrdf-slice -p purrdf-shapes -p purrdf --lib contextual_application` | PASS: facade1/RDF1/shapes2/slice1 | `t1-synchronized-dependent-application-controls-repaired.log` |
| `cargo test --release -p purrdf-shapes --test prebinding_lanes --test exists_relation_prebinding --test blank_focus_relation_prebinding --test prebinding_above_hidden_columns` | PASS: 3/8/3/13 actual controls, 27 total | `t1-synchronized-shacl-prebinding-complete.log` |
| `cargo test --release -p purrdf-sparql-conformance --test sparql_conformance -- w3c-sparql11 --nocapture` | PASS: 29 manifest groups, no new xfail/XPASS/unmodeled failure | `t1-synchronized-w3c-sparql11-repaired.log` |
| `cargo test --release -p purrdf-sparql-conformance --test sparql_conformance -- w3c-sparql10/optional --nocapture` | PASS: two manifests, 7 OPTIONAL +5 OPTIONAL-filter cases | `t1-synchronized-w3c10-optional.log` |
| same with `w3c-sparql10/solution-seq` | PASS: one manifest, 13 cases | `t1-synchronized-w3c10-solution-seq.log` |
| same with `w3c-sparql12/grouping` | PASS: one manifest, 2 cases | `t1-synchronized-w3c12-grouping.log` |
| `cargo test --locked -p purrdf-sparql-eval --test prepared_execution` | PASS: final intended-profile17 | `t1-synchronized-final-prepared-intended-profile.log` |
| `cargo clippy --locked --release -p purrdf-sparql-algebra -p purrdf-sparql-eval --lib --test iterative_traits --test rdflib_contextual --test prebound_grouping --test exists_sep0007` | PASS, warning-clean | `t1-synchronized-final-release-clippy.log` |
| `cargo clippy --locked --release -p purrdf-rdf -p purrdf-slice -p purrdf-shapes -p purrdf --lib` | PASS, warning-clean shipping consumers | `t1-synchronized-final-consumer-release-clippy.log` |
| same consumer release Clippy with `--tests` | FAIL: unchanged baseline `sparql_path_alloc` uses debug-only memo export | `t1-synchronized-final-consumer-tests-clippy.log` |
| same consumer Clippy without `--release`, with `--tests` | PASS intended-profile affected tests, warning-clean | `t1-synchronized-final-consumer-tests-intended-clippy.log` |
| `cargo check --release --lib -p purrdf -p purrdf-rdf -p purrdf-slice -p purrdf-shapes -p purrdf-retrieval -p purrdf-sparql-conformance -p purrdf-wasm -p purrdf-capi -p purrdf-python` | PASS nine actual affected IR consumers | `t1-synchronized-shared-ir-consumer-check-repaired.log` |
| `make layer-hygiene helpers-hygiene rdf-core-hygiene` | PASS: exact layers, helper uniqueness, hash domains, root/kernel/ring fence | `t1-synchronized-final-structural-hygiene.log` |
| `cargo fmt --all -- --check`; `git diff --check` | PASS: explicit separate exit0 statuses | `t1-synchronized-final-quiet-gate-status.log` |
| `cargo run -q --locked -p helper-census -- --no-features` | PASS: explicit exit0 status | `t1-synchronized-final-quiet-gate-status.log` |
| `cargo run -q --locked -p helper-census -- --non-rust-ratchet --merge-base-with origin/main --target worktree` | PASS: zero changed non-Rust paths | `t1-synchronized-final-non-rust-ratchet.log` |
| `cargo build --locked --release --target wasm32-unknown-unknown --lib -p purrdf-sparql-algebra -p purrdf-sparql-eval -p purrdf-shapes -p purrdf-wasm` | PASS affected compilation; before final attribute-only Apply boundary fix | `t1-synchronized-affected-wasm-complete.log` |

The unrelated release test-profile failure is verified against identical synchronized-baseline `shapes/tests/sparql_path_alloc.rs` and its existing debug-gated export; see `raw/t1-consumer-release-test-profile-baseline.log`. The earlier broad release prepared-execution failure has the same baseline cause and remains retained. Intended-profile controls are qualified separately, not relabelled as broad release-test success. No full-workspace discovery gate or timing suite was run.

## Native work and layout proof

Ordinary parsing, preparation, rewritten queries, reused prepared execution, SHACL parameter substitution, and native evaluation select static false/unit modes. There is no ordinary contextual policy allocation, context compiler, new whole-query census, row-delivery callback/storage, witness limit, retry scan, or per-row context initialization. The new boxed policy keeps existing enum sizes and tags; Apply and VarPairs are appended so old discriminant arithmetic and payload offsets remain stable. `PreparedRdflibQuery` storage accounting includes its own wrapper and saturating projection-name heap bytes without changing ordinary `PreparedQuery` representation.

The unit dispatcher uses the original native default attribute and one shared bare direct-argument match. Its contextual boundary and Apply kernel are genuinely out of line. Earlier emitted regressions were discovered and repaired: an explicit native noinline boundary retained an external sret ABI/live recursive frame; a captured match closure added storage/load/caller frame; an inline Apply group body enlarged the main dispatcher. All failed attempts remain in distinct historical artifact directories. Final attribution examines actual MAIN and LIBRARY homes independently: MAIN has restored one save/sub144/CFA160 and ordinary tail transfers; LIBRARY is compared to its own two-save/sub312/CFA336 baseline. Equal frame sizes or allocator logs alone are not treated as proof.

Native LATERAL caches prefix width once as before, and its inline helper takes that width explicitly. Unit correlation and substitution remove the typed input mask/consumer/Option machinery at specialization. Native Join/Minus invoke original algorithms; extracted Filter/Extend/Project/Graph/Group helpers preserve ordinary iteration, ownership, allocation, and drop scope and inline away. Group's native unit domain calls the unchanged shared-blank `visible_columns` loop; the source still handles hidden blank columns before COUNT(DISTINCT *). The moved mutable-expression walker is one unchanged body, not a forwarding runtime layer or second walker. Native false clone mapping has no callback ABI or call, and old-node clone/drop/hash/walk arms preserve their existing operations.

Final paired native evidence uses the identical original Rust probe in `raw/native-cost-probe` and `raw/native-cost-base-ir-probe` against the exact synchronized base. Eleven ordinary query shapes, eleven actual request-substitution windows, and three configured property-function workloads have byte-identical allocation counts/bytes, drop counts, retained bytes, layout, row counts, and metered resource vectors: `raw/t1-native-cost-base-863c75-extended.log` versus `raw/t1-native-cost-candidate-863c75-thin-apply.log` (`cmp` exit0). Layout is GraphPattern144/Expression64/Query264/PreparedQuery368/NodeRef16; EvalCtx944 in attributed ABI. This includes fixed/variable GRAPH, native LATERAL, Group, COUNT DISTINCT star, relation interception, and reuse, but does not pretend the IRI probe alone covers hidden-blank or SHACL semantics; those also have the existing core/actual SHACL controls and exact source/compiled argument.

Exact build: `cargo rustc --offline --release --manifest-path <owned-probe>/Cargo.toml --bin qualification-454-native-cost -vv -- --emit=llvm-ir,asm`. Effective wrapper-selected flags are opt3, thin LTO, codegen-units1, strip=symbols, `-D warnings`, target-cpu=native. `raw/t1-final-source-identity.log` records actual rustc/LLVM, and emitted modules pin CPU znver5/features/ABI. Probe manifest profile spelling is not substituted for actual flags. Build receipts are `raw/t1-synchronized-{base-863c75-extended,candidate-863c75-thin-apply}-ir-build.log`. Final complete unmodified main/eval/algebra modules are `raw/native-cost-base-863c75-extended-ir` and `raw/native-cost-candidate-863c75-thin-apply-ir`; full original function/assembly sections and attributable inventories have corresponding `-sections` and `t1-native-cost-*-inventory.log` names. Calls, branches, loads, byte offsets, spills, and cleanup are retained.

Existing ordinary governor profile charges/trip points are unchanged: ordinary source charge/checkpoint sequence is preserved, exhaustive native soundness controls pass, and paired metered resource vectors are identical. New contextual primitive classification is certified independently; it does not change an existing native profile operation, so no governor profile version is bumped.

The independent native-cost report `tasks/T1-native-cost-review.md` gives final disposition MET at this frozen source, including false clone callback erasure, identical old-node drop dispatch/layout, moved expression-walk caller attribution, native hidden-blank group visibility, and main/library frames/tails. The independent law report `tasks/T1-review.md` gives final PASS at the same 37-file manifest. No performance guarantee is manufactured from a rare branch, equal allocator totals, symbol absence, elapsed host timing, or an uninspected compiler assumption.

The user explicitly removed further wasm cost/frame investigation. At steering time both task-owned wasm emitted builds/inventory had already exited0; no wasm process remained and no further investigation is run. Completed/partial receipts are retained. Existing affected wasm compilation acceptance is separate and recorded above; additional wasm native-cost proof is no longer an acceptance requirement by user instruction.

## Failures, cleanup, and remaining acceptance

Intermediate failures and their repairs remain in raw receipts: exact operator-law failures, governor variant tests, task-owned policy fixture drift, Clippy findings, helper duplicate-address shim, explicit downstream enum omissions, and the three attributable native code-generation regressions. Final checks supersede their checked source, not their historical outcome. The address helper duplication was removed by using typed pattern pointer keys; no ledger exemption was added. Every downstream visitor traverses both Apply children or explicitly rejects contextual admission, with real controls, rather than adding a wildcard/unreachable arm.

All required implementation, semantic, warning, consumer, structural, and logical native-cost gates now qualify the frozen source. The unused stripped baseline binary/assembly and compiled inventory tool were removed after recording their hashes; required original Rust probe sources, raw answers, complete final and failed IR/assembly attribution, and logs remain. The task-owned synchronization stash was verified by exact object ID and dropped; all unrelated stashes remain. `raw/t1-owned-diagnostic-cleanup.log` records this cleanup and reviewer hashes. No owned build/test/proof process remains. The clean baseline is deliberately retained with its complete durably captured proof for the issue's later integration audit; unrelated checkouts and oracle environments were not modified.

## Signed publication receipts

The normal unbypassed hook accepted the 37 explicit shipping paths and signed commit `e72660e8769af222387ecc4fd4f84ea9887e43a1`, tree `72260a771de773d322543b22ea07f1c48cacbf7b`, parent `863c75e2c1e13001bcbe025820d257bd0ee49c4f`. `git verify-commit HEAD` returns0 with a good signature, fingerprint `AF5E0032F7494CEBCAA7BBBE9B87CFBBCFDBAF11`; `%G?` is G. Exact command: `CARGO_BUILD_JOBS=2 git commit -S -m 'fix(sparql): compile contextual mappings through native algebra'`. Receipts: `raw/t1-commit-explicit-files.log`, `raw/t1-signed-commit.log`, `raw/t1-commit-signature.log`, and `raw/t1-commit-identity.log`. Stage evidence was not committed. The shipping status is clean; only untracked `.stage/` remains.

Normal push `CARGO_BUILD_JOBS=2 git push -u origin paudley/454-rdflib-shim-algebra-level-reassignment` returns0. `git ls-remote --heads origin refs/heads/paudley/454-rdflib-shim-algebra-level-reassignment` returns the identical full commit OID. See `raw/t1-push.log` and `raw/t1-remote-head.log`.

Authorized Stage task publication: `stagectl comment 454 --body-file <Stage>/raw/t1-issue-update.md`, exit0, [issue comment 6029391269](https://github.com/Blackcat-Informatics/purrdf/issues/454#issuecomment-6029391269). The exact body/result and primary API readback are retained in `raw/t1-issue-update.md`, `raw/t1-issue-update-result.log`, `raw/t1-issue-update-readback-exact.md`, and its comparison receipt. The first `gh --jq` extraction added one output newline and failed strict comparison; the preserved exact `gh --template '{{.body}}'` extraction compares byte-identically. The comment explicitly distinguishes completed core laws from the authorized next consumer task and does not close or claim completion of the issue.

Current Task 1 gaps: none. Subsequent issue tasks remain separate authorized work and have not been represented as complete. No requirement was moved into an emergency ledger or silently deferred.
