# Shared SmallVec bulk annotation: independent source review

2026-10-08. **Source verdict: PASS. Native-cost verdict remains FAILED on b327 and PENDING for fresh23f7 artifacts.** Exact source delta from b3274735168b7aa063b7163ef5c3f0d4ea8a82e3 is one file/four inserted lines in crates/rdf-core/src/small.rs: two explanatory lines plus tightly scoped inline_always allowance/inline(always) on the existing Extend trait method. Root/G own implementation, staged tree23f7f1b5b72128908ae3b9eab80a2febfc1ad6be and qualification. Reviewer ran no build/test/probe/host/forge/Git mutation.

The complete existing method body is byte-unchanged. Its iterator conversion, lower size_hint reservation, raw_mut pointer/length/capacity, LenOnDrop guard, reserved-slot fill, early exhausted return, panic guard publication and overflow remainder push loop remain the single shared implementation. No unsafe body, raw slot logic, assertion, growth strategy, dependency, feature, cfg or public signature changes. The reason names the actual Project per-row205LLVM/228ASM/CFA112 failure, rather than making an attribute a proof of cost.

This annotation affects all monomorphizations, not only Project. Existing FromIterator, resize/repeat, resize_with and other Extend callers reuse this same home; fill/ownership/panic behavior is unchanged. Existing18 SmallVec tests cover inline/spilled capacities, exact/unknown hints, panic-on-next/drop, ZST/layout and model/ownership cases. Project1 plus existing prepared12/contextual22 gives35 evaluator controls; combined owning53 and core/eval strict clippy/hygiene must bind actual terminal. No claim of their current PASS from preparation. Prior worker45/source behavior proof remains applicable because no replay algorithm changed. Existing qualified docs/wheel protocol proof remains applicable to unchanged source-level API/semantics; actual host optimizer artifacts require fresh comparison.

## Fresh whole-body recheck

Reuse immutable85204 df2 baseline only through the existing exact source/compiler/profile/argv/production-cohort/frame/pair/PyO3 binding and final artifact readbacks. Fresh candidate23f7 native and host inventories must be actual nonempty emitted artifacts. Generation exit0 and32 equality cannot certify cost.

Inspect the complete Project caller and actual residual callees. Require existing bulk reservation/fill in the caller, SSA pointer/capacity/length recurrence, once-final length publication including unwind, and no new per-row Extend/FromIterator/helper frame. A shorter caller is not sufficient. Retain matching output order/unbound cells and original geometric reserve law; no alternative unsafe bulk writer.

Because the annotation is shared, rebind the whole original twelve-row matrix rather than checking only that symbol disappeared. Fresh ordinary dispatcher/operators and numeric bodies must support unchanged allocation/representation/control/recurrence/call-chain arguments; inspect differences where actual compiler composition changed. Shared small-vector traversal/container users in parser/AST/prepare/clone/drop remain algorithmically unchanged, with no new fields/passes from this annotation; source specialization proof remains applicable, while changed optimizer boundaries are assessed in actual emitted artifacts. No new per-function ceremony or new broad semantic suite follows from this scope.

Recheck Filter/Extend/Group inline moved-mint replay and correlation/Application/GRAPH/dedup/numeric seams against exact current bodies or demonstrably unchanged emitted identities. Fresh public Python ABI/query captures/detach/drop/materializer bodies must bind the new core source and actual PyO3 configuration, despite unchanged behavior; prior installed wheel is not that artifact proof. Reuse original row protocol/docs behavior qualification with explicit source applicability rather than repeating unrelated hosts or translations.

Actual b327 body report portfolio-final-bulk-mint-cost-body-review.md remains FAILED, with only Project's live Extend boundary. Source coherence does not supersede that observation. Fresh final candidate whole-cost report is required before any cost PASS; no unconditional host/native/whole-delivery completion is asserted here.
