# Current retained contextual-algebra delivery readiness

Status: IMPLEMENTED AND HISTORICALLY QUALIFIED at cee1c41b2; NOT CURRENT-MAIN QUALIFIED. Next coherent delivery is integration/requalification/publication of this existing implementation, not a second compiler or a fresh row foundation.

Read current issue snapshot, sole plan and later explicit validation restrictions, main `.baseline`/`.goals`, applicable AGENTS, Task3 integration implementation/consumer/native-cost reports, actual retained final Rust result blocks and source, shared host/compiler/numeric seams. Read-only discovery; only this Stage artifact is written. No Cargo, runtime/oracle invocation, source/Git mutation or forge operation occurred. No new branch/worktree was created. External repository submissions remain excluded by current user scope.

## Actual source and completed work

Current HEAD and tracked remote branch are cee1c41b2faa370b7daa60cc7536e784a4756d0e. Shipping status is clean; only separate untracked Stage exists. This signed integration has parents56e636497c049debe2de5445389abf3e018d4783 and dfc0c21adabe557e5d11f027aaf2576bddbe1dd6. The Python row foundation863c75e2c1e13001bcbe025820d257bd0ee49c4f is already an ancestor (actual ancestry check0). Do not duplicate or cherry-pick it. The opening `validation.md` is stale: it describes56e636/currentbase863 and impending integration, while the accepted Task3 reports document its later completed integration and publication.

Implemented native admission/typed contextual algebra keeps graph context C, actual output domain R and initial bindings I separate through the existing parser/evaluator. `rdflib.rs`, `engine.rs` prepared-algebra door and existing shared Apply/operator paths own reassignment/collision, lazy/nonlazy joins, OPTIONAL retry/volatile callback law, logical MINUS/DISTINCT/aggregates, EXISTS/subquery context, empty mappings, duplicate columns and result forms. Ordinary admission rejects contextual IR; no second parser/evaluator or Python semantic interpreter exists. `quad_store.rs:43–102` static QueryMode preserves a unit ordinary mode and contextual graph-selection mode; `query_impl` shares actual host plumbing. Graph.query routes to query_rdflib and uses index-based cells to preserve duplicate columns. Division parsing/forwarding, extension/property/relation settings, named/default/union graph selection and operational errors are integrated. Shared `SumChain` and static tail-cost specialization price contextual streaming numeric work without adding the earlier disproved ordinary native overhead.

Actual Task3 integration repaired genuine aggregate/domain/worker-barrier integration holes; it was not a textual clean-merge assumption. Retained `raw/t3-final-affected-rust-tests.log` contains2306PASS/0failed/0ignored: algebra464,iterative traits3,evaluator1380,xsd298 and eleven evaluator targets (exact_numerics7,exists_sep0007 25,governed_query25,governed_update26,governor_correctness9,numeric_casts14,numeric_contract7,numeric_governance11,numeric_parallel_determinism8,prepared_reuse7,rdflib_contextual22). Contextual target includes the241 frozen genuine7.6 oracle fixtures, original nested vendor witness, numeric/refusal/callback controls and actual engine entry. Later optimization-only static-tail source was bridged by22 contextual tests, strict release clippy, actual emitted proof and byte-identical32-record untimed probe outputs—not relabeled as a new2306-test execution.

Actual locked native install and ONLY15 irreducible `test_contextual_mappings.py` binding tests pass at the recorded module/input identities. Consumer review ends literal PASS; native-cost review ends MET against fresh dfc0c21 baseline, with full paired codegen/ABI/frame/capture/drop/operation and untimed allocation/resource records. Its old failures and repaired compiled bodies remain preserved. I additionally ran read-only `sha256sum --check --quiet raw/t3-full-combined-shipping-source-sha256.log` from the Stage-relative worktree path: exit0, so the49-file final shipping manifest still matches cee source now. The old installed module is historical artifact evidence, not proof of a currently installed combined-main module. No timings or broad Python/vendor reruns were executed or are proposed.

No current-main integration, new-source structural cost proof, current attributable installed binding run, final hosted evidence or completion/PR handoff is established by those older receipts. Task3 implementation documents ordinary verified commit/push/cleanup success; it does not establish those later gates. Current captured issue remains open. Its complete5-comment snapshot preserves published plan/task progress; no PR readiness is inferred from it.

## Current-main interaction and exact conflict seams

Captured origin/main is5384882d65750ee22bddfeeac473095ab9c3db03; merge-base is dfc0c21. Read-only merge-tree returns exit1, prospective tree159356b6cada43e237f01018da4567bef726cdea, exactly FOUR conflicts:

| Path | Required combined resolution |
|---|---|
| bindings/python/python/src/purrdf/compat/rdflib/graph.py | Preserve branch contextual query_rdflib, full configured relation/property/aggregate/division kwargs, graph/default-union selection and duplicate-column positional materialization; add main's dated xpath_regex query/update forwarding and accurate dated-law docs. Main's ordinary Store.query reassignment prose is superseded for Graph.query only; preserve ordinary native Store contracts. |
| bindings/python/src/py_store/quad_store.rs | Keep one static QueryMode/unit ordinary helper and contextual public door, plus ALL main XPath selection/options and division-before-work parsing at ordinary/governed/entailment/prepared/update doors. Add dated selection to contextual door and its declaration/stub. Do not retain two complete host implementations or drop main's caller option to resolve conflicts. |
| docs/CONFORMANCE.md | Preserve current main generated scoreboard and exact current source-owned counters, retain honest explicitly historical broad Python/vendor receipts; no old aggregate total masquerading as current. |
| docs/book/po/zh-Hans.po | Preserve both message/translation sets; regenerate only through owning production extraction/merge workflow, then verify no unintended fuzzy/conflict entries and actual current catalogue/render. Do not hand-fix generated counts. |

Important automatic merges need source inspection even without markers: current main changes engine QueryOptions/native XPath cache and evaluator expressions, resource/account/worker/row-checkpoint/binop/group storage and UDF/protocol paths. Native parser's later ordinary note_scope_consultation mutability change must preserve const-specialized contextual admission. Main's modifier now changes plain grouped output reuse and bounded-loop eligibility; branch's contextual streaming/Apply domains, exact admission before callback/update, local/worker error precedence and continuation proof must survive. Shapes prebinding/property visitors, facade reasoning, slice/remote/SERVICE and recursive traits must still understand branch-only Apply/policy nodes. Main's rules/datalog golden changes are common base behavior, not a reason to restore old goldens. Latest helper/glossary/ratchet gates must see the combined tree. Upcoming402 may advance main again: root should integrate the ACTUAL then-current base after402 settlement, inspect its SHACL/profile/function-admission interactions, and update this predicted four-conflict result rather than assuming538 remains final.

## Smallest concrete execution sequence after root admission

1. Root ordinary base-to-existing-WT merge, resolve both sides as above, inspect automatic seams, restore canonical validation opening to actual candidate identity with historical sections labeled. Scope new production work to real integration holes; do not rewrite qualified compiler laws.
2. First compile owning libraries (`cargo check --locked --jobs8 -p purrdf-sparql-algebra -p purrdf-sparql-eval -p purrdf-python`). Add a bounded Rust contextual dated-XPath actual-engine regression only if combined option propagation is not already exercised: both dated laws, unchanged valid neighbor, malformed option/actionable failure and actual resource error precedence. Keep semantic coverage in Rust; language extraction/forwarding alone may belong in Python.
3. Actual selected Rust qualification: `cargo test --locked --release --jobs8 -p purrdf-sparql-algebra --lib --test iterative_traits`; evaluator `--lib` plus `--test rdflib_contextual --test exists_sep0007 --test prebound_grouping --test prepared_admission --test prepared_reuse --test native_xpath --test numeric_governance --test numeric_parallel_determinism --test governed_query --test governed_update --test governor_correctness`; add exact_numerics/numeric_contract/numeric_casts only if numeric representation/admission changed beyond common base. Test names above exist in current or retained target inventory; revalidate registered target names on integrated source before invocation. Do not issue a blanket --all-tests guess or unsupported release tests: inherited SHACL memo-instrument tests require their supported debug profile.
4. Focused production SHACL caller tests in supported profile: prebinding_lanes, blank-focus/EXISTS relation and hidden-column controls from retained Task1 qualification, plus current native_xpath and per-focus user_fn::tests::invocation_admission if402's admission lands. Relevant conformance inputs may reuse frozen historical answers where unchanged; execute only actually affected native SPARQL groups/engine witness routes, not Python/vendor matrices. Scoped strict all-target clippy/fmt and combined helper/layer/terminal/generated/glossary gates must pass. Affected target portability is compile-only Rust; no task-specific semantic wasm suite.
5. Rebind primary ordinary native cost against ACTUAL new main with the existing same-source probes/codegen recipes and compiler/profile flags. Existing raw/t3 baseline/candidate artifacts and logical source arguments remain reusable only for unchanged seams. New host XPath options/state, engine/cache, row/checkpoint/group/worker/compiler composition invalidates promoting absolute old frames/resources/layouts. Pair the existing untimed32-record allocator/resource probe and existing host/native emitted section inspection on current base versus combined candidate; inspect ordinary unit-mode erasure, direct ABI/capture/drop, loop work/storage, and static numeric tail. Native change common to both is not issue overhead. Never use host timings or declare native preservation from equal answer/allocator totals alone. Retain full attributable emitted proof losslessly; use original production recipes, not guessed target/flags or fake metadata.
6. Build/install current locked native module through existing supported project route, capture module/source/lock/test hashes, run ONLY `bindings/python/tests/test_contextual_mappings.py` (currently15 irreducible cases), with any narrowly necessary dated-option extraction/forwarding neighbor. Preserve genuine frozen Rust oracle answers, do not run rdflib oracle anew or broad Python/vendor/shadow semantic suites under the explicit restriction. Refresh maintained generated documentation/catalogue and source-bound Rust counters honestly, then independent source/consumer/native-cost adjudication.
7. Once real candidate criteria are demonstrated: root normal hooks/commit/push, updated issue/PR/plan publication and actual relevant hosted coverage, followed by completion/gap review and ghprsq finalization/archive/cleanup. Reuse whole qualifying gates across workflow where applicable; no extra blanket local full run is prescribed by this discovery report. If a required hosted full gate is pending, record it pending, never substitute an old T3 receipt.

Standing user amendments govern the historical sole-plan lines that proposed broad differential/vendor execution: “The only things that python or wasm can check in tests are things that ONLY PYTHON OR WASM can test.” The plan also expressly forbids time-based performance measurement and requires logical native-cost proof. Existing Rust oracle fixture/real-engine witnesses remain required; these restrictions do not authorize abandoning semantics or native-cost acceptance. No upstream submission criterion remains.

Current blockers are concrete: unresolved current-main four-path integration and automatic shared seams; missing current combined-source native/caller/structural-cost evidence; missing newly installed attributable narrow binding evidence; and final hosted/publication/merge gates. No missing row foundation, new compiler design, fresh broad oracle campaign or user decision blocks beginning the coherent source integration once root admits it.
