# Shared mint-prefix repair and focused qualification

VERDICT: PASS for source and admitted focused runtime/gates at tree6c3a5773c238dcf95f3cb99fd0637392d11eb6ff. Full emitted-cost acceptance remains FAILED pending fresh bodies; no whole-delivery claim.

One original count_to closure loop moved once to private count_worker_mints_to in the same row_checkpoint home. Concrete existing IntoIter<(u64,TermValue)> and mutable interned position are explicit parameters; all six growth/refusal checkpoints call that home. Exhaustion still breaks without increment; each consumed mint increments interned before count_worker_mint. No replay/refusal ordering, allocation law, branch, new feature, macro-copy loop or fallback changed. Narrow reasoned inline(always) targets the actual extra closure call/frame found in Filter, Extend and Group. Attribute is not emitted erasure proof.

Actual session88707 terminal0 observed through tools.write_stdin; driver.exit0/all five commands0 in `/opt/purrdf-454-current-qualification-20261008/final-mint-rust-1`. Scope purrdf-454-mint-replay-rust-20261008.scope invocationc20a1cee4a12497cb8ef93623fddf0f9 inactive/dead/lane FREE. Live effective64GiB/SwapMax0 retained; raw SDK/private target/build/jobs8/libtest8/inherited wrapper disclosed. Exactly9 existing checkpoint unit controls plus governor_correctness9/governed_query27 =45 actualPASS/0fail/0ignore. Strict evaluator all-target clippy/fmt/own helpers gate PASS. Full source readback0,6c3 tree unchanged throughout; no wheel/docs/emission during run. Unchanged prior docs, current2f3 wheel and160 semantic evidence remain scoped evidence; no previous artifacts promoted to6c3.

After actual terminal, root separately authorized the Project reserved-slot bulk repair. Current treeb3274735168b7aa063b7163ef5c3f0d4ea8a82e3 changes modifier.rs alone from6c3: Solution::new followed by existing SmallVec::extend over the exact original source-column Map, without FromIterator wrapper or separate reserve/per-cell push loop. Existing outer Vec row loop/order/output schema/lift remains unchanged. Source preserves original bulk reservation/final length-store home; fresh emitted proof is mandatory. This Project change is source-only/unqualified until separately admitted focused Project/contextual/prepared checks. No further build began.
