# Production dependency cohort correction

VERDICT: PASS — offline resolver preparation only. Native cost acceptance remains NOT MET; fresh compilation and independent full emitted-body proof are unrun.

Original session76668 was deliberately stopped for a verified cohort defect: generate-lockfile selected regex1.13.1 whereas production locks select1.12.4. Owned scope stop exited0; actual session terminal143; scope inactive. Original partial native emissions and32-record equality remain under `/opt/purrdf-454-current-qualification-20261008/native-cost-current-1` and do not qualify shipping dependencies. Host emission was incomplete. No sibling process was stopped.

The corrected Stage driver creates ALL new probe/native/host outputs beneath the fresh log root’s `artifacts/`. It seeds each probe from corresponding production Cargo.lock, resolves offline ordinarily, then requires locked offline metadata. Every selected external name/version/source/checksum tuple must belong to production. After actual later emissions, every compiler package ID must bind to metadata; the complete compiled external closure must bind to production checksums. Regex alone is insufficient. Both probe locks must remain byte-identical. Production locks are untouched.

Actual witness: `/opt/purrdf-454-production-cohort-resolution-20261008-1`; wrapper `portfolio-production-cohort-resolution.sh` copies the driver’s exact lock-reader and manifest block. Both ordinary and both locked metadata commands exited0; wrapper terminal0 and resolver.exit0. Each closure has39 external packages, zero unapproved tuples; complete external checksum rows and probe locks compare byte-identical. Regex is1.12.4, checksum f1292b7759ae1cb9ec195452d1390a074f0cd8541ab7a5a8c31cd6db45d4a6ba. Independent TOML audit `resolution-structure-audit.json` verifies the sole added package is the owned probe; no retained external package record changes. Cargo prunes unused workspace members and first-party dev/test dependency edges; all11 changed first-party records are listed rather than concealed. An initial supplementary assertion incorrectly demanded those path dependency lists remain identical; its exit1 is recorded in initial-structure-audit-failure.txt. The corrected narrower assertion preserves exact external identities, not normalized output. Full lock diffs, actual command argv, metadata JSON, stderr, terminal codes and checksum bindings are retained.

Production lock readback and staged treed632307fb725304ed864967d5234cdab35bc5c99 remain unchanged. No shipping edits or compiler/probe/artifact-generation run occurred. Fresh cost retry requires root admission and a new log subdir; it repeats these resolution guards and adds actual compiler-frame closure proofs. Native ThinLTO/host no-LTO analytical stages remain distinct from production fat-LTO release, with matched release assertions/overflow OFF.32-record equality never substitutes for full ABI/frame/capture/drop/loop proof. No docs, timings or broad Python/oracle execution was run.
