# Fresh bulk-fill/mint cost body audit

2026-10-08. **Native-cost verdict: FAILED — actual extra Project boundary remains.** Generation99950 subsequently settled actual terminal0/driver0 with both fresh candidate roles and all final readbacks. Candidate source is b3274735168b7aa063b7163ef5c3f0d4ea8a82e3; actual root `/opt/purrdf-454-current-qualification-20261008/final-mint-project-native-cost-1`. Matched immutable baseline is85204/df2 from final-lower-native-cost-1, admitted through exact source/compiler/profiles/argv/compiled-cohort/pairs/Cargo frames and actual PyO3 inputs/config/fingerprint checks. Native candidate emit0 and32 exact untimed comparison0 are actual receipts, not full cost proof. Reviewer performed no build/runtime/source/index/Git/forge mutation.

Complete native module and affected caller/callee LL/assembly selections are retained under `raw/final-bulk-mint-cost-body-review/`. Function selection binds the actual expr::eval_filter/extend and modifier::eval_group_with<...,()> symbols; initial zero selections from incorrect module/function keys were corrected before evidence adjudication.

## Native actual findings

Mint-prefix boundary is erased on this pair. Complete Filter5565 LLVM/4618 assembly, Extend6286/5334 and Group8272/7018 contain neither the former commit_items closure#5 nor new count_worker_mints_to call. The shared replay loop is inlined into its callers; existing count_worker_mint operations remain in the corresponding prefix order. No claim of instruction identity from line counts. Existing45 focused controls and source review establish unchanged next/increment/count and fuel/scratch/refusal sequencing.

**Project still FAILED.** Actual complete Project1421 LLVM/1222 assembly invokes SmallVec::Extend<Map<...,eval_project_sequence closure#1>> in its per-row block504. Baseline df2 original bulk fill was inline. Complete actual new callee is205 LLVM/228 assembly lines: six register pushes, reserve56/CFA112 while caller remains live. Its shared reserved-slot bulk loop restores the correct capacity/length law, but adds an actual per-row call/frame. Smaller Project caller, erased FromIterator wrapper and matching32 records cannot discharge that boundary. Full bodies are candidate-project-full.ll/.s and candidate-project-extend-full.ll/.s; no source annotation is substituted for emission proof.

Root/G were notified promptly; keep this failed candidate and immutable baseline intact. Any further source repair belongs to root/G and requires its actual affected body proof, not relabelling b327.

Complete fresh unit Application2996 LLVM, GRAPH3650, false dedup2594 and numeric871 are identical to the independently inspected2f3 complete bodies after only compiler metadata/attribute ordinals and content-addressed global names are normalized. All four `*-prior-current.diff` files are empty. Actual unit symbols were selected, distinguishing contextual ApplicationPolicy from unit Application and eval_graph_with<...,()> from other routes. Initial incorrect contextual/empty selections were corrected before comparison. Thus the existing detailed arguments for these unchanged operator/numeric bodies apply to this actual fresh native artifact rather than merely to unchanged source labels.

## Whole original criterion applicability

All twelve original rows in portfolio-final-lower-native-cost-body-review.md remain the authoritative whole matrix, not a reduced two-function acceptance. Source review portfolio-final-bulk-mint-source-review.md identifies exactly two changed homes/loops. Unchanged parser/traits/layout/admission/source arguments and existing host protocol/docs evidence remain applicable. Worker row and Group's shared replay finding are discharged on this native pair subject to final source/artifact readbacks; Project remains FAILED. Other unchanged native operator/numeric/dispatcher arguments must bind the fresh emitted inventory/cohort and current source, not names alone. Fresh host boundary inspection and final compiler/PyO3/source/artifact readbacks remain pending at this checkpoint. No final whole-criterion PASS, host completeness or generation terminal is inferred while99950 is live.

## Settled final readbacks and whole matrix

The paragraph above is the attributable pre-host checkpoint. G supplied actual99950 terminal0; driver.exit, candidate-native-emit.exit, candidate-host-emit.exit and untimed-equality.exit are all0. Final source, emitted files, actual host library, immutable baseline source/evidence, and both actual PyO3 fingerprint readbacks passed in the fail-fast driver. Input-tree remains exact b327. Fresh candidate inventories108 native paths/54 pairs and one host pair,21/49 approved external closures, matched effective profiles/compiler/argv and actual PyO3 input/config comparisons admit this pair. No unknown or failed child is treated as success.

Complete fresh host wrapper1026 LLVM/934 assembly, ordinary query_governed2238 LLVM, materializer1631 LLVM/1349 assembly and detached272-byte capture Drop74 LLVM were independently selected. Full wrapper/query/materializer LLVM are identical to the previously verified2f3 bodies after only compiler metadata/attribute ordinals and content-addressed global names; all three host-*-prior-current.diff files empty. Unit capture Drop also matches (host-drop-prior-current.diff empty). Actual vtable identities remain unchanged in these LLVM bodies, so prior independent full vtable-field checks apply, rather than a blind new vtable-label normalization. Fresh complete assembly bodies remain retained. Thus the previous public ABI, detach/restore-on-normal-and-unwind, materialization allocation/drop/control and no eager iterator proof applies to this actual host artifact, not to an older installed module.

| Original whole-cost row | Final b327 judgment |
| --- | --- |
| First-party implementation/dependency/source/compiler closure | DEMONSTRATED; original source review plus strict admitted immutable baseline/new candidate production cohorts. |
| Ordinary parser/admission | DEMONSTRATED; exact unchanged source/hash specialization argument retained. |
| AST/visitor/retained storage/prepare/clone/drop | DEMONSTRATED; unchanged source/layout/iterative-traits proof and exact source-bound retained allocation records. |
| Unit native dispatcher/RowDelivery | DEMONSTRATED; unchanged dispatch source/body applicability and original unit representation argument; no new callback/capture state. |
| Filter/Extend worker replay | DEMONSTRATED; complete affected bodies have inline mint-prefix replay without the failed closure/new helper boundary; source order and owning45 controls retained. |
| Project row/cell work/capacity | FAILED; bulk law restored but205LLVM/228ASM per-row Extend callee adds six pushes/sub56/CFA112. |
| GRAPH/Group/ordinary dedup | DEMONSTRATED; GRAPH and false dedup complete bodies identical to inspected2f3; Group affected prefix boundary erased. Existing group plumbing is distinguished from added boundaries. |
| Correlation/Application/deferred substitution/property-function path | DEMONSTRATED; complete unit Application identical to inspected2f3, direct map lookup preserved and old extra Option closure erased. |
| Primary native numeric recurrence/false tail | DEMONSTRATED; complete871LLVM identical to inspected2f3 bounded recurrence proof, not finite32-only inference. |
| Public Python ABI/captures/detach/drop/materialization | DEMONSTRATED; complete actual fresh host comparisons and retained verified vtables as above. |
| Lazy row allocation placement | DEMONSTRATED; unchanged materializer/no eager iterator, exact original current28 host protocol/27 package identities applicable to source unchanged by these loops. |
| Complete actual profiles/cohorts/final identities | DEMONSTRATED generation/readback acceptance; not cost or timing PASS. Analytical native ThinLTO/host no-LTO remains distinct from production fat-LTO. |

No further concrete finding or unreviewed original cost row remains on this admitted pair beyond Project's actual added call/frame. Root/G received exact findings before any next emission. Overall accepted original row15 is FAILED; no final whole-issue/hosted/merge PASS. Subsequent repairs must prove affected candidate Project bulk-loop/frame work and rebind unchanged evidence; baseline85204 may be reused under the same strict source/compiler/profile/PyO3/artifact admission. No unnecessary new wheel/docs/broad Rust/probe campaign is demanded solely for narrow inlining repair, and no new per-function review ceremony is introduced.
