# Current production-cohort emitted cost audit

2026-10-08. **Current verdict: FAILED / native-cost NOT MET.** Concrete ordinary GRAPH and Project helper boundaries survive in the d632 candidate emission. Artifact generation50132/driver0 and32-record equality are valid production-cohort generation evidence, but do not close these findings. The rest of the full-body audit remains in progress; no completion claim is made from the inspected subset. Main402 has subsequently landed as df2; the retained paired emissions remain explicitly scoped to 2eb versus d632 and cannot qualify that later integration automatically.

The actual source pair is archived main2eb versus candidate treed632. Subsequent staged translation-only projection933daa does not alter the shipping Rust inputs and is separately qualified. All four emits are retained in `/opt/purrdf-454-current-qualification-20261008/native-cost-current-production-1`: native21 external compiled packages/54 actual paired modules each; host49 external compiled packages/one .ll+.s pair each. Actual dependency tuples/checksums bind to production locks, unlike the preserved aborted wrong-regex cohort. Compiler is rustc1.100.0-nightly4b6d04e70/LLVM23.1.1, x86_64 Linux; native O3/ThinLTO/codegen1 and host O3/no-LTO/codegen1, checks-off/strip-symbols/target-cpu native/warnings-denied. These are the specified analytical stages, not production fat-LTO or timing.

## Concrete ordinary GRAPH failure

The full baseline native `eval_graph<RdfDataset>` body is retained at `raw/current-cost-body-review/baseline-graph-full.ll` (3529 lines); candidate `eval_graph_with<RdfDataset,()>` at `candidate-graph-full.ll` (3534 lines). Full affected native modules and corresponding assembly remain in the owned opt generation root, selected by the original role emitted-path inventories. The extracted bodies are complete from define through closing brace, demangled with installed llvm-cxxfilt; no instruction, ABI argument, operand, call, control edge, loop, alloca or frame is removed.

Candidate full-body lines548–550 contain an actual `invoke fastcc ... graph_holds_no_rows<RdfDataset>` on the ordinary variable-graph emptiness-probe path. Assembly `candidate-native-full.s:21479` has the corresponding `callq`. Baseline's corresponding emptiness work is **inlined**: full-body lines566–634 call probe_plan/quad/reifier iterator homes directly, and the baseline ordinary GRAPH body has no graph_holds_no_rows invocation. This difference is not a new contextual arm, diagnostic-only text, or normalized symbol identity.

The current actual helper body is retained completely as `candidate-graph-empty-helper-full.{ll,s}`. It saves five registers, subtracts112 stack bytes and has CFA160 while the ordinary caller remains live. Caller reserve baseline1256 versus candidate1272 is separately observed; the decisive finding is the extra ordinary per-graph helper call/live frame, not a numerical threshold on the16-byte caller difference. Source `modifier.rs:919` is the original graph emptiness home without an inline guarantee; the newly shared generic graph wrapper changes optimizer placement. `append_graph_rows` has an explicit always-inline boundary and is erased at this caller, so that helper extraction itself is not the remaining call.

Source still invokes the same quad/reifier/annotation emptiness operations and no algorithmic second pass is alleged. Nevertheless, accepted cost proof explicitly refuses a new ordinary call/frame that finite allocation/layout samples cannot detect. Root was notified promptly; root owns diagnosis and any shipping repair. A possible inlining repair must be proven by refreshed actual affected emissions, never by the annotation alone or assumptions about production fat-LTO.

## Inspected observations that do not close the blocker

### Concrete ordinary Project failure

The complete candidate ordinary Project body (`candidate-project-full.ll:872–874`) invokes `Vec<Solution>::SpecFromIter<Map<slice::Iter<Solution>, eval_project_sequence::{closure#1}>>::from_iter`. Corresponding assembly `candidate-native-full.s:14861` has an actual non-tail call. Baseline's complete ordinary Project body performs this row projection inline, including both SmallVec grow paths, with no equivalent collect-helper invocation. This is once per projection, not once per row; no second projection algorithm or extra allocation is alleged.

The full actual candidate callee is retained as `candidate-project-collect-helper-full.ll` (374 lines) and `.s` (413 lines). It saves six registers, subtracts200 stack bytes and reaches CFA256 while the ordinary Project caller remains live. Caller reserve664 versus baseline680 therefore does not establish an erased boundary. Source `modifier.rs:253–265` forces the shared sequence function inline, but the nested standard-library collection specialization remains out of line in this actual emission. Root and the assigned repair owner were notified; GRAPH-only repair cannot close this second finding. No speculative shipping fix was applied by this audit.

### Host ABI, detached capture and cleanup

The complete exported PyO3 query wrappers have934 assembly lines each. `host-wrapper-asm.diff` is empty after demangling and normalizing only compiler-generated function/block/exception-label ordinals (block suffixes remain). All actual instructions, argument marshalling, calls, stores and branches are retained. Both wrappers reserve680 bytes/CFA736 with six pushes. This establishes wrapper identity, not identity of the separately called evaluator.

The detached ordinary capture is272 bytes in both full LLVM bodies. Field offsets match: relation specs0, substitutions24, aggregate namespace48, EngineConfig72 (168 bytes), division240, inner dataset reference248 and borrowed query pointer/length256/264. The settled capture remains216 bytes. Candidate unit mode contributes no graph-selection tuple or TermValue storage/drop. Both bodies invoke SuspendAttach::new once before freeze/build/evaluation, and restore via the same16-byte guard on normal and unwind exits before materialize_results. Source `query_impl<()>` reaches the native engine path; the contextual rdflib path is a different static specialization.

The complete74-line capture drop bodies compare identically after normalizing the function header and numeric LLVM metadata/attribute identifiers, recorded in `*-ordinary-drop-metadata-normalized.ll`. Baseline compiler shares this body with the identical governed-query closure; the actual ordinary caller invokes that alias. Candidate invokes its unit query_impl closure drop on failed detach admission. Both dispose relation specs, optional aggregate string, the same168-byte EngineConfig and substitutions with the same unwind/terminate edges. No contextual selection cleanup survives. These specific ABI/capture/cleanup seams are demonstrated; the complete ordinary host query bodies have scheduling/SSA differences and are not declared instruction-identical.

Both full ordinary host query bodies have2114 LLVM lines and the same public internal-fastcc arguments; current ordinary static mode has unit selection and no graph-selection tuple/TermValue capture. Full assembly reserve is baseline2664/CFA2720 versus candidate2648/CFA2704. There is code motion/register and inlined SSA naming variation, so full instruction identity is not asserted. Host captured settled and detached aggregate storage still requires complete caller/closure-drop adjudication.

Native dispatcher ordinary pattern ABI remains144 and EvalCtx1232 in both current modules, with three96-byte temporaries and reserve312. Its unit/no-mode old-arm source dispatch is distinct from the appended Apply arm. Initial native operator reserve observations: Extend2392→1848, Filter2376→1704, Project680→664, Dedup760→760, Group2824→2376, LATERAL1544→unitApplication1464. These are supplementary observations, not substitutes for whole control/loop/caller proof.

### Ordinary forked Filter/Extend commit boundaries

The full operator call tables and selected caller bodies also expose new out-of-line post-join commit boundaries. Candidate Filter `candidate-filter-full.ll:1185–1187` invokes RowCheckpoint::commit_rows; candidate Extend `candidate-extend-full.ll:1418–1420` invokes commit and `1432–1434` invokes commit_into. These invocations are absent from the corresponding baseline complete operator bodies, which contain the commit operations inline. Both baseline and candidate already call for_rows/pass, so those pre-existing checkpoint calls are not new findings.

Complete current commit callees are retained in `candidate-worker-commit-full.ll` (7418 lines across exactly three definitions) and `.s` (6698 lines). commit_rows and commit each reserve968 bytes/CFA1024 after six pushes; commit_into reserves392/CFA448. The caller remains live. These paths execute only after a forked ordinary row loop, not on the sequential Filter/Extend loops, and are once per completed worker join rather than once per row. The existing typed buffer reuse in ungoverned Extend is preserved in source. A shorter enclosing operator frame cannot by itself discharge these added boundaries; the refreshed final artifact audit must cover ordinary worker paths as well as sequential paths. Source operations/worker accounting have not been alleged incorrect from this placement observation.

Full numeric caller bodies (868/871 LLVM lines plus complete assembly) are extracted. Both have the same eight IR temporary sizes and reserve264/CFA320; no out-of-line SumChain::push or aggregate_numeric_tail_cost appears in the actual caller. Source retains existing machine-word early return and `aggregate_numeric_tail_cost::<false>`, erasing the previously excluded duplicate native fast-path test. Full recurrence/control and host numeric callers remain to be adjudicated, not assumed from those searches.

The native SUM/AVG caller's entire candidate recurrence and corresponding baseline control/tail were additionally traced: one machine-word lexical scan with80-byte survivor stride; one shape-filtered SUM/AVG scan; first-value bypass; subsequent saturated count, maximum integral/fraction digits, carry digit and add-cost accumulation; a single latch carrying total shape and Cost sum/peak. There is no extra survivor pass, SumChain state spill or out-of-line per-value push. Both retain the same single bounded-total/default-policy exit after the fold. Candidate's false tail specialization adds no second fast-path test. SUM rendering and AVG's count-shape/decimal-division/quotient/render work remain inlined at this caller; the80-byte integer temporary is the pre-existing AVG count XsdValue, not newly introduced accumulator storage. MIN/MAX retain their separate shape collection and compare_chain call.

This is a bounded native recurrence/call/frame judgment, not a claim of complete assembly identity or automatic host numeric proof. Installed LLVM23 llvm-diff admission succeeded on its unchanged original module. The attempted crate-disambiguator-only normalized numeric comparison exited1: global anonymous constant identities, SSA/PHI ordering, block movement and return merge differ; `numeric-llvm-diff.txt` preserves that outcome. It is not cited as an equality pass. No custom semantic comparator or new runtime oracle was introduced. Host numeric and remaining Group/LATERAL/dedup/operator complete control proofs remain open for the final source-bound paired artifact audit.

Historical source-manifest readback confirms parser/machine, algebra owned/traits/walk/retained storage and exact-cost home unchanged where reused;11 changed evaluator/source manifest entries are explicitly not inherited wholesale. Earlier historical full-body proof is not relabelled as the current build. The actual32-record equality corroborates only sampled allocation/layout/resource records and never overrides the GRAPH failure or missing whole-body judgments.

No compiler, tests, host runtime, timing, source/index/refs or forge posts were executed/mutated by this audit. Only owned Stage report and read-only artifact selections were written. Native cost must remain NOT MET until the concrete finding and all required actual body seams are resolved.
