<!-- SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca> -->
<!-- SPDX-License-Identifier: CC-BY-4.0 -->

# Focused compiler design analysis

Inspected source HEAD `18489a91cb452b1773c60b469d4c30dc33a9a4a4`, tree `5d150fa4076cc75e293b517f79dd080b6ea807ed`. Read-only source/upstream inspection; no execution, install, source mutation or forge action. This is an implementation design candidate with named proof obligations, not an implemented or passing compiler. The complete issue-analysis remains applicable, including assignments without initBindings.

## Feasibility conclusion

There is a coherent first-party lowering route through the existing parser and native evaluator: represent the oracle's row mapping separately from its graph-evaluation context, use fresh SSA carriers to encode assignments, and compile context changes to native correlation/algebra operators. Native `prepare_algebra` already admits owned Query algebra without reparsing. `query_prepared_view` executes it through the shared engine. Compatibility compilation can use these homes without changing ordinary native substitutions or SHACL laws.

A parser flag that merely permits collisions, followed by one global override pass, is insufficient. The source and executed oracle receipts show that assignment output, expression reads and graph matching can observe different values of the same logical variable in one query. The compiler must make those distinctions structural.

Read the finalized 4646-byte `raw/rdflib-7.6-oracle-probe.json`: exact runtime 7.6.0, hashed upstream files, dataset/initBindings and nine witnessed answers. In particular BIND b followed by a this-triple returns b with a's o1/o2; OPTIONAL restores a over all three objects; MINUS retains those three; EXISTS returns zero; grouping yields b/count3; nested group restores a; the later repeated BIND wins; expression failure retains a. These are root-executed primary receipts, not analyst executions.

## Transform state and invariant

Compile each pattern as a function of incoming context C and fixed initBindings I. Its result is a native bag plus a logical output mapping R. Keep all three maps distinct:

- I maps caller-bound logical names to immutable private carriers/constants.
- C maps graph-context names to private carriers; BOUND on a carrier means that key exists in the context.
- R maps returned solution keys to private carriers; BOUND means actual mapping-domain membership. Absence of a key is different from an expression lookup fallback to I.
- Per-node facts retain rdflib's syntactic `_vars`, projection names and lazy-analysis summary, separate from native free-variable sets.

An expression lookup uses R[name] when present, then I[name]. A graph lookup uses C[name]. `FrozenBindings.__getitem__` explains the fallback; `QueryContext.__getitem__` explains the graph lookup. Compiler expression scopes must also implement `forget`: retain keys absent from the earlier C, keys in the operation's `_except` set and all initBinding names. Do not substitute a hidden fallback carrier into actual mapping-domain tests.

User `BOUND(?name)` tests whether that **expression lookup** returns a term, including I fallback. It is not the internal actual-key-domain predicate. `Builtin_BOUND` obtains its argument with variables=True and checks whether it remains a Variable. Internal domain membership uses the R carrier alone; user BOUND uses the expression-visible R/I resolution. This distinction is required when a projection removes an init-bound key but expressions can still look it up.

Define right-preferred mapping merge M(A,B): each key uses B when B has an actual bound key, else A. The oracle's thaw law is **T(R,C) = M(R if R has any actual key else C, I)**. The empty-domain branch is necessary: `clone` passes `bindings or self.bindings`, and `QueryContext.__init__` then updates that mapping with I. Encode presence with BOUND and expression predicates; use fresh immutable variables for every value version. No caller variable is renamed by a text scan.

Generated variable names must be selected from the complete parsed variable census, including expression EXISTS, templates, nested subqueries, graph slots and caller binding names. Persist the public-name/SSA map. Private variables never enter visible SELECT star columns, MINUS sharing domains, user grouping keys or graph templates accidentally. RDF terms retain their native values; aliases do not stringify cells.

The capture-free invariant is per node: each logical name has distinct immutable carriers for each R/C version; an input carrier is read but never an assignment destination in that node's compiled subtree. At a scope edge, Project selects the advertised actual R domain plus explicitly declared transport, then fresh Extend aliases produce the next version. Correlation substitutes only named input carriers; newly assigned carriers are not in the outer row schema. Rename triple/path/graph positions with C resolution, expression slots with the appropriate forgotten-R/I resolution, and output/template slots with final-R resolution. A blanket variable walk applying one rename map cannot uphold this invariant. Prove it by a structural induction test over the compiler's typed operator cases and by executing Project/Group/Exists scope-crossing witnesses; collision-safe names alone prove none of those laws.

## Concrete operator laws and candidate lowerings

| Oracle operation | Required law | Existing native IR lowering candidate |
|---|---|---|
| BGP/path/graph leaf | Evaluate graph positions under C; return C's actual keys plus newly matched keys | Rename leaf variables to fresh match carriers; correlate C with Lateral and/or explicit equality guards; combine context/match mapping with domain-aware aliases. A contiguous BGP uses one context and shared match carriers, not one unrelated variable per triple |
| BIND/Extend | Evaluate inner under same C, evaluate expression over forgotten R with I fallback; success overwrites target; expression error preserves old mapping | Extend into fresh e, then fresh target carrier COALESCE(e, old actual target); other R versions remain. Error with no old actual target leaves target absent. Expression error is not a swallowed operational/governor error |
| Repeated BIND without I | Same overwrite chain, later successful assignment wins | Identical SSA law; do not trigger compilation only when an initBindings target exists |
| Lazy Join | For each left a evaluate RHS under T(a,C); return M(b,a), with left priority and no compatibility check | Lateral(left, compile(right,T(a,C))); keep left/right private R names distinct and synthesize left-preferred output carriers. Avoid native natural-join equality between reassigned left/right logical keys |
| Nonlazy Join | Evaluate both sides under C, deduplicate RHS mappings, compatible natural merge with right priority | Canonicalize actual R keys to shared native private variables, DISTINCT the projected RHS logical mapping, then Join. Transport metadata/context outside compatibility keys or prove fixed transport cells cannot alter compatibility/deduplication |
| UNION | Evaluate each arm under C; concatenate bags with logical name alignment | Union of compiled arms aligned to common R aliases; retain absent cells and arm multiplicities |
| MINUS | Independently evaluate operands under C; subtract when actual domains overlap and all shared bound values are compatible | Minus over Project(left,R-domain) and Project(right,R-domain), restoring transport afterwards without multiplying rows; or a domain-aware correlated NOT EXISTS predicate. Hidden context/init/marker aliases must not fabricate a shared domain |
| OPTIONAL | Evaluate left once; RHS under T(a,C); condition uses b.forget(C); matched output is M(b,a); unmatched allowed only when remembered-scope retry has no satisfying RHS | Lateral(left, wrapper). Inside wrapper use LeftJoin(Unit, Extend(compiled RHS, marker, true), compiled condition), followed by Filter(BOUND(marker) OR NOT EXISTS(retry)). This evaluates successful RHS once and uses native padded row to recognize no match. Retry RHS is compiled under T(remember(a,p1._vars),C), and its condition reads b directly, as upstream does. Final output restores a over b |
| EXISTS/NOT EXISTS | Thaw the expression's current FrozenBindings, then test body nonemptiness | Compile body with T(expression-visible-R, original row context) and embed native Exists; alias correlation must reach body leaves and fresh computed carriers without substituting assignment output targets. NOT EXISTS negates the same witnessed body |
| Sub-SELECT | Evaluate under same C, then restrict actual R domain to projected names; expression fallback to I remains available | Compile child independently; Project actual R columns and controlled transport. Do not run the ordinary native unprojected-assignment localize pass over logical compatibility names or use native request substitutions after compilation |
| GROUP BY/aggregate | Group expressions read row overrides, not C; aggregation emits aggregate mapping, then aliases/SELECT Extend run over it with I fallback | Group on fresh computed keys, rename aggregate destinations, retain sampled/aggregate alias laws from rdflib translator and compile the later alias Extend chain. Fixed context/init transport is not a user group key. Explicit grouping with zero inputs needs oracle's one-empty-mapping behavior, unlike a conventional empty grouped result; LeftJoin(Unit,Group(...)) is a candidate only after exact aggregate/default-value tests |
| FILTER/HAVING/ORDER BY | Read operation-specific visible row, with forget/fallback law where applicable | Rewrite expression reads through R/I map and compile EXISTS recursively; preserve native ordering modifiers and runtime errors according to each operation |
| Final SELECT/star | Public names and values from final mapping; ordered rows retain sequence; star derives logical projection set before SSA variables exist | Fresh final alias Extends plus Project(public names), with oracle's final I fallback if actual projected key is absent. No private columns leak. Star compares names as a set, cells in canonical name order |
| ASK/CONSTRUCT/DESCRIBE | Consume correct compiled row mapping rather than incoming C | Retarget templates/describe variable references to final R/I resolution; keep graph construction/describing in existing production homes |

These lowerings are symbolic, not claims that a naive composition of operators already has the right semantics. Explicitly preserve bag domains, cardinalities, expression errors, row order where specified and context lookup. Existing native Lateral uses `binop::eval_correlated` and `expr::substitute_pattern`: it substitutes an outer row into the RHS. Logical assignment output carriers must therefore be distinct from correlation input carriers. Passing original logical names as native substitutions would reintroduce sameTerm joins and invalidate this design.

Read the actual final merge in `binop::eval_lateral` around lines 607–624: it tests natural compatibility on shared native schema names, then overlays the compatible RHS on the left. Thus the compiler must Project the RHS boundary to **disjoint new R output aliases** (plus only unchanged shared transport explicitly meant to agree). No RHS assignment may write a carrier present in the outer row. The compiler computes oracle left-preferred merge in fresh output aliases after native correlation; the native Lateral merge itself does not implement overwrite/restoration. This requirement applies even if the RHS assignment happens to match the input in one probe.

Upstream `FrozenBindings.project(vars)` filters actual `self.items()` and returns only those keys; it does not materialize an initBinding fallback as an actual projected key. Nevertheless `FrozenBindings.__getitem__` can resolve a missing projected name through I. Keep those two views separate across every output Project: carry the actual projected-domain predicate independently from expression/result lookup. User result `.get`/row access may retrieve I fallback, while MINUS compatibility/domain, DISTINCT mapping equality and subsequent remembered-scope operations use actual items. A hidden transport I alias is available for lookup but cannot be counted as logical row-domain membership. The final public Project is emitted after result-lookup aliases resolve the oracle-visible values; internal Project operations preserve the actual-key metadata rather than prematurely filling missing logical cells.

## Exact parser changes required

Use one parser implementation with an explicitly named compatibility admission entry point. Internally thread its law through the existing parser state; ordinary `parse_query` and ordinary `ParserOptions` consumers keep strict defaults. This is a runtime boundary, not a Cargo feature or duplicated parser.

1. In compatibility admission only, permit rdflib's BIND target collisions, repeated targets, SELECT expression/aggregate alias collisions and GROUP BY alias collisions, including unbound callers. Ordinary rules at `parser/machine.rs:1776`, `finish_select` and EXISTS's rebinding-scope checks remain unchanged. Grammar, terminal classes, IRIs, nesting budgets, datatype and RDF 1.2 validation remain shared.
2. Preserve the group/operator tree needed to reproduce the upstream translator. Current `parser.rs:3005` join removes empty BGPs and merges BGPs even when they came from distinct nested groups. Compatibility joining must distinguish adjacent TriplesBlocks inside one group from separate group operands and retain the latter until lowering. A sidecar keyed by stable parse node identity or a temporary typed compilation representation can hold boundary facts; it must be consumed by the compiler, not escape as an unsupported runtime node.
3. Apply the oracle's specified simplification before lazy analysis. In upstream `analyse`, each Join records lazy = all child summaries, then returns false upward; Slice and Distinct return false; other nodes propagate the conjunction. Embedded expression/pattern descendants can affect this analysis. Do not label every Join lazy or infer it from shared variables. Preserve left-associative source joins until this computation completes.
4. Preserve oracle `_vars` facts needed for Extend expression forget, OPTIONAL remembered-scope retry, filters and subqueries. Upstream excludes Extend.expr from its bound-variable summary and handles RelationalExpression/SubSelect specially. Native visible/free-variable sets are not automatically the same facts.
5. Compute star projection, grouping aliases and template logical names before private SSA variables enter the query. Compatibility grouping cannot enforce ordinary grouping freshness in ways rdflib does not. Native parsing and strict W3C conformance tests must remain unchanged.

Walk/census/lowering should use explicit stacks and existing walk/Child/Nested homes. No second tokenizer, copied upstream implementation, added external dependency or recursively unbounded compiler is justified.

## Shared execution/wiring

Have the Rust compatibility entry parse once, compile the typed compatibility plan to the existing Query IR, pass it to `NativeSparqlEngine::prepare_algebra`, and execute with existing configured environment and no additional ordinary logical substitutions. I is already encoded in the plan/transport. Dataset/governor/registry admission and result materialization remain the ordinary production path. Graph.query calls this explicit native boundary; SPARQLProcessor and inherited graph consumers follow it. Ordinary Store.query, prepared requests, SHACL and other bindings retain their existing semantics.

The compiler should work for all compatibility queries or make a semantics-preserving identity decision from parsed facts, not exception handling. No fallback to Python/rdflib and no text rewriting. Structural admission errors, operational failures and resource refusal must remain typed actionable failures, without using them to replace required oracle-answering cases.

## Named NOT MET proof obligations for the implementation plan

1. **SSA/correlation seam:** demonstrate that Lateral and Exists substitution preserve separate C/R/I carriers through Project and Group; private input aliases can be substituted while fresh assignment outputs remain writable. A zero-case compiler test is not evidence. Include the b/o1/o2 probe as the first production witness.
2. **OPTIONAL retry:** prove matched/unmatched behavior with filters, forgotten ancestor bindings, empty remember maps and RHS expression errors. The proposed padded-row wrapper is not executed yet. Expression volatility must not cause an extra successful-RHS evaluation merely to ask whether it was empty.
3. **Mapping domains:** prove disjoint-domain MINUS and absent projected binding behavior despite hidden transport columns. Test no-init lexical collisions, because successful init-bound probes do not cover that scope.
4. **Grouping:** reconstruct aggregate aliases, SAMPLE/COUNT behavior and empty explicit/implicit groups. Empty-row padding cannot silently invent zero aggregate values or duplicate groups. Preserve row bag cardinality before aggregating.
5. **Boundaries and optimization:** prove raw parse group/lazy facts survive until compatibility lowering; once lowered, native admission, property-function planning and evaluation optimization must not collapse the distinctions the private carriers encode.
6. **Cost:** OPTIONAL's retry duplicates its RHS compilation in a pure tree lowering. Deeply nested retries can expand exponentially. Measure/count the actual lowered size and use bounded sharing or a coherent shared native primitive if the pure existing-node lowering cannot preserve proportional representation; do not disguise exponential work with an arbitrary reassignment refusal. Any additional primitive must be shared engine support, not a second evaluator or global mode that changes native semantics.
7. **Whole scope:** execute the recovered 24+4+13 corpus, compositions, all four result forms and current working neighbors, plus native/SHACL invariant checks. No reassignment xfail, deleted test or renamed refusal discharges a row.

No fundamental impossibility is established by source inspection. The candidate is concrete enough to implement and review, provided the plan explicitly owns these proof obligations and permits repairing a demonstrated native-IR limitation coherently rather than pretending the lowerings were already validated. Do not declare a fully proven existing-operators-only solution until its contextual algebra witnesses run.

## Coherent executable implementation boundary

A first core task can own compatibility admission, preserved typed operator facts, the whole C/R/I compiler and any narrowly necessary shared native primitive, plus Rust execution witnesses for every operator law. Its done condition is successful native execution of compiled algebra for the supplied nine probes, all recovered historical shapes (including no-init collisions), mapping-domain/empty-group/retry tests and size-growth checks, while existing strict native/SHACL tests pass. It cannot commit a placeholder operator or call six implemented operators complete while the seventh refuses. Pure parsing/admission may be a preparatory task only when explicitly identified as preparation with compiler acceptance still pending; it is not issue completion.

A second surface task wires the one native compatibility query entry into Graph.query, inherits it through the plugin/dataset/shadow paths, and adds a new Python differential surface file justified by the genuine 7.6.0 oracle. Its done condition compares typed complete results for the entire matrix, ordered rows where specified, preserves current ordinary callers and full fixture identity, and runs the affected Python/Rust/wasm gates. Publication/final audit is a distinct final task after both behavior units qualify. These boundaries provide reviewable units without silently reducing the issue to initBindings-only reassignment or only the first probes.
