<!-- SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca> -->
<!-- SPDX-License-Identifier: CC-BY-4.0 -->

# Focused Task3 integration source and consumer review

Focused integration review complete at the final static-tail source and installed artifact identities below. Prior Task2 PASS remains qualified at signed 56e636497c049debe2de5445389abf3e018d4783. Integration input main is dfc0c21adabe557e5d11f027aaf2576bddbe1dd6. Sole writer owns normal synchronization and shipping edits; reviewer is read-only except this report, runs no candidate builds and creates no diagnostic processes/debris. Historical pending/failure observations below are retained; final disposition supersedes them only at the expressly rebound identities.

Read Stage3 and merge-tree instructions, current validation index and retained Task2 qualified findings, plus the actual conflicted/resolved host and automatic merge seams. The user's exact validation restriction remains: "The only things that python or wasm can check in tests are things that ONLY PYTHON OR WASM can test." Core numeric/compiler/operator/governor laws are reviewed through Rust tests. Python only checks dispatch, keyword extraction, carrier/result/exception and import surfaces. No task-specific wasm or timing investigation is authorized.

## Combined source observations

The resolved shared QueryMode helper parses main's division policy as its first settled operation, before graph selection, substitutions, relation construction or store snapshot work. Both ordinary and contextual Python entries accept and forward division; Graph forwards it and processor inheritance retains that route. The same options value contains both the existing extension environment and division policy before either engine branch. No second parser/evaluator or alternative numeric/configuration home is introduced. Main's division_policy parses through DivisionPolicy's existing FromStr with actionable ValueError; wrong Python object type remains PyO3 extraction failure.

Automatic engine merge preserves main's division option in ordinary governed-context construction and apply_query_options. The contextual convenience passes options through preparation and execution unchanged, so its shared evaluator receives the caller's precision. EvalCtx worker and UDF children explicitly copy division and inherit exact_deferral; the correlated/Apply RAII guard borrows the current context rather than constructing a fresh default policy or governor state. The issue's contextual row-delivery paths therefore retain the same numeric environment and accounting state.

Main adds ordered arbitrary-precision fuel/scratch deferral and changes native optional predicate loops to ItemLedger ordered commit. Inspected these shared homes and the issue's Apply/yielded branches for interaction: the deferral is installed by existing row loops, nested forks are excluded while one is active, numeric charges use the current context, and correlated guards preserve it. New exact numeric work must be demonstrated inside contextual Apply/aggregate/governed cutoffs at the combined source; two individually green input branches are insufficient. Existing contextual mapping domains, error/refusal laziness, callback order and ordinary admission laws remain required.

The new Rust division control compares ordinary/contextual routes. If exact nonterminating division exposes their deliberate empty-domain differences, the test should retain a bound carrier and test precision rather than change those semantics. This is a test-scope caution, not an observed candidate failure. Fresh affected Rust and narrow binding receipts are pending.

CONFORMANCE conflict resolution must preserve main's updated generated rows and retain explicit historical qualification of broad Python scoreboards. The PO catalog must preserve both sets of source messages and be regenerated; a resolved textual conflict alone does not establish translation/source drift acceptance.

## Concrete automatic-merge findings

The combined native compilation fails five aggregate integration seams: contextual custom init lacks the new division argument, custom finish lacks its numeric-error absorber, AVG finish lacks policy/absorber, and one ordinary aggregate call lacks the domain argument. The writer owns repairs; compilation failure is retained in raw/t3-affected-rust-tests.log. An automatic textual merge was insufficient.

Read raw/t3-division-target-first.log: the first policy test fails [] versus [[None]], exactly the deliberate contextual empty-domain difference noted above. This is an overstrong native/contextual test equivalence assumption, not a new source defect. The writer was notified to retain a bound carrier and compare precision at that meaningful domain; no domain law should be changed to pass this test.

The writer identified a further admission hole: contextual streaming accumulators do not call main's aggregate_numeric_cost survivor-chain admission. Their exact numeric work needs pricing through the existing shape/cost home before execution, including streamed addition/extreme comparison and final quotient/custom aggregate work; a shadow arithmetic implementation or full survivor reevaluation is not acceptable.

Independent source review found four contextual-owned sites directly recording expression_barrier, bypassing main's new EvalCtx::record_barrier suppression while a worker exact_deferral is active. The current context and its deferral are preserved through correlated/Apply guards, and pure EXISTS bodies can be visited by the fork-safety walk, so this interaction is admitted. Merely changing the recording call is insufficient: contextual_lanes returns None on refusal and the empty implicit-group path expects a globally observed barrier, which suppression can leave absent. The contextual group must propagate its local refusal coherently into truncation without prematurely recording a shared worker barrier or panicking. Exact row/governor/parallel controls at the repaired combined source remain required. Findings were sent directly to writer and parent; no shipping edits or builds were performed by this reviewer.

## Mutable repair source observations

Inspected the local Cell refusal repair: records through shared ctx.record_barrier, retains the first local trip independently, explicitly returns Truncated using that trip even when the worker global barrier is suppressed, and guards subsequent group finishes after a refusal. This avoids the empty implicit-group expect panic and further callbacks after a stopped finish. Execution and source freeze remain pending.

Shared xsd cost::SumChain factors the prior longest-whole/largest-scale/count shape recurrence; the native batch sum_chain delegates to it and contextual lanes price each addition before the actual NumericFold step. Shared aggregate_numeric_tail_cost prices final division/rendering before finish. The contextual extreme comparison uses Shape cmp_cost plus a size envelope, differing from the native batch compare_chain's magnitude grouping; qualify deterministic conservative admission, not identical native/contextual charge vectors. The native specialist must rebind source and compiled ordinary fast paths after this refactoring.

Sent remaining custom-lane admission finding: ContextualNumericCost currently returns zero for Custom and has no sum shape at finish, while configured first-party statistical aggregates advertise exact_numeric_cost(_under) on the ordinary route. Their streaming numeric work needs applicable shared/contained step and finish admission before execution; SUM/AVG controls alone do not qualify that custom aggregate contract. No final PASS is inferred from successful compilation of a mutable partial repair.

## Custom streaming repair and observed controls

The initial all-custom buffering proposal was rejected on concrete callback semantics: a Volatile aggregate must step in contextual row order across groups, and even a Stable aggregate can fail on its first step before later volatile argument expressions run. Current source instead retains accepted tuples for the existing complete-only exact_numeric_cost_under declaration, preflights the empty prefix before init and each accepted prefix before its immediate step, charges work high-water growth and the current complete scratch estimate, then uses the existing contained init/step/finish homes. The last accepted prefix reserves finish arithmetic; no finish-time replay of steps occurs. Both cost and accumulator errors remain contained and operational errors propagate immediately.

This generic complete-declaration fallback may rescan prefixes quadratically for a declaration which scans all operands. It is confined to explicitly contextual custom aggregates and preserves the existing extension API and callback/error contract; it does not establish an equal contextual/native charge vector or a new contextual performance claim. Prefix bytes are charged conservatively each time, rather than as a work-like high-water delta. Ordinary Rust preservation requires the independent combined-source emitted/source cost rebind.

Read raw/t3-ordered-custom-contextual-tests-repaired.log: actual release contextual target passes all 21 tests. Its new owned observer checks Stable and Volatile intergroup arg/step order, both first-step operational error cases with no subsequent arguments, and declared work refusal before the first custom step. This receipt qualifies those controls and current prefix source, pending final immutable source identity and broader affected gates. Requested focused empty-group initial-cost and nonzero custom scratch refusal neighbors; these exercise the actual new admission boundaries, rather than repeat callback examples. No reviewer build or test was run.

Read the integration-only Python delta: one test checks invalid division ValueError precedence over Python term extraction and wrong-type PyO3 TypeError on both actual native doors; the four existing Python receiver dispatch cases now assert division forwarding. These are irreducible language-boundary checks, with no new semantic matrix. Graph's explicit kwarg and the contextual stub match the native entry's existing main division policy. Existing narrow carrier/result tests retain their Task2 binding rationale. Execution and installed/source identity at the combined candidate are still pending.

The added 1,500-driver nested FILTER EXISTS/implicit AVG control compares full answer and evidence under full, half fuel and half scratch across configured 1/2/4-thread pools. Source review finds Compiler::Filter lowers through row_operation_base to an outer Apply with a singleton native Filter, or merges into a row-pipeline RHS. Consequently a green pool comparison establishes nested cutoff and pool consistency; pool size and driver count alone do not prove this query entered a worker exact_deferral. This qualification was sent to the writer; no synthetic instrumentation or unsupported actual-fork claim is imposed. Source-local refusal remains correctly independent of global worker recording. Main's separate native parallel exact controls still require combined-source execution.

Read the final custom observer extension: an empty implicit-group declaration refuses fuel before init (initialized count stays zero and no argument/update events), and a nonzero declared scratch estimate refuses before the first update after its argument event. These are the requested new boundaries; final affected gate is compiling at raw/t3-final-affected-rust-tests.log, not yet a pass. Independently checked raw/t3-final-rust-start-sha256.log against current files with sha256sum --check --quiet, exit 0. Modifier identity is 76c868e6ed54bc74860f3b72fbff1fea058719290e00e19da3abfaad27b6ab87, contextual test e41d47ba4fc8c33efc0952e594d156caa8a60ae0eb50b430f98184fc56ea221b, exact cost 0fb10be2d0047d51f37a9a426e034461b95915c9da29a7f5f0ff292c1066b355.

The final CONFORMANCE delta against dfc0c21 preserves main's generated 3945/81 Python rows and adds the historical snapshot qualification outside the generated block. No dependency delta exists against that main in Cargo.lock, root Cargo.toml or the evaluator manifest. Both translated and original source messages still require the final docs/catalog receipt.

Independently read the complete raw/t3-final-affected-rust-tests.log results: algebra 464, iterative traits 3, evaluator unit 1380, exact numerics 7, EXISTS 25, governed query 25, governed update 26, governor correctness 9, numeric casts 14, numeric contract 7, numeric governance 11, numeric parallel determinism 8, prepared reuse 7, contextual 22 and xsd unit 298: 2306 passed, zero failed/ignored. The final contextual 22 includes custom empty-cost/scratch refusal, callback/error order, all frozen contextual fixtures and the qualified nested cutoff/pool consistency control. Owner terminal exit and final source manifest recheck, installed narrow binding receipt, docs/catalog gate and independent combined-source native logical-cost proof are still required before final disposition.

Read final release clippy failure in raw/t3-final-release-clippy.log: contextual finish numeric-error absorber's unit-return closure requires a trailing semicolon under semicolon_if_nothing_returned. This is an owned shipping gate failure, not waived by the passed tests. Writer owns the one-token repair, warning-free re-execution and final source/codegen/module rebind. The 2306-pass receipt remains semantic evidence for that unit-return-only hygiene delta; no reviewer demands an unrelated full semantic repeat.

Read raw/t3-final-lint-repaired-release-clippy.log successful release completion after the owned repairs. The intermediate second lint failure (test closure semicolon and excessive-bools observer configuration) is retained by writer. The final manifest differs only in modifier.rs fc8f8eae8574082d22df923c97fa15a7391367a31c881c98d3514280dab6675a and contextual test 5fd7872ac5b8983de918023f784f84b3c24f064eec46e48e4870b39d808f652d. Reviewed the Pricing enum replacing three mutually exclusive cost booleans: same seven scenarios and exact ZERO/prefix/initial/bytes declaration cases, with no changed intended semantics. Focused contextual 22 re-execution will bind this test refactor; no shipping ordinary-body change beyond the unit-return semicolon occurred.

Read raw/t3-lint-repaired-contextual-tests.log terminal successful result: all 22 passed, zero failed/ignored. This rebinds the test refactor and unit-return source repair. Semantic and release lint checks are complete at the repaired freeze; final installed language-boundary receipt, docs/catalog and source/artifact identity plus independent native cost disposition remain pending.

Read raw/t3-final-catalog-terminal-receipts.log: make book-po-update exit 0, regenerated catalog cmp exit 0, msgfmt format/statistics check exit 0, fuzzy search no matches. Writer supplies the executed statistics: 2957 translated messages, no fuzzy/untranslated. Source documentation did not change after this gate. Together with the reviewed CONFORMANCE/PO merge this completes scoped docs/catalog acceptance. Read raw/t3-native-probe-terminal-receipts.log: candidate native probe exit 0 and all 32 untimed output/allocation records compare equal against dfc0c21 main. Independent native emitted proof disposition is still pending; identical records alone do not replace it.

Independent native reviewer found a concrete ordinary cost failure in the current emitted artifacts: SumChain and numeric tail helpers remain outlined despite inline annotations, adding calls/live callee frames, and the tail repeats bounded/default-policy work already excluded by its caller. Read tasks/T3-integration-native-cost-review.md actual emitted finding. This is NOT MET at the current candidate; equal 32-record allocations/results do not override the compiled evidence. Writer owns targeted helper erasure and fresh source/codegen/module attribution. No final PASS is issued while this defect remains. Existing semantic and docs receipts remain qualified to their observed source bodies; no shipping modification by this reviewer.

Reviewed the targeted repair: reasoned, narrowly scoped inline(always) annotations on SumChain::push and shared aggregate_numeric_tail_cost only, with no arithmetic/control body change. Corresponding clippy allows carry concrete performance reasons and do not suppress a semantic finding. Independently checked raw/t3-inline-cost-repaired-source-sha256.log against current files, quiet exit 0: modifier 751ceaf699dcc9b3b547cd9bd15ed4f0ce97e022a78d7c7e5d051e49b406a178 and exact cost 6228ad322df4ceb8596067a9eae705e84dc85f4b252bd07b5727daa658d85d0d; contextual test remains 5fd7872a. Source annotations alone do not close the emitted cost finding. Fresh compiled proof, warning-free gate and installed identities remain required.

The repaired native emit and selected release clippy terminate exit 0; repaired 32-record untimed probe compares equal. Independent compiled review confirms the new helper calls/live frames are erased, but detects a second NOT MET: repeated policy-mask/compare/branch remains at native block369 after the caller already excluded that fast path. Fresh main has no such second check, and native bounded totals with nondefault division reach it. Writer owns removing the redundant native guard while retaining contextual bounded/default admission. A compile-time caller specialization or contextual-only guard placement preserves the single arithmetic home; no runtime flag or new ordinary cost is justified. No final PASS from partial erasure.

Reviewed CHECK_FAST_PATH static specialization: contextual finish uses true, ordinary aggregate_numeric_cost uses false only after its existing bounded/default early return. One shared arithmetic body remains, no runtime flag or additional ordinary argument, and the contextual guard/policy law stays intact. Independently checked raw/t3-static-tail-repaired-source-sha256.log, quiet exit 0; only modifier changes from prior annotation freeze, now 815f752eda5df480766e5d1d7f5dcbfd04de257480f273209ade5e7ae856c7ac. Actual static-tail native probe exit 0 and 32-record comparison exit 0 were read. Fresh emitted disposition and lint/module rebind remain required.

Read independent native review's final static-tail numeric comparison: both concrete native blockers are resolved at the static-tail source/artifact pair. The recurrence/tail execute inline without added calls/live frames/state or repeated policy test. Existing arithmetic/control paths retain their work; saturating nonnegative addition/max reassociation has no new allocation, conversion, loop or callback. Complete IR has fewer static sat-add/max sites and assembly retains the same 20 calls; those counts support the read paths rather than license added operations elsewhere. Fresh untimed 32-record native stdout compares equal again, SHA d3e5f397 as recorded by native review, covering ordinary queries/bindings/division/configured relations/layouts and lifecycle allocation windows. Repaired release Clippy exit 0 is executed. Final same-command host emit/source/module attribution remains pending, so no overall verdict yet.

Independently read final tasks/T3-integration-native-cost-review.md MET for primary ordinary native Rust at static-tail 39-path source manifest c9492b9fb2b85b9ad8f5f0a1669d1a24cf154553f3c94f7a414292c727bab2a8 versus fresh main dfc0c21. Full final host LLVM/assembly are byte-identical to the already-read paired host boundaries; hashes and final manifest check bind them to current source. Operator/caller ABI, frames, original arms, retained layouts and algorithms, unit/false erasure and repaired numeric recurrence/tail are complete. Both actual performance defects remained NOT MET until compiled repairs were read. This closes the scoped performance acceptance without timing, an allowance or an unseen-target claim. Only final installed narrow language-boundary/source/artifact identity remains before this review's overall disposition.

## Final executed consumer and source rebind

Independently read raw/t3-final-bound-python-boundary-tests.log: exactly 15 collected and 15 passed, no skip/xfail, three expected ConjunctiveGraph deprecation warnings. Raw/t3-static-tail-gate-terminal-receipts.log records actual install exit 0, first and identity-bound boundary gates exit 0, and postgate module/lock/test/source checks exit 0. The initial module locator looked under .venv instead of the editable package; its diagnostic was repaired before the identity-bound repeat, not counted as successful attribution. Actual module is bindings/python/python/src/purrdf/purrdf_native.abi3.so, SHA b5b0366f0d57e76596cc17f88f02c223b0e181ef68b3866bc2673990ad143433. Install used the actual optimized dev profile with debuginfo; it is binding-semantic evidence, distinct from the matched optimized native cost builds and their specified stages.

Final binding input SHA identities: uv.lock 06275d43821c8351f89f88071af043ce4c4645fe3adcf2126b2f28f031cafc01; narrowed test 3e0cc4e1844395f9672316dc0f743653e4eff1e6c46ddb01cd8371195faee2dd; Graph source 8dadcb532dbf9250264b99b1c0bca6a045ff0dcb3e40d5a98465ecfb714831f6; stub 467194bab3f3d02ac6a59d1c334f58e8e540371942600a214f5d546bc68cd96b. Complete 49 shipping-path manifest raw/t3-full-combined-shipping-source-sha256.log SHA 3b03a07b97ff96de219fba8279e654e4d7f6fc7ef162b3ea4d6767452c472c63. Rust affected 39-path static-tail manifest SHA c9492b9fb2b85b9ad8f5f0a1669d1a24cf154553f3c94f7a414292c727bab2a8. Independently checked all four manifests (Rust, complete shipping, binding inputs and actual installed module) against current files in one read-only sha256sum --check --quiet invocation, exit 0.

The 2306-pass affected Rust gate and 22-pass focused rerun remain precisely qualified to their observed snapshots. Subsequent targeted erasure changes add reasoned inline annotations and specialize only the already-excluded native guard, keeping contextual guard true and one arithmetic body. Source equivalence, fresh warning-free release clippy, final executed 32-record native comparison and actual emitted proof bridge those small optimization-only deltas; no obsolete compiled receipt is misrepresented as an execution of different source. Broad Python semantic scoreboards remain historical and unrefreshed under the user's exact restriction. No task-specific wasm or elapsed-time performance check was run or required by this scope.

Provenance/source review finds original first-party integration code using existing typed compiler, shared evaluator/accumulator and xsd cost homes. No issue-introduced dependency, copied upstream body/table, runtime RDFLib dependency, second parser/evaluator, semantic Cargo feature or generated shipping hand edit is present. Frozen external fixture inputs/answers are data, with the prior qualified Task2 provenance retained; this review does not recertify unrelated main features. Main's numeric/division/governor changes and issue contextual delivery/configuration/result surfaces are coherently composed at the rebound source. No concrete source/consumer finding or required scoped acceptance remains open.

Reviewer owns no process, build output, temporary probe or shipping debris; only this report was changed. No cleanup/work item is handed to the user or root. This verdict is source/consumer integration acceptance at the manifest above, not a claim that a commit, push, PR merge or hosted gate has occurred.

VERDICT: PASS
