# Final main402 interaction with454

Status: READ-ONLY SOURCE ASSESSMENT; no current final integration qualification. Actual origin/main df2cec88b0f8e05e05ef3d01d14714474be6bbb1 versus retained454 MERGE_HEAD2eb04d61f3d65f34ec77b396b5d03c05c23fd5ee. Do not alter current merge-in-progress identity or promote archived2eb proof to df2.

Read both current454 mode/algebra/evaluator/host paths and main402 delta. This is substantive shared-source interaction: main engine PreparedQuery adds Option<Box<Query>> original parsed provenance and retained-size charge before joining prebound assignments (engine.rs source_query/admitted/PlanCache); main EvalCtx and QueryOptions add borrowed optional UserFunctionAdmission inherited by workers/function children; engine entrypoints add request-local RefusalPublication and final-storage-precedence finish, FunctionAdmission typed cause, bounded workspace admission and governed/fallible construct publication. These touch exact ordinary layout/caller/prepare/capture seams of cost proof. Parent original2eb bodies/layout1232 cannot prove current df2 combined bodies by a disjoint-file claim. No new external dependencies introduced: main lock change adds only conformance-kit first-party closure.

454 contextual prepared wrappers call the same query_prepared_view/governed home (current engine.rs1075–1126) so after coherent merge they must inherit main typed invocation publication rather than retain a bypass. Preserve mode-specific compile/source visible projection and generic QueryMode() plain path; reconcile admitted constructor’s new source argument with contextual preparation, retaining original authored algebra for selected admission. Main worker/child user_function_admission must survive all454 static mode contexts. Native plain/SHACL continues native prebinding; contextual rdflib behavior must not leak into SHACL restrictions or original-source checks. Main SomeValue hard Admission/QuerySource capsule precedence must remain distinct from ordinary semantic suppression. Main ShEx/shapes/WASM JobAmbient’s new query-law context and10swapped fields must remain untouched while carrying454’s shared algebra Apply arm in exhaustive prebinding/checkers.

Read-only `git merge-tree --trivial-merge` using base2eb, main df2, index933daa retained at portfolio-main402-predicted-merge.txt. Shared engine/eval/lib/prebinding auto-combine textually; PO contains a textual conflict. This predicts no code marker but is not semantic compilation evidence or a final committed candidate. Three new repair deltas are not part of that historical933daa index and must be preserved separately. Main source constructor/worker changes make source review and bounded qualification mandatory even if clean.

Preferred sequencing: root settle current owning in-progress2eb merge normally only when its required gate claims are truthful; then ordinary base synchronization df2 in SAME existing454 WT, resolving both sides and retaining the GRAPH inline/prose/row fixes. Alternatively root can bind a final clean merge candidate after its qualified current normal commit and qualify that exact candidate before ghprsq; avoid repairing/emitting an intermediate2eb cohort only to repeat final common-source proof. No abort/reset/rebase/rewrite/new branch needed. A current-source normal commit must not claim full nativecost/docs completion while missing.

After actual final source exists, narrow execution: owning compile/strictalltargetclippy evaluator/algebra/Python/shapes; exact existing contextual target + newXPathcontextual law/resource regression; main user_fn invocation_admission group, prepared_parameters and prepared source_query controls; main dated_execution (SomeValue hard admission vs semantic negative/worker/cause precedence) and existing prebinding_lanes/blank-focus/exists/hidden-column controls; governor/numeric parallel/source precedence targeted entrypoints whose worker/option fields changed; exhaustive serializer/Apply controls. Reuse unaffected2125 tests by byte/source seam mapping, no blanketmatrix ritual. Combined helper/layers/terminal/ratchet/stub gates must run on actual combined source because added kit/corpus/algebra helpers can create census intersections. Rebuild one current production wheel and rerun exactly existing28 boundaries: native library ABI and source changed even with unchanged Python files. Do not reuse prior installed nativeSO as current df2 artifact.

Native cost final proof requires exact immutable df2 baseline plus actual combined candidate, production lock seeds/full compiler external checksum bindings, same named native ThinLTO/host noLTO settings; emitted modules/ordinary host caller/PreparedQuery retention/EvalCtx layout/worker capture must be regenerated for both roles. The old2eb generated sample/body audit remains diagnosis/history, not final equality. Keep exact32 record equality refusal; baseline now incorporates main’s intentional provenance/layout changes so compare combinedcandidate against df2, not demand unrelated402 storage changes equal2eb. Full independent old-arm loop/control/ABI/frame/capture/drop/numeric proof remains required, and actual GRAPH no-helper frame after repair must be shown. No normalization of these costs.

Docs final integration must preserve both current translated contextual messages and main402 added product/profile claims, then owning PO refresh/source binding followed by current glossary7poisons/6arms/render/generated/prose gates as affected. Old broad Python snapshot may remain explicitly historical and its generated comparison must remain strict; no broad Python/vendor/oracle rerun authorized. Whole completion/hooks/push/hosted/finalghprsq remain root’s later gates, never inferred here. External submissions remain excluded and untouched.
