# Actual missing-field fixture qualification

VERDICT: PASS for admitted test-only source/compilation/lint qualification. Existing hosted attempt remains FAILED, fresh hosted/publication NOT MET.

Actual session25250 terminal0 observed through tools.write_stdin; evidence /opt/purrdf-454-current-qualification-20261008/current-hosted-fixture-rust-1/session-terminal.json and all six commands/driver exits0. Scope purrdf-454-hosted-fixture-rust-20261008.scope invocation29bd0976a75945f1979a676e6326ccb7 captured active64GiB/SwapMax0; terminal inactive/dead/lane FREE. Raw same SDK/private existing target/build/tmp/jobs8/libtest8/inherited kache and exact same WTvenv Python3.13 PYO3_PYTHON recorded.

Exactly three existing named tests actually ran/PASS/zero failed or ignored: umbrella reasoning contextual_application_visitors_preserve_children_and_ordinary_admission_refuses_it; RDF description contextual_application_visits_both_operands_and_nested_expression_causes; slice ownership contextual_application_collects_both_child_iris_and_nested_exists. No new test/corpus or semantic suite expansion. Actual cargo check --workspace --lib --tests --locked --jobs8 exited0, compiling entire library/test-target closure after omitted-field inventory. This is compile coverage, not executed whole-workspace tests. Strict all-target clippy for purrdf/purrdf-rdf/purrdf-slice and workspace fmt both0.

Full tracked source readback0/staged tree1905c6847912d5ee3d6f7de618a575d7cb5bd2f2 unchanged/no unstaged source. Three cfg(test) initializer fields false, production kernels byte-unchanged; original72fa cost/ABI/native-host/28wheel/docs evidence remains scoped applicable, no re-emission or whole-host repeat. Independent source review/validator law preserves raw nested-Graph structural slice fixture without misusing the restricted directGraph admission flag. Old hosted workspace101 and mandatory assembly projection mismatch remain explicit owning failures. No commit/push/new dispatch/evidence copy during qualification; normal signed fixture commit/publication and source-bound fresh CI require root admission, including actual owning SIMD projection generation.
