# Candidate-only bulk Project/mint artifact generation

VERDICT: PASS for actual candidate-only artifact generation and immutable baseline admission. Full native-cost acceptance remains FAILED / NOT MET: current native Project invokes an additional per-row SmallVec::Extend callee/frame.

Actual session99950 terminal0 observed via tools.write_stdin; driver.exit0 and all seven child commands0 retained at `/opt/purrdf-454-current-qualification-20261008/final-mint-project-native-cost-1`. Scope purrdf-454-mint-project-native-cost-20261008.scope invocationb42b69a0f46b4f08a96a9c13214c7102 inactive/dead/lane FREE; live64GiB/SwapMax0 captured. Raw active SDK/private fresh candidate native/host roots/jobs8/inherited kache retained. No timing claim; same named native ThinLTO/host no-LTO O3/codegen1/strip/assertions+overflowOFF/target-cpu native profiles and actual verbose argv.

Fresh candidateb3274735168b7aa063b7163ef5c3f0d4ea8a82e3 remained frozen through both emissions and all final readbacks. Baseline is the EXACT settled85204 baseline roles/df2 source, not its historical candidate. Driver requires actual85204terminal0, source18278 tracked Git blobs plus final hash readback; identical compiler/Cargo/PATH/start-profile/effective proof settings/absolute interpreter and admitted wrapper; original selected native executable and non-test Python library frames;108 baseline native paths/54 nonempty LL+ASM pairs and one nonempty host pair; revalidated actual compiled production package checksum closures21 native/49 host. Every baseline manifest/frame/argv/cohort/probe/record receipt is hashed before/after, along with original executable/LL/S/host libraries. No old frame path rewriting or baseline recompilation occurred.

Actual PyO3 build identity extends beyond interpreter path: baseline/candidate build-script package/ABI cfg/link-lib/link-path/env vectors compare exactly for pyo3-ffi/pyo3; both actual RerunIfEnvChanged/rustflags fingerprint records compare exactly. Configuration override/cross/no-Python/signature/print environment must remain absent; absolute WTvenv Python path remains identical. Both original and fresh fingerprint files hash-readback0. This proves the actual emitted Python3.13 limited-API configuration binding without an invented interpreter config or package replacement claim.

Fresh candidate native108 nonempty paths/54 LL+ASM pairs, unique native executable and21 compiled external checksums; fresh host one complete LL+ASM pair, unique non-test .so/.rlib frame and49 compiled external checksums. All current and reused source/inputs/emits/libraries/fingerprint/evidence hashes read back0. Actual32 candidate untimed records compare whole-byte exactly with original baseline32; equality0/SHA2566e29edae8b91192ac748de338a08f2e8c0f9832648b8d8fc3508d3fc2e361f4e. Source/index remainedb327/no unstaged shipping changes.

Independent fresh native audit shows shared mint replay inline in Filter/Extend/Group, but Project calls the existing SmallVec::Extend Map callee per row: complete205LLVM/228ASM body/CFA112 absent from baseline's inline bulk loop. Returning to the correct bulk source law did not erase this frame. Full current host pair has been supplied for final independent whole-criterion applicability review. No full-cost PASS follows from generation/equality or unchanged host finding. Owning shared-home annotation strategy is proposed in portfolio-smallvec-bulk-boundary-proposal.md, source-only/no further repair made during generation. All older failures remain preserved. No wheel/docs/full-suite repetition, commit/push/external repository action.
