# Fresh lower-repair artifact generation

VERDICT: PASS for admitted artifact generation/checksum binding/exact32-record equality. Full native-cost acceptance is FAILED / NOT MET: independent current native audit retains an additional ordinary Extend mint-prefix closure call/live frame.

Actual session85204 terminal0 observed via tools.write_stdin; driver.exit0/all four owning emission exits0 and all metadata/resolution/probe/equality exits0 retained in `/opt/purrdf-454-current-qualification-20261008/final-lower-native-cost-1`. Scope purrdf-454-final-lower-native-cost-20261008.scope invocation6a692ca8afce4bbb9db7c0ab1869432f inactive/dead; lane FREE. Actual active64GiB/SwapMax0 receipt plus compiler argv/cgroup process snapshot retained, inherited kache disclosed. No elapsed-time/performance claim. Raw active SDK/jobs8/private fresh role targets/builds, identical absolute qualified WTvenv Python3.13 interpreter.

Candidate staged tree2f3ee2d75b30145ac053be6587223d892b26368c remained frozen throughout all four role emissions and final readbacks; HEADfd963c263/MERGE_HEADdf2cec88 unchanged/no unstaged shipping source. Immutable baseline `/opt/purrdf-454-native-cost-main-df2cec88` binds every18278 tracked Git blob, then complete final hash readback0. All candidate tracked source/probe inputs/production locks/native emitted files/host emitted files/actual host libraries read back0.

Four fresh actual compiler-frame closures admitted against exact source production name/version/source/checksum records:21 compiled external packages each native role,49 each host role, zero unapproved tuples. Ordinary offline seed-lock resolution followed by locked metadata; probe locks byte-identical. Each native role108 nonempty paths/54 matched LL+assembly pairs; each host role one complete nonempty LL+assembly pair plus uniquely selected actual non-test .so/.rlib frame. Exact inventories, frame metadata, full verbose effective compiler argv and checksums retained. Native named analytical O3/ThinLTO and host O3/no-LTO, codegen1/strip symbols/assertions+overflow OFF/target-cpu native/warnings denied remain accurately distinguished from final production fat-LTO identity.

Actual untimed probes each emitted exactly32 complete records; whole byte comparison exit0, both SHA256 `6e29edae8b91192ac748de338a08f2e8c0f9832648b8d8fc3508d3fc2e361f4e`. No normalization/subset/old-candidate promotion. New native pair was supplied to independent reviewer while host emission continued; complete settled host pair/49-package receipts and all readbacks were then supplied after actual terminal0.

Independent current fullbody audit `portfolio-final-lower-native-cost-body-review.md` finds named lower checkpoints erased and Project cell loop inlined without FromIterator, but actual ordinary Extend has four calls to commit_items closure#5 (mint-prefix count_to) absent from df2 baseline. Complete47LLVM/80ASM callee has a nonempty-path six-push/sub88/CFA144 frame and80-byte value temporary; empty prefix returns before frame. Shorter other frames or matching32 records do not discharge this extra work. Full Application/host/other criterion audit continues; no blanket native-cost PASS is asserted. Preserve exact current2f3 artifacts and all older300e/wrong-cohort failures. A new source repair must rebind actual affected qualification/current candidate bodies. No source edit, cost repair, docs/wheel repetition, commit, push or external repository action occurred during generation.
