# Final72fa selected evidence packaging proposal

2026-10-08. **Artifact packaging remains preparation only: no large artifact copying, compression, relocation, removal, capture, build or forge action executed.** Root admitted the plaintext/archive policy scan and preservation of this proposal's original rejected prose outside the selected Stage only. Its actual scan/report is recorded in tasks/portfolio-final-credential-policy-scan.md. Separate root admission is required for the artifact operations below. Source/body cost PASS is bound to72fa2c1ff03b00b4052bccf17895a091805785cf and actual85330; upcoming test-only1905 source does not relabel these emissions. Existing `raw/t2-evidence-packaging.md` lossless/credential/readback contract and Stagectl merge-preflight apply.

## Measured inputs and exact selection

Existing selected Stage contains5275 regular files,5,780,710,671 bytes, no observed symlinks; nine plaintext files exceed100,000,000 bytes and eight exceed104,857,600 bytes. All existing evidence—including every failed-body/source/review/receipt record—must remain losslessly represented. Do not replace or discard that history to reduce size.

Proposed final role homes under `raw/current-qualification/`:

| Archive home | Original selection | Actual bytes/files |
| --- | --- | --- |
| `immutable-baseline85204/receipts/` | `/opt/purrdf-454-current-qualification-20261008/final-lower-native-cost-1`: every top-level `baseline-*` file plus compiler.txt,cargo.txt,effective-proof-profiles.txt,profile-environment.txt,session-terminal.json,driver.exit,matched-python.txt,common-probe-source.sha256 |64files/6,128,139bytes. Historical85204 candidate receipts remain in existing history, not relabeled baseline. |
| `immutable-baseline85204/native/`, `host/` | Every path in that root's baseline-native-emitted-paths.txt and baseline-host-emitted-paths.txt, exactly110full LL/S files |237,492,125 native+135,088,259 host bytes; largest native70,236,641 and hostLL104,781,948. |
| `candidate72fa-85330/receipts/` | Every top-level regular file in `/opt/purrdf-454-current-qualification-20261008/final-project-private-kernel-native-cost-1` |109files/8,662,630bytes, including all reused-baseline admission/cohort/PyO3/finalreadback/session records. |
| `candidate72fa-85330/native/`, `host/` | Every path in its candidate-native-emitted-paths.txt and candidate-host-emitted-paths.txt, exactly110full LL/S files |249,468,035 native+147,149,202 host bytes; largest native78,067,944 and hostLL114,638,589. |
| Each role's `selected-artifacts/` | Every actual path in its native-inputs.sha256 and host-library-artifacts.sha256: executable, shared probe source/Cargo.toml/Cargo.lock, actual selected host.so/.rlib |Baseline6files/52,813,784bytes; candidate6files/55,345,418bytes. No full target/build/fingerprint directory. |
| `owning-private-kernel35/`, `owning-project-governor71/`, `owning-smallvec53/`, `owning-mint45/`, `owning-lower160/` | Top-level regular files only from final-project-private-kernel-rust-1, final-project-view-lift-rust-1, final-smallvec-bulk-rust-1, final-mint-rust-1, final-lower-rust-1 respectively |29/2,318,590;30/2,308,975;32/2,321,128;28/2,319,363;34/2,438,891. Preserve source scopes and expected counts rather than relabel all as72fa runs. |
| `owning-doc-generation/`, `owning-doc-validation/` | All top-level regular receipts/preimages from final-doc-generation-1 and final-doc-validation-1 |23/7,950,771 and44/2,339,181. |
| `owning-doc-validation/rendered.tar.gz` | Every path from final-doc-validation-1/rendered-html-artifacts.sha256, not merely HTML subset, retained as lossless data archive rather than new executable Stage JavaScript tooling |164files/13,514,502bytes;37English+37zh HTML inventories, styles/scripts/support files retained. Exact member paths/modes/hash manifest and original source/tree/PO preimages remain attributable. |
| `owning-wheel28/` | All top-level final-lower-python-1 receipts plus its exact wheel/purrdf-3.0.1-cp313-abi3-linux_x86_64.whl |35receipts/2,345,236bytes+wheel15,474,555bytes. Keep27entries/native/module/interpreter/install/readback records and28actual tests. No installed venv or unrelated process dump. |

Full final role top-level metadata/selected frames/actual argv, production lock and registry closures, actual compiler/profile/PyO3 configuration/build inputs/fingerprints and originals' manifests remain unchanged. Treat each role's original probe/interpreter/tool inputs distinctly; no new probe execution. Reconstruct final source through its canonical committed/audit head tree and baseline through df2cec88b0f8e05e05ef3d01d14714474be6bbb1 retained in its ancestors. Retain exact source-start/tracked-path/hash manifests. Do NOT copy the full source tar or source byte files into selected Stage: the actual policy rejects public OpenPGP armor markers in first-party parsing code and a frozen test fixture. The existing owned baseline `/opt/purrdf-454-native-cost-main-df2cec88/source.tar` remains unchanged outside publication with its SHA/readbacks; Git tree reconstruction preserves every original source byte without redaction or compressed concealment. No final full-source archive or whole build checkout is proposed.

## Existing historical Stage and lossless representation

All current Stage records stay selected, including failed2eb/d632,300e,2f3,b327,23f7,4828,579 and both diagnostic histories. Keep primary reports/source excerpts/commands/exits/readbacks directly readable. Canonical deterministic gzip companions replace large selected plaintext only after separate root admission of relocation/removal and exact verification; originals remain in their current location during compression/review. In particular do not silently delete the full-module historical audits merely because current proof passes.

Concrete canonical threshold: every existing nongzip regular file over1MiB (244files/5,069,471,729bytes), plus each newly selected LL/S/source archive over1MiB, is eligible for `gzip -n -1 -k`. Retain small files and already compressed gzip/wheel unchanged. Use one canonical companion per original byte identity; existing verified same-content companions may be reused only after full readback. Deterministic same-byte gzip blobs naturally deduplicate in Git even when historical paths differ. No tar containing all full targets and no second redundant large plaintext copy is proposed.

For each actual selection write a path map with original absolute/Stage-relative path, archive-relative companion path, original size/mode/SHA256, stored size/SHA256 and compression status. Keep every original absolute-path manifest verbatim. Reconstruction: restore named originals with `gzip -dc ARCHIVED.gz > ORIGINAL`; verify full manifest before interpreting receipts or replaying commands. Preserve basename/path roles using the map, not flattened ambiguous hashes. Replay depends on matching Rust SDK/production registry lock/interpreter/tool identities and recorded profiles; copied artifacts allow read-only body proof without a compiler run.

## Credential and archive admission protocol

Before compression scan complete plaintext/binary bytes and receipts with the actual capture helper's current CREDENTIAL expression at `/home/paudley/stage/stage-scripts/ghprsq-stage.py`, filename-only output. Do not restate matching literals in selected prose, weaken/change the expression or print matches. Include source archives' member streams and decompressed existing archives when evaluating plaintext content policy. A match blocks packaging until owned policy-compatible remediation; gzip must never conceal a rejected original. Actual scan found the original editable paragraph itself matched the helper. Root-authorized original bytes/hash remain in the task-owned private history path recorded in raw/final-credential-policy-scan-20261008/proposal-private-history-root.txt; they are excluded from selected publication, including compressed publication. Immutable source matches remain in their original canonical Git/source records outside Stage, not redacted or changed.

For every newly compressed path require actual gzip exit0, `gzip -t`0, full `cmp ORIGINAL <(gzip -dc ORIGINAL.gz)`0 and decompressed SHA equal original's retained manifest. Verify each copied noncompressed artifact against its original manifest, all selected emitted counterparts nonempty and no symlink-to-disposable-target substitution. Record actual stored size: any oversized gzip is a real unresolved publication blocker, not presumed compressible. Original relocation/removal is a distinct root-admitted phase after qualified lossless companions/readbacks, retaining owned originals outside the selected publication directory until remote archive verification/cleanup authorization.

## Size estimate and actual capture constraints

No new compression has run, so no exact final compressed size exists. Actual existing15gzip files total387,772,112bytes. Three measured large LLVM examples have original172,422,504/187,097,013/187,178,194 and stored34,467,226/37,360,385/37,375,159bytes (about20%). Applying that observed ratio to the244eligible originals gives about1.014GB; existing noneligible/current gzip+small records contribute about0.711GB, so existing Stage would be roughly1.73GB of stored file bytes. A15–30% ratio range yields about1.47–2.23GB. These are estimates, not publication admission. After separate compression admission, group actual originals by canonical SHA/size, verify byte equality before deduplication, compress one representative per identity and map every historical role/path to reconstructible stored bytes. Measure actual stored unique-byte sum, largest blob and actual capture pack before publication. Preserve every historical record and original until authorized archival/readback/cleanup. GitHub's single-push limit is2GiB, so the20% estimate cannot establish fit; do not use LFS, another repository or multi-push bypass to evade that guard.

Inspected actual ghprsq/capture implementation has **no100MB filtering rule**: it captures every selected file, ignores ignore/attribute/filter exclusions, scans stable snapshots, validates the tree, and merely prints an all-evidence notice above20,000,000bytes. The external forge blocks files over100MiB (104,857,600bytes); use conservative100,000,000stored-byte preflight ceiling. [GitHub's actual file-limit documentation](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github). Current nine>100MB/eight>100MiB files therefore require packaging, not silent capture exclusion.

Select only the existing direct `.stage/rdflib-shim-algebra-level-reassignment` home explicitly. Source must be normally committed/clean outside that selected directory before final ghprsq capture. Stop all evidence writers and finalize maps/prose before root performs the supported local capture preview for this concrete size/content risk; no preview/objects/refs were created in this proposal. Any later report/receipt changes invalidate preview. Final `refs/ghprsq/pr/<PR>/stage` capture is separate from source and must contain the complete qualified selected bytes; root verifies essential archived reports/manifests/representative reconstructed module and binding records before worktree cleanup. No publication/merge/cleanup is authorized by this preparation.
