# Final bulk-fill and mint-prefix source review

2026-10-08. **Source verdict: PASS for the two bounded repairs; emitted-cost verdict: PENDING.** Read-only review compares immutable failed2f3ee2d75b30145ac053be6587223d892b26368c with the current source delta in modifier.rs and row_checkpoint.rs. Root/G own source/index/build actions. No compiler, runtime, probe, source/Git/forge mutation by this reviewer.

Project replaces explicit reserve plus cell-by-cell push with Solution::new() and the existing SmallVec::extend over src.iter().map. The map preserves original column order, missing-column None and exact selected cell values. Its lower size_hint is src.len(), so the existing shared Extend home performs the original geometric lower-bound reserve, retains raw destination pointer/capacity/length through bulk filling and commits length through LenOnDrop. Explicit outer Vec::with_capacity/row loop remains; no FromIterator wrapper, unsafe duplicate slot writer or reserve_exact alternative is introduced. This addresses the actual repeated tag/capacity/length work found in2f3, subject to compiler-body proof.

Moved-mint replay replaces the one local count_to closure with one scoped inline helper in its existing checkpoint home. The loop condition, values.next exhaustion break, increment-before-count ordering and count_worker_mint call are identical. Every prior invocation passes the same mutable values/interned and upto (growth, values_end or mark.count); charge/refusal/output ordering remains unchanged. No new state, traversal, allocation, capacity policy or swallowing of errors. The narrowly reasoned inline allowance addresses the observed live closure frame, without altering the algorithm.

Existing45 mint controls/owning gates are reported settled; Project35 controls/owning gates remain bound to their actual terminal rather than this source verdict. These deltas do not change Python protocol/ABI/docs, so prior qualified wheel28/docs9 and unaffected native integration behavior evidence remain applicable. Existing checkpoint/governed-worker/projection controls are the meaningful touched-source checks; no blanket repeat of all Rust/host semantics or finite32 oracle is imposed.

## Fresh artifact recheck

The baseline is immutable85204 df2 from final-lower-native-cost-1. Fresh candidate native and host bodies must bind actual new source, exact compiler/role argv/profile, production closure checksums and PyO3 config/interpreter input/fingerprint identities. Reuse is conditional on driver hard admission and final readbacks, not on old exit0. The reviewed driver compares SDK/compiler/profile and complete baseline manifests, uniquely selects actual Cargo frames/nonempty LL/S pairs, and compares baseline/current PyO3 build inputs/config; G owns execution.

Recheck complete ordinary Project row and cell loops: geometric allocation law, bulk pointer/length recurrence, once-final length publication including unwind, and no new per-row collector/Extend call frame. Recheck the actual affected Filter/Extend/Group replay callers and any live moved-mint callee: old closure#5 and new helper names must not survive as added calls/frames; equivalent inline loops and existing count_worker_mint boundary must preserve prefix replay. Smaller caller frames are not sufficient.

Rebind all twelve settled original criterion rows in portfolio-final-lower-native-cost-body-review.md. Actual changed evaluator optimizer seams require fresh body inspection; unchanged parser/traits/source arguments and demonstrated host ABI/materializer/drop/row allocation may reuse only exact applicability. A new host module alone does not emit every imported evaluator dependency, and no such completeness claim is made. Inspect actual fresh host boundary bodies and dependency/source/cohort binding. No extra per-function review ceremony is added. Overall native-cost remains NOT MET until the two known failures are discharged on the fresh admitted candidate and no additional work is found.

Old2f3/300e/2eb findings remain attributable FAILED diagnostics. Old308 run37790706268/watch98969 is truly terminal and fully retained, with no watcher or new dispatch by this reviewer.
