<!-- SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca> -->
<!-- SPDX-License-Identifier: CC-BY-4.0 -->

# Task 2 independent source and consumer review

Final source and consumer disposition: **PASS for Task 2 at the identities below**, under the quoted user validation override. Earlier mutable/failed observations are retained as history and do not qualify abandoned source. Normal verified commit/push and later issue/PR workflow completion remain separate from this source review.
Review base is signed Task 1 `e72660e8769af222387ecc4fd4f84ea9887e43a1`, with synchronized integration base `863c75e2c1e13001bcbe025820d257bd0ee49c4f`.

## Final accepted source and evidence

Final tracked Task2 binary diff SHA-256 is `132447b8f8eabd1ea892725ca38d66ab5dd86d42b42effc262b794203e8752db`; final binding-only test source SHA-256 after the vocabulary-home correction is `9b547977e29cc2c0dde850cc4249e4e9784e8a00287c14b391a3808448d3ee49`. The fifteen-path final Rust manifest `raw/t2-unit-mode-rust-start-sha256.log` has SHA-256 `b558417ac39046a6ca70ebe02b087cda343961b05de1cc78fc023c6dd0651804` and independently checks without mismatches after final install and binding execution. Host is `0918fd1f8a17d0e4d88504be88937fe4388365d3e2609306e2daaf7233bc55d6`, contextual compiler `1a2e3dbdd2ab0e7284513ae4bcc4b4eb64be0a63bda2ec07036dd10796d1c005`, parser `e5acb6e57811d5ea866403093efceba9a2d2ffbda1db84b5793648632aa4158a`.

Production wiring, configuration forwarding, result carriers, lazy single-graph operational errors, syntactic group ownership and retained nested expression context are inspected and causally qualified. Actual Rust evidence is 1909 affected core tests, then eighteen contextual controls after the allocation-only borrowed-map refinement, including all 241 permanent answer/callback fixtures and new concrete witnesses. The exact original frozen vendor failure now passes through a first-party Rust fixture wrapper. Native release Clippy passes at the final compiler/host source. All concrete review findings have owned source repairs and executed relevant controls; no emergency-ledger or xfail/corpus weakening was introduced.

`raw/t2-final-native-install.log` records successful normal optimized development-profile installation. `raw/t2-final-python-only-bindings.log` collects fourteen irreducible Python binding cases and passes all fourteen (only three expected ConjunctiveGraph deprecation warnings). `raw/t2-final-installed-identities.log` binds genuine RDFLib7.6.0, Python3.13.12 and the actual native module path. The module SHA-256 is `282264e4a45c28cad41f66dd7ec517d2f728f595360edd83b8affacf976979a4`, lock `06275d43821c8351f89f88071af043ce4c4645fe3adcf2126b2f28f031cafc01`, as independently checked and captured by `raw/t2-final-module-lock-test-sha256.log`. This installed binding artifact is correctness evidence; separate release artifacts support cost evidence.

Read the final focused `tasks/T2-native-cost-review.md` disposition and its actual paired proof. It binds the same manifest and concludes primary native structural cost MET: full false-parser IR/control-flow/assembly identity, restored unit-mode ordinary host capture and caller/drop identity, unchanged primary dispatcher/caller recursive frames, layouts, clone/drop/traits paths and ordinary algorithms, corroborated by identical untimed allocation/resource records. No timing measurement or task-specific wasm work was performed. Finite untimed records corroborate the inspected source/compiled whole-domain argument; they are not substituted for it.

No new runtime dependency, feature, second parser/evaluator, upstream implementation body/table or runtime upstream query dependency appears in the reviewed delta. Frozen upstream files remain unchanged and are existing licensed test data, not copied shipping implementations. Docs describe the actual contextual/ordinary boundary, generated translation checks pass (2927 translated messages, zero fuzzy/untranslated/source drift), and broad Python scoreboards are explicitly historical snapshots outside untouched generated rows. The user excluded broad Python semantic reruns; their earlier failures and superseded receipts remain visible and are never called final broad-suite passes.

Reviewer created no shipping edits, builds, live processes or diagnostic debris. The owned report is the only reviewer mutation. No work or cleanup item is handed to the user.

## Contract and initial source inspection

Read applicable repository AGENTS, the root `.baseline` and `.goals`, authoritative plan completeness table and Task 2/3 requirements, current validation index, Stage 1/Stagectl reviewer/evidence instructions, and final Task 1 source-law and native-cost dispositions. The user excludes further task-specific wasm investigation and prohibits timing performance measurement. Review is read-only except this owned Stage report; candidate builds/tests belong to the sole shipping writer.

The inspected production path is `Graph.query` → `_QuadStore.query_rdflib` → shared `query_impl::<true>` → `NativeSparqlEngine::query_rdflib_with_options_view` → existing typed `prepare_rdflib_query`/`query_rdflib_prepared_view`. The host helper retains existing owned conversion while the GIL is held, frozen dataset/registry/engine evaluation while detached, typed diagnostic materialization and shared result conversion. Ordinary `_QuadStore.query` selects the same helper with const false. No runtime upstream evaluator import, query reassignment text rewrite, copied implementation body/table, runtime dependency or second parser/evaluator appears in this Task 2 delta.

The new convenience route reuses the existing `build_probes` conversion home; its body is unchanged and its visibility becomes crate-wide. That home preserves scoped blank qualification, admitted IRIs, datatype/language/direction and iterative quoted triple conversion. The new method creates contextual bindings and prepared plans only when explicitly invoked. Existing ordinary engine methods and core representations remain unchanged in this two-file delta. Final source identity and affected native-cost rebind remain required; historical Task 1 full-file hashes do not certify mutable Task 2 files.

Graph now forwards all existing engine configuration axes, and the existing processor delegates kwargs to Graph. Dataset/ConjunctiveGraph inherit the query method. Integer-indexed solution wrapping preserves actual duplicate column occurrences rather than repeatedly reading the first name. Empty-domain suppression remains in the typed core publication home; the wrapper adds no fabricated rows.

## Open executed-evidence and coverage checks

The initial new Python matrix selects 198 available frozen inputs out of the 241 native cases, retaining the four zero-callback ASK inputs and excluding unsupported Python custom-callback execution. It compares associated columns, bags with duplicate multiplicities, ordered sequences, None cells, ASK booleans and graph isomorphism. Six BNODE controls check identity patterns rather than random labels. Shadow execution is isolated and compares the frozen 198 answers. These are inspected test intentions, not yet executed qualifications.

Quad fixtures redirect Graph and processor parameter labels to Dataset. Consequently four collected route labels cannot claim four distinct named-graph production routes. Actual route coverage and totals must describe this honestly.

Sent the writer an actionable coverage finding: matrix initial terms are only URIRef and its canonicalizer covers ordinary RDFLib literals, so it does not qualify actual new-route direction/triple/scoped-blank binding conversion or malformed binding diagnostics. Existing conversion unit tests are not actual new-route execution. Requested new-file binding controls for these axes and configuration witnesses, preserving the compat carrier's explicit quoted-triple refusal where RDFLib has no counterpart. Duplicate-column controls should also assess named/get/asdict access if distinct same-name cells are exposed; genuine RDFLib selects its last label whereas the existing wrapper reads the first occurrence.

Final install identity, actual matrix/config/term/error results, full Python/vendor/shadow/installed-empty-graph gates, supported profiles, accurate maintained documentation/counts and stable source manifest are pending. No PASS is inferred from the initial successful library compilation or mutable install process.

## Consumer findings during execution

The first installed matrix run fails four named-fixture ConjunctiveGraph cases (747 pass before maxfail stops), proving inherited routing alone did not preserve default-union selection. The writer owns the existing dataset-selection repair and attributable requalification. `_DatasetGraph` also shares the whole native store but carries `_graph_name`; its actual query scope needs coverage.

Executed a read-only genuine rdflib 7.6.0 scope probe using `/home/paudley/Active/purrdf/bindings/python/.venv/bin/python`, exit 0. Inputs: default graph `(ex:a,ex:p,ex:d)`, named g and h each `(ex:a,ex:p,ex:n)`. Dataset(false) plain BGP returns d; named view and processor(named view) plain BGP return n. Dataset `GRAPH ex:h` returns n, while named view and processor(named view) `GRAPH ex:h` both raise the genuine single-graph/dataset-required error. After assigning `dataset.default_union=True`, plain BGP returns d and n once, including default triples and deduplicating identical triples across named graphs. Exact probe queries are `SELECT ?o WHERE {?s <http://example.org/p> ?o}` and `SELECT ?o WHERE {GRAPH <http://example.org/h> {?s <http://example.org/p> ?o}}`. These oracle observations were sent to the writer. They are not candidate passes.

Duplicate-label lookup repair now reads last-occurrence indices. Sent the remaining actual last-unbound inconsistency: original asdict filters cells before duplicate overwrite, retaining a prior bound value when the final same-name occurrence is None. Genuine RDFLib asdict omits the label. Its get also returns None for an existing unbound label even when a default was supplied, using that default only for missing labels. Requested coherent final-label asdict/get repair and new-file controls. No upstream implementation was copied; source inspection establishes behavior only.

The writer's initial graph-scope repair adds a pre-execution traversal rejecting any GRAPH in a single-graph plan. This is a confirmed semantic blocker, not merely a possible risk: genuine rdflib 7.6.0 on an empty Graph returns [] for `SELECT ?s WHERE { ?s <http://example.org/p> ?o OPTIONAL { GRAPH <http://example.org/g> {?x ?p ?y} } }` and for the analogous `FILTER EXISTS { GRAPH ... }`; it raises the dataset-required error for the corresponding MINUS because its RHS is evaluated eagerly. Read-only oracle probe exit 0, exact version asserted. The eager presence scan rejects all three, changing the first two answers. Sent the writer the actual witnesses and required evaluation-time error semantics, preserving ordinary native work. Final repair and executed attribution remain pending.

Additional genuine oracle probe, exit 0: `SELECT ?x WHERE { BIND(IF(true,1,EXISTS { GRAPH <http://example.org/g> {?s ?p ?o}}) AS ?x) }` yields 1; replacing true with false raises dataset-required. These confirm lazy expression behavior independently of empty-driver behavior.

Source-level repair now removes the eager scan. The contextual compiler specializes `SINGLE_GRAPH` statically and wraps Graph nodes in the existing Apply with a boxed `dataset_required` policy leaf. Both existing outlined Apply entries reject only when actually reached. Validation constrains this marker to an empty driver/Graph RHS with no competing policy modes; clone, expression rebuild and property-function transforms preserve it. No second evaluation/parser home, ordinary EvalCtx/options field or dispatcher branch was added. New source and executed receipts must rebind the affected proof; this paragraph records inspected repair intent, not final runtime PASS.

## Full gate uncovered nested outermost binding defect

The final-frozen module receipt identifies native artifact SHA-256 `c08110b6c4f888380a088f1270ab602bf2b56cd6ac58e1874a8c27fc7026e7ee`, genuine oracle 7.6.0 and locked dependency SHA `06275d43821c8351f89f88071af043ce4c4645fe3adcf2126b2f28f031cafc01`. Independently checked the frozen Rust end manifest against current source, exit 0 at that sampling. The complete new file then passed 809 intermediate tests, but the actual full gate fails the untouched vendor `nested_filter_outermost_binding_propagation`: outer 4725 pass/4 strict xfail/1 skip/1 fail, vendor 80 pass/5 xfail/1 fail with no XPASS or stale key. This is a required repair, not permission to add a ledger entry. All earlier frozen contextual receipts need affected requalification after the compiler repair.

Independent reduced diagnostic executed against that installed module and genuine oracle, exit 0. Own query:

```sparql
PREFIX ex:<http://example.org/>
SELECT ?new WHERE {
  VALUES (?action ?old ?new ?t1) {
    (ex:a ex:old ex:good ex:t1) (ex:a ex:old ex:bad ex:t1)
  }
  FILTER NOT EXISTS {
    ?action ex:used ?t2 . ?old ex:member ?t2 .
    FILTER (?t1 != ?t2)
    FILTER NOT EXISTS { ?new ex:member ?t2 }
  }
} ORDER BY ?new
```

Seven triples: a used t1,t2; old member t1,t2; good member t1,t2; bad member t1. Genuine oracle selects good only, candidate selects bad and good. A simpler middle VALUES version passed both; this narrows the missing inherited correlation to the real middle BGP/nonlazy-Join context rather than every nested EXISTS. Sent the small original witness and negative/control requirements to the writer. It copies no upstream implementation or test body.

Read actual compiler `expression`, `lookup`, `thaw`, leaf merge, Filter/Join build and source-fact collection, plus genuine FrozenBindings/context operations as behavioral evidence. In particular the oracle forget operation retains its full matched solution context separately from its filtered mapping; thaw of an empty mapping uses that context, not necessarily the operator input C. This distinction and explicit private context transport must be traced before any repair is accepted. Blindly filling every absent key of a nonempty mapping would contradict existing projected-empty/mapping-domain laws. Final source/real vendor and regression results remain pending.

Two attempted contextual carry repairs fail the same narrow native regression (2 rows versus 1; the prior 14 controls including 241-case matrix pass). The writer preserved both failures. The expression context-union and expanded private Project lists do not establish causal closure. Actual runtime Apply invokes substitution with DECLARED/PRESERVE=true, skipping the ordinary Project narrowing in that window; Apply's outer substitution masks declared inputs and then reconstructs them from bound driver cells. These inspected masks explain why a Project declaration alone is insufficient, but are not the observed cause of this witness.

Independent actual-plan diagnosis now identifies the cause. In `raw/t2-nested-context-plan-diagnostic.log`, C aliases for s,x,y,z are slots0,1,2,3. The middle `FILTER(x != y)` is emitted with x lookup `If(Bound(C_x), UNDEF, R_x)`; outer EXISTS has bound C_x, so this inner isolated Filter drops every middle witness before reaching nested EXISTS. The compiler marks only the top Filter at an EXISTS root as nonisolated, whereas its parser represents two leading Filter nodes for the two source conditions.

Executed genuine 7.6.0 translation metadata probe, exit 0, on `SELECT ?s WHERE { ?s ex:q ?z . ?s ex:p ?x FILTER NOT EXISTS { ?s ex:p ?y FILTER(?x != ?y) FILTER NOT EXISTS { ?z ex:r ?y } } }`: the executable outer EXISTS body is ONE Filter, `no_isolated_scope=True`, operand Join, expression ConditionalAndExpression containing both the relational condition and nested NOT EXISTS. This confirms the isolation mismatch directly. Sent the actual observation to the writer and parent, requiring preservation of group boundaries and combined-expression order/error/callback laws rather than another guessed carry fix. No new native substitution behavior is authorized or needed by this diagnosis. Final repaired source/regression/vendor evidence remains required.

Additional genuine multiple-filter probes, exit 0, expose the required operational continuation law: `SELECT ?x WHERE { VALUES ?x {1} FILTER(1/0) FILTER(EXISTS {GRAPH <http://example.org/g> {?s ?p ?o}}) }` raises dataset-required. Replacing first expression with false also raises; reversing EXISTS and false also raises. Genuine translated root expression is ConditionalAndExpression in source condition order. Its raw operand retrieval is eager before EBV conjunction, so distinct sequential Filter stages cannot suppress a later operational failure after an earlier false/error. Sent these actual witnesses to the writer. A leading-isolation-only patch would not discharge this consumer law; a compiler-only lowering can reuse existing expression/row continuation homes and must preserve ordinary native VM work.

## Coherent same-group repair inspected

The actual repair now folds only each contextual parser GroupState's collected filters into Expression::and before group_join can normalize away empty group ownership. Element::Filter appends in source order; Expression::and extends its left chain in that order. The shared VM compile.rs lines 484–494 emits each operand and its EBV before the final Kleene combination; its work-list transfer at lines 313–319 restores that evaluation order. Thus false/error operands do not prevent a later reached operational GRAPH refusal, while IF still uses its separate lazy branch implementation. OPTIONAL consumes the repaired owning group filter_count of one; nested child-group filters are not peeled into the owning group condition. Ordinary RDFLIB=false retains the old vector and wrapper loop, subject to final emitted-native proof.

The current rdflib.rs diff contains no speculative inherited-context union or expanded private projection transport. Searched affected parser/compiler and owned test source for TEMP diagnostic markers: none remain. Existing test status eprintln messages are genuine harness output, not temporary source probes. New consumer controls distinguish same-group versus nested-brace isolation and both false/error-before-GRAPH operand orders.

Read raw/t2-group-filter-native-tests.log in full: warning-free release build and 15 passed, including the concrete positive/negative nested EXISTS regression, contextual_matrix (241 frozen callback/answer cases), policy identity, configured relations, continuation cutoffs and ordinary transformation rejection. This qualifies that native run's recorded source, not the ongoing rebuilt Python module or later mutable edits. Final installed-source identity, complete 819-control consumer run/full vendor/shadow gate, updated maintained counts and final native cost report remain required.

## Current user validation override

The parent delivered the user's exact current steering: **"python tests are forbidden."** No new Python tests, pytest/vendor/shadow executions or Python oracle test probes are authorized. This overrides the original plan's remaining Python validation criteria. Already completed receipts remain historical observations and retain their actual failures; unexecuted former Python criteria are excluded by the user, not reported as executed passes. Remaining acceptance is reviewed through actual Rust regression/callback tests, production source wiring and native logical-cost evidence. The sole writer has been notified to stop owned live Python tests without a user cleanup handoff. Final installed artifact identity, if generated by a build, is build attribution rather than a Python test pass.

The user's subsequent exact clarification is **"The only things that python or wasm can check in tests are things that ONLY PYTHON OR WASM can test."** The override therefore permits focused irreducible Python binding checks (dispatch, keyword forwarding, Python term/result carriers, exceptions, GIL and import-shadow boundaries), while core RDF/compiler/evaluator/operator/BNODE/differential matrix/group/filter semantics belong to Rust. The original broad Python/vendor semantic gates remain excluded; no full pytest/vendor matrix rerun is demanded. The new Python file must be narrowed to those language-only surfaces and the missing group/scope operational neighbors must receive executed Rust controls. Task-specific wasm remains outside scope by the user's earlier instruction.

## Remaining observed local-projection defect

Read the completed historical raw/t2-group-filter-consumer-controls.log without executing Python: 817 pass and TWO real failures. The local-subselect/nested EXISTS witness from the earlier independent oracle probes selects both a and b instead of a; its negated variant selects nothing instead of b. The user narrowing Python validation does not erase a known source defect. Both variants require Rust-owned reproduction and repair; the writer and parent were notified.

Source hypothesis (not yet actual runtime diagnosis): Project correctly publishes only local names into its logical Mapping. At a nonisolated EXISTS root Filter, expression/map_exists_bodies builds its inner driver only from that immediate Mapping. With local bound, thaw's present marker is true, so an absent outer name receives UNDEF rather than inherited C_outer; the inner EXISTS is then uncorrelated. This is a different seam from the repaired syntactic filter ownership defect. Expanding public/logical projection domains or globally restoring every absent mapping name would be unsound; inherited expression context must preserve isolated-filter forgetting and explicit Project/mapping-domain laws. Final actual native regression and cause closure remain required.

## Narrowed Python-only surface review

Read the rewritten test_contextual_mappings.py completely: eight functions yield fourteen parameterized cases by source count. The core 198-input semantic matrix, BNODE and group/filter/scope oracle tests are removed. The retained tests exercise actual Python receiver dispatch with a recording delegator that calls the real native store, Python graph-view/default_union keyword extraction, isolated import shadow, tuple/name/get/asdict ResultRow APIs, PyO3 dictionary/configuration/exception boundaries, Python term extraction/scoped blank/result lifetime, and aggregate/standpoint keyword/tuple forwarding. These surfaces cannot be exercised by a Rust query result alone. Minimal queries trigger these bindings rather than constituting a second core semantic suite. The new Why-not-Rust header states these concrete boundaries. Actual focused execution after final rebuild remains pending; no source-count estimate is treated as collected or passed tests.

The attempted broader native target receipt raw/t2-group-filter-final-core-controls.log fails compilation because crates/sparql-algebra/tests/iterative_traits.rs:895 omits the new dataset_required initializer. This is actionable within the owned policy change and requires repair plus the appropriate gate; the earlier native fifteen-test pass does not cover that algebra test target.

## Repaired current Rust gate independently adjudicated

The actual current repair limits retained-context visibility to the nonisolated leading EXISTS Filter: its expression-visible map is C union R, with R overriding matching names. Logical Compiled.mapping and row-operation inputs remain R; isolated filters retain their prior mapping/forgetting law. The local Project public domain is unchanged. The earlier context-union-every-EXISTS/private-Project transport guesses remain removed.

Read raw/t2-rust-core-neighbors-before-projection-fix.log: 17 pass and one concrete Rust failure, actual a,b versus expected a. Read the complete terminal summaries in raw/t2-current-rust-core-controls.log: algebra 464, iterative traits 3, evaluator 1375, EXISTS 25, grouping 16, contextual 18 and request-governor 8, all pass (1909 tests). The contextual target now executes both local-projection signs plus projected-missing and wholly unbound outer neighbors, brace isolation, lazy IF/empty OPTIONAL/EXISTS versus eager MINUS refusal, both false/error-before-GRAPH orders, five actual callback/order/ASK laws and the frozen 241-case answer/callback matrix. The new policy initializer and mirror are repaired in iterative_traits and its actual target passes.

Independently checked raw/t2-current-rust-start-sha256.log after this gate with sha256sum --check --quiet, exit 0. It binds 15 affected Rust paths including the policy mirror and current regression target. Current compiler SHA-256 is 12b1f4296222df9945cde217f196c051c9e855aeb994e2343d41ee09fe52b288, parser e5acb6e57811d5ea866403093efceba9a2d2ffbda1db84b5793648632aa4158a, Python native host 2a6b3c7a9123bc5a4b3014732ffd01bf9682616876adf6329e052d3be2abd89d and Rust test 27b7fb6e3bb7dd51e4af97cdb67d541d66c411557829b60afd49366ef3963ef6. Narrow Python source SHA-256 is 1ab3b510dd2ffb1e2e0fa2550c1301807eaf7ed667ac3431fb1d6ddddeacd01a. Current tracked delta receipt eb0985ba6a0ee890e75f00b4e085d7832ae0f900460e6c093597ce7323306d22 identifies that sampling; later docs-only changes need their own attribution. Final installed fourteen-case binding evidence and affected logical native-cost proof still remain required.

Read actual affected-clippy receipts. raw/t2-current-affected-release-clippy.log successfully checks the two affected native crates in the release profile. The earlier nonrelease raw/t2-current-affected-clippy.log fails a prepared_execution target because set_memo_verification_enabled is unavailable in that profile/configuration. It is preserved as a failed invocation, not counted as a pass; attribution to the required production-profile gate must be recorded. No blanket all-profile clippy success is asserted.

Maintained docs now explicitly label the generated Python rows as the last complete broad-suite snapshot, outside the untouched generated matrix block, and qualify the handwritten binding-suite count likewise. The narrow fourteen-case surface receipt must not be used to fabricate a complete refreshed broad-suite count. README inventory now describes the binding-only file and assigns core semantics to Rust. The current English/Chinese contextual route docs are consistent with source; generated translation locations came from the actual regeneration home.

The native-cost reviewer subsequently found an unnecessary isolated-contextual Filter map clone introduced by the narrow projection remedy. Inspected the repair: isolated filters now borrow their original compiled.mapping; only nonisolated root-EXISTS visibility owns the C union R map. This changes no domain or expression law and removes that allocation. The previous compiler hash and 1909-test source sampling are historical; raw/t2-borrowed-filter-contextual-tests.log and refreshed source/install attribution must qualify the final borrowed-map source. Unaffected broad-unit evidence may be reused with this exact allocation-only source explanation, rather than claiming that earlier gate executed a later source.

Read the final borrowed-map eighteen-test receipt: all pass, with the unchanged regression target. Read raw/t2-borrowed-filter-release-clippy.log: release checks succeed through purrdf-python and affected dependency crates. Final compiler hash is now 1a2e3dbdd2ab0e7284513ae4bcc4b4eb64be0a63bda2ec07036dd10796d1c005; independently checked the then-current final Rust manifest, exit 0.

## Typed ordinary host mode repair

Subsequently read the complete QueryMode host repair. Ordinary mode and its Selection are unit (); its dataset operation returns the same Arc and its RDFLIB constant is false. The contextual mode extracts an owned TermValue selection under the GIL, then applies the same single COW selection body. The contextual early return is exactly the De Morgan form of the prior mutation guard, preserving graph union, named/default graph views, graph declarations and annotation/reifier surfaces. The generic helper uses static monomorphization, retains shared configuration/execution/materialization homes, and dispatches to the original ordinary engine branch. No dynamic mode or second query body was added. Actual emitted caller/capture/frame proof remains required; source-level unit state alone is not treated as emitted identity. This supersedes the earlier host hash and requires refreshed build/install attribution.

The focused native-cost report now independently inspects actual repaired unit-mode emission: original twelve-argument host ABI, settled capture176/detached192 restored, no scope stores/adapters or selected-graph destructor, identical actual caller operations/caller frame, and query frame2264 versus signed-baseline2296. The primary consumer dispatcher/evaluated closure boundaries also remain unchanged. These discharge the host failure; parser specialization/probe final disposition remains pending separately. Independently checked raw/t2-unit-mode-rust-start-sha256.log, exit 0; current host SHA-256 is 0918fd1f8a17d0e4d88504be88937fe4388365d3e2609306e2daaf7233bc55d6. Paired untimed native record logs have identical SHA-256 7cc55ec0ce0cdff2e1feade336b09b98153b496868cc523c8be02a8e1187dfc2.

Read the first-party Rust frozen-vendor witness wrapper completely: it extracts only existing Turtle and SPARQL fixture literals from the unchanged licensed vendor source and calls the existing native RDF parser and contextual engine. It neither executes Python nor copies an upstream implementation body. Read raw/t2-exact-vendor-native-witness.log terminal success: columns nAction/nRedundantRecord/nSupersedingRecord, one actual correct action-1-2/record-123-1/record-1-2 row, exact frozen vendor witness native PASS. Its explicit assertion is the upstream set-answer law; the observed receipt also shows one row. This closes the original concrete vendor failure using Rust, without claiming the excluded whole Python vendor suite was rerun.

## Final vocabulary-home rebind

Independently inspected the sole subsequent test-only correction: import the existing compat.namespace.XSD home and use str(XSD.integer) for the same typed-literal datatype bytes. No native source, module, configuration or semantics changed. Read raw/t2-final-python-only-bindings-vocabulary-home.log: actual fourteen cases all pass with the same three expected deprecation warnings. Read raw/t2-final-module-lock-test-vocabulary-home-sha256.log: module282264e4a45c28cad41f66dd7ec517d2f728f595360edd83b8affacf976979a4 and lock06275d43821c8351f89f88071af043ce4c4645fe3adcf2126b2f28f031cafc01 unchanged; final test9b547977e29cc2c0dde850cc4249e4e9784e8a00287c14b391a3808448d3ee49. Independently checked the complete raw/t2-final-source-vocabulary-home-sha256.log, exit0. Prior native/cost evidence is unaffected. This rebind supersedes the earlier test hash and preserves the final accepted disposition.

VERDICT: PASS
