# Existing SmallVec bulk annotation delivery

Status: SOURCE IMPLEMENTED/STAGED, RUNTIME/EMITTED PROOF UNRUN. Root accepted the complete proposal and settledb327 cost audit before this exact change. New staged tree23f7f1b5b72128908ae3b9eab80a2febfc1ad6be; MERGE_HEADdf2/HEADfd963 unchanged; no unstaged shipping source. No build, test, wheel/docs or emission ran during this edit.

Only crates/rdf-core/src/small.rs changes relative tob327: exactly four added lines (two reason comments, scoped clippy allowance, inline(always)) on the existing Extend trait method. Its complete body, unsafe/raw_mut/LenOnDrop guard, reservation/growth/final store/remainder loop/assertions remain byte-unchanged. No other core method, wrapper or duplicated container body. The reason is the actual extra Project per-row205LLVM/228ASM/CFA112 frame, not a timing claim or annotation-as-proof.

This shared generic Rust home affects all SmallVec Extend instantiations; equivalent algorithm/runtime ownership laws are unchanged, but optimizer/body applicability across ordinary callers must be inspected. It is portable Rust with no new wasm/native cfg, dependency, feature or external side effect. Existing cold grow/no-inline contracts remain unchanged. Fresh candidate native/host proof must show inline bulk Project SSA/final-length work, no extra frame or cell capacity loop, and whole-criterion applicability to other container users.

Prepared phase smallvec-rust selects actual owning small::tests group from small_tests.rs:18 registered tests include two256-case model/ownership properties across inline capacities0/1/4/8, every ownership-path drop counting, unknown/exact-hint Extend panic safety, clone/retain/dedup/drop panic, forgotten iterator, ZST/overaligned/layout/auto-trait/overflow/macro/id-row behavior. Exact Project1 plus existing prepared12/contextual22 =35 evaluator tests. Strict core+eval all-target clippy/fmt, owning helpers/core ring-fence gate. Require18 and1 actual counted outcomes/nonzero targets/zero failure or ignore; no test for the annotation or mirrored unsafe implementation.

Driver source syntax check PASS, actual qualification UNRUN until root inspects/admit source23f7 and the sole lane. Prior45 worker replay/35 Project/source semantics and unchanged docs/wheel are scoped evidence, not new emitted identity. Candidate-only cost route reuses settled85204 baseline only through exact production source/compiler/profile/selected-frame/cohort/PyO3/artifact admission/readbacks; no old candidate promotion. No commit/push/forge/external action.
