# Project view/Lift repair: independent source assessment

2026-10-08. **Source verdict: PASS. Fresh emitted cost: PENDING;23f7 actual cost remains FAILED.** Exact diff23f7f1b5b72128908ae3b9eab80a2febfc1ad6be→4828a699a924d840b1c3272853ee7bca3c65943e changes modifier.rs only. Reviewer inspected complete ordinary/contextual callers, helper, Lift::at/absorb/finish/fields and existing SmallVec::as_slice/Deref. No builds, tests, probes, source/index/forge mutations by reviewer.

Ordinary order remains Lift::at(node), child evaluation with its original early error propagation, absorb(0), the unchanged opaque-child empty-schema finish, layout, projection, finish. Caller retains the same already-absorbed Lift rather than transferring it into the helper. No fresh Lift is created for ordinary projection, no certificate reclassification and no altered governor charge/error handling.

Contextual active-delivery closure still creates the selected schema first, then Lift::at(node) before projection allocation, then finishes projection with that same Lift. Static inactive mode still calls ordinary eval_project. Shared helper now returns the same SolutionSeq directly; it previously contained no fallible operation returning an EvalError, only Ok around finish, so removing its Result wrapper removes no refusal or error path.

Lift has no custom Drop; its node borrow, ChildEdges, optional certificate and optional Arc schema remain owned once and released through normal Rust field cleanup. Projection allocation/indexing unwind still drops partially built cells/rows/schema and the retained Lift, without a new Lift-specific observer. Successful finish moves its existing certificate into Truncation or returns Complete exactly as before. No clone, added allocation, fallback or swallowed failure.

Existing row.as_slice returns the shared SmallVec immutable slice via its existing Deref home. Borrow is once per input row and lasts through projection; source row is never mutated. Selected-column order, missing-column None and same cell copying remain unchanged. Indexing a selected out-of-range column preserves bounds panic; no unchecked access, unsafe duplicate or eager ownership/copy is introduced. Existing geometric bulk reservation and outer Vec capacity remain.

Root reports actual5286 terminal0/all71 owning controls, strict evaluator clippy/format/source readback. These are Project1/contextual22/prepared12/governor9/governed27, proportionate to touched semantics. Prior SmallVec53, mint45 and unchanged docs/wheel behavior qualification apply by exact source scope; no blanket repeat or new host semantic mirror is required. This report is independent source assessment, not a substituted runtime receipt.

Fresh candidate native+host artifacts are already root-admitted under strict immutable85204 source/compiler/profile/production-cohort/frame/PyO3/config/artifact reuse. Whole original twelve-row audit remains required. In complete Project inspect source row tag/pointer/length established once before bulk selected-cell loop, destination bulkSSA/final-store/panic guard and absence of Extend/FromIterator frame; inspect no extra104-byte Lift transfer/live temporary/copy/drop versus baseline. Caller reserve alone is not a zero-frame or arbitrary byte threshold. Rebind changed kernel optimizer composition and actual host ABI/captures/detach/drop/materialization, and reuse only identity-qualified unchanged parser/storage/numeric/operator arguments. No unconditional PASS from inline attributes,71 test success, generation0 or finite32 samples.
