# Final lower-repair native-cost criterion audit

2026-10-08. **Status: FAILED; native cost NOT MET on the actual df2/2f3 pair.** The settled adjudication below supersedes the historical preparation matrix. This is the independent read-only whole-criterion matrix for accepted plan completeness row15 and its validation policy. Source tree2f3ee2d75b30145ac053be6587223d892b26368c is compared with actual archived main df2cec88b0f8e05e05ef3d01d14714474be6bbb1. The actual generation root is `/opt/purrdf-454-current-qualification-20261008/final-lower-native-cost-1`. No compiler, runtime/probe, source/index/Git/forge mutation is performed by this reviewer.

The original requirement is unchanged primary native allocation, representation and algorithmic work through parse, prepare/admission, plan storage/copy/drop, ordinary reused execution and correlation/operator paths. Source specialization and actual emitted control/call/frame work establish the proof;32 untimed sampled records corroborate but cannot substitute. No timing, regression allowance or usually-false runtime compatibility switch is accepted. This matrix does not impose separate per-function runs or a reviewer count: shared source/body evidence can cover related seams together.

## Evidence applicability and whole-criterion matrix

| Original obligation / changed seam | Actual proof to adjudicate | Current verdict |
| --- | --- | --- |
| Original first-party implementation, one production engine and no added runtime dependency/feature | Accepted T1/T2 source/provenance reviews plus exact current changed-source/production compiler cohort readbacks; contextual compile/execution remains in existing Rust homes. No upstream evaluator or copied translator body establishes this claim. | Prior source arguments applicable where bytes unchanged; fresh input/cohort binding PENDING. |
| Ordinary parser and admission specialize away compatibility state/checks | Original qualified false-parser/entry/callee source argument can be reused after exact unchanged scanner/traits/manifest binding. Inspect fresh emitted work only where the shared composition changes or source cannot establish erasure; do not invent a new parser corpus/per-function ceremony. Strict ordinary grammar native tests corroborate behavior, not erasure alone. | Fresh unchanged-source binding PENDING; no automatic new full parser audit imposed. |
| AST, visitor, retained plan, preparation, clone/drop and shared storage | Current GraphPattern/SolutionSeq/Expr/plan representation and exact untimed retained/allocation records; changed AST arms handled by existing iterative walks/admission/hash/copy/drop, contextual boxed policy allocated only for contextual nodes. New old-arm state or extra traversal must be explained/refused. | Fresh layout/records and source/body binding PENDING. |
| Native dispatcher and unit RowDelivery | Complete ordinary RdfDataset dispatcher/old-arm kernels; same ABI/representation, unit delivery callback/state absent, no extra forwarding or work on old arms. Appended contextual grammar arms are distinguished from ordinary branch work. | 300e ABI was112 result/144 pattern/1248 context; fresh current proof PENDING. |
| Ordinary Filter/Extend sequential and worker loops | Complete current caller/callee chains, charge/admission/truncation/first-error order, stopped chunk selection and typed output-buffer reuse. No added per-row callback/state/loop or post-join helper call/frame compared with matched base. Existing for_rows/pass is distinguished from new boundaries. | 300e FAILED: Committing::of/commit_items/admit_rows lower helpers retained after outer methods erased. Fresh repair proof PENDING. |
| Ordinary Project work and capacity law | Whole row and cell loops, same selected cell order/unbound cells and allocation/reservation strategy. SmallVec new()+reserve(src.len()) must preserve original geometric lower-bound pre-reservation; no repeated growth or per-row collect helper/frame. | 300e FAILED per-row249LLVM/248ASM collect helper/CFA144; owning source correction is not emission proof. Fresh PENDING. |
| GRAPH, Group and ordinary dedup/domain modes | Complete graph emptiness/append paths; ordinary group key/domain/aggregate/worker paths; false adjacent dedup caller/callees. No extra graph emptiness helper or hidden domain/callback state/loop. Worker calls already present in base are not findings solely by their names. | Historical GRAPH helper failure corrected in300e; full current proof PENDING. 300e ordinary Dedup full2214ASM matched after verified static rename; must rebind actual current bodies. |
| Correlation, LATERAL/unit Application, deferred substitution, configured property functions | Complete ordinary application/deferred lookup/substitution/correlation/call path; current unit mode has no policy argument/state or extra output-domain/copy pass. Preserve original per-driver work/admission and actual configured-relation path. | 300e FAILED actual deferred-map lookup closure call (79LLVM/60ASM leaf, once per application with map). Root Option-match repair awaits fresh caller/callee proof. |
| Native numeric recurrence and false tail | Full survivor scan, first-value bypass, total shape/count/max/carry and Cost sum/peak recurrence; same object/frame/loop work; no extra accumulator/push/fast-path test. SUM/AVG tail/render/count division and separate MIN/MAX comparison retain original homes/work. Independently compiled host kernels need actual applicable evidence too. | 300e bounded native recurrence proof retained, same eight objects/reserve264/CFA320; fresh bodies/source binding PENDING, not promoted by source annotation. |
| Ordinary public Python Store.query ABI/captures/detach/drop/materialization | Current public wrapper and ordinary query/capture bodies, normal+unwind GIL restoration before materialization, no contextual tuple/TermValue capture or mode callback, allocation/drop/control/frame unchanged. Materializer and its referenced vtables checked before label normalization. | 300e bounded wrapper934ASM/drop74LLVM/materializer1349ASM identities and216/272 captures retained; fresh current proof PENDING. Old installed wheel cannot substitute. |
| Row protocol allocation placement and ordinary representation | PyQuerySolution stores original variables/row; lazy iterator ref+position created only on explicit iter(row), ownership/exhaustion/index protocol from actual28 current wheel tests. Query/result materialization must not eagerly allocate/copy the new iterator; native compiler modes carry no Python state. | Current functional wheel86805 actual28PASS/27 byte readbacks is boundary evidence, not CPU-cost proof. Fresh materializer/storage body binding PENDING. |
| Actual artifact/profile/cohort completeness and final source readback | Four roles selected through Cargo JSON, nonempty exact LL/S pairs, matched exact SDK/compiler/argv/checksum closures/interpreter, source before/after unchanged, production-lock cohort admitted. Analytical native O3/ThinLTO and host O3/no-LTO are explicitly not production fat-LTO/timing. All emitted bodies remain available; finite32 equality alone cannot certify any row above. | Generation active; actual terminal/readbacks PENDING. |

## Prior failures and functional coverage

Current read-only source hash binding confirms parser/machine.rs SHA256e5acb6e57811d5ea866403093efceba9a2d2ffbda1db84b5793648632aa4158a and traits.rs SHA2567583787a766ea1a27e8e81b623aaa42faf95abf64c66510d5446ed55ded70430 match the qualified original source proof recorded in T3-integration-native-cost-review.md. That specific parserfalse/old-node iterative trait/admission argument remains reusable; the changed evaluator/worker/host optimizer seams do not inherit blanket PASS from it. Source was only read, and generation's final input readbacks remain pending.

Historical2eb/d632 and df2/300e failures remain in portfolio-current-native-cost-body-review.md and portfolio-final-native-cost-body-review.md. The first found ordinary GRAPH, outer Project and outer worker commit boundaries; the second found inner Project, lower worker boundaries and the deferred lookup leaf. Smaller enclosing frames, unchanged samples and annotations did not discharge actual callees. They remain attributable diagnostics rather than current acceptance.

Current source corrections are functionally qualified by owning lower Rust36216 actual160PASS (151 across twelve integration targets plus nine checkpoint unit controls; all seven owning commands/gates0), fresh wheel86805 actual28PASS with exact27 package-entry readbacks, and docs85659 actual9PASS. Those receipts establish their stated behaviors/source; none is silently called full native-cost proof. The native-cost review does not reopen broad semantic/Python/vendor suites or invent a timing campaign. Other original issue acceptance rows and mandatory final hosted/integration/completion are separate whole-delivery gates.

## Completion rule

Each matrix row needs an actual source/artifact-backed judgment; missing bodies or unexplained added work remains FAILED/NOT MET. Reuse an unchanged source argument or immutable matched baseline only after identity admission, and compare actual current candidate bodies for affected optimizer/capture/callee seams. Existing proven bodies may discharge related obligations together; no arbitrary repeat count. Final PASS requires every original cost obligation, not merely the three most recent findings disappearing. No final whole-issue/hosted/merge readiness is asserted here.

308 original watch98969 subsequently settled exit1. Run37790706268 completed FAILURE; profile/comparison failures and artifacts are retained in the308 monitor report. No fresh dispatch/cancellation or local build was performed by this reviewer.

## Settled whole-criterion adjudication

Actual85204 terminal0/driver0; all four individual emit.exit files and untimed-equality.exit are0. Exact final source/artifact readbacks and approved compiled closures admit all four roles: native108 nonempty paths/54 pairs each, host one pair each,21 native/49 host external tuples. Generation/sample equality is not cost acceptance. Subsequent shipping repairs do not relabel immutable2f3 artifacts.

Complete bodies and demangled modules are retained under `raw/final-lower-cost-body-review/`. Actual inventory suffix selects LL versus assembly: baseline host inventory lists assembly first. Initial empty host selections caused by assuming order were corrected before review; no empty body was accepted.

| Whole original obligation | Settled judgment on this pair |
| --- | --- |
| First-party implementation, dependency/feature law, source/compiler closure | DEMONSTRATED by accepted source reviews and exact four-role production compiled-cohort/readback admission. |
| Ordinary parser/admission | DEMONSTRATED by exact unchanged parser/traits hashes above and original static specialization proof; no new ordinary field/check/pass. |
| AST/visitor/retained plan/prepare/clone/drop/storage | DEMONSTRATED by retained source/layout proof and unchanged iterative traits; contextual-only boxes remain contextual. Source-bound retained/allocation records corroborate, rather than replace, this argument. |
| Unit native dispatch/RowDelivery | DEMONSTRATED for dispatch: result112/pattern144/context1248 ABI retained; unit delivery introduces no callback/capture object. This does not discharge worker/operator failures below. |
| Filter/Extend worker replay | FAILED: shared count_to closure remains a real call/frame in both callers. Sequential unit paths add no per-row callback; worker replay still fails. |
| Project capacity/cell work | FAILED: collector erased and geometric reserve preserved, but manual push adds representation/capacity/length work per cell. |
| GRAPH/Group/ordinary dedup | GRAPH's extra emptiness helper erased; ordinary unit append operations remain in existing homes. Group also reaches the FAILED count_to replay boundary. Complete false dedup2594 LLVM lines match after verified static dedup<...,false> names and metadata/global labels; dedup-normalized.diff empty. |
| Correlation/unit Application/deferred substitution/property functions | Previous extra Option.and_then deferred lookup closure erased; complete2996-line unit Application calls existing map get directly under the existing Some-map path. Lookup/clone/substitution remain, without an extra ApplicationOption capture or output-domain pass. No additional finding. |
| Primary native numeric recurrence/false tail | Bounded recurrence DEMONSTRATED: same eight stack objects,80-byte lexical survivor stride, one shape-filtered SUM/AVG fold, first-value bypass, saturated count/max shape/carry/add-cost and sum/peak recurrence, one outer latch and post-fold bounded/default tail. No SumChain object/push, second survivor pass or false-tail callee. MIN/MAX retain original separate collection/comparison. Nonempty numeric-normalized.diff retains block motion; no instruction identity claimed. |
| Public Python ABI/captures/detach/drop/materialization | DEMONSTRATED afresh by complete current host bodies below. Host standalone LL imports evaluator dependencies, so no claim that it independently emits every dependency numeric/operator body. Primary-native proof covers shared kernels; host proof covers the actual ABI/capture/materialization boundary. |
| Lazy row allocation placement/ordinary representation | DEMONSTRATED: unchanged actual materializer stores row/schema, creates no new iterator. Explicit iter(row) alone allocates reference/position iterator; current28 host cases and27 wheel-entry readbacks establish protocol behavior. |
| Four-role profiles/cohorts/final identity | Artifact generation DEMONSTRATED; cost acceptance FAILED. Matched analytical native O3/ThinLTO and host O3/no-LTO remain distinct from production fat-LTO/timing. |

### Two remaining concrete findings

**Shared moved-mint prefix replay.** Complete candidate-worker-count-to-full.ll has47 lines and assembly80 lines. Empty prefix returns before frame setup; nonempty prefix saves six registers, reserves88 bytes/CFA144, uses the existing80-byte value temporary and calls ScratchInterner::count_worker_mint while caller frame remains live. Extend invokes it at LLVM3201/3265/3328/3417. Filter has four replay sites; Group has inspected site5604. This corrects the earlier incomplete Extend-only scope. One shared-home erasure defect affects those callers; it is prefix/checkpoint work, not an unconditional per-output callback. Baseline corresponding loops are inline. The name contains commit_items but denotes closure#5, not a retained out-of-line commit_items function.

**Project repeated cell work.** Baseline blocks543/599 retain raw pointer/capacity/length in SSA through reserved bulk fill; final length is stored once at604 (606 on unwind). Candidate514→551→571 reloads representation tag/heap pointer/length and computes capacity per cell;571 stores incremented length each cell and returns to514. Both preserve geometric lower-bound reservation, and candidate has no per-row FromIterator callee. These facts do not remove actual added cell work. Related SolutionTerm/ConstCell printed names do not imply different runtime cell sizes; the finding concerns the shared reserved fill law.

Both findings and scope were promptly sent to root/G. No third concrete finding was found in the remaining inspected complete seams. Overall row15 remains FAILED; smaller caller frames and exact samples cannot close it.

### Fresh complete host proof

Public query wrapper934 assembly lines each: host-wrapper-normalized.diff empty after local/exception/content-addressed labels only. Detached unit capture Drop74 LLVM lines each,272 bytes with identical field drops: host-unit-capture-drop-normalized.diff empty. Complete ordinary query_governed2238 LLVM lines each: after static query_governed/query_impl<()> and metadata substitutions the sole residual was an error vtable label. Actual baseline1R/candidate22 vtables have identical size32/error closure/drop fields; only after that check were names normalized. host-query-normalized.diff empty. Both detach through SuspendAttach and restore on normal/cleanup before materialization. Contextual360-byte tuple specialization is excluded from ordinary proof.

Materialize_results1631 LLVM/1349 assembly each. Complete referenced vtables retained and inspected: baseline1R/candidate22 error closure/drop size32;1J/1T String fmt::Write size48;2c/2q fmt::Error Debug size32. All pairwise fields/function contents match. Their verified-label normalization makes host-materialize-vtable-normalized.diff empty. Thus ordinary allocation/drop/control/representation match, without eager new iterator allocation. These are fresh2f3 bodies, not inherited300e proof.

### Correction scope and meaningful evidence reuse

Root/G own shipping corrections. A shared explicitly inlined moved-mint prefix helper preserves existing replay algorithm/home. Focused existing nine checkpoint controls and relevant governed Filter/Extend/Group prefix/error controls plus owning strict clippy qualify source repair; no automatic repeat of unchanged wheel28/docs9/all151 Rust cases is required.

For Project, Solution::new() plus projected.extend(src.iter().map(...)) reuses existing SmallVec bulk home: raw_mut/LenOnDrop once-final-store and exact size_hint/geometric reserve. Keep explicit outer Vec loop; no duplicate core unsafe/raw writes or reserve_exact substitute. This coherent source choice requires fresh actual candidate emission proving inlined Extend without another frame and matching bulk cell work. Existing projection/query behavior controls cover touched behavior; no new Python semantic mirror or blanket suite follows from this rewrite.

Fresh candidate native and host emission is mandatory for affected optimizer seams. Immutable85204 baseline is reusable with exact source/compiler/profile/argv/cohort/artifact admission; regenerating an unchanged baseline is not ceremony. Recheck both failures across actual affected callers, retain the whole matrix, and reuse unaffected demonstrated rows only with exact applicability. No whole-issue/hosted/merge PASS is asserted.
