Current cohort correction: see [portfolio-native-cost-cohort-correction.md](portfolio-native-cost-cohort-correction.md). Original76668 is aborted143/wrong dependency cohort; no current cost PASS. Fresh offline resolver witness passes all39 external identities/checksums, but compilation and full proof await root readmission.

# Current native-cost and complete emitted proof — preparation only

Status: READY FOR ROOT/INDEPENDENT SOURCE REVIEW; NOT EXECUTED. Current candidate tree d632307fb725304ed864967d5234cdab35bc5c99. No cost build, allocator probe, timing, documentation or source mutation occurred in this preparation.402 currently owns the local execution lane. Bounded native controls/owning row Rust/Python phases have separately passed and do not establish CPU-operation preservation.

The sole plan's native-cost contract requires proof over parse, prepare/admit, storage/clone/drop, reused execution, correlated substitution, operator/consumer/host boundaries: unchanged allocation/representation/algorithmic work, with complete emitted ABI/frame/capture/drop/loop inspection where source is insufficient. A disabled mode, equal output, small frame alone, or helper inline annotation is not proof. No numeric regression allowance or elapsed-time acceptance is introduced.

## Attributable inputs and exact proof profiles

Baseline is root's actual tracked git-archive snapshot of main2eb04d61f3d65f34ec77b396b5d03c05c23fd5ee at `/opt/purrdf-454-native-cost-main-2eb04d61`, not historical dfc. Root's tar/readback provenance is [baseline report](portfolio-current-native-cost-baseline.md). Driver requires baseline OID equal retained MERGE_HEAD, compares every tracked blob to that snapshot before builds, hashes every baseline input and reads them back afterward. Candidate tracked/index source is similarly frozen/read back. No new worktree/branch or shipping mutation is needed.

The retained identical common untimed32-record Rust probe source has actual SHA256 aef409ac8b1122df07bab53f1053f5356decb5b3059db583013e7664bea40587. Both owned probe copies must byte-match; ordinary four first-party dependencies point to the corresponding exact source root, each probe must seed its corresponding full production Cargo.lock, ordinarily resolve offline without changing any external identity/checksum, and then pass locked offline metadata; resolved locks must byte-match and all manifests/locks/executables are retained. No old emitted body or execution total is promoted to current source.

Actual workspace release is O3/fat-LTO/codegen1/strip-symbols with debug assertions and overflow checks default OFF; dev/test are O3/checks ON. The prepared paired proof uses the **historically accepted matched ThinLTO release emission stage**, O3/ThinLTO/codegen1/strip-symbols/assertions and overflow OFF, target-cpu=native, warnings denied. This is a named analytical emission stage, not a claim that workspace release defaults to ThinLTO. The paired ordinary Python host proof is separately **matched no-LTO release emission**, otherwise identical; it is pre-link body/ABI proof, not final fat-LTO instruction identity. Both roles receive the same explicit flags/current active SDK and absolute supported PYO3_PYTHON. Verbose actual rustc argv and compiler/profile/JSON artifacts must substantiate those settings after admission.

The driver's cost phase preserves complete emitted modules and actual compiler-selected executable/library roles. ThinLTO can emit several linked component pairs; the earlier draft's exactly-two-file assumption was corrected source-only. It requires nonempty paired .ll/.s files plus actual main/algebra/eval/xsd modules, retaining ALL matched component bytes/paths/hashes, not excerpts or only the entry wrapper. Host selection requires one non-test purrdf_native compiler-artifact frame, actual .so and .rlib, and its complete .ll/.s pair; all identities are reread before artifact-generation success. Any missing/malformed/ambiguous output refuses.

Independent source review found that the draft host path-count check alone could accept two LLVM paths or empty files. The Stage-only correction now uses one shared emitted-pair validator for both stages: every inventoried path must be nonempty and have its exact opposite-extension counterpart inside the selected inventory; LLVM/assembly counts must match and be nonzero. Host mode additionally requires exactly one pair, hence one nonempty .ll and one nonempty .s. Native mode retains all paired modules. No artifact-generation/probe execution occurred for this correction; bash syntax passes and shipping source/index remains d632.

## Untimed execution coverage

The32 complete records cover one layout record (GraphPattern/Expression/Query/PreparedQuery/NodeRef), thirteen ordinary query windows, thirteen matching request-binding windows, two exact/fixed division windows and three configured relation windows. Actual calls cover parse, retained bytes, clone/drop, prepare/query-admission, warmed reused execution, governed consumed vectors, correlation/OPTIONAL/MINUS/EXISTS/LATERAL/named graphs, projection/filter/BIND/ordering/distinct/grouping and bounded/arbitrary-precision SUM/AVG. Existing counting allocator windows are the only measurement home; no clocks, benchmark harness or host latency measurement.

Both actual executables must run successfully, emit exactly32 complete records and byte-match the whole output. A disagreement is a concrete finding to diagnose, not a receipt to normalize away. This establishes sampled representation/allocation/resource laws; it does not replace whole-function operation/ABI proof below.

## Required complete-body adjudication

|Owning source seam|Actual paired body/caller proof required|Refusal condition|
|---|---|---|
|Ordinary parser specialization; algebra walk/owned/clone/drop/retained/admission|Read actual ordinary parserfalse path, qualification_parse caller and recursive/iterative old-node trait/drop/admission paths; original strict grammar remains. Added Apply arm only its new discriminant; old cases retain original work and iterative storage.|Runtime contextual checks/state/extra allocations on native path, enlarged ordinary layout/storage or new recursion/live frame.|
|eval dispatcher and unit RowDelivery|Full actual RdfDataset dispatcher, caller, per-old-arm ABI/loads/tail transfers; M::ACTIVE=false and unit storage/callback erase. Current main's XPath/cache/governor/scratch/worker state belongs to BOTH roles.|Additional old-arm mode test/load/wrapper/callback or retained contextual state; branch usually false is insufficient.|
|Filter/Extend/Project and row checkpoints|Complete shared sequence kernels/callers, source ordering and compiled erasure; preserve main's ordinary buffer reuse (`mem::take`), governor reservation/commit/resume and worker ordering.|Extra sequence-call boundary/storage/loop, lost buffer reuse, additional ordinary per-row work or changed resource/error ordering.|
|Group/Graph/Dedup/LATERAL/correlation/property-functions|Full old operator and unit application bodies, actual GroupDomain/unit no-op erasure, substitution/memo/guard actions, frames/calls and loops. Ordinary first-party options/configuration stay shared.|Contextual domain remapping, scope walk/clone or consumer callback on ordinary rows; RHS duplication/algorithmic work or extra live calls/frames.|
|Exact SumChain and aggregate tail|Actual native SUM/AVG caller and inlined recurrence: one shape step/operand and original count/max/carry/cost order, no retained push return/state traffic, no out-of-line push/tail and no second already-excluded bounded/default policy test. Both exact/fixed and large-number neighbors included.|Any prior concrete native failure reappears: helper call/live-frame/state traffic, redundant fast-path check or additional pass/shape conversion/Cost operation.|
|Python ordinary Store.query static QueryMode=()|Complete ordinary PyO3 wrapper, query body, detached capture and closure drop, with current main's division/XPath config on both sides. Unit selection/dataset forwarding erase; no contextual TermValue/scope ownership/drop. Native results/materialization/layout are unchanged.|Extra host mode forwarding ABI/call depth/capture/drop/graph-selection work on ordinary query; equal frame alone cannot prove it.|
|New host row protocol|Inspect changed query.rs/module materialization boundary against baseline; existing row storage/layout unchanged. New iterator is only invoked on iter(row), owns one Python reference plus position and converts one cell per successful next; length hint is O1.|Moving eager conversion or iterator allocation into ordinary query/materialization, native cell copy/cache, self-iterator state, or silently treating new host iteration cost as zero.|

Body comparison may normalize symbol/path/metadata identifiers while preserving every substantive call, instruction, control edge, load/store/drop/alloca and frame. Whole-module bytes need not match: symbol layout/code motion alone is not extra work, and added contextual-only bodies are expected. The reviewer must cite full attributable function/module identities and actual line locations, with source operation arguments for changed layouts. Summary symbols/frame totals supplement, never replace, full actual bodies.

Source reuse is bounded: current parser/machine SHA e5acb6e57811d5ea866403093efceba9a2d2ffbda1db84b5793648632aa4158a and traits SHA7583787a766ea1a27e8e81b623aaa42faf95abf64c66510d5446ed55ded70430 match the previously qualified source arguments. Exact cost home SHA6228ad322df4ceb8596067a9eae705e84dc85f4b252bd07b5727daa658d85d0d also matches the forced-inline repair. Current compiled bodies nevertheless must rebind changed compiler/main composition; historical absolute frames/artifacts are not current qualification.

## Concrete pending execution

After explicit lane admission, invoke the existing source-bound Stage driver `cost` with ROOT=current454, EXPECT_TREE=d632..., EVIDENCE=existing owned root, a fresh cost log subdirectory, BASELINE_ROOT=/opt/purrdf-454-native-cost-main-2eb04d61, BASELINE_OID=2eb04d61..., and PYO3_PYTHON=current supported absolute interpreter. Native baseline/candidate emits and probes are sequential; host baseline/candidate emits follow sequentially. Private native/host target/build directories are distinct per role. No Python semantic/vendor execution or timing occurs.

Driver terminal0 means complete source/artifact generation, readbacks and exact32 equality only. It deliberately writes `cost-verdict-pending.txt`; independent full-body/native-cost adjudication remains REQUIRED before MET. Missing required body/evidence is FAILED with the exact gap, never conditional PASS. Eventual402 source integration is separately assessed after its current owned fixes; nothing is prematurely imported here.
