# Current native-cost artifact generation

VERDICT: PASS — actual production-dependency-cohort artifact generation and untimed32-record equality. Full native-cost acceptance is NOT YET MET: independent full emitted-body ABI/frame/capture/drop/loop adjudication remains required. No docs or broader completion verdict.

Owning prepared cost driver executed sequentially on exact staged treed632307fb725304ed864967d5234cdab35bc5c99, HEADcee1c41b2faa370b7daa60cc7536e784a4756d0e and retained MERGE_HEAD2eb04d61f3d65f34ec77b396b5d03c05c23fd5ee. Baseline `/opt/purrdf-454-native-cost-main-2eb04d61` was verified against every18107 tracked Git blob before execution. Evidence root `/opt/purrdf-454-current-qualification-20261008/native-cost-current-production-1`; all new outputs reside within its fresh `artifacts/` subdirectories. No previous attempt’s artifacts were reused.

Actual scope purrdf-454-native-cost-production-20261008.scope, invocation42007d7ab26147769d3ede7203ec0af7, session50132. Tools.write_stdin supplied actual terminal0; retained session-50132.exit and driver.exit both0. Terminal scope inactive/dead recorded; lane FREE. Scope limits64GiB RAM and zero swap were captured. Raw active SDK Cargo executed with jobs8/private build and target directories, with inherited RUSTC_WRAPPER=kache (not wrapper-free); actual Cargo/kache/rustc containment snapshot shows them within this scope. Compiler identities, explicit profile settings, env wrapper disclosure and complete verbose compiler argv are retained. No speed, host latency or swap-performance claim is made.

Both probes seeded their corresponding production Cargo.lock before ordinary offline metadata resolution and subsequent locked metadata; all four metadata commands exited0. Probe locks byte-identical. Complete selected external tuples must belong to production by name/version/source/checksum. Every actual compiler artifact package ID bound to metadata, and the complete compiled external closure bound to production checksums:21 native packages per side and49 host packages per side, zero unapproved external tuples in every role. Regex1.12.4 is the actual production pin. See all four *compiled-external-checksums.tsv and *compiled-metadata-admission.json, not regex alone. Host builds used the original locked production manifests directly.

Both native emissions exited0. Each retained108 nonempty emitted paths:54 exact same-stem LLVM/assembly pairs, including full main/algebra/evaluator/XSD modules. Selected executable compiler frame unique and real; executable/input identities retained. Both real untimed probes exited0 and emitted exactly32 records; whole outputs compare byte-identical with actual equality0. SHA256 both137c7bba30adda360ca907e37ce8efbe98ea9be56fe19c105c0cf6e2345f4119. Nothing was normalized or repeated until equality. This measures the existing counting-allocator windows and fixed inputs, not timing, and does not replace the full-body proof.

Both host emissions exited0. Each selected actual non-test purrdf_native artifact frame is unique, holds actual nonempty .so/.rlib, and retains exactly one nonempty matched .ll/.s pair. Full emitted body inventories are *host-emitted-paths.txt; actual selected frames, library and emitted SHA256 receipts retained. Native stage uses matched release O3/ThinLTO/codegen1/strip-symbols/assertions OFF/overflow OFF/target-cpu-native. Host stage differs only in LTO=false. These are specifically named analytical emitted-body stages; production workspace release fat-LTO is not relabeled as ThinLTO/no-LTO. Matching baseline/candidate Python executable is the actually qualified WT venv.

All eight per-side input/native-emission/host-emission/host-library readbacks passed, as did full baseline source and current tracked source readbacks. Final driver verified unchanged staged tree and clean unstaged shipping diff. generation-terminal-summary.json provides counts and terminal binding; driver cost-verdict-pending.txt explicitly preserves the independent-proof requirement. No source/production lock edits, commits, push, docs execution, host timing, broad Python/oracle/vendor rerun or external submission occurred.

Historical failure preserved: original76668 selected regex1.13.1 through standalone generate-lockfile and was stopped only after verified wrong cohort. Actual terminal143 and inactive scope retained under native-cost-current-1. Its partial outputs/sample equality do not qualify current shipping-native acceptance. Offline corrected preparation evidence and initial supplementary path-edge assertion failure are retained separately under `/opt/purrdf-454-production-cohort-resolution-20261008-1`; see portfolio-native-cost-cohort-correction.md. The newly completed phase independently re-resolved and recompiled the correct production cohort.
