# Fresh outer bulk Project artifact generation

VERDICT: PASS for artifact generation and immutable-baseline admission; full native-cost acceptance FAILED / NOT MET after complete fresh twelve-row audit.

Actual session97434 terminal0 observed via tools.write_stdin. Evidence /opt/purrdf-454-current-qualification-20261008/final-project-outer-bulk-native-cost-1 contains session-terminal.json, all seven commands and driver exits0, complete compiler/artifact/argv logs. Candidate57906333c273e8e7dde7a3877e44ee6919cc7983 frozen through both emissions and final source/artifact/config readbacks. Scope purrdf-454-project-outer-bulk-native-cost-20261008.scope invocationb4674ab06d8d4e8b91b4476b17c57a99; actual live64GiB/SwapMax0 captured; terminal inactive/dead/lane FREE. Raw same SDK/private fresh candidate roots/jobs8/inherited kache retained; no timing claim.

Strict immutable85204 baseline roles only reused: exact df2 source, compiler/PATH/profile/wrapper/interpreter, production-lock/checksum closures21 native/49 host, actual selected executable/non-test library frames, all original source/artifact/config hashes read back. Fresh candidate native108 nonempty paths54 LL/S pairs; host one nonempty LL/S pair and actual library frame. Actual PyO3 ABI/cfg/link/env and rerun-env/rustflags inputs match baseline. All32 untimed records compare whole-byte exactly. All baseline/current source/artifact/evidence readbacks0; no old candidate promotion. Analytical native ThinLTO/host no-LTO settings remain distinct from production fat-LTO.

Independent [complete twelve-row audit](portfolio-final-project-outer-bulk-cost-body-review.md) confirms outer normal/unwind final length publication correct, source-row decoding hoisted, destination bulk work correct, extra Lift transfer erased. Sole failure is outlined outer SpecExtend callee263LLVM/311ASM/CFA224, caller24-byte Map capsule and once-per-projection generic capacity/count/reserve fallback setup absent from baseline inline loop. Cost criterion remains FAILED regardless of35 semantic tests and32 equal records. Other seven native bodies match prior4828 after verified metadata/source-location changes; complete fresh host four bodies and actual static vtables/PyO3 bindings match, no additional unreviewed row. No shipping edit, diagnostic build, packaging copy, commit or forge action during frozen generation. The later separately admitted paired diagnostic has its own report. All failed prior artifacts retained.
