/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/* libpurrdf — the PURRDF purrdf semantic RDF-1.2 C-ABI. */
/* GENERATED by cbindgen; do not edit. Edit crates/rdf-capi and regenerate. */

#ifndef PURRDF_H
#define PURRDF_H

#pragma once

/* WARNING: generated file — edit crates/rdf-capi instead. */
#define PURRDF_MAJOR 0
#define PURRDF_MINOR 10
#define PURRDF_PATCH 0


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI major version. `0` signals the surface is still **beta** — the freeze
 * discipline (append-only status enum, drift-gated header) is in place, but the
 * version stays pre-1.0 until a real C consumer + the rdflib shim exercise it.
 */
#define PURRDF_ABI_MAJOR 0

/**
 * ABI minor version.
 */
#define PURRDF_ABI_MINOR 1

/**
 * ABI patch version.
 */
#define PURRDF_ABI_PATCH 0

/**
 * Status returned by every fallible entry point as `i32`. `Ok == 0`.
 *
 * Append-only: never renumber a variant. `Panic` is parked at 100 to leave room
 * for ordinary status codes to grow contiguously from 10.
 */
enum PurrdfStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Success.
     */
    PURRDF_STATUS_OK = 0,
    /**
     * A required pointer argument was null.
     */
    PURRDF_STATUS_NULL_POINTER = 1,
    /**
     * A C string argument was not valid UTF-8.
     */
    PURRDF_STATUS_INVALID_UTF8 = 2,
    /**
     * An argument was structurally invalid (e.g. an unknown enum tag).
     */
    PURRDF_STATUS_INVALID_ARGUMENT = 3,
    /**
     * The requested media type / format id is not supported.
     */
    PURRDF_STATUS_UNSUPPORTED_FORMAT = 4,
    /**
     * Parsing the input bytes failed.
     */
    PURRDF_STATUS_PARSE_ERROR = 5,
    /**
     * Serializing the dataset failed.
     */
    PURRDF_STATUS_SERIALIZE_ERROR = 6,
    /**
     * Evaluating the SPARQL query failed.
     */
    PURRDF_STATUS_QUERY_ERROR = 7,
    /**
     * Freezing a mutable graph into a dataset failed.
     */
    PURRDF_STATUS_FREEZE_ERROR = 8,
    /**
     * A cursor has no more rows (a non-error terminal signal, returned > 0).
     */
    PURRDF_STATUS_CURSOR_EXHAUSTED = 9,
    /**
     * A GTS container read/write operation failed.
     */
    PURRDF_STATUS_GTS_ERROR = 10,
    /**
     * A panic was caught at the FFI boundary (should never reach the caller in
     * normal operation).
     */
    PURRDF_STATUS_PANIC = 100,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfStatus PurrdfStatus;
#else
typedef int32_t PurrdfStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The kind tag of a [`PurrdfTermView`].
 *
 * These are the canonical discriminant values for the `int32_t kind` field of
 * [`PurrdfTermView`]. An unknown value in that field yields
 * [`PurrdfStatus::InvalidArgument`] — never UB.
 */
enum PurrdfTermKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * An IRI; `lexical` is the IRI string.
     */
    PURRDF_TERM_KIND_IRI = 0,
    /**
     * A blank node; `lexical` is the label, `blank_scope` the scope ordinal.
     */
    PURRDF_TERM_KIND_BLANK = 1,
    /**
     * A literal; `lexical`/`datatype`/`language`/`direction` are meaningful.
     */
    PURRDF_TERM_KIND_LITERAL = 2,
    /**
     * An RDF-1.2 quoted triple; `lexical` is empty — materialize the components
     * via `purrdf_term_to_ntriples` using this view's `term_id`.
     */
    PURRDF_TERM_KIND_TRIPLE = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfTermKind PurrdfTermKind;
#else
typedef int32_t PurrdfTermKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The optional base direction of a literal (RDF-1.2 `i18n` direction).
 *
 * These are the canonical discriminant values for the `int32_t direction` field
 * of [`PurrdfTermView`]. An unknown value yields [`PurrdfStatus::InvalidArgument`]
 * — never UB.
 */
enum PurrdfDirection
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * No base direction.
     */
    PURRDF_DIRECTION_NONE = 0,
    /**
     * Left-to-right.
     */
    PURRDF_DIRECTION_LTR = 1,
    /**
     * Right-to-left.
     */
    PURRDF_DIRECTION_RTL = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfDirection PurrdfDirection;
#else
typedef int32_t PurrdfDirection;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The kind tag of a [`PurrdfGraphMatch`].
 *
 * These are the canonical discriminant values for the `int32_t kind` field of
 * [`PurrdfGraphMatch`]. An unknown value yields [`PurrdfStatus::InvalidArgument`]
 * — never UB.
 */
enum PurrdfGraphMatchKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Match any graph (default or named).
     */
    PURRDF_GRAPH_MATCH_KIND_ANY = 0,
    /**
     * Match only the default graph.
     */
    PURRDF_GRAPH_MATCH_KIND_DEFAULT = 1,
    /**
     * Match the named graph given by `name`.
     */
    PURRDF_GRAPH_MATCH_KIND_NAMED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfGraphMatchKind PurrdfGraphMatchKind;
#else
typedef int32_t PurrdfGraphMatchKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An owned byte buffer. Opaque to C; read via `purrdf_buffer_data`, release
 * with `purrdf_buffer_free`.
 */
typedef struct PurrdfBuffer PurrdfBuffer;

/**
 * A pattern-quad cursor. It holds an `Arc<RdfDataset>` clone (`pin`) so the
 * term arena the views borrow into cannot dangle — the cursor stays valid even
 * after every `PurrdfDataset` handle is freed. Matching rows are pulled lazily
 * from the core's owned indexed cursor and are never collected. Single-threaded.
 */
typedef struct PurrdfCursor PurrdfCursor;

/**
 * A frozen, immutable RDF-1.2 dataset. Wraps `Arc<RdfDataset>`, so it is
 * `Send + Sync`: it may be read concurrently from multiple threads. Release
 * with `purrdf_dataset_free`.
 */
typedef struct PurrdfDataset PurrdfDataset;

/**
 * An owned error: a status code plus a NUL-terminated message. Opaque to C.
 */
typedef struct PurrdfError PurrdfError;

/**
 * A copy-on-write mutable graph: a suppression-delta over a frozen base
 * dataset. Single-threaded mutable — NOT `Sync`; do not touch one from two
 * threads. Release with `purrdf_graph_free`.
 */
typedef struct PurrdfGraph PurrdfGraph;

/**
 * An immutable compiled JSON-LD context. Release with
 * `purrdf_jsonld_context_free`; the handle is safe for concurrent reads.
 */
typedef struct PurrdfJsonLdContext PurrdfJsonLdContext;

/**
 * A reasoning session over one ontology. Release with [`purrdf_reasoner_free`].
 *
 * Every `purrdf_entail_*` function above takes the document as a C string and rebuilds
 * everything it needs, so asking three questions parses and reverse-maps the ontology
 * three times. This handle holds the parsed document instead: [`purrdf_reasoner_open`]
 * parses once, the first question needing a knowledge base reverse-maps once, and later
 * questions reuse both.
 *
 * # Thread safety — UNLIKE [`PurrdfDataset`](crate::handles::PurrdfDataset)
 *
 * This handle is `Send` but **NOT `Sync`**: answering a question MUTATES the shared
 * knowledge base, so two threads may not use one handle concurrently. A frozen dataset
 * may be read from many threads; a session may not. Move it between threads, or open
 * one per thread — the README's thread-safety table says the same.
 */
typedef struct PurrdfReasoner PurrdfReasoner;

/**
 * A SPARQL SELECT result cursor. Owns its variable names and solution rows
 * (dataset-independent `TermValue`s).
 *
 * **Lifetime invariant (load-bearing):** `rows` is IMMUTABLE for the cursor's
 * whole life — `purrdf_rowcursor_next` only advances `current`, never mutates,
 * reorders, or reallocates the `Vec`. A `PurrdfStr` returned by
 * `purrdf_rowcursor_term` borrows directly into `rows[current]`'s owned
 * `TermValue`; those pointers stay valid for the cursor's life (documented
 * conservatively as "until the next `_next`/`_free`"). The C side never frees a
 * `PurrdfStr.ptr`. Single-threaded.
 */
typedef struct PurrdfRowCursor PurrdfRowCursor;

/**
 * A borrowed UTF-8 slice. `ptr` is **not** NUL-terminated — use `len`. The
 * memory is owned by libpurrdf; the C side must **never** `free()` it. As an
 * output, a view's pointers are valid only until the next `*_cursor_next` /
 * `*_rowcursor_next` on the same cursor, or until the owning handle is freed.
 * As an input, the caller owns the bytes and they need only outlive the call.
 * `ptr` may be null when `len == 0`.
 */
typedef struct {
    /**
     * Pointer to the first byte (borrowed; never freed by the other side).
     */
    const uint8_t *ptr;
    /**
     * Length in bytes.
     */
    size_t len;
} PurrdfStr;

/**
 * A structured, borrowed term view. Which fields are meaningful depends on
 * `kind` (see [`PurrdfTermKind`]). All `PurrdfStr` fields follow the borrowing
 * contract on [`PurrdfStr`]. `term_id` is the dataset-local opaque id of the
 * term (`0` when the view was not produced from an interned dataset term, e.g.
 * a SPARQL solution value); it is meaningful ONLY against the dataset that
 * produced the view and must never be compared across datasets.
 *
 * `kind` is an `int32_t` carrying a [`PurrdfTermKind`] discriminant (0–3).
 * `direction` is an `int32_t` carrying a [`PurrdfDirection`] discriminant (0–2).
 * An unknown value in either field yields [`PurrdfStatus::InvalidArgument`] —
 * never undefined behaviour.
 */
typedef struct {
    /**
     * The term kind tag (`int32_t`; see [`PurrdfTermKind`] for valid values).
     * An unknown discriminant yields `PurrdfStatus::InvalidArgument`, not UB.
     */
    int32_t kind;
    /**
     * IRI string / blank label / literal lexical form (empty for `Triple`).
     */
    PurrdfStr lexical;
    /**
     * Datatype IRI (`Literal` only; empty otherwise).
     */
    PurrdfStr datatype;
    /**
     * Language tag (`Literal` only; empty when absent).
     */
    PurrdfStr language;
    /**
     * Base direction (`int32_t`; see [`PurrdfDirection`] for valid values;
     * `Literal` only). An unknown discriminant yields `PurrdfStatus::InvalidArgument`,
     * not UB.
     */
    int32_t direction;
    /**
     * Blank-node scope ordinal (`Blank` only).
     */
    uint32_t blank_scope;
    /**
     * Dataset-local opaque term id (`0` = none). See the struct docs.
     */
    uint32_t term_id;
} PurrdfTermView;

/**
 * A graph-slot match passed by value into `purrdf_quads_for_pattern`. For
 * `Named`, `name` is an **input** term view the caller fills.
 *
 * `kind` is an `int32_t` carrying a [`PurrdfGraphMatchKind`] discriminant (0–2).
 * An unknown value yields [`PurrdfStatus::InvalidArgument`] — never UB.
 */
typedef struct {
    /**
     * Which graphs to match (`int32_t`; see [`PurrdfGraphMatchKind`] for valid
     * values). An unknown discriminant yields `PurrdfStatus::InvalidArgument`, not UB.
     */
    int32_t kind;
    /**
     * The named-graph term (meaningful only when `kind == Named`).
     */
    PurrdfTermView name;
} PurrdfGraphMatch;

/**
 * The SemVer ABI version reported by `purrdf_abi_version`.
 */
typedef struct {
    /**
     * Major version: incompatible ABI change.
     */
    uint32_t major;
    /**
     * Minor version: backward-compatible additions.
     */
    uint32_t minor;
    /**
     * Patch version: backward-compatible fixes.
     */
    uint32_t patch;
} PurrdfAbiVersion;

/**
 * `#[repr(C)]` twin of `purrdf_core`'s `RdfStoreCapabilities` (each `bool`
 * rendered as `0`/`1`). The seven flags mirror the kernel exactly.
 */
typedef struct {
    /**
     * The dataset distinguishes named graphs from the default graph.
     */
    uint8_t named_graphs;
    /**
     * The dataset carries RDF-1.2 quoted triples (the star layer).
     */
    uint8_t quoted_triples;
    /**
     * The dataset carries reifier bindings.
     */
    uint8_t reifiers;
    /**
     * The dataset carries annotation triples.
     */
    uint8_t annotations;
    /**
     * The dataset carries per-quad source locations.
     */
    uint8_t source_locations;
    /**
     * The dataset carries projection loss records.
     */
    uint8_t loss_records;
    /**
     * The dataset carries an out-of-band lookaside.
     */
    uint8_t lookaside;
} PurrdfCapabilities;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Expose the buffer's bytes as a borrowed pointer + length. The pointer is
 * valid until `purrdf_buffer_free(buf)`; the C side must not free it. For an
 * empty buffer `*out_ptr` may be a non-null dangling pointer with `*out_len == 0`.
 *
 * # Safety
 * `buf` must be a live buffer handle; `out_ptr`/`out_len` must be writable.
 */
int32_t purrdf_buffer_data(const PurrdfBuffer *buf, const uint8_t **out_ptr, size_t *out_len);

/**
 * Release a buffer handle. No-op on null.
 *
 * # Safety
 * `buf` must be null or a live buffer handle not already freed.
 */
void purrdf_buffer_free(PurrdfBuffer *buf);

/**
 * Open a pattern cursor. Each of `s`/`p`/`o` is a nullable input term view
 * (null = unbound). `g` is a non-null [`PurrdfGraphMatch`] (use kind `Any` for
 * "any graph"). A bound term/graph value that is interned nowhere yields an
 * empty cursor (not an error). The cursor pins the dataset's `Arc` and advances
 * the selected core index lazily; opening it does not collect matching rows.
 *
 * # Safety
 * `dataset` must be a live handle; the view/match pointers must be valid where
 * non-null; the out-params must be writable.
 */
int32_t purrdf_quads_for_pattern(const PurrdfDataset *dataset,
                                 const PurrdfTermView *s,
                                 const PurrdfTermView *p,
                                 const PurrdfTermView *o,
                                 const PurrdfGraphMatch *g,
                                 PurrdfCursor **out_cursor,
                                 PurrdfError **out_error);

/**
 * Advance to the next quad. On success fills the four term views; `out_has_graph`
 * is `0` for default-graph quads (the `out_g` view is then a zeroed placeholder).
 * The `PurrdfStr` pointers inside the views are valid until the next
 * `purrdf_cursor_next` on this cursor or `purrdf_cursor_free`. Returns
 * `PurrdfStatus::CursorExhausted` (a non-error terminal signal, `> 0`) when no
 * rows remain.
 *
 * # Safety
 * `cursor` must be a live cursor; the out-params must be writable.
 */
int32_t purrdf_cursor_next(PurrdfCursor *cursor,
                           PurrdfTermView *out_s,
                           PurrdfTermView *out_p,
                           PurrdfTermView *out_o,
                           PurrdfTermView *out_g,
                           uint8_t *out_has_graph);

/**
 * Release a cursor handle. No-op on null.
 *
 * # Safety
 * `cursor` must be null or a live cursor not already freed.
 */
void purrdf_cursor_free(PurrdfCursor *cursor);

/**
 * Materialize an RDF document under a SPARQL entailment regime.
 *
 * `document` is parsed as N-Quads, which accepts an N-Triples document
 * unchanged, so a document that names a graph keeps naming it. `regime` is one
 * of `simple`, `rdf`, `rdfs`, `owl-rl`, `owl-direct`, `rif`, `d` — the same
 * spellings the CLI, WASM and the Python surface accept — and ALL SEVEN
 * materialize; none is refused for being the regime it is.
 *
 * `program` is the regime's own rule document. `rif` entails under the CALLER's
 * rules, so for that spelling `program` is a normative RIF-in-XML document (an
 * `Import` is refused: resolving one is I/O this boundary does not perform).
 * Every other regime's rule table is the specification's, so `program` must be
 * the empty string `""` — a non-empty one is an ERROR rather than a silently
 * discarded argument, because a caller who passed rules to `rdfs` believes they
 * ran.
 *
 * On success `*out_nquads` receives the canonical (RDFC-1.0) N-Quads closure —
 * every input quad plus every triple the regime's implemented rules infer — and
 * `*out_report` receives the byte-stable rendered reasoning report, which names
 * which rules fired and how often, which specification rules did NOT fire, which
 * constructs were left at a boundary, the evaluation budget, and the calculus's
 * contract hash. **Free BOTH with `purrdf_buffer_free`.** The report is not
 * optional: all seventy-eight OWL 2 RL rules now run, so a caller that reported
 * "OWL-RL entailment" without saying which CONSTRUCTS were left at a boundary
 * would be making exactly the overclaim the report exists to prevent — a
 * complete rule table is not a complete closure.
 *
 * On any error neither out-param is written, so there is nothing to free.
 *
 * # Safety
 * `document`, `regime` and `program` must be non-null, NUL-terminated C strings;
 * `out_nquads` and `out_report` must be writable pointers; `out_error` must be
 * null or writable.
 */
int32_t purrdf_entail_materialize_to_nquads(const char *document,
                                            const char *regime,
                                            const char *program,
                                            PurrdfBuffer **out_nquads,
                                            PurrdfBuffer **out_report,
                                            PurrdfError **out_error);

/**
 * Write the rule table the specification *defines* `regime` by — one canonical
 * rule name per newline-terminated line, in specification table order — to
 * `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * An empty buffer for a regime with no rule table of its own (`simple`, plus
 * `owl-direct`, which decides through the tableau, and `rif`, which entails under the
 * caller's rules — all three still MATERIALIZE). `owl-rl` yields all 78 rules of OWL 2
 * Profiles §4.3 Tables 4–9 whether or not this build fires them — that is the
 * point: diff it against `purrdf_entail_implemented_rules` to measure the gap.
 *
 * # Safety
 * `regime` must be a non-null, NUL-terminated C string; `out_buffer` must be a
 * writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_entail_rules(const char *regime, PurrdfBuffer **out_buffer, PurrdfError **out_error);

/**
 * Write the subset of `purrdf_entail_rules(regime)` this build's chase actually
 * fires today to `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * `purrdf_entail_rules(r)` minus `purrdf_entail_implemented_rules(r)` is the
 * regime's measurable gap — the same set the rendered report's `missing` lines
 * name.
 *
 * # Safety
 * `regime` must be a non-null, NUL-terminated C string; `out_buffer` must be a
 * writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_entail_implemented_rules(const char *regime,
                                        PurrdfBuffer **out_buffer,
                                        PurrdfError **out_error);

/**
 * Write the rules this build fires BEYOND `regime`'s specification table to
 * `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * Disjoint from both `purrdf_entail_rules(regime)` and
 * `purrdf_entail_implemented_rules(regime)`: the normative table is a statement
 * about the specification and does not move because this build fires a sound rule
 * the table happens not to list. A rendered report names the same rules on its
 * `extension` line — this answers the question without materializing a dataset
 * first. Empty for a lane with nothing added to it.
 *
 * # Safety
 * `regime` must be a non-null, NUL-terminated C string; `out_buffer` must be a
 * writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_entail_extensions(const char *regime,
                                 PurrdfBuffer **out_buffer,
                                 PurrdfError **out_error);

/**
 * Decide whether an ontology has a model at all.
 *
 * `document` is parsed as N-Quads (which accepts N-Triples). `step_cap` narrows
 * the per-decision tableau step cap; **0 means the knowledge base's own cap**, not
 * a cap of zero steps. The cap can only NARROW — a value above the knowledge
 * base's own ceiling has no effect — so this cannot be used to make a hard
 * instance answerable, only to make the `budget-exhausted` certificate reachable.
 *
 * On success `*out_answer` receives `consistency true|false|unknown` and
 * `*out_certificate` the rendered `purrdf-dl-certificate 1` block, which says
 * whether the search was `decided`, `decided-within-boundaries` (some axiom of the
 * supplied ontology never became a DL clause — the certificate names each
 * construct) or `budget-exhausted`. **Free BOTH with `purrdf_buffer_free`.**
 *
 * This is the only DL service that answers for an unsatisfiable ontology, because
 * it is the one that detects one; every other refuses rather than returning the
 * vacuous answer an ontology with no model gives.
 *
 * # Safety
 * `document` must be a non-null, NUL-terminated C string; `out_answer` and
 * `out_certificate` must be writable pointers; `out_error` must be null or
 * writable.
 */
int32_t purrdf_entail_consistency(const char *document,
                                  uint32_t step_cap,
                                  PurrdfBuffer **out_answer,
                                  PurrdfBuffer **out_certificate,
                                  PurrdfError **out_error);

/**
 * Classify: the entailed subsumption hierarchy over the ontology's named classes.
 *
 * `*out_answer` receives `equivalent`, `subclass`, `direct` and `unsatisfiable`
 * lines (in that block order); `*out_certificate` the `purrdf-dl-certificate 1`
 * block. **Free BOTH with `purrdf_buffer_free`.** `step_cap` behaves exactly as in
 * [`purrdf_entail_consistency`].
 *
 * Costs one tableau decision per ORDERED pair of named classes plus the
 * consistency check, which the certificate's `decisions` line reports so the cost
 * is a measurement rather than a surprise.
 *
 * # Safety
 * As [`purrdf_entail_consistency`].
 */
int32_t purrdf_entail_classify(const char *document,
                               uint32_t step_cap,
                               PurrdfBuffer **out_answer,
                               PurrdfBuffer **out_certificate,
                               PurrdfError **out_error);

/**
 * Realize: the entailed types of the ontology's named individuals, and the most
 * specific of them.
 *
 * `*out_answer` receives `type` lines followed by `direct-type` lines;
 * `*out_certificate` the `purrdf-dl-certificate 1` block. **Free BOTH with
 * `purrdf_buffer_free`.**
 *
 * # Safety
 * As [`purrdf_entail_consistency`].
 */
int32_t purrdf_entail_realize(const char *document,
                              uint32_t step_cap,
                              PurrdfBuffer **out_answer,
                              PurrdfBuffer **out_certificate,
                              PurrdfError **out_error);

/**
 * Instance retrieval: the named individuals entailed to be instances of `class`.
 *
 * `class` is ONE N-Triples term — `<iri>` or `_:label`, angle brackets included. A
 * class the ontology never mentions is not an error: nothing constrains it, so the
 * empty answer for it is a real answer.
 *
 * `*out_answer` receives `instance <term>` lines; `*out_certificate` the
 * `purrdf-dl-certificate 1` block. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `document` and `class` must be non-null, NUL-terminated C strings; `out_answer`
 * and `out_certificate` must be writable pointers; `out_error` must be null or
 * writable.
 */
int32_t purrdf_entail_instances(const char *document,
                                const char *class_,
                                uint32_t step_cap,
                                PurrdfBuffer **out_answer,
                                PurrdfBuffer **out_certificate,
                                PurrdfError **out_error);

/**
 * Axiom entailment: does the ontology entail `axiom`?
 *
 * `axiom` is ONE triple of the OWL 2 RDF mapping, in N-Triples syntax. Seven
 * reserved predicates select the seven named axiom kinds — `rdfs:subClassOf`,
 * `owl:equivalentClass`, `owl:disjointWith`, `rdf:type`, `owl:sameAs`,
 * `owl:differentFrom`, `rdfs:subPropertyOf` — and any other predicate is an
 * object-property assertion. No encoding is invented: this is the mapping the
 * reasoner's own reverse mapping reads.
 *
 * `*out_answer` receives `entails true|false|unknown` and then the axiom as it was
 * READ (`axiom <kind>` plus one `term` line each), so a caller can see which axiom
 * its predicate selected. `*out_certificate` receives the
 * `purrdf-dl-certificate 1` block. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `document` and `axiom` must be non-null, NUL-terminated C strings; `out_answer`
 * and `out_certificate` must be writable pointers; `out_error` must be null or
 * writable.
 */
int32_t purrdf_entail_entails(const char *document,
                              const char *axiom,
                              uint32_t step_cap,
                              PurrdfBuffer **out_answer,
                              PurrdfBuffer **out_certificate,
                              PurrdfError **out_error);

/**
 * Certify the ontology against the OWL 2 profiles.
 *
 * Purely syntactic — no tableau, no closure, no budget — so this is the one
 * reasoning service whose certificate is NOT a `purrdf-dl-certificate`: there is
 * no search whose completeness could be reported, and rendering a fabricated one
 * would be exactly the overclaim the certificates exist to prevent.
 *
 * `*out_answer` receives `certified <profile>` lines, most restrictive first (EL,
 * QL, RL, DL, Full). `*out_certificate` receives the
 * `purrdf-owl-profile-certificate 1` block: every violation with its blocking
 * term, the node it was written on and the reason, a dense `certifies-<profile>`
 * line per profile, and the `one-directional true` gate — a certification PROVES
 * membership, a violation does NOT prove non-membership. **Free BOTH with
 * `purrdf_buffer_free`.**
 *
 * # Safety
 * `document` must be a non-null, NUL-terminated C string; `out_answer` and
 * `out_certificate` must be writable pointers; `out_error` must be null or
 * writable.
 */
int32_t purrdf_entail_profile(const char *document,
                              PurrdfBuffer **out_answer,
                              PurrdfBuffer **out_certificate,
                              PurrdfError **out_error);

/**
 * Extract the locality module of the ontology for a seed signature.
 *
 * `signature` is one N-Triples term per line (blank lines ignored). `method` is
 * `bot`, `top` or `star`; an unknown spelling is refused with the accepted set
 * named.
 *
 * `*out_answer` receives the extracted module as canonical (RDFC-1.0) N-Quads —
 * the same serializer `purrdf_entail_materialize_to_nquads` uses.
 * `*out_certificate` receives the `purrdf-module-extraction 1` block: the method,
 * the axiom count, the signature the fixpoint CLOSED to, every triple kept
 * conservatively, and the `conservative` gate that says whether the module is the
 * minimal one or a sound superset. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `document`, `signature` and `method` must be non-null, NUL-terminated C strings;
 * `out_answer` and `out_certificate` must be writable pointers; `out_error` must
 * be null or writable.
 */
int32_t purrdf_entail_extract_module(const char *document,
                                     const char *signature,
                                     const char *method,
                                     PurrdfBuffer **out_answer,
                                     PurrdfBuffer **out_certificate,
                                     PurrdfError **out_error);

/**
 * Justify a Description-Logic axiom: a minimal subset of the ontology that still
 * entails it.
 *
 * A tableau performs no derivation steps, so this is a JUSTIFICATION and
 * deliberately not called a proof; `purrdf_entail_explain_conclusion` is the chase
 * lane's genuinely derivational explanation, and the two are different kinds of
 * thing rather than two spellings of one.
 *
 * `axiom` is read exactly as `purrdf_entail_entails` reads it.
 *
 * `*out_answer` receives the justification's axioms as canonical (RDFC-1.0)
 * N-Quads — a justification introduces no term, so it is an ordinary RDF 1.2
 * dataset of axioms already present in the input. `*out_certificate` receives the
 * `purrdf-justification 1` block, whose `sufficient` and `minimal` lines are
 * **re-decided** over the justification alone and over each of its
 * one-axiom-smaller subsets, so they check the answer rather than restate it.
 * **Free BOTH with `purrdf_buffer_free`.**
 *
 * An ontology that does not entail the axiom is an error, not an empty
 * justification: the empty set reads as "nothing is needed" and means the
 * opposite.
 *
 * # Safety
 * `document` and `axiom` must be non-null, NUL-terminated C strings; `out_answer`
 * and `out_certificate` must be writable pointers; `out_error` must be null or
 * writable.
 */
int32_t purrdf_entail_justify(const char *document,
                              const char *axiom,
                              PurrdfBuffer **out_answer,
                              PurrdfBuffer **out_certificate,
                              PurrdfError **out_error);

/**
 * Explain one triple of a chase closure: which rules, from which premises.
 *
 * `regime` is one of the same spellings every other entry point accepts.
 * `conclusion` is ONE N-Quads statement; its graph, if it names one, selects the
 * closure to explain.
 *
 * `*out_answer` receives `asserted`, `steps` and one `rule` line per cited rule.
 * `*out_certificate` receives the `purrdf-chase-proof 1` block, whose `derived-*`
 * lines are what the CHECKER re-derived from the proof term and the clause
 * program — not what the proof claims — so a proof whose stated conclusion its own
 * premises do not license shows up as differing lines rather than a silent
 * `checked true`. **Free BOTH with `purrdf_buffer_free`.**
 *
 * `rdf` and `rdfs` are refused by name: four of their rules conclude about a FRESH
 * blank node, an existential head has no Datalog semantics, and a "proof" of such
 * a step could only be believed.
 *
 * # Safety
 * `document`, `regime` and `conclusion` must be non-null, NUL-terminated C
 * strings; `out_answer` and `out_certificate` must be writable pointers;
 * `out_error` must be null or writable.
 */
int32_t purrdf_entail_explain_conclusion(const char *document,
                                         const char *regime,
                                         const char *conclusion,
                                         PurrdfBuffer **out_answer,
                                         PurrdfBuffer **out_certificate,
                                         PurrdfError **out_error);

/**
 * The certain answers of a basic graph pattern under an entailment regime.
 *
 * A certain answer is a substitution the knowledge base ENTAILS the pattern under —
 * true in every model, not merely present in one closure — which is what SPARQL's
 * entailment regimes define the answers to a basic graph pattern to be.
 *
 * `regime` is one of the same spellings every other entry point accepts, minus the two
 * this service is not total over: `owl-direct` is query-directed and `rif` entails under
 * a rule document, and each is defined by an input this signature does not carry, so
 * both are refused by name rather than served by a weaker lane.
 *
 * `pattern` is N-Triples with `?name` in any position. A blank node in it is a
 * NON-DISTINGUISHED variable — constrained by the match, not projected, and not a
 * column — which is what SPARQL says a query blank node is.
 *
 * `*out_answer` receives `mechanism`, one `var` line per projected variable, one `row`
 * line per certain answer, and a `limit` line per reason the row set may not be
 * EXHAUSTIVE. Every row is sound unconditionally; what needs a precondition is the claim
 * about a row that is NOT there, so no `limit` lines is the claim that the row set is
 * complete. `*out_certificate` receives the run's `purrdf-reasoning-report 4` block.
 * **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `regime`, `document` and `pattern` must be non-null, NUL-terminated C strings;
 * `out_answer` and `out_certificate` must be writable pointers; `out_error` must be null
 * or writable.
 */
int32_t purrdf_entail_certain_answers(const char *regime,
                                      const char *document,
                                      const char *pattern,
                                      PurrdfBuffer **out_answer,
                                      PurrdfBuffer **out_certificate,
                                      PurrdfError **out_error);

/**
 * Does `premise` entail the conclusion GRAPH under `regime`'s rule table?
 *
 * NOT `purrdf_entail_entails`, which asks the OWL 2 Direct-Semantics TABLEAU about one
 * AXIOM and renders a `purrdf-dl-certificate 1` block. This asks the regime's RULE TABLE
 * about a conclusion GRAPH and renders a `purrdf-reasoning-report 4` one. Different
 * question, different calculus, different certificate — and the two banners differ so
 * neither can be parsed as the other.
 *
 * `*out_answer` opens `mechanism <name>`: WHICH of the seven mechanisms reached the
 * verdict. `strict-table` is the regime's own rule table, run once, with the conclusion
 * matched into (or proven absent from) its closure; the other five —  `refutation`,
 * `freeze`, `comprehension`, `reflexivity`, `data-range` — exist because no head in that
 * table has the conclusion's shape at all. `composite` is two or more of those folded over
 * one conclusion, which a conjunction can need and which is spelled that way rather than by
 * any one constituent's name. The name is the canonical spelling and never an enum ordinal,
 * so an eighth mechanism cannot renumber a reading of an old one.
 *
 * Then THREE verdicts, never two: `entailment entailed` (with one `binding` line per
 * existential of the conclusion), `entailment not-entailed` (a PROOF — the procedure was
 * complete for this premise — with a `miss` line), or `entailment undecided` (what an
 * incomplete procedure is entitled to say instead, with an `undecided` line naming which
 * hypothesis of which theorem the input broke). Reading the third as the second would
 * turn a limitation of this library into a false statement about the caller's data.
 * **Free BOTH buffers with `purrdf_buffer_free`.**
 *
 * # Safety
 * `regime`, `premise` and `conclusion` must be non-null, NUL-terminated C strings;
 * `out_answer` and `out_certificate` must be writable pointers; `out_error` must be null
 * or writable.
 */
int32_t purrdf_entail_graph_entails(const char *regime,
                                    const char *premise,
                                    const char *conclusion,
                                    PurrdfBuffer **out_answer,
                                    PurrdfBuffer **out_certificate,
                                    PurrdfError **out_error);

/**
 * `purrdf_entail_graph_entails` with the warrant RE-DECIDED, without running a reasoner.
 *
 * The re-check re-derives nothing, deliberately: "the closure follows from the premise"
 * is the chase's claim and `purrdf_entail_explain_conclusion` is its checker, while "the
 * conclusion follows from the closure" is this one and is finite and purely
 * combinatorial — a graph homomorphism, or a set of lookups against a refutation's own
 * closure. Folding them would cost what the original call cost and give a caller no
 * independent check at all.
 *
 * `*out_answer` is `purrdf_entail_graph_entails`'s, plus `warrant present|absent` and
 * `verified true|false|not-applicable`. `warrant absent` / `verified not-applicable` is
 * a `not-entailed` or an `undecided`: there is no evidence to re-decide, and a `false`
 * there would read as a failed check rather than as an absent one.
 * **Free BOTH buffers with `purrdf_buffer_free`.**
 *
 * # Safety
 * `regime`, `premise` and `conclusion` must be non-null, NUL-terminated C strings;
 * `out_answer` and `out_certificate` must be writable pointers; `out_error` must be null
 * or writable.
 */
int32_t purrdf_entail_verify_entailment(const char *regime,
                                        const char *premise,
                                        const char *conclusion,
                                        PurrdfBuffer **out_answer,
                                        PurrdfBuffer **out_certificate,
                                        PurrdfError **out_error);

/**
 * Open a reasoning session over `document`.
 *
 * `step_cap` narrows the per-decision tableau step cap for every question asked through
 * this session, and behaves exactly as in [`purrdf_entail_consistency`]: **0 means the
 * knowledge base's own cap**, not a cap of zero steps, and it can only NARROW.
 *
 * On success `*out_reasoner` receives a handle to free with [`purrdf_reasoner_free`].
 *
 * Nothing is reverse-mapped here, so an ontology whose knowledge base cannot be built
 * still opens — and fails on the first question that needs one, with that question's own
 * error. That is deliberate: `profile`, `extract_module`, `justify` and
 * `explain_conclusion` never reason, and `profile` answers for any parseable document.
 *
 * # Safety
 * `document` must be a non-null, NUL-terminated C string; `out_reasoner` must be a
 * writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_reasoner_open(const char *document,
                             uint32_t step_cap,
                             PurrdfReasoner **out_reasoner,
                             PurrdfError **out_error);

/**
 * Release a reasoning session. No-op on null.
 *
 * # Safety
 * `reasoner` must be null or a live session handle not already freed.
 */
void purrdf_reasoner_free(PurrdfReasoner *reasoner);

/**
 * Is the knowledge base consistent? See [`purrdf_entail_consistency`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_consistency`] writes
 * for the same document. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `out_answer` and `out_certificate` must be
 * writable pointers; `out_error` must be null or writable.
 */
int32_t purrdf_reasoner_consistency(PurrdfReasoner *reasoner,
                                    PurrdfBuffer **out_answer,
                                    PurrdfBuffer **out_certificate,
                                    PurrdfError **out_error);

/**
 * The entailed subsumption hierarchy. See [`purrdf_entail_classify`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_classify`] writes
 * for the same document. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `out_answer` and `out_certificate` must be
 * writable pointers; `out_error` must be null or writable.
 */
int32_t purrdf_reasoner_classify(PurrdfReasoner *reasoner,
                                 PurrdfBuffer **out_answer,
                                 PurrdfBuffer **out_certificate,
                                 PurrdfError **out_error);

/**
 * The entailed types of the named individuals. See [`purrdf_entail_realize`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_realize`] writes
 * for the same document. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `out_answer` and `out_certificate` must be
 * writable pointers; `out_error` must be null or writable.
 */
int32_t purrdf_reasoner_realize(PurrdfReasoner *reasoner,
                                PurrdfBuffer **out_answer,
                                PurrdfBuffer **out_certificate,
                                PurrdfError **out_error);

/**
 * The individuals entailed to be instances of `class`. See [`purrdf_entail_instances`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_instances`] writes for
 * the same document and `class`. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `class` must be a non-null, NUL-terminated C
 * string; `out_answer` and `out_certificate` must be writable pointers; `out_error` must
 * be null or writable.
 */
int32_t purrdf_reasoner_instances(PurrdfReasoner *reasoner,
                                  const char *class_,
                                  PurrdfBuffer **out_answer,
                                  PurrdfBuffer **out_certificate,
                                  PurrdfError **out_error);

/**
 * Does the ontology entail `axiom`? See [`purrdf_entail_entails`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_entails`] writes for
 * the same document and `axiom`. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `axiom` must be a non-null, NUL-terminated C
 * string; `out_answer` and `out_certificate` must be writable pointers; `out_error` must
 * be null or writable.
 */
int32_t purrdf_reasoner_entails(PurrdfReasoner *reasoner,
                                const char *axiom,
                                PurrdfBuffer **out_answer,
                                PurrdfBuffer **out_certificate,
                                PurrdfError **out_error);

/**
 * A justification for `axiom`. See [`purrdf_entail_justify`].
 *
 * `*out_answer` and `*out_certificate` are exactly what [`purrdf_entail_justify`] writes for
 * the same document and `axiom`. **Free BOTH with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `axiom` must be a non-null, NUL-terminated C
 * string; `out_answer` and `out_certificate` must be writable pointers; `out_error` must
 * be null or writable.
 */
int32_t purrdf_reasoner_justify(PurrdfReasoner *reasoner,
                                const char *axiom,
                                PurrdfBuffer **out_answer,
                                PurrdfBuffer **out_certificate,
                                PurrdfError **out_error);

/**
 * Which OWL 2 profiles the ontology is provably in. See [`purrdf_entail_profile`].
 *
 * Purely syntactic: never builds a knowledge base, so it answers even for an ontology
 * whose other services would fail. **Free BOTH buffers with `purrdf_buffer_free`.**
 *
 * # Safety
 * As the other session services.
 */
int32_t purrdf_reasoner_profile(const PurrdfReasoner *reasoner,
                                PurrdfBuffer **out_answer,
                                PurrdfBuffer **out_certificate,
                                PurrdfError **out_error);

/**
 * A module for `signature` under `method`. See [`purrdf_entail_extract_module`].
 *
 * **Free BOTH buffers with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `signature` and `method` must be non-null,
 * NUL-terminated C strings; the out-params must be writable.
 */
int32_t purrdf_reasoner_extract_module(const PurrdfReasoner *reasoner,
                                       const char *signature,
                                       const char *method,
                                       PurrdfBuffer **out_answer,
                                       PurrdfBuffer **out_certificate,
                                       PurrdfError **out_error);

/**
 * Why `conclusion` holds under `regime`. See [`purrdf_entail_explain_conclusion`].
 *
 * **Free BOTH buffers with `purrdf_buffer_free`.**
 *
 * # Safety
 * `reasoner` must be a live session handle; `regime` and `conclusion` must be non-null,
 * NUL-terminated C strings; the out-params must be writable.
 */
int32_t purrdf_reasoner_explain_conclusion(const PurrdfReasoner *reasoner,
                                           const char *regime,
                                           const char *conclusion,
                                           PurrdfBuffer **out_answer,
                                           PurrdfBuffer **out_certificate,
                                           PurrdfError **out_error);

/**
 * Return the status code carried by an error, or `Panic` if `err` is null.
 *
 * # Safety
 * `err` must be null or a pointer returned by a libpurrdf entry point and not
 * yet freed.
 */
int32_t purrdf_error_code(const PurrdfError *err);

/**
 * Return the borrowed, NUL-terminated message of an error. Valid until
 * `purrdf_error_free(err)`. Returns null if `err` is null.
 *
 * # Safety
 * Same contract as [`purrdf_error_code`].
 */
const char *purrdf_error_message(const PurrdfError *err);

/**
 * Release an error handle. No-op on null. Idempotent only in the sense that the
 * caller must not pass the same non-null pointer twice.
 *
 * # Safety
 * `err` must be null or a pointer returned by a libpurrdf entry point and not
 * already freed.
 */
void purrdf_error_free(PurrdfError *err);

/**
 * Branch a single-threaded mutable COW graph off a frozen dataset. `*out_graph`
 * is a caller-owned handle (free with `purrdf_graph_free`); the source dataset
 * is unaffected and may be freed independently.
 *
 * # Safety
 * `dataset` must be a live handle; `out_graph` must be writable.
 */
int32_t purrdf_graph_from_dataset(const PurrdfDataset *dataset, PurrdfGraph **out_graph);

/**
 * Insert a value-quad into the effective set. `s`/`p`/`o` are required input
 * term views; `g` may be null (default graph). `out_changed` (nullable)
 * receives `1` if the effective set changed, else `0` (an already-present quad
 * is a no-op; inserting a previously-removed base quad un-suppresses it).
 *
 * # Safety
 * `graph` must be a live handle; the view pointers must be valid where
 * non-null; the out-params must be writable.
 */
int32_t purrdf_graph_insert(PurrdfGraph *graph,
                            const PurrdfTermView *s,
                            const PurrdfTermView *p,
                            const PurrdfTermView *o,
                            const PurrdfTermView *g,
                            uint8_t *out_changed,
                            PurrdfError **out_error);

/**
 * Remove a value-quad from the effective set. Removing a delta-added quad drops
 * it; removing a base quad creates a suppression. `out_changed` (nullable)
 * receives `1` if the effective set changed.
 *
 * # Safety
 * Same contract as [`purrdf_graph_insert`].
 */
int32_t purrdf_graph_remove(PurrdfGraph *graph,
                            const PurrdfTermView *s,
                            const PurrdfTermView *p,
                            const PurrdfTermView *o,
                            const PurrdfTermView *g,
                            uint8_t *out_changed,
                            PurrdfError **out_error);

/**
 * Compact the COW delta into a fresh frozen dataset. The graph remains valid
 * (free it separately with `purrdf_graph_free`). `*out_dataset` is a
 * caller-owned handle.
 *
 * # Safety
 * `graph` must be a live handle; `out_dataset` must be writable.
 */
int32_t purrdf_graph_freeze(const PurrdfGraph *graph,
                            PurrdfDataset **out_dataset,
                            PurrdfError **out_error);

/**
 * Release a graph handle. No-op on null.
 *
 * # Safety
 * `graph` must be null or a live graph handle not already freed.
 */
void purrdf_graph_free(PurrdfGraph *graph);

/**
 * Read a GTS container into a fresh frozen dataset. `*out_dataset` is a
 * caller-owned handle (free with `purrdf_dataset_free`).
 *
 * **Lossless**, including the RDF-1.2 statement layer: a reifier-bound quoted
 * triple written by `to_gts` is read back intact via the canonical fold-back
 * (`read_graph` → `import_gts_graph`). The earlier `gts-missing-reifier-binding`
 * gap was closed by the native text-codec work.
 *
 * # Safety
 * `bytes` must be valid for `len` bytes; the out-params must be writable.
 */
int32_t purrdf_from_gts(const uint8_t *bytes,
                        size_t len,
                        PurrdfDataset **out_dataset,
                        PurrdfError **out_error);

/**
 * Write a frozen dataset to canonical GTS container bytes under `profile`
 * (e.g. `"dist"`). The output goes to `*out_buffer` (free with
 * `purrdf_buffer_free`).
 *
 * # Safety
 * `dataset` must be a live handle; `profile` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_to_gts(const PurrdfDataset *dataset,
                      const char *profile,
                      PurrdfBuffer **out_buffer,
                      PurrdfError **out_error);

/**
 * Release a dataset handle. No-op on null.
 *
 * # Safety
 * `dataset` must be null or a live dataset handle not already freed.
 */
void purrdf_dataset_free(PurrdfDataset *dataset);

/**
 * Write the number of quads in the dataset to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_dataset_quad_count(const PurrdfDataset *dataset, size_t *out);

/**
 * Write the number of interned terms in the dataset to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_dataset_term_count(const PurrdfDataset *dataset, size_t *out);

/**
 * Parse `len` bytes of `media_type` (e.g. `"text/turtle"`, `"application/n-quads"`)
 * into a fresh frozen dataset. `base_iri` and `source_name` may be null. On
 * success `*out_dataset` is a caller-owned handle (free with
 * `purrdf_dataset_free`); on failure `*out_error` is set.
 *
 * # Safety
 * `bytes` must be valid for `len` bytes; the `c_char` pointers must be null or
 * NUL-terminated; the out-params must be writable.
 */
int32_t purrdf_parse(const uint8_t *bytes,
                     size_t len,
                     const char *media_type,
                     const char *base_iri,
                     const char *source_name,
                     PurrdfDataset **out_dataset,
                     PurrdfError **out_error);

/**
 * Project a frozen RDF dataset into a canonical deterministic USTAR carrier.
 *
 * `profile` is a NUL-terminated projection profile name. `config_json` is the
 * mandatory profile-tagged configuration and must be valid for `config_len`
 * bytes. On success, `*out_archive` and `*out_loss_ledger_json` are independent
 * caller-owned buffers released with `purrdf_buffer_free`. The loss ledger is
 * always computed and uses PurRDF's versioned canonical JSON schema.
 * Research-object profiles are `croissant-1.1`, `ro-crate-1.3`,
 * `datacite-4.6`, `dcat-3`, and `frictionless-data-package-1`. The `dcat-rdf`
 * dataset-description view and `void` are also available as write-only profiles.
 *
 * # Safety
 * `dataset` must be a live handle; `profile` must be a valid C string;
 * `config_json` must be readable for `config_len` bytes; the two output pointers
 * must be non-null, distinct, and writable. `out_error` may be null or writable.
 */
int32_t purrdf_project(const PurrdfDataset *dataset,
                       const char *profile,
                       const uint8_t *config_json,
                       size_t config_len,
                       PurrdfBuffer **out_archive,
                       PurrdfBuffer **out_loss_ledger_json,
                       PurrdfError **out_error);

/**
 * Project a frozen RDF dataset and payload-only USTAR into an attached RO-Crate.
 *
 * `assets_archive` is a canonical PurRDF USTAR containing payload members only;
 * metadata and preview names are reserved to the engine. The profile and tagged
 * configuration must select attached `ro-crate-1.3` packaging. Output ownership
 * matches [`purrdf_project`].
 *
 * # Safety
 * `dataset` must be a live handle; `profile` must be a valid C string;
 * `config_json` and `assets_archive` must be readable for their respective lengths;
 * the two output pointers must be non-null, distinct, and writable. `out_error` may
 * be null or writable.
 */
int32_t purrdf_project_with_assets(const PurrdfDataset *dataset,
                                   const char *profile,
                                   const uint8_t *config_json,
                                   size_t config_len,
                                   const uint8_t *assets_archive,
                                   size_t assets_len,
                                   PurrdfBuffer **out_archive,
                                   PurrdfBuffer **out_loss_ledger_json,
                                   PurrdfError **out_error);

/**
 * Lift a canonical USTAR carrier into a fresh frozen RDF dataset.
 *
 * Only the closed bidirectional profiles are accepted; curated CSVW terms, OBO
 * Graphs, and SKOS fail as invalid arguments instead of pretending to round-trip.
 * All five research-object profiles are bidirectional. On success,
 * `*out_dataset` is released with `purrdf_dataset_free` and
 * `*out_loss_ledger_json` with `purrdf_buffer_free`.
 *
 * # Safety
 * `archive` and `config_json` must be readable for their respective lengths;
 * `profile` must be a valid C string; output pointers must be non-null and
 * writable. `out_error` may be null or writable.
 */
int32_t purrdf_lift(const uint8_t *archive,
                    size_t archive_len,
                    const char *profile,
                    const uint8_t *config_json,
                    size_t config_len,
                    PurrdfDataset **out_dataset,
                    PurrdfBuffer **out_loss_ledger_json,
                    PurrdfError **out_error);

/**
 * Execute a SPARQL query. The result shape is reported in `*out_kind`:
 * `0` = SELECT → `*out_rows` is a `PurrdfRowCursor` (free with
 * `purrdf_rowcursor_free`); `1` = CONSTRUCT/DESCRIBE → `*out_graph` is a
 * `PurrdfDataset` (free with `purrdf_dataset_free`); `2` = ASK → `*out_boolean`
 * is `0`/`1`. Exactly one output is set per kind. `base_iri` may be null.
 *
 * # Safety
 * `dataset` must be a live handle; `query` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_query(const PurrdfDataset *dataset,
                     const char *query,
                     const char *base_iri,
                     int32_t *out_kind,
                     PurrdfRowCursor **out_rows,
                     PurrdfDataset **out_graph,
                     uint8_t *out_boolean,
                     PurrdfError **out_error);

/**
 * Execute a SPARQL query and serialize the result to the SPARQL 1.1 Query
 * Results JSON format (SELECT and ASK) into `*out_buffer` (UTF-8). A
 * CONSTRUCT/DESCRIBE graph is rendered as N-Triples inside a documented
 * `{"graph": "..."}` envelope. The simple/robust path — no row cursor needed.
 *
 * # Safety
 * `dataset` must be a live handle; `query` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_query_json(const PurrdfDataset *dataset,
                          const char *query,
                          const char *base_iri,
                          PurrdfBuffer **out_buffer,
                          PurrdfError **out_error);

/**
 * Write the number of result variables (columns) to `*out`.
 *
 * # Safety
 * `rc` must be a live row cursor; `out` must be writable.
 */
int32_t purrdf_rowcursor_variable_count(const PurrdfRowCursor *rc, size_t *out);

/**
 * Write a borrowed, NUL-terminated variable name for column `i` to `*out`.
 * Valid until `purrdf_rowcursor_free`. `InvalidArgument` if `i` is out of range.
 *
 * # Safety
 * `rc` must be a live row cursor; `out` must be writable.
 */
int32_t purrdf_rowcursor_variable_name(const PurrdfRowCursor *rc, size_t i, const char **out);

/**
 * Advance to the next solution row. Returns `PurrdfStatus::CursorExhausted`
 * (a non-error terminal signal, `> 0`) when no rows remain.
 *
 * # Safety
 * `rc` must be a live row cursor.
 */
int32_t purrdf_rowcursor_next(PurrdfRowCursor *rc);

/**
 * Read the term in `column` of the CURRENT row. `out_bound` receives `0` when
 * the variable is UNBOUND in this row (the view is then a zeroed placeholder),
 * else `1`. The view's `PurrdfStr` pointers are valid until the next
 * `purrdf_rowcursor_next` or `purrdf_rowcursor_free`. `InvalidArgument` if no
 * row is current (call `_next` first) or `column` is out of range.
 *
 * # Safety
 * `rc` must be a live row cursor; the out-params must be writable.
 */
int32_t purrdf_rowcursor_term(const PurrdfRowCursor *rc,
                              size_t column,
                              PurrdfTermView *out_view,
                              uint8_t *out_bound);

/**
 * Release a row cursor handle. No-op on null.
 *
 * # Safety
 * `rc` must be null or a live row cursor not already freed.
 */
void purrdf_rowcursor_free(PurrdfRowCursor *rc);

/**
 * Compile a reusable context from a versioned JSON-LD options document.
 *
 * # Safety
 * `options_json` must point to `options_len` readable bytes; the output pointers
 * must be writable. On success, free `*out_context` with
 * `purrdf_jsonld_context_free`.
 */
int32_t purrdf_jsonld_context_compile(const uint8_t *options_json,
                                      size_t options_len,
                                      PurrdfJsonLdContext **out_context,
                                      PurrdfError **out_error);

/**
 * Release a compiled JSON-LD context handle. No-op on null.
 *
 * # Safety
 * `context` must be null or a live handle not already freed.
 */
void purrdf_jsonld_context_free(PurrdfJsonLdContext *context);

/**
 * Serialize JSON-LD or YAML-LD with exactly one versioned options document or
 * reusable compiled context. `yaml_schema_url` may be null and overrides the
 * options document for YAML-LD when supplied.
 *
 * # Safety
 * `dataset` and `media_type` must be live/non-null. If `options_json` is not
 * null it points to `options_len` readable bytes and `context` must be null; if
 * `options_json` is null, `options_len` must be zero and `context` must be live.
 * Output pointers must be writable.
 */
int32_t purrdf_serialize_jsonld_configured(const PurrdfDataset *dataset,
                                           const char *media_type,
                                           const uint8_t *options_json,
                                           size_t options_len,
                                           const PurrdfJsonLdContext *context,
                                           const char *yaml_schema_url,
                                           PurrdfBuffer **out_buffer,
                                           PurrdfError **out_error);

/**
 * Serialize the frozen dataset to `media_type` (e.g. `"text/turtle"`,
 * `"application/n-quads"`). `base_iri` may be null. The output bytes go to
 * `*out_buffer` (free with `purrdf_buffer_free`). When `out_statement_rows_dropped`
 * is non-null it receives the number of RDF-1.2 statement-layer rows dropped
 * because the target format cannot represent quoted triples (`0` for
 * star-capable formats) — so the caller can detect lossy projection.
 *
 * # Safety
 * `dataset` must be a live handle; the `c_char` pointers must be null or
 * NUL-terminated; the out-params must be writable.
 */
int32_t purrdf_serialize(const PurrdfDataset *dataset,
                         const char *media_type,
                         const char *base_iri,
                         PurrdfBuffer **out_buffer,
                         size_t *out_statement_rows_dropped,
                         PurrdfError **out_error);

/**
 * Validate a data graph (N-Triples) against a shapes graph (Turtle) and write
 * the SARIF 2.1.0 report bytes to `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * # Safety
 * `shapes_ttl` and `data_nt` must be non-null, NUL-terminated C strings;
 * `out_buffer` must be a writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_shacl_validate_to_sarif(const char *shapes_ttl,
                                       const char *data_nt,
                                       PurrdfBuffer **out_buffer,
                                       PurrdfError **out_error);

/**
 * Entail a data graph (N-Triples) under a shapes graph (Turtle) and write the
 * materialized dataset (base graph plus every inferred triple) as canonical
 * N-Triples bytes to `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * # Safety
 * `shapes_ttl` and `data_nt` must be non-null, NUL-terminated C strings;
 * `out_buffer` must be a writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_shacl_entail_to_ntriples(const char *shapes_ttl,
                                        const char *data_nt,
                                        PurrdfBuffer **out_buffer,
                                        PurrdfError **out_error);

/**
 * Render a single term view to one N-Triples term token (e.g. `<iri>`, `_:b`,
 * `"lex"^^<dt>`, or `<<( s p o )>>` for a non-asserting quoted-triple term)
 * into `*out_buffer` (UTF-8, no trailing dot). When the view carries a dataset
 * `term_id`, the term is resolved against `dataset` (so quoted triples
 * materialize recursively); otherwise the token is built from the view fields
 * (non-triple only).
 *
 * # Safety
 * `dataset` must be the live handle the view's `term_id` came from (when
 * non-zero); `view` and the out-params must be valid.
 */
int32_t purrdf_term_to_ntriples(const PurrdfDataset *dataset,
                                const PurrdfTermView *view,
                                PurrdfBuffer **out_buffer,
                                PurrdfError **out_error);

/**
 * Write the libpurrdf ABI version to `*out`.
 *
 * # Safety
 * `out` must be null-checked-writable for one `PurrdfAbiVersion`.
 */
int32_t purrdf_abi_version(PurrdfAbiVersion *out);

/**
 * Write the dataset's capability flags to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_capabilities(const PurrdfDataset *dataset, PurrdfCapabilities *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PURRDF_H */
