/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/* libpurrdf — the PURRDF purrdf semantic RDF-1.2 C-ABI. */
/* GENERATED by cbindgen; do not edit. Edit crates/rdf-capi and regenerate. */

#ifndef PURRDF_H
#define PURRDF_H

#pragma once

/* WARNING: generated file — edit crates/rdf-capi instead. */
#define PURRDF_MAJOR 0
#define PURRDF_MINOR 4
#define PURRDF_PATCH 3


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI major version. `0` signals the surface is still **beta** — the freeze
 * discipline (append-only status enum, drift-gated header) is in place, but the
 * version stays pre-1.0 until a real C consumer + the rdflib shim exercise it.
 */
#define PURRDF_ABI_MAJOR 0

/**
 * ABI minor version.
 */
#define PURRDF_ABI_MINOR 1

/**
 * ABI patch version.
 */
#define PURRDF_ABI_PATCH 0

/**
 * Status returned by every fallible entry point as `i32`. `Ok == 0`.
 *
 * Append-only: never renumber a variant. `Panic` is parked at 100 to leave room
 * for ordinary status codes to grow contiguously from 10.
 */
enum PurrdfStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Success.
     */
    PURRDF_STATUS_OK = 0,
    /**
     * A required pointer argument was null.
     */
    PURRDF_STATUS_NULL_POINTER = 1,
    /**
     * A C string argument was not valid UTF-8.
     */
    PURRDF_STATUS_INVALID_UTF8 = 2,
    /**
     * An argument was structurally invalid (e.g. an unknown enum tag).
     */
    PURRDF_STATUS_INVALID_ARGUMENT = 3,
    /**
     * The requested media type / format id is not supported.
     */
    PURRDF_STATUS_UNSUPPORTED_FORMAT = 4,
    /**
     * Parsing the input bytes failed.
     */
    PURRDF_STATUS_PARSE_ERROR = 5,
    /**
     * Serializing the dataset failed.
     */
    PURRDF_STATUS_SERIALIZE_ERROR = 6,
    /**
     * Evaluating the SPARQL query failed.
     */
    PURRDF_STATUS_QUERY_ERROR = 7,
    /**
     * Freezing a mutable graph into a dataset failed.
     */
    PURRDF_STATUS_FREEZE_ERROR = 8,
    /**
     * A cursor has no more rows (a non-error terminal signal, returned > 0).
     */
    PURRDF_STATUS_CURSOR_EXHAUSTED = 9,
    /**
     * A GTS container read/write operation failed.
     */
    PURRDF_STATUS_GTS_ERROR = 10,
    /**
     * A panic was caught at the FFI boundary (should never reach the caller in
     * normal operation).
     */
    PURRDF_STATUS_PANIC = 100,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfStatus PurrdfStatus;
#else
typedef int32_t PurrdfStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The kind tag of a [`PurrdfTermView`].
 *
 * These are the canonical discriminant values for the `int32_t kind` field of
 * [`PurrdfTermView`]. An unknown value in that field yields
 * [`PurrdfStatus::InvalidArgument`] — never UB.
 */
enum PurrdfTermKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * An IRI; `lexical` is the IRI string.
     */
    PURRDF_TERM_KIND_IRI = 0,
    /**
     * A blank node; `lexical` is the label, `blank_scope` the scope ordinal.
     */
    PURRDF_TERM_KIND_BLANK = 1,
    /**
     * A literal; `lexical`/`datatype`/`language`/`direction` are meaningful.
     */
    PURRDF_TERM_KIND_LITERAL = 2,
    /**
     * An RDF-1.2 quoted triple; `lexical` is empty — materialize the components
     * via `purrdf_term_to_ntriples` using this view's `term_id`.
     */
    PURRDF_TERM_KIND_TRIPLE = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfTermKind PurrdfTermKind;
#else
typedef int32_t PurrdfTermKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The optional base direction of a literal (RDF-1.2 `i18n` direction).
 *
 * These are the canonical discriminant values for the `int32_t direction` field
 * of [`PurrdfTermView`]. An unknown value yields [`PurrdfStatus::InvalidArgument`]
 * — never UB.
 */
enum PurrdfDirection
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * No base direction.
     */
    PURRDF_DIRECTION_NONE = 0,
    /**
     * Left-to-right.
     */
    PURRDF_DIRECTION_LTR = 1,
    /**
     * Right-to-left.
     */
    PURRDF_DIRECTION_RTL = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfDirection PurrdfDirection;
#else
typedef int32_t PurrdfDirection;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The kind tag of a [`PurrdfGraphMatch`].
 *
 * These are the canonical discriminant values for the `int32_t kind` field of
 * [`PurrdfGraphMatch`]. An unknown value yields [`PurrdfStatus::InvalidArgument`]
 * — never UB.
 */
enum PurrdfGraphMatchKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Match any graph (default or named).
     */
    PURRDF_GRAPH_MATCH_KIND_ANY = 0,
    /**
     * Match only the default graph.
     */
    PURRDF_GRAPH_MATCH_KIND_DEFAULT = 1,
    /**
     * Match the named graph given by `name`.
     */
    PURRDF_GRAPH_MATCH_KIND_NAMED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PurrdfGraphMatchKind PurrdfGraphMatchKind;
#else
typedef int32_t PurrdfGraphMatchKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An owned byte buffer. Opaque to C; read via `purrdf_buffer_data`, release
 * with `purrdf_buffer_free`.
 */
typedef struct PurrdfBuffer PurrdfBuffer;

/**
 * A pattern-quad cursor. It holds an `Arc<RdfDataset>` clone (`pin`) so the
 * term arena the views borrow into cannot dangle — the cursor stays valid even
 * after every `PurrdfDataset` handle is freed. The matching rows are snapshot
 * into an owned `Vec<QuadIds>` at creation (no live iterator, so no
 * self-referential borrow). Single-threaded.
 */
typedef struct PurrdfCursor PurrdfCursor;

/**
 * A frozen, immutable RDF-1.2 dataset. Wraps `Arc<RdfDataset>`, so it is
 * `Send + Sync`: it may be read concurrently from multiple threads. Release
 * with `purrdf_dataset_free`.
 */
typedef struct PurrdfDataset PurrdfDataset;

/**
 * An owned error: a status code plus a NUL-terminated message. Opaque to C.
 */
typedef struct PurrdfError PurrdfError;

/**
 * A copy-on-write mutable graph: a suppression-delta over a frozen base
 * dataset. Single-threaded mutable — NOT `Sync`; do not touch one from two
 * threads. Release with `purrdf_graph_free`.
 */
typedef struct PurrdfGraph PurrdfGraph;

/**
 * A SPARQL SELECT result cursor. Owns its variable names and solution rows
 * (dataset-independent `TermValue`s).
 *
 * **Lifetime invariant (load-bearing):** `rows` is IMMUTABLE for the cursor's
 * whole life — `purrdf_rowcursor_next` only advances `current`, never mutates,
 * reorders, or reallocates the `Vec`. A `PurrdfStr` returned by
 * `purrdf_rowcursor_term` borrows directly into `rows[current]`'s owned
 * `TermValue`; those pointers stay valid for the cursor's life (documented
 * conservatively as "until the next `_next`/`_free`"). The C side never frees a
 * `PurrdfStr.ptr`. Single-threaded.
 */
typedef struct PurrdfRowCursor PurrdfRowCursor;

/**
 * A borrowed UTF-8 slice. `ptr` is **not** NUL-terminated — use `len`. The
 * memory is owned by libpurrdf; the C side must **never** `free()` it. As an
 * output, a view's pointers are valid only until the next `*_cursor_next` /
 * `*_rowcursor_next` on the same cursor, or until the owning handle is freed.
 * As an input, the caller owns the bytes and they need only outlive the call.
 * `ptr` may be null when `len == 0`.
 */
typedef struct {
    /**
     * Pointer to the first byte (borrowed; never freed by the other side).
     */
    const uint8_t *ptr;
    /**
     * Length in bytes.
     */
    size_t len;
} PurrdfStr;

/**
 * A structured, borrowed term view. Which fields are meaningful depends on
 * `kind` (see [`PurrdfTermKind`]). All `PurrdfStr` fields follow the borrowing
 * contract on [`PurrdfStr`]. `term_id` is the dataset-local opaque id of the
 * term (`0` when the view was not produced from an interned dataset term, e.g.
 * a SPARQL solution value); it is meaningful ONLY against the dataset that
 * produced the view and must never be compared across datasets.
 *
 * `kind` is an `int32_t` carrying a [`PurrdfTermKind`] discriminant (0–3).
 * `direction` is an `int32_t` carrying a [`PurrdfDirection`] discriminant (0–2).
 * An unknown value in either field yields [`PurrdfStatus::InvalidArgument`] —
 * never undefined behaviour.
 */
typedef struct {
    /**
     * The term kind tag (`int32_t`; see [`PurrdfTermKind`] for valid values).
     * An unknown discriminant yields `PurrdfStatus::InvalidArgument`, not UB.
     */
    int32_t kind;
    /**
     * IRI string / blank label / literal lexical form (empty for `Triple`).
     */
    PurrdfStr lexical;
    /**
     * Datatype IRI (`Literal` only; empty otherwise).
     */
    PurrdfStr datatype;
    /**
     * Language tag (`Literal` only; empty when absent).
     */
    PurrdfStr language;
    /**
     * Base direction (`int32_t`; see [`PurrdfDirection`] for valid values;
     * `Literal` only). An unknown discriminant yields `PurrdfStatus::InvalidArgument`,
     * not UB.
     */
    int32_t direction;
    /**
     * Blank-node scope ordinal (`Blank` only).
     */
    uint32_t blank_scope;
    /**
     * Dataset-local opaque term id (`0` = none). See the struct docs.
     */
    uint32_t term_id;
} PurrdfTermView;

/**
 * A graph-slot match passed by value into `purrdf_quads_for_pattern`. For
 * `Named`, `name` is an **input** term view the caller fills.
 *
 * `kind` is an `int32_t` carrying a [`PurrdfGraphMatchKind`] discriminant (0–2).
 * An unknown value yields [`PurrdfStatus::InvalidArgument`] — never UB.
 */
typedef struct {
    /**
     * Which graphs to match (`int32_t`; see [`PurrdfGraphMatchKind`] for valid
     * values). An unknown discriminant yields `PurrdfStatus::InvalidArgument`, not UB.
     */
    int32_t kind;
    /**
     * The named-graph term (meaningful only when `kind == Named`).
     */
    PurrdfTermView name;
} PurrdfGraphMatch;

/**
 * The SemVer ABI version reported by `purrdf_abi_version`.
 */
typedef struct {
    /**
     * Major version: incompatible ABI change.
     */
    uint32_t major;
    /**
     * Minor version: backward-compatible additions.
     */
    uint32_t minor;
    /**
     * Patch version: backward-compatible fixes.
     */
    uint32_t patch;
} PurrdfAbiVersion;

/**
 * `#[repr(C)]` twin of `purrdf_core`'s `RdfStoreCapabilities` (each `bool`
 * rendered as `0`/`1`). The seven flags mirror the kernel exactly.
 */
typedef struct {
    /**
     * The dataset distinguishes named graphs from the default graph.
     */
    uint8_t named_graphs;
    /**
     * The dataset carries RDF-1.2 quoted triples (the star layer).
     */
    uint8_t quoted_triples;
    /**
     * The dataset carries reifier bindings.
     */
    uint8_t reifiers;
    /**
     * The dataset carries annotation triples.
     */
    uint8_t annotations;
    /**
     * The dataset carries per-quad source locations.
     */
    uint8_t source_locations;
    /**
     * The dataset carries projection loss records.
     */
    uint8_t loss_records;
    /**
     * The dataset carries an out-of-band lookaside.
     */
    uint8_t lookaside;
} PurrdfCapabilities;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Expose the buffer's bytes as a borrowed pointer + length. The pointer is
 * valid until `purrdf_buffer_free(buf)`; the C side must not free it. For an
 * empty buffer `*out_ptr` may be a non-null dangling pointer with `*out_len == 0`.
 *
 * # Safety
 * `buf` must be a live buffer handle; `out_ptr`/`out_len` must be writable.
 */
int32_t purrdf_buffer_data(const PurrdfBuffer *buf, const uint8_t **out_ptr, size_t *out_len);

/**
 * Release a buffer handle. No-op on null.
 *
 * # Safety
 * `buf` must be null or a live buffer handle not already freed.
 */
void purrdf_buffer_free(PurrdfBuffer *buf);

/**
 * Open a pattern cursor. Each of `s`/`p`/`o` is a nullable input term view
 * (null = unbound). `g` is a non-null [`PurrdfGraphMatch`] (use kind `Any` for
 * "any graph"). A bound term/graph value that is interned nowhere yields an
 * empty cursor (not an error). The cursor pins the dataset's `Arc`.
 *
 * # Safety
 * `dataset` must be a live handle; the view/match pointers must be valid where
 * non-null; the out-params must be writable.
 */
int32_t purrdf_quads_for_pattern(const PurrdfDataset *dataset,
                                 const PurrdfTermView *s,
                                 const PurrdfTermView *p,
                                 const PurrdfTermView *o,
                                 const PurrdfGraphMatch *g,
                                 PurrdfCursor **out_cursor,
                                 PurrdfError **out_error);

/**
 * Advance to the next quad. On success fills the four term views; `out_has_graph`
 * is `0` for default-graph quads (the `out_g` view is then a zeroed placeholder).
 * The `PurrdfStr` pointers inside the views are valid until the next
 * `purrdf_cursor_next` on this cursor or `purrdf_cursor_free`. Returns
 * `PurrdfStatus::CursorExhausted` (a non-error terminal signal, `> 0`) when no
 * rows remain.
 *
 * # Safety
 * `cursor` must be a live cursor; the out-params must be writable.
 */
int32_t purrdf_cursor_next(PurrdfCursor *cursor,
                           PurrdfTermView *out_s,
                           PurrdfTermView *out_p,
                           PurrdfTermView *out_o,
                           PurrdfTermView *out_g,
                           uint8_t *out_has_graph);

/**
 * Release a cursor handle. No-op on null.
 *
 * # Safety
 * `cursor` must be null or a live cursor not already freed.
 */
void purrdf_cursor_free(PurrdfCursor *cursor);

/**
 * Return the status code carried by an error, or `Panic` if `err` is null.
 *
 * # Safety
 * `err` must be null or a pointer returned by a libpurrdf entry point and not
 * yet freed.
 */
int32_t purrdf_error_code(const PurrdfError *err);

/**
 * Return the borrowed, NUL-terminated message of an error. Valid until
 * `purrdf_error_free(err)`. Returns null if `err` is null.
 *
 * # Safety
 * Same contract as [`purrdf_error_code`].
 */
const char *purrdf_error_message(const PurrdfError *err);

/**
 * Release an error handle. No-op on null. Idempotent only in the sense that the
 * caller must not pass the same non-null pointer twice.
 *
 * # Safety
 * `err` must be null or a pointer returned by a libpurrdf entry point and not
 * already freed.
 */
void purrdf_error_free(PurrdfError *err);

/**
 * Branch a single-threaded mutable COW graph off a frozen dataset. `*out_graph`
 * is a caller-owned handle (free with `purrdf_graph_free`); the source dataset
 * is unaffected and may be freed independently.
 *
 * # Safety
 * `dataset` must be a live handle; `out_graph` must be writable.
 */
int32_t purrdf_graph_from_dataset(const PurrdfDataset *dataset, PurrdfGraph **out_graph);

/**
 * Insert a value-quad into the effective set. `s`/`p`/`o` are required input
 * term views; `g` may be null (default graph). `out_changed` (nullable)
 * receives `1` if the effective set changed, else `0` (an already-present quad
 * is a no-op; inserting a previously-removed base quad un-suppresses it).
 *
 * # Safety
 * `graph` must be a live handle; the view pointers must be valid where
 * non-null; the out-params must be writable.
 */
int32_t purrdf_graph_insert(PurrdfGraph *graph,
                            const PurrdfTermView *s,
                            const PurrdfTermView *p,
                            const PurrdfTermView *o,
                            const PurrdfTermView *g,
                            uint8_t *out_changed,
                            PurrdfError **out_error);

/**
 * Remove a value-quad from the effective set. Removing a delta-added quad drops
 * it; removing a base quad creates a suppression. `out_changed` (nullable)
 * receives `1` if the effective set changed.
 *
 * # Safety
 * Same contract as [`purrdf_graph_insert`].
 */
int32_t purrdf_graph_remove(PurrdfGraph *graph,
                            const PurrdfTermView *s,
                            const PurrdfTermView *p,
                            const PurrdfTermView *o,
                            const PurrdfTermView *g,
                            uint8_t *out_changed,
                            PurrdfError **out_error);

/**
 * Compact the COW delta into a fresh frozen dataset. The graph remains valid
 * (free it separately with `purrdf_graph_free`). `*out_dataset` is a
 * caller-owned handle.
 *
 * # Safety
 * `graph` must be a live handle; `out_dataset` must be writable.
 */
int32_t purrdf_graph_freeze(const PurrdfGraph *graph,
                            PurrdfDataset **out_dataset,
                            PurrdfError **out_error);

/**
 * Release a graph handle. No-op on null.
 *
 * # Safety
 * `graph` must be null or a live graph handle not already freed.
 */
void purrdf_graph_free(PurrdfGraph *graph);

/**
 * Read a GTS container into a fresh frozen dataset. `*out_dataset` is a
 * caller-owned handle (free with `purrdf_dataset_free`).
 *
 * **Lossless**, including the RDF-1.2 statement layer: a reifier-bound quoted
 * triple written by `to_gts` is read back intact via the canonical fold-back
 * (`read_graph` → `import_gts_graph`). The earlier `gts-missing-reifier-binding`
 * gap was closed by the native text-codec work.
 *
 * # Safety
 * `bytes` must be valid for `len` bytes; the out-params must be writable.
 */
int32_t purrdf_from_gts(const uint8_t *bytes,
                        size_t len,
                        PurrdfDataset **out_dataset,
                        PurrdfError **out_error);

/**
 * Write a frozen dataset to canonical GTS container bytes under `profile`
 * (e.g. `"dist"`). The output goes to `*out_buffer` (free with
 * `purrdf_buffer_free`).
 *
 * # Safety
 * `dataset` must be a live handle; `profile` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_to_gts(const PurrdfDataset *dataset,
                      const char *profile,
                      PurrdfBuffer **out_buffer,
                      PurrdfError **out_error);

/**
 * Release a dataset handle. No-op on null.
 *
 * # Safety
 * `dataset` must be null or a live dataset handle not already freed.
 */
void purrdf_dataset_free(PurrdfDataset *dataset);

/**
 * Write the number of quads in the dataset to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_dataset_quad_count(const PurrdfDataset *dataset, size_t *out);

/**
 * Write the number of interned terms in the dataset to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_dataset_term_count(const PurrdfDataset *dataset, size_t *out);

/**
 * Parse `len` bytes of `media_type` (e.g. `"text/turtle"`, `"application/n-quads"`)
 * into a fresh frozen dataset. `base_iri` and `source_name` may be null. On
 * success `*out_dataset` is a caller-owned handle (free with
 * `purrdf_dataset_free`); on failure `*out_error` is set.
 *
 * # Safety
 * `bytes` must be valid for `len` bytes; the `c_char` pointers must be null or
 * NUL-terminated; the out-params must be writable.
 */
int32_t purrdf_parse(const uint8_t *bytes,
                     size_t len,
                     const char *media_type,
                     const char *base_iri,
                     const char *source_name,
                     PurrdfDataset **out_dataset,
                     PurrdfError **out_error);

/**
 * Execute a SPARQL query. The result shape is reported in `*out_kind`:
 * `0` = SELECT → `*out_rows` is a `PurrdfRowCursor` (free with
 * `purrdf_rowcursor_free`); `1` = CONSTRUCT/DESCRIBE → `*out_graph` is a
 * `PurrdfDataset` (free with `purrdf_dataset_free`); `2` = ASK → `*out_boolean`
 * is `0`/`1`. Exactly one output is set per kind. `base_iri` may be null.
 *
 * # Safety
 * `dataset` must be a live handle; `query` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_query(const PurrdfDataset *dataset,
                     const char *query,
                     const char *base_iri,
                     int32_t *out_kind,
                     PurrdfRowCursor **out_rows,
                     PurrdfDataset **out_graph,
                     uint8_t *out_boolean,
                     PurrdfError **out_error);

/**
 * Execute a SPARQL query and serialize the result to the SPARQL 1.1 Query
 * Results JSON format (SELECT and ASK) into `*out_buffer` (UTF-8). A
 * CONSTRUCT/DESCRIBE graph is rendered as N-Triples inside a documented
 * `{"graph": "..."}` envelope. The simple/robust path — no row cursor needed.
 *
 * # Safety
 * `dataset` must be a live handle; `query` must be a NUL-terminated C string;
 * the out-params must be writable.
 */
int32_t purrdf_query_json(const PurrdfDataset *dataset,
                          const char *query,
                          const char *base_iri,
                          PurrdfBuffer **out_buffer,
                          PurrdfError **out_error);

/**
 * Write the number of result variables (columns) to `*out`.
 *
 * # Safety
 * `rc` must be a live row cursor; `out` must be writable.
 */
int32_t purrdf_rowcursor_variable_count(const PurrdfRowCursor *rc, size_t *out);

/**
 * Write a borrowed, NUL-terminated variable name for column `i` to `*out`.
 * Valid until `purrdf_rowcursor_free`. `InvalidArgument` if `i` is out of range.
 *
 * # Safety
 * `rc` must be a live row cursor; `out` must be writable.
 */
int32_t purrdf_rowcursor_variable_name(const PurrdfRowCursor *rc, size_t i, const char **out);

/**
 * Advance to the next solution row. Returns `PurrdfStatus::CursorExhausted`
 * (a non-error terminal signal, `> 0`) when no rows remain.
 *
 * # Safety
 * `rc` must be a live row cursor.
 */
int32_t purrdf_rowcursor_next(PurrdfRowCursor *rc);

/**
 * Read the term in `column` of the CURRENT row. `out_bound` receives `0` when
 * the variable is UNBOUND in this row (the view is then a zeroed placeholder),
 * else `1`. The view's `PurrdfStr` pointers are valid until the next
 * `purrdf_rowcursor_next` or `purrdf_rowcursor_free`. `InvalidArgument` if no
 * row is current (call `_next` first) or `column` is out of range.
 *
 * # Safety
 * `rc` must be a live row cursor; the out-params must be writable.
 */
int32_t purrdf_rowcursor_term(const PurrdfRowCursor *rc,
                              size_t column,
                              PurrdfTermView *out_view,
                              uint8_t *out_bound);

/**
 * Release a row cursor handle. No-op on null.
 *
 * # Safety
 * `rc` must be null or a live row cursor not already freed.
 */
void purrdf_rowcursor_free(PurrdfRowCursor *rc);

/**
 * Serialize the frozen dataset to `media_type` (e.g. `"text/turtle"`,
 * `"application/n-quads"`). `base_iri` may be null. The output bytes go to
 * `*out_buffer` (free with `purrdf_buffer_free`). When `out_statement_rows_dropped`
 * is non-null it receives the number of RDF-1.2 statement-layer rows dropped
 * because the target format cannot represent quoted triples (`0` for
 * star-capable formats) — so the caller can detect lossy projection.
 *
 * # Safety
 * `dataset` must be a live handle; the `c_char` pointers must be null or
 * NUL-terminated; the out-params must be writable.
 */
int32_t purrdf_serialize(const PurrdfDataset *dataset,
                         const char *media_type,
                         const char *base_iri,
                         PurrdfBuffer **out_buffer,
                         size_t *out_statement_rows_dropped,
                         PurrdfError **out_error);

/**
 * Validate a data graph (N-Triples) against a shapes graph (Turtle) and write
 * the SARIF 2.1.0 report bytes to `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * # Safety
 * `shapes_ttl` and `data_nt` must be non-null, NUL-terminated C strings;
 * `out_buffer` must be a writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_shacl_validate_to_sarif(const char *shapes_ttl,
                                       const char *data_nt,
                                       PurrdfBuffer **out_buffer,
                                       PurrdfError **out_error);

/**
 * Entail a data graph (N-Triples) under a shapes graph (Turtle) and write the
 * materialized dataset (base graph plus every inferred triple) as canonical
 * N-Triples bytes to `*out_buffer` (free with `purrdf_buffer_free`).
 *
 * # Safety
 * `shapes_ttl` and `data_nt` must be non-null, NUL-terminated C strings;
 * `out_buffer` must be a writable pointer; `out_error` must be null or writable.
 */
int32_t purrdf_shacl_entail_to_ntriples(const char *shapes_ttl,
                                        const char *data_nt,
                                        PurrdfBuffer **out_buffer,
                                        PurrdfError **out_error);

/**
 * Render a single term view to one N-Triples term token (e.g. `<iri>`, `_:b`,
 * `"lex"^^<dt>`, or `<< s p o >>` for a quoted triple) into `*out_buffer`
 * (UTF-8, no trailing dot). When the view carries a dataset `term_id`, the term
 * is resolved against `dataset` (so quoted triples materialize recursively);
 * otherwise the token is built from the view fields (non-triple only).
 *
 * # Safety
 * `dataset` must be the live handle the view's `term_id` came from (when
 * non-zero); `view` and the out-params must be valid.
 */
int32_t purrdf_term_to_ntriples(const PurrdfDataset *dataset,
                                const PurrdfTermView *view,
                                PurrdfBuffer **out_buffer,
                                PurrdfError **out_error);

/**
 * Write the libpurrdf ABI version to `*out`.
 *
 * # Safety
 * `out` must be null-checked-writable for one `PurrdfAbiVersion`.
 */
int32_t purrdf_abi_version(PurrdfAbiVersion *out);

/**
 * Write the dataset's capability flags to `*out`.
 *
 * # Safety
 * `dataset` must be a live handle; `out` must be writable.
 */
int32_t purrdf_capabilities(const PurrdfDataset *dataset, PurrdfCapabilities *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PURRDF_H */
