PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:     <http://ex/>
PREFIX purrdf:  <https://blackcatinformatics.ca/purrdf/>
ASK {
  ?r rdf:reifies <<( ?s ?p ?o )>> .
  FILTER( purrdf:heldIn(?r, ex:unrelated) )
}
