# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: CC-BY-4.0
# Competency (#349): find carriers that ENACT a mode without any vantage
# recording that they DESCRIBE it — pure use, no mention: performances,
# demands, dark patterns; never reports or analyses.
PREFIX gmeow: <https://blackcatinformatics.ca/gmeow/>
SELECT DISTINCT ?carrier WHERE {
    ?carrier gmeow:hasAboutness gmeow:aboutnessEnacts .
    FILTER NOT EXISTS { ?carrier gmeow:hasAboutness gmeow:aboutnessDescribes }
}
