# Competency question: "What deception-related event types and veridicality values does GMEOW model?"
# Expected: eventTypeDeception, eventTypeLie, eventTypePaltering, eventTypeOmission,
#           eventTypeDistortion, eventTypeBullshit, eventTypeSelfDeception,
#           eventTypeFabrication, eventTypeForgery, eventTypeImpersonation,
#           eventTypeDisinformation,
#           ClaimVeridicality, veridicalityUntrue, veridicalityLicensedFalsehood.
# Issues #215, #216, #217.

PREFIX gmeow: <https://blackcatinformatics.ca/gmeow/>

SELECT ?deceptionType WHERE {
    { ?deceptionType a gmeow:EventType . FILTER(?deceptionType IN (
        gmeow:eventTypeDeception,
        gmeow:eventTypeLie,
        gmeow:eventTypePaltering,
        gmeow:eventTypeOmission,
        gmeow:eventTypeDistortion,
        gmeow:eventTypeBullshit,
        gmeow:eventTypeSelfDeception,
        gmeow:eventTypeFabrication,
        gmeow:eventTypeForgery,
        gmeow:eventTypeImpersonation,
        gmeow:eventTypeDisinformation
    )) }
    UNION
    { BIND(gmeow:ClaimVeridicality AS ?deceptionType) }
    UNION
    { ?deceptionType a gmeow:ClaimVeridicality }
}
ORDER BY ?deceptionType
