# Competency question (negative): "Is a fiction claim ever flagged as a lie?"
# A claim asserted accordingTo a NarrativeReferenceFrame with licensed-falsehood
# veridicality must NOT be returned as a lie.
# Expected: empty result — the safety property holds.

PREFIX gmeow: <https://blackcatinformatics.ca/gmeow/>

SELECT ?fictionClaim WHERE {
    ?fictionClaim gmeow:accordingTo ?narrativeFrame .
    ?fictionClaim gmeow:claimVeridicality gmeow:veridicalityLicensedFalsehood .
    FILTER EXISTS {
        ?deceptionEvent gmeow:eventType gmeow:eventTypeLie .
        ?deceptionEvent gmeow:projectedStandpoint ?fictionClaim .
    }
}
ORDER BY ?fictionClaim
