// SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

// Bench targets are not public API: `criterion_group!` expands to a `pub fn`,
// which would otherwise trip the workspace `missing_docs` lint.
#![allow(missing_docs)]

//! Per-value-node cost of the ShEx `PATTERN` facet's
//! [`PatternCache`](crate) after it replaced a per-value-node recompile.
//!
//! `prepared_validate.rs` exercises the shape precompilation path, but its
//! fixture carries **no** pattern facet, so the cache this branch added is
//! otherwise unmeasured. This target drives MANY value nodes through ONE
//! [`validate`] call (the cache is per-validation-call, so a fresh call per
//! node would never hit it) and separates the three regimes:
//!
//! * `shared_valid` — one pattern shared by every node, every value matching.
//!   After the first node the probe is a cache hit; the measured cost is the
//!   match, not the compile.
//! * `shared_invalid` — one pattern shared by every node that does **not
//!   compile**. `PatternCache` memoizes the failure as an `Arc<str>`, so this
//!   is the memoized-failure path: the reason string is derived once and then
//!   cloned per node rather than re-compiled.
//! * `distinct_patterns` — a distinct pattern per node, so every node is a
//!   cache **miss** and pays a full translation + build. The control that
//!   shows the shared cases are genuinely hitting the memo.
//!
//! Report-only, `cargo bench -p purrdf-shex --bench pattern_validate` (the
//! `make bench` lane) — excluded from `make check`. No timing is asserted.

use std::sync::Arc;

use criterion::{Criterion, Throughput, black_box, criterion_group, criterion_main};
use purrdf_core::{RdfDataset, RdfDatasetBuilder, RdfLiteral, TermValue};
use purrdf_shex::{Schema, ShapeSelector, parse_shexc, validate};

/// Nodes per shared-pattern validation call.
const NODE_COUNT: usize = 3_000;
/// Shapes (and focus nodes) in the distinct-pattern fixture.
const DISTINCT_PATTERNS: usize = 512;
const NS: &str = "http://example.org/ns#";

/// One validation call's inputs: the schema, the frozen data, and the shape map
/// associating every `widget-N` node with the fixture's shape.
struct Fixture {
    schema: Schema,
    data: Arc<RdfDataset>,
    map: Vec<(TermValue, ShapeSelector)>,
}

/// A schema whose single `Widget` shape requires one `ex:code` `LITERAL` value
/// to satisfy `PATTERN pattern`, over [`NODE_COUNT`] focus nodes that each
/// carry one `ex:code` literal. Values are generated by a counter — no RNG, no
/// iteration-order dependence.
fn shared_fixture(pattern: &str) -> Fixture {
    let schema_src = format!("<{NS}Widget> {{ <{NS}code> LITERAL /{pattern}/ }}");
    let schema = parse_shexc(&schema_src, None).expect("shared-pattern fixture schema parses");

    let mut builder = RdfDatasetBuilder::new();
    let p_code = builder.intern_iri(&format!("{NS}code"));
    let mut map = Vec::with_capacity(NODE_COUNT);
    for idx in 0..NODE_COUNT {
        let subject_iri = format!("{NS}widget-{idx}");
        let subject = builder.intern_iri(&subject_iri);
        let value = builder.intern_literal(RdfLiteral::simple(format!("W-{idx}")));
        builder.push_quad(subject, p_code, value, None);
        map.push((
            TermValue::iri(subject_iri),
            ShapeSelector::Label(format!("{NS}Widget")),
        ));
    }
    let data = builder.freeze().expect("freeze shared-pattern dataset");
    Fixture { schema, data, map }
}

/// A schema of `count` shapes, each with its own `ex:code` `PATTERN`, and
/// `count` focus nodes each associated with a different shape — so one
/// validation call compiles `count` distinct patterns.
fn distinct_fixture(count: usize) -> Fixture {
    use std::fmt::Write as _;

    let mut schema_src = String::new();
    for idx in 0..count {
        writeln!(
            schema_src,
            "<{NS}Shape{idx}> {{ <{NS}code> LITERAL /^W-{idx}-[0-9]+$/ }}"
        )
        .expect("distinct-pattern schema builds");
    }
    let schema = parse_shexc(&schema_src, None).expect("distinct-pattern fixture schema parses");

    let mut builder = RdfDatasetBuilder::new();
    let p_code = builder.intern_iri(&format!("{NS}code"));
    let mut map = Vec::with_capacity(count);
    for idx in 0..count {
        let subject_iri = format!("{NS}widget-{idx}");
        let subject = builder.intern_iri(&subject_iri);
        let value = builder.intern_literal(RdfLiteral::simple(format!("W-{idx}-42")));
        builder.push_quad(subject, p_code, value, None);
        map.push((
            TermValue::iri(subject_iri),
            ShapeSelector::Label(format!("{NS}Shape{idx}")),
        ));
    }
    let data = builder.freeze().expect("freeze distinct-pattern dataset");
    Fixture { schema, data, map }
}

fn bench_pattern_validate(c: &mut Criterion) {
    let shared_valid = shared_fixture(r"^W-[0-9]+$");
    // `[a` is an unterminated character class: the ShExC lexer accepts it and
    // the shared compiler refuses it, which is exactly the cache's failure arm.
    let shared_invalid = shared_fixture("[a");
    let distinct = distinct_fixture(DISTINCT_PATTERNS);

    // Untimed sanity: the valid fixtures must conform, the bad-pattern fixture
    // must report a violation for every node, and no fixture may be empty.
    let valid = validate(&shared_valid.schema, &shared_valid.data, &shared_valid.map);
    assert!(
        valid.all_conformant(),
        "shared_valid fixture must conform for every node"
    );
    assert_eq!(valid.entries.len(), NODE_COUNT);
    let invalid = validate(
        &shared_invalid.schema,
        &shared_invalid.data,
        &shared_invalid.map,
    );
    assert_eq!(invalid.entries.len(), NODE_COUNT);
    assert!(
        !invalid.all_conformant(),
        "shared_invalid fixture must report the non-compiling pattern"
    );
    let distinct_report = validate(&distinct.schema, &distinct.data, &distinct.map);
    assert!(
        distinct_report.all_conformant(),
        "distinct_patterns fixture must conform for every node"
    );

    let mut group = c.benchmark_group("shex_pattern_validate");
    group.sample_size(10);

    group.throughput(Throughput::Elements(
        u64::try_from(NODE_COUNT).expect("fixture size fits u64"),
    ));
    group.bench_function("shared_valid", |bencher| {
        bencher.iter(|| {
            let result = validate(
                black_box(&shared_valid.schema),
                black_box(&shared_valid.data),
                black_box(&shared_valid.map),
            );
            assert!(result.all_conformant());
            black_box(result);
        });
    });
    group.bench_function("shared_invalid", |bencher| {
        bencher.iter(|| {
            let result = validate(
                black_box(&shared_invalid.schema),
                black_box(&shared_invalid.data),
                black_box(&shared_invalid.map),
            );
            assert!(!result.all_conformant());
            black_box(result);
        });
    });

    group.throughput(Throughput::Elements(
        u64::try_from(DISTINCT_PATTERNS).expect("fixture size fits u64"),
    ));
    group.bench_function("distinct_patterns", |bencher| {
        bencher.iter(|| {
            let result = validate(
                black_box(&distinct.schema),
                black_box(&distinct.data),
                black_box(&distinct.map),
            );
            assert!(result.all_conformant());
            black_box(result);
        });
    });
    group.finish();
}

criterion_group!(benches, bench_pattern_validate);
criterion_main!(benches);
