// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

//! Generate `crates/xsd/tests/vectors/exact_numeric_vectors.txt`: XPath F&O 3.1
//! numeric answers over `xsd:integer`/`xsd:decimal` operands of any size, computed
//! by the exact rational oracle (`purrdf_testkit::exact`), which shares no code
//! with `purrdf_xsd`.
//!
//! ```text
//! cargo run -p purrdf-xsd --example gen_exact_numeric_vectors > \
//!     crates/xsd/tests/vectors/exact_numeric_vectors.txt
//! ```
//!
//! Each record is `operation  left  right  answer`:
//!
//! * `add`, `sub`, `mul` — `op:numeric-add/-subtract/-multiply`, the canonical
//!   lexical form of the exact result;
//! * `div` — `op:numeric-divide` at eighteen fractional digits truncated toward
//!   zero (the default division precision), or `division-by-zero`;
//! * `div-exact` — the exact quotient, or `non-terminating`, or `division-by-zero`;
//! * `cmp` — `<`, `=` or `>`;
//! * `double`, `float` — the correctly rounded `xs:double`/`xs:float` bit pattern of
//!   the left operand (the right operand is `-`);
//! * `canonical` — the canonical lexical form of the left operand.
//!
//! An operand containing `.` is an `xsd:decimal`, any other an `xsd:integer`.

use std::cmp::Ordering;

use purrdf_testkit::exact::{Direction, Rational as Oracle};
use purrdf_testkit::rng::splitmix64_next;
use purrdf_testkit::vectors::Recorder;

/// A seeded operand: an integer or decimal of one to about a hundred and fifty
/// digits, with leading and trailing zeros in its spelling.
fn operand(state: &mut u64) -> String {
    let digits = |state: &mut u64, len: u64| -> String {
        (0..len)
            .map(|_| char::from(b'0' + u8::try_from(splitmix64_next(state) % 10).expect("a digit")))
            .collect()
    };
    let width = match splitmix64_next(state) % 4 {
        0 => 1 + splitmix64_next(state) % 8,
        1 => 36 + splitmix64_next(state) % 6,
        2 => 1 + splitmix64_next(state) % 70,
        _ => 100 + splitmix64_next(state) % 50,
    };
    let whole = digits(state, width);
    let sign = match splitmix64_next(state) % 3 {
        0 => "-",
        1 => "+",
        _ => "",
    };
    if splitmix64_next(state).is_multiple_of(2) {
        return format!("{sign}{whole}");
    }
    let places = splitmix64_next(state) % 45;
    let mut fraction = digits(state, places);
    if splitmix64_next(state).is_multiple_of(4) {
        fraction.push_str("000");
    }
    format!("{sign}{whole}.{fraction}")
}

/// The edge operands: zeros, units, the `i128` and eighteen-digit boundaries and
/// their neighbours.
const EDGES: [&str; 14] = [
    "0",
    "-0.0",
    "1",
    "-1",
    "170141183460469231731687303715884105727",
    "170141183460469231731687303715884105728",
    "-170141183460469231731687303715884105728",
    "-170141183460469231731687303715884105729",
    "0.000000000000000001",
    "0.0000000000000000001",
    "1.000000000000000000000000000000000000001",
    "99999999999999999999.999999999999999999",
    "3",
    "7",
];

fn canonical(value: &Oracle) -> String {
    value.to_canonical_decimal().expect("a terminating value")
}

fn main() {
    let mut recorder = Recorder::new();
    recorder
        .comment("XPath F&O 3.1 numeric answers over xsd:integer/xsd:decimal operands of any size")
        .and_then(|r| {
            r.comment("(generated by crates/xsd/examples/gen_exact_numeric_vectors.rs from")
        })
        .and_then(|r| {
            r.comment("the exact rational oracle purrdf_testkit::exact; never edit by hand).")
        })
        .and_then(|r| r.comment(""))
        .and_then(|r| {
            r.comment(
                "Fields: operation, left, right, answer. See the generator for each operation.",
            )
        })
        .expect("header comments");
    let mut state = 0xF0A5_E4AC_u64;
    let mut pairs: Vec<(String, String)> = Vec::new();
    for a in EDGES {
        for b in EDGES {
            pairs.push((a.to_owned(), b.to_owned()));
        }
    }
    for _ in 0..600 {
        pairs.push((operand(&mut state), operand(&mut state)));
    }
    let mut record = |fields: [&str; 4]| {
        recorder.record(&fields).expect("a record");
    };
    for (a, b) in &pairs {
        let (x, y) = (
            Oracle::parse(a).expect("a numeral"),
            Oracle::parse(b).expect("a numeral"),
        );
        record(["add", a, b, &canonical(&x.add(&y))]);
        record(["sub", a, b, &canonical(&x.sub(&y))]);
        record(["mul", a, b, &canonical(&x.mul(&y))]);
        match x.div(&y) {
            None => {
                record(["div", a, b, "division-by-zero"]);
                record(["div-exact", a, b, "division-by-zero"]);
            }
            Some(quotient) => {
                let truncated = quotient.round_to_scale(18, Direction::TowardZero);
                record(["div", a, b, &canonical(&truncated)]);
                let exact = quotient
                    .to_canonical_decimal()
                    .unwrap_or_else(|| "non-terminating".to_owned());
                record(["div-exact", a, b, &exact]);
            }
        }
        let order = match x.cmp_value(&y) {
            Ordering::Less => "<",
            Ordering::Equal => "=",
            Ordering::Greater => ">",
        };
        record(["cmp", a, b, order]);
    }
    for (a, _) in &pairs {
        let x = Oracle::parse(a).expect("a numeral");
        // An exact zero converts to +0, whatever sign its spelling carries.
        let x = if x.is_zero() { Oracle::from_i128(0) } else { x };
        record(["double", a, "-", &format!("{:016x}", x.to_f64().to_bits())]);
        record(["float", a, "-", &format!("{:08x}", x.to_f32().to_bits())]);
        record(["canonical", a, "-", &canonical(&x)]);
    }
    print!("{}", recorder.render());
}
