// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

// Repeatable npm ecosystem probe for the PurRDF wasm package. Report-only: it
// measures current package behavior and capability boundaries without turning
// the numbers into ranking claims.

import { execFileSync } from "node:child_process";
import { mkdtemp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

import { parsePackument } from "../tests/npm-pack-output.mjs";

const REPO_ROOT = resolve(fileURLToPath(new URL("../../../../", import.meta.url)));
const PACKAGE_ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const PACKAGE_SPECS = [
  ["n3", "2.1.1"],
  ["rdf-ext", "2.6.0"],
  ["graphy", "4.3.7"],
  ["@comunica/query-sparql", "5.2.4"],
  ["oxigraph", "0.5.9"],
];
const DEFAULT_COMMAND_TIMEOUT_MS = 120_000;
const NPM_INSTALL_TIMEOUT_MS = 300_000;
const PROBE_TIMEOUT_MS = 120_000;

function parseArgs(argv) {
  const args = { report: null, json: null };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--write-report") {
      args.report = argv[++i];
    } else if (arg === "--write-json") {
      args.json = argv[++i];
    } else {
      throw new Error(`unknown argument ${arg}`);
    }
  }
  return args;
}

function run(command, args, options = {}) {
  const { timeout = DEFAULT_COMMAND_TIMEOUT_MS, ...execOptions } = options;
  return execFileSync(command, args, {
    cwd: REPO_ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
    shell: process.platform === "win32" && command === "npm",
    timeout,
    ...execOptions,
  });
}

async function directorySize(path) {
  const entry = await stat(path);
  if (!entry.isDirectory()) return entry.size;
  let total = 0;
  for (const child of await readdir(path)) {
    total += await directorySize(join(path, child));
  }
  return total;
}

async function packageInfo(nodeModules, packageName, packument) {
  const packagePath = join(nodeModules, ...packageName.split("/"));
  const packageJsonPath = join(packagePath, "package.json");
  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
  const dependencies = Object.keys(packageJson.dependencies ?? {});
  return {
    name: packageName,
    version: packageJson.version,
    engines: packageJson.engines ?? null,
    dependencyCount: dependencies.length,
    installedBytes: await directorySize(packagePath),
    tarballBytes: packument?.size ?? null,
    unpackedBytes: packument?.unpackedSize ?? null,
  };
}

function packagePathForReport(name) {
  return name === "purrdf" ? "@blackcatinformatics/purrdf" : name;
}

function renderCell(result) {
  if (!result) return "n/a";
  if (result.status === "ok") {
    const detail = result.detail ? `; ${result.detail}` : "";
    return `ok (${result.ms} ms${detail})`;
  }
  if (result.status === "unsupported") return `unsupported: ${result.reason}`;
  return `error: ${result.error}`;
}

function renderBytes(value) {
  if (value == null) return "n/a";
  return `${value.toLocaleString("en-US")} B`;
}

function renderReport(data) {
  const packages = Object.values(data.packages);
  const rows = Object.entries(data.results).map(([name, result]) => {
    const version = data.packages[name]?.version ?? "n/a";
    return [
      packagePathForReport(name),
      version,
      renderCell(result.parse),
      renderCell(result.serialize),
      renderCell(result.select),
      renderCell(result.propertyPath),
      renderCell(result.aggregation),
      renderCell(result.graphIdentity),
      renderCell(result.rdf12),
    ];
  });
  const packageRows = packages.map((pkg) => [
    packagePathForReport(pkg.key),
    pkg.version,
    pkg.engines ? JSON.stringify(pkg.engines) : "none declared",
    String(pkg.dependencyCount),
    renderBytes(pkg.installedBytes),
    renderBytes(pkg.tarballBytes),
    renderBytes(pkg.unpackedBytes),
  ]);

  return `<!--
SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
SPDX-License-Identifier: CC-BY-4.0
-->

# npm RDF Ecosystem Probe

This report is generated by:

\`\`\`sh
node crates/rdf-wasm/js/bench/ecosystem-probe.mjs --write-report docs/NPM-ECOSYSTEM.md
\`\`\`

Generated: ${data.generatedAt}

Runtime: ${data.runtime.node} on ${data.runtime.platform} ${data.runtime.arch}

Corpus: ${data.corpus.quads} deterministic N-Triples statements plus RDF 1.2
N-Quads with a quoted-triple object and a directional language literal.

The table records measured behavior for these package versions only. An
unsupported cell means the tested package does not expose that capability in
the installed package surface used by this probe.

## Package Footprint

| Package | Version | Engines | Direct deps | Installed package bytes | Tarball bytes | Unpacked bytes |
| --- | --- | --- | ---: | ---: | ---: | ---: |
${packageRows.map((row) => `| ${row.join(" | ")} |`).join("\n")}

## Capability Probe

| Package | Version | Parse | Serialize | SELECT | Property path | Aggregation | Graph identity | RDF 1.2 triple terms / directional literals |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows.map((row) => `| ${row.join(" | ")} |`).join("\n")}

## Raw JSON

\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`
`;
}

const runner = String.raw`
import { performance } from "node:perf_hooks";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const SIMPLE_NT = Array.from({ length: 80 }, (_, i) => [
  "<https://bench.example/s" + i + "> <https://bench.example/p> <https://bench.example/o" + i + "> .",
  "<https://bench.example/s" + i + "> <https://bench.example/score> \"" + i + "\"^^<http://www.w3.org/2001/XMLSchema#integer> .",
  i < 79
    ? "<https://bench.example/s" + i + "> <https://bench.example/link> <https://bench.example/s" + (i + 1) + "> ."
    : "<https://bench.example/s" + i + "> <https://bench.example/name> \"tail\" .",
]).flat().join("\n") + "\n";

const RDF12_NQ = [
  '<https://bench.example/s> <https://bench.example/msg> "مرحبا"@ar--rtl .',
  '<https://bench.example/s> <https://bench.example/quote> <<( <https://bench.example/a> <https://bench.example/p> <https://bench.example/b> )>> .',
  "",
].join("\n");

const SELECT_SIMPLE = "PREFIX ex: <https://bench.example/> SELECT ?o WHERE { ex:s42 ex:p ?o }";
const SELECT_PATH = "PREFIX ex: <https://bench.example/> SELECT ?name WHERE { ex:s0 ex:link+/ex:name ?name }";
const SELECT_AGG = "PREFIX ex: <https://bench.example/> SELECT (COUNT(?s) AS ?count) WHERE { ?s ex:p ?o }";

function unsupported(reason) {
  return { status: "unsupported", reason };
}

function fail(error) {
  return { status: "error", error: String(error?.message ?? error).split("\n")[0] };
}

async function measure(fn, detailFn) {
  const start = performance.now();
  let value;
  try {
    value = await fn();
  } catch (error) {
    return fail(error);
  }
  const ms = Number((performance.now() - start).toFixed(3));
  let detail;
  try {
    detail = detailFn ? detailFn(value) : undefined;
  } catch {
    detail = undefined;
  }
  return detail ? { status: "ok", ms, detail } : { status: "ok", ms };
}

async function graphyParse(graphy, input, format) {
  const reader = graphy.content[format].read();
  const quads = [];
  await new Promise((resolve, reject) => {
    reader.on("data", (quad) => quads.push(quad));
    reader.on("error", reject);
    reader.on("end", resolve);
    reader.end(input);
  });
  return quads;
}

async function graphyWrite(graphy, quads, format) {
  const writer = graphy.content[format].write();
  let output = "";
  await new Promise((resolve, reject) => {
    writer.on("data", (chunk) => {
      output += chunk;
    });
    writer.on("error", reject);
    writer.on("end", resolve);
    for (const quad of quads) writer.write(quad);
    writer.end();
  });
  return output;
}

function n3Quads() {
  return new N3.Parser({ format: "N-Triples" }).parse(SIMPLE_NT);
}

const purrdf = await import("@blackcatinformatics/purrdf");
const N3 = await import("n3");
const rdfExt = (await import("rdf-ext")).default;
const graphy = (await import("graphy")).default;
const comunica = await import("@comunica/query-sparql");
const oxigraph = await import("oxigraph");

await purrdf.ready();
const purrdfDataset = purrdf.Dataset.parse(SIMPLE_NT, "ntriples");
const purrdfEngine = new purrdf.QueryEngine();

const oxStore = () => {
  const store = new oxigraph.Store();
  store.load(SIMPLE_NT, { format: "nt" });
  return store;
};
const oxQueryStore = oxStore();

const comunicaEngine = new comunica.QueryEngine();
const comunicaStore = new N3.Store(n3Quads());

const results = {
  purrdf: {
    parse: await measure(() => purrdf.Dataset.parse(SIMPLE_NT, "ntriples"), (ds) => String(ds.size) + " quads"),
    serialize: await measure(() => purrdfDataset.serialize("ntriples"), (text) => String(text.length) + " chars"),
    select: await measure(() => purrdfEngine.select(purrdfDataset, SELECT_SIMPLE), (r) => {
      const count = r.rowCount;
      r.free();
      return String(count) + " rows";
    }),
    propertyPath: await measure(() => purrdfEngine.select(purrdfDataset, SELECT_PATH), (r) => {
      const count = r.rowCount;
      r.free();
      return String(count) + " rows";
    }),
    aggregation: await measure(() => purrdfEngine.select(purrdfDataset, SELECT_AGG), (r) => r.rows.take(0)?.count?.value ?? "no count"),
    graphIdentity: await measure(() => {
      const a = purrdf.Dataset.parse("_:a <https://bench.example/p> <https://bench.example/o> .", "ntriples");
      const b = purrdf.Dataset.parse("_:b <https://bench.example/p> <https://bench.example/o> .", "ntriples");
      return a.isomorphic(b);
    }, (same) => "blank-node isomorphic=" + same),
    rdf12: await measure(() => purrdf.Dataset.parse(RDF12_NQ, "nquads"), (ds) => String(ds.size) + " quads"),
  },
  n3: {
    parse: await measure(n3Quads, (quads) => String(quads.length) + " quads"),
    serialize: await measure(async () => {
      const writer = new N3.Writer({ format: "N-Triples" });
      writer.addQuads(n3Quads());
      return await new Promise((resolve, reject) => {
        writer.end((error, result) => (error ? reject(error) : resolve(result)));
      });
    }, (text) => String(text.length) + " chars"),
    select: unsupported("no SPARQL engine in n3 package"),
    propertyPath: unsupported("no SPARQL engine in n3 package"),
    aggregation: unsupported("no SPARQL engine in n3 package"),
    graphIdentity: unsupported("no RDFC/isomorphism API in n3 package"),
    rdf12: await measure(() => new N3.Parser({ format: "N-Quads" }).parse(RDF12_NQ), (quads) => String(quads.length) + " quads"),
  },
  "rdf-ext": {
    parse: unsupported("rdf-ext core package has no parser without extra format packages"),
    serialize: unsupported("rdf-ext core package has no serializer without extra format packages"),
    select: unsupported("no SPARQL engine in rdf-ext package"),
    propertyPath: unsupported("no SPARQL engine in rdf-ext package"),
    aggregation: unsupported("no SPARQL engine in rdf-ext package"),
    graphIdentity: await measure(() => {
      const a = rdfExt.dataset(new N3.Parser({ format: "N-Triples" }).parse("_:a <https://bench.example/p> <https://bench.example/o> ."));
      const b = rdfExt.dataset(new N3.Parser({ format: "N-Triples" }).parse("_:b <https://bench.example/p> <https://bench.example/o> ."));
      return a.equals(b);
    }, (same) => "dataset.equals=" + same),
    rdf12: unsupported("rdf-ext core package has no parser without extra format packages"),
  },
  graphy: {
    parse: await measure(() => graphyParse(graphy, SIMPLE_NT, "nt"), (quads) => String(quads.length) + " quads"),
    serialize: await measure(async () => graphyWrite(graphy, await graphyParse(graphy, SIMPLE_NT, "nt"), "nt"), (text) => String(text.length) + " chars"),
    select: unsupported("no SPARQL engine in graphy package"),
    propertyPath: unsupported("no SPARQL engine in graphy package"),
    aggregation: unsupported("no SPARQL engine in graphy package"),
    graphIdentity: unsupported("no RDFC/isomorphism API in graphy package"),
    rdf12: await measure(() => graphyParse(graphy, RDF12_NQ, "nq"), (quads) => String(quads.length) + " quads"),
  },
  "@comunica/query-sparql": {
    parse: unsupported("query package consumes RDF/JS sources; parsing supplied by source package"),
    serialize: unsupported("query package does not expose graph serializer"),
    select: await measure(async () => {
      const bindings = await comunicaEngine.queryBindings(SELECT_SIMPLE, { sources: [comunicaStore] });
      return await bindings.toArray();
    }, (rows) => String(rows.length) + " rows"),
    propertyPath: await measure(async () => {
      const bindings = await comunicaEngine.queryBindings(SELECT_PATH, { sources: [comunicaStore] });
      return await bindings.toArray();
    }, (rows) => String(rows.length) + " rows"),
    aggregation: await measure(async () => {
      const bindings = await comunicaEngine.queryBindings(SELECT_AGG, { sources: [comunicaStore] });
      return await bindings.toArray();
    }, (rows) => rows[0]?.get("count")?.value ?? "no count"),
    graphIdentity: unsupported("no RDFC/isomorphism API in query-sparql package"),
    rdf12: unsupported("RDF 1.2 parse support depends on the supplied source parser"),
  },
  oxigraph: {
    parse: await measure(oxStore, (store) => String(store.size) + " quads"),
    serialize: await measure(() => oxStore().dump({ format: "nq" }), (text) => String(text.length) + " chars"),
    select: await measure(() => oxQueryStore.query(SELECT_SIMPLE), (rows) => String(rows.length) + " rows"),
    propertyPath: await measure(() => oxQueryStore.query(SELECT_PATH), (rows) => String(rows.length) + " rows"),
    aggregation: await measure(() => oxQueryStore.query(SELECT_AGG), (rows) => rows[0]?.get("count")?.value ?? "no count"),
    graphIdentity: unsupported("no RDFC/isomorphism API exposed in oxigraph JS package"),
    rdf12: await measure(() => {
      const store = new oxigraph.Store();
      store.load(RDF12_NQ, { format: "nq" });
      return store;
    }, (store) => String(store.size) + " quads"),
  },
};

console.log(JSON.stringify({ results, corpus: { quads: purrdfDataset.size } }));
`;

const args = parseArgs(process.argv.slice(2));
const root = await mkdtemp(join(tmpdir(), "purrdf-ecosystem-"));
try {
  const packOutput = run("npm", ["pack", "--json", "--pack-destination", root], {
    cwd: PACKAGE_ROOT,
  });
  const purrdfPackument = parsePackument(packOutput, "npm pack for PurRDF");
  const packuments = { purrdf: purrdfPackument };
  for (const [name, version] of PACKAGE_SPECS) {
    const packument = parsePackument(
      run("npm", ["pack", "--json", "--pack-destination", root, `${name}@${version}`]),
      `npm pack for ${name}@${version}`,
    );
    packuments[name] = packument;
  }

  const project = join(root, "project");
  await mkdir(project);
  await writeFile(
    join(project, "package.json"),
    JSON.stringify({ private: true, type: "module" }, null, 2),
  );
  const installSpecs = [
    join(root, purrdfPackument.filename),
    ...PACKAGE_SPECS.map(([name, version]) => `${name}@${version}`),
  ];
  run("npm", ["install", "--ignore-scripts", "--no-audit", "--no-fund", ...installSpecs], {
    cwd: project,
    stdio: "inherit",
    timeout: NPM_INSTALL_TIMEOUT_MS,
  });

  const runnerPath = join(project, "probe-runner.mjs");
  await writeFile(runnerPath, runner);
  const raw = run(process.execPath, [runnerPath], {
    cwd: project,
    timeout: PROBE_TIMEOUT_MS,
  });
  const probe = JSON.parse(raw);
  const nodeModules = join(project, "node_modules");
  const packages = {
    purrdf: {
      key: "purrdf",
      ...(await packageInfo(
        nodeModules,
        "@blackcatinformatics/purrdf",
        purrdfPackument,
      )),
    },
  };
  for (const [name] of PACKAGE_SPECS) {
    packages[name] = {
      key: name,
      ...(await packageInfo(nodeModules, name, packuments[name])),
    };
  }

  const data = {
    generatedAt: new Date().toISOString(),
    runtime: {
      node: process.version,
      platform: process.platform,
      arch: process.arch,
    },
    commands: [
      "npm pack --json --pack-destination <tmp>",
      `npm install --ignore-scripts --no-audit --no-fund <local-purrdf.tgz> ${PACKAGE_SPECS.map(([name, version]) => `${name}@${version}`).join(" ")}`,
      "node <tmp>/project/probe-runner.mjs",
    ],
    corpus: probe.corpus,
    packages,
    results: probe.results,
  };

  const report = renderReport(data);
  if (args.report) {
    const reportPath = resolve(REPO_ROOT, args.report);
    await writeFile(reportPath, report);
    console.log(`wrote ${reportPath}`);
  } else {
    console.log(report);
  }
  if (args.json) {
    const jsonPath = resolve(REPO_ROOT, args.json);
    await writeFile(jsonPath, `${JSON.stringify(data, null, 2)}\n`);
    console.log(`wrote ${jsonPath}`);
  }
} finally {
  await rm(root, { force: true, recursive: true });
}
