// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

//! The language-independent full lowercase mapping, including Final_Sigma.
//!
//! Scalar mappings use the standard character iterator. Unicode §3.13's
//! conditional sigma law uses the selected UCD's Cased and Case_Ignorable
//! properties, generated by the same workspace Unicode generator.

use super::case_tables;
use crate::allocation::{Admission, Memory, StorageError};

/// An allocation-free full lowercase iterator over the original input.
/// Context skips Case_Ignorable before testing Cased, including their overlap.
#[derive(Clone, Debug)]
pub struct Lowercase<'a> {
    input: &'a str,
    characters: core::str::CharIndices<'a>,
    mapped: Option<core::char::ToLowercase>,
    preceding_cased: bool,
}

/// Iterate the full lowercase mapping without allocating a destination.
///
/// Greek sigma is final only when preceded by a cased scalar and not followed
/// by one, ignoring case-ignorable scalars in each context. Neither locale rules
/// nor an independently normalized spelling change the original input context.
#[must_use]
pub fn lowercase(input: &str) -> Lowercase<'_> {
    Lowercase {
        input,
        characters: input.char_indices(),
        mapped: None,
        preceding_cased: false,
    }
}

fn case_ignorable(character: char) -> bool {
    crate::terminals::in_ranges(u32::from(character), case_tables::CONTEXT_PROPERTIES[0].1)
}
fn cased(character: char) -> bool {
    crate::terminals::in_ranges(u32::from(character), case_tables::CONTEXT_PROPERTIES[1].1)
}

impl Iterator for Lowercase<'_> {
    type Item = char;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            if let Some(mapped) = &mut self.mapped {
                if let Some(character) = mapped.next() {
                    return Some(character);
                }
                self.mapped = None;
            }
            let (offset, character) = self.characters.next()?;
            let preceding_cased = self.preceding_cased;
            if !case_ignorable(character) {
                self.preceding_cased = cased(character);
            }
            if character == 'Σ' {
                // Each suffix scan ends at the first non-ignorable scalar.
                // Sigma itself is not ignorable, so scanned ignorable runs
                // between sigmas are disjoint: the whole iterator is linear.
                let following_cased = self.input[offset + character.len_utf8()..]
                    .chars()
                    .find(|&next| !case_ignorable(next))
                    .is_some_and(cased);
                return Some(if preceding_cased && !following_cased {
                    'ς'
                } else {
                    'σ'
                });
            }
            self.mapped = Some(character.to_lowercase());
        }
    }
}

/// Exact UTF-8 extent of the same contextual writer.
///
/// # Errors
/// Returns an unrepresentable native output length.
pub fn lowercase_len(input: &str) -> Result<usize, StorageError> {
    lowercase(input).try_fold(0usize, |length, character| {
        length
            .checked_add(character.len_utf8())
            .ok_or(StorageError::SizeOverflow)
    })
}

/// Write the exact contextual mapping into one before-admitted destination.
/// The returned String remains under this original Memory until destroyed or
/// transferred with its original grant by the caller.
///
/// # Errors
/// Returns checked extent, caller admission or actual allocator refusal.
pub fn lowercase_with_memory<S: Admission + ?Sized>(
    input: &str,
    memory: &mut Memory<'_, S>,
) -> Result<String, StorageError> {
    let length = lowercase_len(input)?;
    let mut output = String::new();
    memory.reserve_string(&mut output, length)?;
    for character in lowercase(input) {
        output.push(character);
    }
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frozen_final_sigma_and_full_mapping_vectors() {
        for (input, expected) in [
            ("", ""),
            ("Σ", "σ"),
            ("ΟΣ", "ος"),
            ("ΟΣΑ", "οσα"),
            ("Α.Σ", "α.ς"),
            ("ΟΣ.Α", "οσ.α"),
            ("ΟΣ.\u{301}", "ος.\u{301}"),
            ("A\u{345}Σ", "a\u{345}ς"),
            ("\u{345}Σ", "\u{345}σ"),
            ("AΣ\u{345}B", "aσ\u{345}b"),
            ("AΣ\u{345}", "aς\u{345}"),
            ("\u{1c5}Σ", "\u{1c6}ς"),
            ("AΣ\u{1c5}", "aσ\u{1c6}"),
            ("İΣ", "i\u{307}ς"),
            ("AΣ\u{200d}", "aς\u{200d}"),
            ("AΣ1", "aς1"),
            ("AΣΣ", "aσς"),
            ("ΣΣ", "σς"),
            ("A\u{558}Σ", "a\u{558}σ"),
            ("A\u{559}Σ", "a\u{559}ς"),
        ] {
            let mut resident = crate::allocation::Resident;
            let mut memory = Memory::new(&mut resident);
            let output = lowercase_with_memory(input, &mut memory).unwrap();
            assert_eq!(output, expected, "{input:?}");
            if core::char::UNICODE_VERSION == super::super::UNICODE_VERSION {
                assert_eq!(
                    output,
                    input.to_lowercase(),
                    "whole-string resident reference"
                );
            }
            memory.release_string(output).unwrap();
            assert_eq!(memory.admitted_bytes(), 0);
        }
    }

    #[test]
    fn generated_context_range_boundaries_match_the_existing_whole_string_law() {
        // The compiler's std tables can advance independently of the shipped UCD.
        // Always check the pinned source, and also compare std when its version agrees.
        let source = include_str!("../../../iri/unicode/17.0.0/DerivedCoreProperties.txt");
        let mut ignorable = Vec::new();
        let mut cased = Vec::new();
        for line in source.lines() {
            let line = line.split('#').next().unwrap().trim();
            let Some((span, property)) = line.split_once(';') else {
                continue;
            };
            let target = match property.trim() {
                "Case_Ignorable" => &mut ignorable,
                "Cased" => &mut cased,
                _ => continue,
            };
            let span = span.trim();
            let (low, high) = span.split_once("..").unwrap_or((span, span));
            target.push((
                u32::from_str_radix(low, 16).unwrap(),
                u32::from_str_radix(high, 16).unwrap(),
            ));
        }
        let contains = |character: char, ranges: &[(u32, u32)]| {
            ranges
                .iter()
                .any(|&(low, high)| (low..=high).contains(&u32::from(character)))
        };
        for &(_, ranges) in case_tables::CONTEXT_PROPERTIES {
            for &(low, high) in ranges {
                for point in [low.saturating_sub(1), low, high, high + 1] {
                    let Some(character) = char::from_u32(point) else {
                        continue;
                    };
                    for input in [
                        format!("A{character}Σ"),
                        format!("AΣ{character}B"),
                        format!("{character}Σ"),
                        format!("AΣ{character}"),
                    ] {
                        let mut expected = String::new();
                        for (offset, character) in input.char_indices() {
                            if character == 'Σ' {
                                let preceding = input[..offset]
                                    .chars()
                                    .rev()
                                    .find(|&value| !contains(value, &ignorable));
                                let following = input[offset + character.len_utf8()..]
                                    .chars()
                                    .find(|&value| !contains(value, &ignorable));
                                expected.push(
                                    if preceding.is_some_and(|value| contains(value, &cased))
                                        && !following.is_some_and(|value| contains(value, &cased))
                                    {
                                        'ς'
                                    } else {
                                        'σ'
                                    },
                                );
                            } else {
                                expected.extend(character.to_lowercase());
                            }
                        }
                        if core::char::UNICODE_VERSION == super::super::UNICODE_VERSION {
                            assert_eq!(
                                expected,
                                input.to_lowercase(),
                                "same-version std reference: {input:?}"
                            );
                        }
                        let mut resident = crate::allocation::Resident;
                        let mut memory = Memory::new(&mut resident);
                        let output = lowercase_with_memory(&input, &mut memory).unwrap();
                        assert_eq!(output, expected, "{input:?}");
                        memory.release_string(output).unwrap();
                        assert_eq!(memory.admitted_bytes(), 0);
                    }
                }
            }
        }
    }

    #[test]
    fn long_ignorable_run_uses_the_original_context_without_a_work_buffer() {
        let mut input = String::from("AΣ");
        input.extend(core::iter::repeat_n('\u{301}', 100_000));
        input.push('B');
        let expected = input.to_lowercase();
        let mut resident = crate::allocation::Resident;
        let mut memory = Memory::new(&mut resident);
        let output = lowercase_with_memory(&input, &mut memory).unwrap();
        assert_eq!(output, expected);
        assert!(output.starts_with("aσ"));
        memory.release_string(output).unwrap();
    }
}
