#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

"""Build step: bind the wasm-bindgen glue's handle on the instance's exports to the
asynchronous runtime's poison gate.

The glue (`purrdf_wasm.js`, generated by `wasm-bindgen --target web`) reaches the
wasm instance through one module variable, `wasm`, assigned once in
`__wbg_finalize_init` as `wasm = instance.exports;`. Every constructor, method,
getter, static, free function and finalizer of the package reads its exports
through that variable. A trap out of an asynchronous job leaves the instance dead
(the job's stack context in place of the caller's, borrowed `RefCell`s, possibly
half-applied mutations), so the runtime in `purrdf_jspi.mjs` must be able to bar
every one of those entry points at once. This step rewrites the assignment into

    wasm = <alias>.purrdf_jspi_bind_glue(instance.exports, (gated) => { wasm = gated; });

where `<alias>` is a namespace the glue already imports `./purrdf_jspi.mjs` as.
wasm-bindgen imports the module once per raw import the instance declares
(`purrdf_jspi_suspend`, `purrdf_jspi_panicked`); every one of those namespaces is the
same module instance, so the first serves.
The runtime keeps the reassigning closure and, on poisoning, points `wasm` at an
object that refuses every call. What it returns for a live instance is a copy of the
exports whose functions poison the instance when a trap escapes them, so a trap out
of a synchronous call is seen as well as one out of a job.

The rewrite is exact or the build fails: the glue must import the runtime (at least
once) and assign `wasm = instance.exports;` exactly once, inside
`__wbg_finalize_init`. A glue layout this does not recognize is a wasm-bindgen
change to review, never something to skip.

Usage: `bind-wasm-glue.py <purrdf_wasm.js>` (rewrites in place), or `--self-test`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

IMPORT = re.compile(r'^import \* as ([A-Za-z_$][A-Za-z0-9_$]*) from "\./purrdf_jspi\.mjs"$', re.MULTILINE)
ASSIGNMENT = re.compile(r"^(\s*)wasm = instance\.exports;$", re.MULTILINE)
FINALIZE = re.compile(r"^function __wbg_finalize_init\(instance, module\) \{$", re.MULTILINE)


class GlueError(Exception):
    """The glue's layout is not the one this step rewrites."""


def bind(source: str) -> str:
    """Return `source` with its exports assignment bound to the poison gate."""
    aliases = IMPORT.findall(source)
    if not aliases:
        raise GlueError("expected `import * as <name> from \"./purrdf_jspi.mjs\"`, found none")
    assignments = list(ASSIGNMENT.finditer(source))
    if len(assignments) != 1:
        raise GlueError(f"expected one `wasm = instance.exports;`, found {len(assignments)}")
    finalizers = list(FINALIZE.finditer(source))
    if len(finalizers) != 1:
        raise GlueError(f"expected one `function __wbg_finalize_init(instance, module) {{`, found {len(finalizers)}")
    assignment = assignments[0]
    body_start = finalizers[0].end()
    body_end = source.find("\n}", body_start)
    if not body_start < assignment.start() < body_end:
        raise GlueError("`wasm = instance.exports;` is not inside `__wbg_finalize_init`")
    indent = assignment.group(1)
    bound = f"{indent}wasm = {aliases[0]}.purrdf_jspi_bind_glue(instance.exports, (gated) => {{ wasm = gated; }});"
    return source[: assignment.start()] + bound + source[assignment.end() :]


GLUE = """import * as import1 from "./purrdf_jspi.mjs"

let wasmModule, wasmInstance, wasm;
function __wbg_finalize_init(instance, module) {
    wasmInstance = instance;
    wasm = instance.exports;
    wasmModule = module;
    wasm.__wbindgen_start();
    return wasm;
}
"""


def self_test() -> None:
    bound = bind(GLUE)
    expected = "    wasm = import1.purrdf_jspi_bind_glue(instance.exports, (gated) => { wasm = gated; });"
    assert expected in bound, bound
    assert "wasm = instance.exports;" not in bound
    assert bound.replace(expected, "    wasm = instance.exports;") == GLUE
    # One namespace import per raw import: the first alias is bound, and the rest of the
    # glue is untouched.
    twice = GLUE.replace(
        'import * as import1 from "./purrdf_jspi.mjs"\n',
        'import * as import1 from "./purrdf_jspi.mjs"\nimport * as import2 from "./purrdf_jspi.mjs"\n',
    )
    bound_twice = bind(twice)
    assert expected in bound_twice, bound_twice
    assert bound_twice.replace(expected, "    wasm = instance.exports;") == twice
    refusals = {
        "no runtime import": GLUE.replace('import * as import1 from "./purrdf_jspi.mjs"\n', ""),
        "already bound": bound,
        "two assignments": GLUE + "wasm = instance.exports;\n",
        "outside the finalizer": GLUE.replace("    wasm = instance.exports;\n", "") + "wasm = instance.exports;\n",
        "renamed finalizer": GLUE.replace("__wbg_finalize_init", "__wbg_finish"),
    }
    for name, source in refusals.items():
        try:
            bind(source)
        except GlueError:
            continue
        raise AssertionError(f"the {name} fixture was not refused")
    print("OK: bind-wasm-glue self-test passed")


def main(argv: list[str]) -> int:
    if argv == ["--self-test"]:
        self_test()
        return 0
    if len(argv) != 1:
        print("usage: bind-wasm-glue.py <purrdf_wasm.js> | --self-test", file=sys.stderr)
        return 2
    path = Path(argv[0])
    try:
        path.write_text(bind(path.read_text(encoding="utf-8")), encoding="utf-8")
    except GlueError as error:
        print(f"ERROR: {path}: {error}", file=sys.stderr)
        return 1
    print(f"OK: {path} binds its exports to the poison gate")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
