#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

set -euo pipefail

mode="${1:---check}"
if [ "$#" -gt 1 ]; then
  echo "usage: $0 [--check|--write]" >&2
  exit 2
fi
case "$mode" in
  --check | --write) ;;
  *)
    echo "usage: $0 [--check|--write]" >&2
    exit 2
    ;;
esac

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# The scratch lives beside the build output, not under $TMPDIR: this gate
# generates into it across a `cargo` build that may take minutes, and /tmp is
# not a place a directory survives that reliably. See scripts/build-scratch.sh.
. "$(dirname "${BASH_SOURCE[0]}")/build-scratch.sh"
tmp="$(build_scratch_dir check-generated)"
trap 'rm -rf "$tmp"' EXIT

cd "$repo"

cargo run -p purrdf-rdf --example gen_loss_matrix --locked -- rdf \
  > "$tmp/rdf-loss-matrix.json"
cargo run -p purrdf-rdf --example gen_loss_matrix --locked -- transcode \
  > "$tmp/transcode-loss-matrix.json"
# The entailment rule inventory, read out of `RuleId` / `rules()` / `implemented()`
# rather than transcribed. Guarding it here is what keeps a coverage claim in the
# book a build artifact instead of a sentence someone has to remember to update.
cargo run -p purrdf-entail --example gen_rule_inventory --locked \
  > "$tmp/entailment-rules.md"
# The XSD/XPath `\p{IsX}` Unicode block-escape lookup table, parsed out of the
# vendored `Blocks.txt` rather than transcribed. Piped through `rustfmt` because
# the generator's raw output is committed as real Rust source
# (`crates/rdf-core/src/xsd_regex/blocks.rs`), which `cargo fmt --all --check`
# also governs — comparing pre-rustfmt bytes here would make the file
# permanently "stale" the moment anyone reformats the workspace.
cargo run -p purrdf-core --example gen_unicode_blocks --locked \
  | rustfmt --edition 2024 --emit stdout \
  > "$tmp/blocks.rs"
# Every other Unicode table in the workspace, generated by the one generator from
# the one vendored Unicode Character Database under `crates/iri/unicode/`, at one
# version: `purrdf_lex::unicode::UNICODE_VERSION`. The generator refuses files of
# another release, and every table set but `normalization` (which carries the
# version) asserts it at compile time.
#   normalization   - purrdf-lex: combining classes, decompositions, composites
#   text            - purrdf-text: full case folding, the UAX 29 word-break data
#   idna            - purrdf-iri: the RFC 5892 derived property and the IDNA tables
#   ecma-properties - purrdf-jsonschema: the names an ECMA-262 `\p{…}` may spell
#   ecma-ranges     - purrdf-jsonschema: those properties' ranges, simple folding
for set in normalization text idna ecma-properties ecma-ranges; do
  cargo run -p purrdf-lex --example gen_unicode_tables --locked -- "$set" \
    | rustfmt --edition 2024 --emit stdout \
    > "$tmp/unicode-$set.rs"
done

# Complete WHATWG character-reference data, pinned independently of the Unicode
# release. The native generator validates every spelling and numeric recovery
# value; generated source retains the data's separate BSD-3-Clause notice.
cargo run -p purrdf-lex --example gen_html_entities --locked \
  | rustfmt --edition 2024 --emit stdout \
  > "$tmp/html-entities.rs"

# The one Unicode table NOT at `purrdf_lex::unicode::UNICODE_VERSION`, and why:
# the XSD `\p{IsX}` block table of purrdf-core is pinned to the Unicode version of
# the tables embedded in the locked `regex-syntax`, because every translated XSD
# pattern runs on the `regex` engine, and a block escape must agree with the
# engine's own classes at every boundary code point. The pin is the pair below.
# A `regex-syntax` bump fails here until the vendored `Blocks.txt`, the committed
# table and this pair move together (the helpers ledger records the table as a
# criterion-(a) variant of the one Unicode version).
blocks_unicode_pin="16.0.0"
blocks_regex_syntax_pin="0.8.11"
locked_regex_syntax="$(awk '/^name = "regex-syntax"$/ { getline; gsub(/"/, "", $3); print $3 }' Cargo.lock)"
if [ "$locked_regex_syntax" != "$blocks_regex_syntax_pin" ]; then
  echo "Cargo.lock locks regex-syntax ${locked_regex_syntax:-<none>}, but the XSD block table is pinned to regex-syntax $blocks_regex_syntax_pin (Unicode $blocks_unicode_pin); move the pin, Blocks.txt and crates/rdf-core/src/xsd_regex/blocks.rs together." >&2
  exit 1
fi
if [ "$(head -n 1 crates/rdf-core/vendor/unicode/Blocks.txt)" != "# Blocks-$blocks_unicode_pin.txt" ]; then
  echo "crates/rdf-core/vendor/unicode/Blocks.txt is not Unicode $blocks_unicode_pin, the version pinned to regex-syntax $blocks_regex_syntax_pin." >&2
  exit 1
fi
blocks_pin_tuple="(${blocks_unicode_pin//./, })"
if ! grep -qF "    $blocks_pin_tuple" crates/rdf-core/src/xsd_regex/blocks.rs; then
  echo "crates/rdf-core/src/xsd_regex/blocks.rs does not report the pinned Unicode $blocks_unicode_pin from unicode_version()." >&2
  exit 1
fi

check_file() {
  local generated="$1"
  local committed="$2"
  if ! cmp -s "$generated" "$committed"; then
    echo "$committed is stale; regenerate it from the Rust source." >&2
    diff -u "$committed" "$generated" >&2 || true
    exit 1
  fi
}

sync_file() {
  local generated="$1"
  local committed="$2"
  if [ "$mode" = "--write" ]; then
    cp -- "$generated" "$committed"
  fi
  check_file "$generated" "$committed"
}

sync_file "$tmp/rdf-loss-matrix.json" generated/rdf-loss-matrix.json
sync_file "$tmp/transcode-loss-matrix.json" generated/transcode-loss-matrix.json
sync_file "$tmp/entailment-rules.md" docs/book/src/entailment-rules.md
sync_file "$tmp/blocks.rs" crates/rdf-core/src/xsd_regex/blocks.rs
sync_file "$tmp/unicode-normalization.rs" crates/lex/src/unicode_tables.rs
sync_file "$tmp/unicode-text.rs" crates/text/src/unicode_tables.rs
sync_file "$tmp/unicode-idna.rs" crates/iri/src/idna_tables.rs
sync_file "$tmp/unicode-ecma-properties.rs" crates/jsonschema/src/ecma/property_tables.rs
sync_file "$tmp/unicode-ecma-ranges.rs" crates/jsonschema/src/ecma/unicode_ranges.rs
sync_file "$tmp/html-entities.rs" crates/lex/src/html/entities.rs

# Recompute every dictionary row, cost, collision report, canonical artifact and
# expected identity from the frozen separately distributed source data.
cargo run -p purrdf-text --example gen_lexicons --locked -- --check

# The inventory above is now known-current. Prose elsewhere RESTATES its numbers
# (and the conformance matrix's), and prose is not covered by any byte-diff — a
# coverage table sat at `RDFS 14 / 18` for exactly that reason, three lines under
# a sentence promising it could not fall behind. This gate machine-checks every
# such restatement against the generated artifact it claims to summarize.
python3 scripts/check-doc-claims.py

viz_tmp="$tmp/visualization"
viz_committed="docs/book/src/assets/visualization"
cargo run -p purrdf-rdf --example viz_samples --locked -- \
  "$viz_tmp" --svg-only

generated_count=0
for generated_svg in "$viz_tmp"/*.svg; do
  generated_count=$((generated_count + 1))
  sync_file "$generated_svg" "$viz_committed/$(basename "$generated_svg")"
done
if [ "$mode" = "--write" ]; then
  for committed_svg in "$viz_committed"/*.svg; do
    [ -e "$committed_svg" ] || continue
    if [ ! -e "$viz_tmp/$(basename "$committed_svg")" ]; then
      rm -- "$committed_svg"
    fi
  done
fi
committed_count=$(find "$viz_committed" -maxdepth 1 -type f -name '*.svg' | wc -l)
if [ "$generated_count" -ne "$committed_count" ]; then
  echo "$viz_committed contains stale or missing SVG samples" >&2
  exit 1
fi

cargo test -p purrdf-core --lib --locked \
  sssom::tests::corpus_accessibility_parses_and_validates_clean
