#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

"""Hold the workspace's hash domains unique, prefix-free and spelt through ``Domain``.

A hash domain is the byte string that names one preimage family: a digest of one
structure can never be read as a digest of another because each preimage starts
with (or carries, as its named ``domain`` part) its own domain. Every domain in
shipping code is a ``purrdf_hash::Domain`` constant, registered next to the
construction it separates. This gate collects every ``Domain::new(b"…")`` (and
``Domain::new("…".as_bytes())``) literal in shipping Rust — ``src/`` trees
outside ``#[cfg(test)]`` items and test-only modules — and fails on:

* **a duplicate**: two registrations with the same bytes. One family has one
  domain constant; a second construction needs its own domain;
* **a prefix violation**: one domain is a byte-prefix of another, so a preimage
  under the shorter one could begin like a preimage under the longer one;
* **an empty domain**, which is a prefix of every other one;
* **a raw domain literal** (rule ``raw-hash-domain``): a domain-shaped string or
  byte-string literal handed to a hasher, or declared as a domain constant,
  without going through ``Domain``. The rule, stated exactly:

  - a *hasher call* is ``.update(``, ``.chain_update(``, ``::digest(``,
    ``blake3::hash(``, ``derive_key(``, ``new_keyed(``, ``fnv1a64(``,
    ``fnv::fold(``, a framing helper (any ``frame…(``, ``frame_str(`` and
    ``frame_hash(`` included), a ``push_part(``/``append_framed(``/
    ``append_framed_part(``/``append_key_part(`` preimage part, ``.field(`` on
    a digest builder or a digest builder's ``Digest::new(``; a domain-shaped
    literal anywhere in the call's argument list is a hit;
  - a literal is *domain-shaped* when it holds a NUL byte, when it carries a
    version token (``v`` and digits after ``-``, ``.``, ``/``, ``:``, ``_`` or a
    space, ending the literal or followed by a separator), or when its bytes
    equal or begin with a registered domain;
  - a *domain constant* is a ``const`` or ``static`` whose name contains
    ``DOMAIN``, ``DIGEST_TAG``, ``IDENTITY_TAG`` or ``KEY_SALT``, or is ``D_``
    followed by an upper-case name, typed as a string or byte string. Its value
    is a hit unless it is an IRI (``RDFS_DOMAIN``, the vocabulary term, is a
    constant of that name and no hash domain) and not domain-shaped.

  Field labels inside a preimage (``b"slice-iri\\x1f"``), separators and
  protocol bytes are not domain-shaped and pass. Test code is out of scope: a
  test that recomputes a frozen digest from its raw preimage is an independent
  oracle, not a second spelling;
* **a shared domain** (rule ``shared-hash-domain``): a registered domain that
  appears in hasher calls of two or more functions of the file registering it —
  one domain opening two constructions. Openings of one constant from different
  files are not compared: they are the streaming and one-shot forms of one
  construction.

Exceptions are rows of the ``hash-domain`` job in ``helpers-ledger.toml`` whose
``detector`` is one of this gate's rules, each naming a documented anchor:

* ``shared-hash-domain`` sanctions the shared domain its ``symbol`` names;
* ``undomained-digest`` records a function that computes a published identity
  digest with no domain. There is no workspace-wide ``undomained-digest``
  refusal — a content address over raw bytes, an RDFC hash or a SPARQL ``MD5()``
  needs no domain, and no syntax tells those from an identity preimage — so the
  row is the record of a reviewed decision, and it is held true: the function
  must still compute a digest and name no ``Domain``.

A row that no longer matches its detector is STALE and fails, and a row without
an anchor fails; ``check-shared-helpers.py`` resolves the anchors through the
census and requires their documentation.

The registry table in ``crates/hash/README.md`` (between the
``hash-domain-registry`` markers) is the collected set; this gate fails when the
two differ, and ``--write-readme`` regenerates the table. ``--self-test`` runs
seeded workspaces through every rule, each refusal beside a valid neighbour that
passes. ``--list`` prints the collected set.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = PurePosixPath("crates/hash/README.md")
README_BEGIN = "<!-- hash-domain-registry:begin (generated by scripts/check-hash-domains.py --write-readme) -->"
README_END = "<!-- hash-domain-registry:end -->"
RULE_ID = "raw-hash-domain"
SHARED_RULE_ID = "shared-hash-domain"
UNDOMAINED_RULE_ID = "undomained-digest"
EXCEPTION_RULES = (SHARED_RULE_ID, UNDOMAINED_RULE_ID)
LEDGER_PATH = PurePosixPath("helpers-ledger.toml")
LEDGER_JOB = "hash-domain"

# ---------------------------------------------------------------------------
# Lexing: comments blanked, literals replaced by numbered placeholders, so the
# rules below are regular expressions over code alone.


@dataclass(frozen=True)
class Literal:
    """One string or byte-string literal: its decoded bytes and where it starts."""

    data: bytes
    line: int
    byte_string: bool


PLACEHOLDER = re.compile(r"\x00(\d+)\x00")


def decode_escapes(body: str, byte_string: bool) -> bytes:
    """The bytes a non-raw Rust (byte) string literal body denotes."""
    out = bytearray()
    index = 0
    while index < len(body):
        char = body[index]
        if char != "\\":
            out += char.encode("utf-8")
            index += 1
            continue
        kind = body[index + 1]
        index += 2
        if kind == "n":
            out += b"\n"
        elif kind == "r":
            out += b"\r"
        elif kind == "t":
            out += b"\t"
        elif kind == "0":
            out += b"\0"
        elif kind in "\\'\"":
            out += kind.encode()
        elif kind == "x":
            value = int(body[index : index + 2], 16)
            out += bytes([value]) if byte_string else chr(value).encode("utf-8")
            index += 2
        elif kind == "u":
            close = body.index("}", index)
            out += chr(int(body[index + 1 : close].replace("_", ""), 16)).encode("utf-8")
            index = close + 1
        elif kind == "\n":
            while index < len(body) and body[index] in " \t\r\n":
                index += 1
        else:
            raise ValueError(f"unknown escape \\{kind}")
    return bytes(out)


TOKEN = re.compile(
    r"(?P<line>//)|(?P<block>/\*)"
    r"|(?<![A-Za-z0-9_])(?P<raw>(?P<raw_prefix>[bc]?)r(?P<hashes>#*)\")"
    r"|(?P<plain>(?<![A-Za-z0-9_])(?P<plain_prefix>[bc]?)\"|\")"
    r"|(?<![A-Za-z0-9_])(?P<char>b?')"
)
CHAR_BODY = re.compile(r"(?:\\(?:x[0-9a-fA-F]{2}|u\{[0-9a-fA-F_]+\}|.)|[^\\\n])'")


def mask(source: str) -> tuple[str, list[Literal]]:
    """``source`` with comments blanked and every string, byte-string and raw
    literal replaced by ``\\0<n>\\0`` (its index into the returned list). Line
    breaks are kept, so a position's line number is unchanged."""
    out: list[str] = []
    literals: list[Literal] = []
    index = 0
    counted = [0, 1]  # a position, and the line it is on

    def keep_lines(text: str) -> str:
        return "\n" * text.count("\n")

    def literal(text: str, data: bytes, byte_string: bool) -> None:
        counted[1] += source.count("\n", counted[0], index)
        counted[0] = index
        literals.append(Literal(data, counted[1], byte_string))
        out.append(f"\x00{len(literals) - 1}\x00" + keep_lines(text))

    while True:
        token = TOKEN.search(source, index)
        if token is None:
            out.append(source[index:])
            break
        out.append(source[index : token.start()])
        index = token.start()
        if token.group("line"):
            end = source.find("\n", index)
            index = len(source) if end == -1 else end
        elif token.group("block"):
            depth, cursor = 1, token.end()
            while cursor < len(source) and depth:
                if source.startswith("/*", cursor):
                    depth, cursor = depth + 1, cursor + 2
                elif source.startswith("*/", cursor):
                    depth, cursor = depth - 1, cursor + 2
                else:
                    cursor += 1
            out.append(keep_lines(source[index:cursor]))
            index = cursor
        elif token.group("raw"):
            hashes = token.group("hashes")
            end = source.index('"' + hashes, token.end())
            text = source[token.end() : end]
            literal(text, text.encode("utf-8"), token.group("raw_prefix") == "b")
            index = end + 1 + len(hashes)
        elif token.group("plain"):
            cursor = token.end()
            while source[cursor] != '"':
                cursor += 2 if source[cursor] == "\\" else 1
            text = source[token.end() : cursor]
            byte_string = token.group("plain_prefix") == "b"
            literal(text, decode_escapes(text, byte_string), byte_string)
            index = cursor + 1
        else:
            character = CHAR_BODY.match(source, token.end())
            if character:
                out.append("' '")
                index = character.end()
            else:
                out.append(token.group(0))
                index = token.end()
    return "".join(out), literals


def line_of(code: str, position: int) -> int:
    return code.count("\n", 0, position) + 1


def matching_brace(code: str, open_at: int) -> int:
    depth = 0
    for cursor in range(open_at, len(code)):
        if code[cursor] == "{":
            depth += 1
        elif code[cursor] == "}":
            depth -= 1
            if depth == 0:
                return cursor
    return len(code) - 1


CFG_TEST = re.compile(r"#\[cfg\((?:test|all\(test\b[^\]]*\)|any\(test\b[^\]]*\))\)\]")
ATTRIBUTE = re.compile(r"\s*#!?\[[^\]]*\]")
TEST_MOD_DECL = re.compile(r"\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*;")


def strip_test_items(code: str) -> tuple[str, list[str]]:
    """``code`` with every ``#[cfg(test)]`` item blanked, and the names of the
    test-only modules it declares out of line (``#[cfg(test)] mod name;``)."""
    out = code
    out_of_line: list[str] = []
    for found in reversed(list(CFG_TEST.finditer(code))):
        cursor = found.end()
        while True:
            attribute = ATTRIBUTE.match(code, cursor)
            if not attribute:
                break
            cursor = attribute.end()
        declaration = TEST_MOD_DECL.match(code, cursor)
        if declaration:
            out_of_line.append(declaration.group(1))
            end = declaration.end()
        else:
            brace = code.find("{", cursor)
            semicolon = code.find(";", cursor)
            if brace != -1 and (semicolon == -1 or brace < semicolon):
                end = matching_brace(code, brace) + 1
            else:
                end = semicolon + 1 if semicolon != -1 else len(code)
        blanked = "".join("\n" if char == "\n" else " " for char in code[found.start() : end])
        out = out[: found.start()] + blanked + out[end:]
    return out, out_of_line


def child_module_paths(file: PurePosixPath, name: str) -> list[PurePosixPath]:
    """Where an out-of-line ``mod name;`` declared in ``file`` lives."""
    directory = file.parent if file.name in ("lib.rs", "main.rs", "mod.rs") else file.parent / file.stem
    return [directory / f"{name}.rs", directory / name / "mod.rs"]


# ---------------------------------------------------------------------------
# Collection.


@dataclass(frozen=True)
class Registration:
    """One ``Domain::new(…)`` literal in shipping code."""

    data: bytes
    file: str
    line: int
    const: str


@dataclass(frozen=True)
class Scan:
    registrations: list[Registration]
    hasher_literals: list[tuple[str, int, bytes, str]]
    domain_consts: list[tuple[str, int, bytes, str]]
    # ``(file, line, const, detail)``: a registered domain that opens hashers in
    # two or more functions of its file.
    shared: list[tuple[str, int, str, str]]
    # ``(file, function)``: every function that computes a digest and names no
    # ``Domain``.
    undomained: set[tuple[str, str]]


DOMAIN_NEW = re.compile(r"\bDomain::new\(\s*(?:&\s*)?\x00(\d+)\x00\s*(?:\.as_bytes\(\)\s*)?\)")
CONST_NAME_BEFORE = re.compile(r"\b(?:const|static)\s+([A-Z][A-Z0-9_]*)\s*:[^=;]*=\s*$")
HASHER_CALL = re.compile(
    r"(?:\.(?:update|chain_update|field)|::digest|\bblake3::hash|\bderive_key|\bnew_keyed|\bfnv1a64|\bfnv::fold"
    r"|\bframe\w*|\bpush_part|\bappend_framed(?:_part)?|\bappend_key_part|\bDigest::new|\bhash_fold"
    r"|\b\w*Hasher::new)\s*\("
)
DIGEST_OPEN = re.compile(
    r"\b(?:Hasher|RecordHasher|Sha1|Sha224|Sha256|Sha384|Sha512|Sha3_\d+|Md5)::new\(\)|\bDigest::bare\("
    r"|::digest\(|\bblake3::hash\(|\bblake3_256\(|\bContentDigest::of\("
)
FUNCTION = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)")
DOMAIN_CONST = re.compile(
    r"\b(?:const|static)\s+([A-Z][A-Z0-9_]*)\s*:\s*&\s*(?:'static\s+)?(?:str|\[u8\]|\[u8;\s*\d+\])\s*=\s*\x00(\d+)\x00"
)
DOMAIN_CONST_NAME = re.compile(r"DOMAIN|DIGEST_TAG|IDENTITY_TAG|KEY_SALT|^D_[A-Z]")
IRI = re.compile(rb"[A-Za-z][A-Za-z0-9+.-]*:(?://|[^/])")
VERSION_TOKEN = re.compile(rb"[-./:_ ]v\d+(?=$|[-./:_ \x00\x1f])")


def call_arguments(code: str, open_at: int) -> str:
    """The text between the parenthesis at ``open_at`` and its match."""
    depth = 0
    for cursor in range(open_at, len(code)):
        if code[cursor] == "(":
            depth += 1
        elif code[cursor] == ")":
            depth -= 1
            if depth == 0:
                return code[open_at + 1 : cursor]
    return code[open_at + 1 :]


def function_spans(code: str) -> list[tuple[int, int, str]]:
    """``(start, end, name)`` of every function with a body."""
    spans = []
    for found in FUNCTION.finditer(code):
        depth = 0
        for cursor in range(found.end(), len(code)):
            char = code[cursor]
            if char in "([":
                depth += 1
            elif char in ")]":
                depth -= 1
            elif depth == 0 and char == ";":
                break
            elif depth == 0 and char == "{":
                spans.append((found.start(), matching_brace(code, cursor), found.group(1)))
                break
    return spans


def enclosing_function(spans: list[tuple[int, int, str]], position: int) -> str | None:
    """The innermost function around ``position``."""
    around = [span for span in spans if span[0] <= position <= span[1]]
    return min(around, key=lambda span: span[1] - span[0])[2] if around else None


def scan_source(path: str, source: str) -> Scan:
    """Every registration, hasher-call literal and domain constant in one file of
    shipping code (its ``#[cfg(test)]`` items already excluded by the caller)."""
    code, literals = mask(source)
    code, _ = strip_test_items(code)
    registrations = []
    for found in DOMAIN_NEW.finditer(code):
        head = code[max(0, found.start() - 200) : found.start()]
        const = CONST_NAME_BEFORE.search(head)
        literal = literals[int(found.group(1))]
        registrations.append(
            Registration(literal.data, path, line_of(code, found.start()), const.group(1) if const else "(inline)")
        )
    hasher_literals = []
    for call in HASHER_CALL.finditer(code):
        arguments = call_arguments(code, call.end() - 1)
        for placeholder in PLACEHOLDER.finditer(arguments):
            if re.search(r"Domain::new\(\s*(?:&\s*)?$", arguments[: placeholder.start()]):
                continue
            literal = literals[int(placeholder.group(1))]
            hasher_literals.append((path, line_of(code, call.start()), literal.data, call.group(0).rstrip("( ")))
    domain_consts = []
    for found in DOMAIN_CONST.finditer(code):
        if DOMAIN_CONST_NAME.search(found.group(1)):
            literal = literals[int(found.group(2))]
            domain_consts.append((path, line_of(code, found.start()), literal.data, found.group(1)))
    spans = function_spans(code)
    local = {registration.const for registration in registrations}
    openers: dict[str, set[str]] = {}
    first_line: dict[str, int] = {}
    for call in HASHER_CALL.finditer(code):
        arguments = call_arguments(code, call.end() - 1)
        function = enclosing_function(spans, call.start())
        for const in local:
            if function is not None and re.search(rf"\b{const}\b", arguments):
                openers.setdefault(const, set()).add(function)
                first_line.setdefault(const, line_of(code, call.start()))
    shared = [
        (path, first_line[const], const, f"`{const}` opens hashers in {len(functions)} functions ({', '.join(sorted(functions))})")
        for const, functions in sorted(openers.items())
        if len(functions) > 1
    ]
    undomained = set()
    for start, end, name in spans:
        body = code[start:end]
        if DIGEST_OPEN.search(body) and not re.search(r"\bDomain\b", body) and not any(re.search(rf"\b{const}\b", body) for const in local):
            undomained.add((path, name))
    return Scan(registrations, hasher_literals, domain_consts, shared, undomained)


def shipping_files(root: Path) -> dict[str, str]:
    """Every shipping ``.rs`` file under a ``src/`` tree of ``crates/`` or
    ``bindings/``, minus the test-only modules declared out of line."""
    listing = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "--", "crates", "bindings"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    files = {
        path: (root / path).read_text(encoding="utf-8")
        for path in listing
        if path.endswith(".rs") and "/src/" in path and (root / path).is_file()
    }
    return drop_test_modules(files)


def drop_test_modules(files: dict[str, str]) -> dict[str, str]:
    """``files`` without the modules a ``#[cfg(test)] mod name;`` declares, and
    without whatever those modules declare in turn."""
    excluded: set[str] = set()
    pending: list[tuple[str, bool]] = [(path, False) for path in files]
    seen: set[str] = set()
    while pending:
        path, inherited = pending.pop()
        if path in seen and not inherited:
            continue
        seen.add(path)
        if inherited:
            excluded.add(path)
        code, _ = mask(files[path])
        _, test_children = strip_test_items(code)
        all_children = [found.group(1) for found in TEST_MOD_DECL.finditer(code)] if inherited else []
        for name in test_children + all_children:
            for candidate in child_module_paths(PurePosixPath(path), name):
                if str(candidate) in files and str(candidate) not in excluded:
                    pending.append((str(candidate), True))
    return {path: text for path, text in files.items() if path not in excluded}


def scan_workspace(files: dict[str, str]) -> Scan:
    registrations, hasher_literals, domain_consts, shared, undomained = [], [], [], [], set()
    for path in sorted(files):
        scan = scan_source(path, files[path])
        registrations += scan.registrations
        hasher_literals += scan.hasher_literals
        domain_consts += scan.domain_consts
        shared += scan.shared
        undomained |= scan.undomained
    return Scan(registrations, hasher_literals, domain_consts, shared, undomained)


# ---------------------------------------------------------------------------
# The rules.


def render(data: bytes) -> str:
    """A byte-string literal body for ``data`` (printable ASCII kept)."""
    out = []
    for byte in data:
        if byte == 0:
            out.append("\\0")
        elif byte in (0x22, 0x5C):
            out.append("\\" + chr(byte))
        elif 0x20 <= byte < 0x7F:
            out.append(chr(byte))
        else:
            out.append(f"\\x{byte:02x}")
    return "".join(out)


def domain_shaped(data: bytes, registered: set[bytes]) -> bool:
    """Whether a literal looks like a hash domain (see the module docs)."""
    if b"\0" in data or VERSION_TOKEN.search(data):
        return True
    return any(data.startswith(domain) for domain in registered)


def raw_literal_hits(scan: Scan) -> list[tuple[str, int, str]]:
    """``(file, line, detail)`` for every ``raw-hash-domain`` hit."""
    registered = {registration.data for registration in scan.registrations if registration.data}
    hits = []
    for path, line, data, call in scan.hasher_literals:
        if domain_shaped(data, registered):
            hits.append((path, line, f'b"{render(data)}" is handed to `{call}(…)` without a `Domain`'))
    for path, line, data, name in scan.domain_consts:
        if data and (domain_shaped(data, registered) or not IRI.match(data)):
            hits.append((path, line, f'`{name}` = b"{render(data)}" is a domain constant that is not a `Domain`'))
    return sorted(set(hits))


def item_name(symbol: str) -> str:
    """The last path segment of a ledger ``crate::path::item`` symbol."""
    return symbol.rsplit("::", 1)[-1]


def exception_matches(scan: Scan) -> set[tuple[str, str, str]]:
    """``(file, detector, item)`` for everything a ledger exception row may name:
    each ``shared-hash-domain`` hit, and each function that computes a digest
    without a ``Domain`` (``undomained-digest``). A row outside this set is
    STALE."""
    matched = {(path, SHARED_RULE_ID, const) for path, _line, const, _detail in scan.shared}
    matched |= {(path, UNDOMAINED_RULE_ID, function) for path, function in scan.undomained}
    return matched


def ledger_exceptions(ledger_path: Path = REPO_ROOT / LEDGER_PATH) -> list[dict]:
    """The ``hash-domain`` job's variant rows whose detector is one of this
    gate's rules."""
    with ledger_path.open("rb") as handle:
        ledger = tomllib.load(handle)
    return [
        variant
        for job in ledger.get("job", [])
        if job["id"] == LEDGER_JOB
        for variant in job.get("variant", [])
        if variant["detector"] in EXCEPTION_RULES
    ]


def rule_hits(scan: Scan) -> dict[str, list[tuple[str, int, str, str]]]:
    """This gate's hits, by census rule id, as ``(file, line, item, detail)``:
    what ``check-shared-helpers.py`` adds to the ledger job naming each rule."""
    return {
        f"rule:{RULE_ID}": [(path, line, "", detail) for path, line, detail in raw_literal_hits(scan)],
        f"rule:{SHARED_RULE_ID}": [(path, line, const, detail) for path, line, const, detail in scan.shared],
    }


def exception_findings(scan: Scan, exceptions: list[dict]) -> list[str]:
    """Every ``shared-hash-domain`` hit no exception row declares, and every row
    that is STALE or names no anchor. The rows' anchors are resolved, and their
    documentation required, by ``check-shared-helpers.py`` through the census."""
    findings = []
    declared = {(row["file"], row["detector"], item_name(row["symbol"])) for row in exceptions}
    for path, line, const, detail in scan.shared:
        if (path, SHARED_RULE_ID, const) not in declared:
            findings.append(
                f"FAIL: {path}:{line}: rule:{SHARED_RULE_ID}: {detail}; one domain names one preimage family — "
                f"give each construction its own domain, or declare a published identity as a `{LEDGER_JOB}` "
                "variant row in helpers-ledger.toml"
            )
    matched = exception_matches(scan)
    for row in exceptions:
        where = f"helpers-ledger.toml `{LEDGER_JOB}` variant `{row['symbol']}`"
        if not row.get("anchor"):
            findings.append(f"FAIL: {where}: names no documented anchor stating why it may exist")
        if (row["file"], row["detector"], item_name(row["symbol"])) not in matched:
            findings.append(
                f"FAIL: {where}: STALE — {row['file']} no longer has a `{item_name(row['symbol'])}` the "
                f"`{row['detector']}` detector matches; remove the row"
            )
    return findings


def registry_findings(scan: Scan, exceptions: list[dict] | None = None) -> list[str]:
    findings = []
    by_bytes: dict[bytes, list[Registration]] = {}
    for registration in scan.registrations:
        by_bytes.setdefault(registration.data, []).append(registration)
    for data, sites in sorted(by_bytes.items()):
        if not data:
            for site in sites:
                findings.append(f"FAIL: {site.file}:{site.line}: `{site.const}` is an empty domain, a prefix of every other")
        if len(sites) > 1:
            where = ", ".join(f"{site.file}:{site.line} `{site.const}`" for site in sites)
            findings.append(f'FAIL: domain b"{render(data)}" is registered {len(sites)} times ({where}); one family, one domain')
    distinct = sorted(data for data in by_bytes if data)
    for shorter in distinct:
        for longer in distinct:
            if longer != shorter and longer.startswith(shorter):
                first, second = by_bytes[shorter][0], by_bytes[longer][0]
                findings.append(
                    f'FAIL: domain b"{render(shorter)}" ({first.file}:{first.line} `{first.const}`) is a prefix of '
                    f'b"{render(longer)}" ({second.file}:{second.line} `{second.const}`)'
                )
    for path, line, detail in raw_literal_hits(scan):
        findings.append(f"FAIL: {path}:{line}: rule:{RULE_ID}: {detail}")
    findings.extend(exception_findings(scan, exceptions or []))
    return findings


def readme_table(scan: Scan) -> str:
    rows = sorted(scan.registrations, key=lambda registration: (registration.data, registration.file))
    lines = [
        README_BEGIN,
        "",
        "| Domain bytes | Constant | Defined in |",
        "|---|---|---|",
    ]
    for registration in rows:
        lines.append(f'| `b"{render(registration.data)}"` | `{registration.const}` | `{registration.file}` |')
    lines += ["", README_END]
    return "\n".join(lines)


def readme_with_table(readme: str, table: str) -> str | None:
    begin, end = readme.find(README_BEGIN), readme.find(README_END)
    if begin == -1 or end == -1 or end < begin:
        return None
    return readme[:begin] + table + readme[end + len(README_END) :]


# ---------------------------------------------------------------------------
# Self-test: seeded workspaces, each refusal beside a valid neighbour.

CLEAN_WORKSPACE = {
    "crates/alpha/src/lib.rs": (
        "use purrdf_hash::Domain;\n"
        "/// A slashed domain.\n"
        'pub const RECORD_DOMAIN: Domain = Domain::new(b"purrdf-alpha/record/v1");\n'
        'pub(crate) const D_ARTIFACT: Domain = Domain::new(b"purrdf.alpha.v1.artifact\\0");\n'
        'const D_ARTIFACT_SET: Domain = Domain::new(b"purrdf.alpha.v1.artifact-set\\0");\n'
        'const SNAPSHOT: Domain = Domain::new("path-snapshot-edge-set-v1".as_bytes());\n'
        "pub fn digest(hasher: &mut Hasher, iri: &str) {\n"
        "    hasher.update(RECORD_DOMAIN.as_bytes());\n"
        '    hasher.update(b"\\x1f");\n'
        '    hasher.update(b"slice-iri\\x1f");\n'
        "    hasher.update(iri.as_bytes()); // b\"purrdf-alpha/record/v1\" in a comment is fine\n"
        '    push_part(&mut bytes, b"domain", RECORD_DOMAIN.as_bytes());\n'
        '    let _message = "a version string v2 that is not hashed";\n'
        "}\n"
        '/// `hasher.update(b"purrdf-alpha/raw/v1")` in documentation is not code.\n'
        "pub const RDFS_DOMAIN: &str = \"http://www.w3.org/2000/01/rdf-schema#domain\";\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        '    const RECORD_DOMAIN: Domain = Domain::new(b"purrdf-alpha/record/v1");\n'
        '    fn oracle(h: &mut Hasher) { h.update(b"purrdf-alpha/record/v1"); }\n'
        "}\n"
        "#[cfg(test)]\n"
        "mod golden;\n"
    ),
    "crates/alpha/src/golden.rs": 'fn oracle(h: &mut Hasher) { h.update(b"purrdf.alpha.v1.artifact\\0"); }\n',
    "crates/alpha/tests/it.rs": 'const X: Domain = Domain::new(b"purrdf-alpha/record/v1");\n',
    "crates/beta/src/lib.rs": (
        "use purrdf_hash::Domain;\n"
        'const LEAF_DOMAIN: Domain = Domain::new(b"gts-mmr-leaf-v1");\n'
        'const PARENT_DOMAIN: Domain = Domain::new(b"gts-mmr-parent-v1");\n'
        'const ROOT: Domain = Domain::new(br"merkle-root");\n'
    ),
}


def run_fixture(files: dict[str, str], exceptions: list[dict] | None = None) -> list[str]:
    with tempfile.TemporaryDirectory(prefix="hash-domain-fixture-") as directory:
        root = Path(directory)
        for relative, text in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        subprocess.run(["git", "init", "-q"], cwd=root, check=True)
        return registry_findings(scan_workspace(shipping_files(root)), exceptions)


def with_line(file: str, line: str) -> dict[str, str]:
    files = dict(CLEAN_WORKSPACE)
    files[file] = files[file] + line
    return files


SELF_TEST_CASES: list[tuple[str, dict[str, str], str | None]] = [
    ("the clean seeded workspace passes, its tests and test modules out of scope", CLEAN_WORKSPACE, None),
    (
        "a second registration of the same bytes is refused",
        with_line("crates/beta/src/lib.rs", 'const AGAIN: Domain = Domain::new(b"purrdf-alpha/record/v1");\n'),
        "registered 2 times",
    ),
    (
        "a registration extending another one is refused as a prefix violation",
        with_line("crates/beta/src/lib.rs", 'const OTHER: Domain = Domain::new(b"purrdf-alpha/record/v12");\n'),
        "is a prefix of",
    ),
    (
        "a registration differing in its last byte passes",
        with_line("crates/beta/src/lib.rs", 'const OTHER: Domain = Domain::new(b"purrdf-alpha/record/v2");\n'),
        None,
    ),
    (
        "a domain that is a byte-prefix of another is refused",
        with_line("crates/beta/src/lib.rs", 'const MMR: Domain = Domain::new(b"gts-mmr-leaf");\n'),
        "is a prefix of",
    ),
    (
        "a NUL-terminated neighbour of a registered domain is not its prefix and passes",
        with_line("crates/beta/src/lib.rs", 'const D_ARTIFACTS: Domain = Domain::new(b"purrdf.alpha.v1.artifacts\\0");\n'),
        None,
    ),
    (
        "an empty domain is refused",
        with_line("crates/beta/src/lib.rs", 'const NOTHING: Domain = Domain::new(b"");\n'),
        "empty domain",
    ),
    (
        "a one-byte domain that begins no other one passes",
        with_line("crates/beta/src/lib.rs", 'const X: Domain = Domain::new(b"x");\n'),
        None,
    ),
    (
        "a versioned byte literal handed to update is refused",
        with_line("crates/beta/src/lib.rs", 'fn f(h: &mut H) { h.update(b"purrdf-beta/raw/v1"); }\n'),
        f"rule:{RULE_ID}",
    ),
    (
        "the same bytes through a registered Domain pass",
        with_line(
            "crates/beta/src/lib.rs",
            'const RAW: Domain = Domain::new(b"purrdf-beta/raw/v1");\nfn f(h: &mut H) { h.update(RAW.as_bytes()); }\n',
        ),
        None,
    ),
    (
        "a NUL-terminated str literal framed into a hasher is refused",
        with_line("crates/beta/src/lib.rs", 'fn f(h: &mut H) { frame_str(h, "purrdf.beta.tag\\0"); }\n'),
        f"rule:{RULE_ID}",
    ),
    (
        "a field label framed into a hasher passes",
        with_line("crates/beta/src/lib.rs", 'fn f(h: &mut H) { frame_str(h, "graph"); h.update(b"merkle\\x1f"); }\n'),
        None,
    ),
    (
        "a literal re-spelling a registered unversioned domain is refused",
        with_line("crates/beta/src/lib.rs", 'fn f(h: &mut H) { h.update(b"merkle-root\\x1f"); }\n'),
        f"rule:{RULE_ID}",
    ),
    (
        "a one-shot digest over a versioned literal is refused",
        with_line("crates/beta/src/lib.rs", 'fn f() { Sha256::digest(b"gts-thing-v3"); }\n'),
        f"rule:{RULE_ID}",
    ),
    (
        "a one-shot digest over a word with a v inside it passes",
        with_line("crates/beta/src/lib.rs", 'fn f() { Sha256::digest(b"gts-thing-vx3 ev1l"); }\n'),
        None,
    ),
    (
        "a domain constant declared as a raw &str is refused",
        with_line("crates/beta/src/lib.rs", 'const CONTENT_DOMAIN: &str = "purrdf-beta/registry";\n'),
        f"rule:{RULE_ID}",
    ),
    (
        "a vocabulary IRI in a constant named DOMAIN passes",
        with_line("crates/beta/src/lib.rs", 'const OWL_DOMAIN: &str = "http://www.w3.org/2002/07/owl#domain";\n'),
        None,
    ),
    (
        "a raw literal in a #[cfg(test)] function is out of scope",
        with_line("crates/beta/src/lib.rs", '#[cfg(test)]\nfn oracle(h: &mut H) { h.update(b"purrdf-beta/raw/v1"); }\n'),
        None,
    ),
    (
        "the same raw literal outside #[cfg(test)] is refused",
        with_line("crates/beta/src/lib.rs", 'fn oracle(h: &mut H) { h.update(b"purrdf-beta/raw/v1"); }\n'),
        f"rule:{RULE_ID}",
    ),
]


SHARED_SOURCE = (
    'const TAG: Domain = Domain::new(b"purrdf-beta/contract/v1");\n'
    "fn layout_a(h: &mut H) { frame(h, TAG.as_bytes()); frame(h, b\"calculus\"); }\n"
    "fn layout_b(h: &mut H, d: &[u8; 32]) { frame(h, TAG.as_bytes()); h.update(d); }\n"
)
UNDOMAINED_SOURCE = (
    "pub fn fingerprint(terms: &[u8]) -> Result<[u8; 32], E> {\n"
    "    let mut hasher = purrdf_hash::blake3::Hasher::new();\n"
    "    hasher.update(terms);\n"
    "    Ok(*hasher.finalize().as_bytes())\n"
    "}\n"
)
DOMAINED_SOURCE = (
    'const FINGERPRINT: Domain = Domain::new(b"purrdf-beta/fingerprint/v1");\n'
    "pub fn fingerprint(terms: &[u8]) -> Result<[u8; 32], E> {\n"
    "    let mut hasher = purrdf_hash::blake3::Hasher::new();\n"
    "    hasher.update(FINGERPRINT.as_bytes());\n"
    "    hasher.update(terms);\n"
    "    Ok(*hasher.finalize().as_bytes())\n"
    "}\n"
)


def exception_row(symbol: str, detector: str, anchor: str | None = None) -> dict:
    return {
        "symbol": symbol,
        "file": "crates/beta/src/lib.rs",
        "detector": detector,
        "criterion": "a",
        "anchor": symbol if anchor is None else anchor,
        "reason": "a published identity",
    }


EXCEPTION_CASES: list[tuple[str, dict[str, str], list[dict], str | None]] = [
    (
        "a domain opening hashers in two functions, undeclared, is refused",
        with_line("crates/beta/src/lib.rs", SHARED_SOURCE),
        [],
        f"rule:{SHARED_RULE_ID}",
    ),
    (
        "the same shared domain declared as a ledger exception passes",
        with_line("crates/beta/src/lib.rs", SHARED_SOURCE),
        [exception_row("fixture_beta::TAG", SHARED_RULE_ID)],
        None,
    ),
    (
        "a declared shared domain that now opens one construction is STALE",
        with_line("crates/beta/src/lib.rs", SHARED_SOURCE.replace("frame(h, TAG.as_bytes()); h.update(d);", "h.update(d);")),
        [exception_row("fixture_beta::TAG", SHARED_RULE_ID)],
        "STALE",
    ),
    (
        "a declared undomained digest passes",
        with_line("crates/beta/src/lib.rs", UNDOMAINED_SOURCE),
        [exception_row("fixture_beta::fingerprint", UNDOMAINED_RULE_ID)],
        None,
    ),
    (
        "a declared undomained digest that now opens under a Domain is STALE",
        with_line("crates/beta/src/lib.rs", DOMAINED_SOURCE),
        [exception_row("fixture_beta::fingerprint", UNDOMAINED_RULE_ID)],
        "STALE",
    ),
    (
        "a declared exception naming no anchor is refused",
        with_line("crates/beta/src/lib.rs", UNDOMAINED_SOURCE),
        [exception_row("fixture_beta::fingerprint", UNDOMAINED_RULE_ID, anchor="")],
        "no documented anchor",
    ),
    (
        "a declared exception naming a function the file lacks is STALE",
        CLEAN_WORKSPACE,
        [exception_row("fixture_beta::fingerprint", UNDOMAINED_RULE_ID)],
        "STALE",
    ),
]


def self_test() -> int:
    cases: list[tuple[str, bool]] = []
    for name, files, exceptions, fragment in [
        (name, files, [], fragment) for name, files, fragment in SELF_TEST_CASES
    ] + EXCEPTION_CASES:
        findings = run_fixture(files, exceptions)
        if fragment is None:
            cases.append((name, findings == []))
        else:
            cases.append((name, len(findings) == 1 and fragment in findings[0]))
        if not cases[-1][1]:
            for finding in findings:
                print(f"  {finding}")
    # The registry table.
    scan = scan_workspace(drop_test_modules({"crates/beta/src/lib.rs": CLEAN_WORKSPACE["crates/beta/src/lib.rs"]}))
    table = readme_table(scan)
    readme = f"# Title\n\n{README_BEGIN}\nstale\n{README_END}\n\ntail\n"
    regenerated = readme_with_table(readme, table)
    cases.append(("a stale README table is regenerated between its markers", regenerated is not None and "stale" not in regenerated and regenerated.endswith("tail\n")))
    cases.append(("a README without the markers is reported, not rewritten", readme_with_table("# Title\n", table) is None))
    cases.append(("a current README table is left exactly as it is", regenerated is not None and readme_with_table(regenerated, table) == regenerated))
    cases.append(("the table lists each registration once, sorted by bytes", table.count("| `b\"") == 3 and table.index("gts-mmr-leaf") < table.index("merkle-root")))
    # The escapes the collector decodes.
    cases.append(("escapes decode to the bytes the compiler emits", decode_escapes(r"a\0b\x1f\u{e9}\n", False) == b"a\0b\x1f\xc3\xa9\n" and decode_escapes(r"\xff", True) == b"\xff"))
    failed = 0
    for name, held in cases:
        print(f"{'PASS' if held else 'FAIL'}: {name}")
        failed += not held
    if failed:
        print(f"check-hash-domains self-test: {failed} case(s) failed")
        return 1
    print("OK: check-hash-domains self-test")
    return 0


# ---------------------------------------------------------------------------


def main() -> int:
    arguments = sys.argv[1:]
    if arguments == ["--self-test"]:
        return self_test()
    if arguments not in ([], ["--write-readme"], ["--list"]):
        print("usage: check-hash-domains.py [--self-test | --write-readme | --list]", file=sys.stderr)
        return 2
    scan = scan_workspace(shipping_files(REPO_ROOT))
    if arguments == ["--list"]:
        for registration in sorted(scan.registrations, key=lambda registration: registration.data):
            print(f'{registration.file}:{registration.line}\t{registration.const}\tb"{render(registration.data)}"')
        return 0
    readme_path = REPO_ROOT / README_PATH
    readme = readme_path.read_text(encoding="utf-8")
    updated = readme_with_table(readme, readme_table(scan))
    try:
        exceptions = ledger_exceptions()
    except (OSError, tomllib.TOMLDecodeError) as exc:
        print(f"FAIL: {LEDGER_PATH}: {exc}")
        return 1
    findings = registry_findings(scan, exceptions)
    if updated is None:
        findings.append(f"FAIL: {README_PATH} has no `{README_BEGIN}` … `{README_END}` block")
    elif arguments == ["--write-readme"]:
        readme_path.write_text(updated, encoding="utf-8")
    elif updated != readme:
        findings.append(
            f"FAIL: the domain registry table in {README_PATH} is not the collected set; "
            "run `python3 scripts/check-hash-domains.py --write-readme`"
        )
    if findings:
        for finding in findings:
            print(finding)
        return 1
    print(
        f"OK: {len(scan.registrations)} hash domains registered through purrdf_hash::Domain, unique and "
        f"prefix-free; no raw domain literal reaches a hasher; {len(exceptions)} ledger-declared exception(s) "
        f"hold; the {README_PATH} registry table is current"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
