#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0
#
# Drive the LUBM comparison workload end to end: acquire, generate, convert, query.
#
# Original native profile purrdf-lubm-native-v1, specified in crates/bench/LUBM_PROFILE.md.
# Only the external ontology and fourteen published queries are acquired by digest.
# All generated bytes and mechanically projected schema remain ignored build output.
# Every query row names its regime and full/one-file/slice rung.

set -euo pipefail

# The laws every lane in this repository shares — how it dies, how its scratch
# directory is cleaned up, how the certificates it wrote are revoked when it
# fails, and how the executable that certifies every number is validated — live
# in ONE implementation that all three lanes source. See scripts/lane-common.sh.
LANE="lubm-lane"
LANE_BINARY="purrdf binary"
# shellcheck source=scripts/lane-common.sh
source "$(dirname "${BASH_SOURCE[0]}")/lane-common.sh"

UNIVERSITIES="${LUBM_UNIVERSITIES:-1}"
SEED="${LUBM_SEED:-0}"
INDEX="${LUBM_INDEX:-0}"
readonly LUBM_DEFAULT_ONTO="http://swat.cse.lehigh.edu/onto/univ-bench.owl"
ONTO="${LUBM_ONTO:-${LUBM_DEFAULT_ONTO}}"
# example.org is RFC 2606's reserved documentation domain and this repository's own
# fixture convention. It is a placeholder for the corpus's publication IRI, which a
# locally generated corpus does not have -- not a claim that anything is published
# there. An operator who publishes a corpus sets this to where it actually lives.
readonly LUBM_DEFAULT_DOC_BASE="http://example.org/lubm/"
DOC_BASE="${LUBM_DOC_BASE:-${LUBM_DEFAULT_DOC_BASE}}"
ENTAIL_SLICE="${LUBM_ENTAIL_SLICE:-3000}"
OUT="${LUBM_OUT:-target/lubm}"
BIN="${LUBM_BIN:-}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${REPO_ROOT}/target/bench-artifacts"

# Graph acceptance is registered for revocation on failed runs. Generation receipts
# bind the generator's bytes; only a fresh verified graph acceptance is consumed.

# `LUBM_OUT` IS HONOURED AS WRITTEN. An absolute path is the arena, verbatim; a
# relative one is resolved against the repository root, which is what the
# `target/lubm` default has always meant and what keeps the lane independent of
# the caller's working directory.
#
# Prefixing `REPO_ROOT` unconditionally — which is what this did — quietly turned
# `LUBM_OUT=/mnt/big/arena` into `<repo>/mnt/big/arena`: nothing appeared where
# the operator asked, the arena landed INSIDE the working tree and outside
# `target/`, and the lane reported success. `docs/BENCHMARKS.md` documents an
# absolute `SCALE_OUT` and `SCALE_OUT` already behaves this way, so the trap was
# one the documentation trained an operator straight into.
case "${OUT}" in
  /*) ARENA_ROOT="${OUT}" ;;
  *) ARENA_ROOT="${REPO_ROOT}/${OUT}" ;;
esac

# A WRITE WHOSE STATUS IS NOT CHECKED IS A SILENT DROP, and `lane_write_checked`
# is where every redirection in all three lanes goes. `$1` is the destination,
# `$2` the role, and the rest is the command whose stdout becomes the file; the
# third argument of the shared function names WHERE the bytes were going, and
# this lane spells it as the path plus its knob.
write_checked() {
  local destination="$1" role="$2"
  shift 2
  lane_write_checked "${destination}" "${role}" \
    "'${destination}' (under LUBM_OUT='${OUT}')" "$@"
}

# `LUBM_OUT` is a knob, so an arena that cannot be created is a LANE failure that
# quotes the bytes back — not a bare `mkdir: cannot create directory ...` with no
# hint which knob supplied the path.
mkdir_checked() {
  lane_mkdir_checked "$1" "LUBM_OUT='${OUT}'"
}

# A DATASET IS THE THING EVERY NUMBER BELOW IS ABOUT, so an empty one is a hard
# failure and never a row in the report. An empty dataset converts cleanly,
# answers every one of the 14 queries 0, and digests to the SHA-256 of the empty
# string. See the digest law at step 5, and `lane_require_nonempty_file` for why
# that digest is described in the diagnostic and never printed.
require_nonempty_file() {
  lane_require_nonempty_file "$1" "$2"
}

step() {
  echo ""
  echo "=== $* ==="
}

# Shell-arithmetic counts use the shared positive guard. Native seed/index
# values are admitted and normalized by Spec below.
lane_require_positive LUBM_UNIVERSITIES UNIVERSITIES
lane_require_positive LUBM_ENTAIL_SLICE ENTAIL_SLICE
# Cheap necessary conditions preserve early knob diagnostics without building a
# tool for an arena that cannot be used. Spec performs full IRI admission below.
[[ "${DOC_BASE}" == *:* ]] || die "LUBM_DOC_BASE must be an absolute IRI (got '${DOC_BASE}')"
[[ "${ONTO}" == *:* ]] || die "LUBM_ONTO must be an absolute IRI (got '${ONTO}')"

# `LUBM_BIN` NAMES THE EXECUTABLE EVERY NUMBER IN THIS REPORT IS ABOUT, so it is
# validated by the SAME implementation `SCALE_BIN` and `WATDIV_BIN` are:
# `lane_require_executable` for the path, `lane_run_probe` for whether it runs,
# `lane_require_probe_said_something` for whether it produced anything.
#
# `[[ -x ]]` ALONE IS NOT A CHECK FOR AN EXECUTABLE: a DIRECTORY carries the
# execute bit, so `LUBM_BIN=/tmp` passed it. And the execute bit is not proof the
# binary runs: `/bin/false` carries it too, reached step 5, and made the lane die
# with `purrdf convert failed on ... -- the CLI could not parse LUBM's RDF/XML`.
# That diagnostic was FALSE in every particular — the CLI never ran, the RDF/XML
# parses, and the fault was in the knob — and an operator following it would go
# hunting a parser bug that does not exist.
#
# AND RUNNING IS NOT CONVERTING. A CLI that answers `--version` and then writes an
# empty file for every conversion is the shape that reached step 5, converted all
# 15 files to nothing, passed its own `converted == owl_count` check 15 of 15,
# and published `sha256(lubm-data.nq)` — the SHA-256 of the empty string — as the
# provenance of a corpus that did not exist. So the probe here is a ROUND TRIP,
# exactly as `scale-corpus.sh` round-trips a manifest: the binary is handed a
# one-triple RDF/XML document and must hand back N-Quads. That is what makes the
# empty-conversion refusal reachable before step 1, with no network and
# no generated corpus to mistake the fault for.
#
# `$1` is how to name the binary in a diagnostic; `$2` is 1 when `LUBM_BIN`
# supplied the path and 0 when this lane built it. Sets `PURRDF_VERSION`.
validate_purrdf_bin() {
  local provenance="$1" from_knob="$2"
  lane_require_executable LUBM_BIN "${from_knob}" "${BIN}" "the purrdf CLI"

  lane_run_probe "${provenance}" "for its version" "${BIN}" --version
  lane_require_probe_said_something "${provenance}" "for its version" \
    "A binary that says nothing is not the purrdf CLI, and this lane records what it
  printed beside every number in the report as the provenance of that number."
  PURRDF_VERSION="${LANE_PROBE_OUT}"
  # THE PIN-KEY SUFFIX HAS ONE DEFINITION, and it is not here. This used to be
  # `${PURRDF_VERSION// /-}` in each lane while the self-test built the same suffix
  # from `Cargo.toml` -- three constructions, none compared. A release adding a git
  # hash or a second banner line would make every version-keyed pin unreachable, and
  # an unreachable pin reads as "no pin for this binary" and exits 0. One environment
  # change, every pin silently off. Asking for the suffix also validates the shape:
  # the derivation refuses anything that is not `<name> <semver>` by name.
  PURRDF_PIN_SUFFIX="$(python3 "${REPO_ROOT}/scripts/benchmark-acquire.py" \
    --pin-version-suffix "${PURRDF_VERSION}")" ||
    die "the binary reported a version line no pin key can be built from:
  '${PURRDF_VERSION}'
  Every version-keyed pin would be unreachable, which a lane reports as 'no pin
  recorded' and exits 0 on -- so this is refused rather than carried."

  # One triple, in the reserved documentation domain this repository's fixtures
  # use. It exercises the RDF/XML conversion of the external ontology in step 5;
  # native department payloads use N-Triples instead.
  local probe_in="${LANE_TMP}/probe.rdf" probe_out="${LANE_TMP}/probe.nq"
  cat >"${probe_in}" <<'PROBE_RDFXML'
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:ex="http://example.org/lane-probe#">
  <rdf:Description rdf:about="http://example.org/lane-probe/s">
    <ex:p rdf:resource="http://example.org/lane-probe/o"/>
  </rdf:Description>
</rdf:RDF>
PROBE_RDFXML
  rm -f "${probe_out}"
  lane_run_probe "${provenance}" \
    "to convert a one-triple RDF/XML document to N-Quads" \
    "${BIN}" convert --from rdfxml --to nquads \
    --base "http://example.org/lane-probe/probe.rdf" "${probe_in}" "${probe_out}"
  [[ -s "${probe_out}" ]] ||
    die "${provenance} exited 0 converting a one-triple RDF/XML document and produced
  NO N-QUADS AT ALL.
  A CLI that converts everything to nothing converts LUBM's files to nothing too,
  one empty file at a time, and every one of those conversions exits 0. The lane
  would then publish a digest as the provenance of a corpus that does not exist.
  It stops here instead, before a byte is fetched and before the generator runs."
  # And what it DID produce has to be N-Quads, by the same check the converted
  # dataset gets at step 5. One law, one implementation.
  lane_require_nquads "${probe_out}" \
    "the N-Quads ${provenance} produced from a one-triple document"
}

# Validate the prebuilt CLI before acquiring artifacts or generating a corpus;
# every one of those is a chance for the real fault to be mistaken for a problem
# with the corpus. An unset `LUBM_BIN` is validated at step 2 instead, once the
# build that produces the binary has run.
BIN_FROM_KNOB=0
if [[ -n "${BIN}" ]]; then
  BIN_FROM_KNOB=1
  validate_purrdf_bin "LUBM_BIN='${BIN}'" 1
fi

# AND SO IS THE ARENA. `LUBM_OUT` is a knob exactly as `LUBM_BIN` is, and a knob
# error is not worth a download either: an unusable arena discovered at step 3 has
# already cost a network fetch, and an operator reading the failure has to work
# out which of the two knobs it was about. The arena is created here instead, once,
# and every later `mkdir_checked` under it is then a subdirectory of a path already
# proved usable.
# Build and admit every native configuration before acquiring anything or generating.
# Cargo owns executable freshness and its configured target directory.
native_check() {
  CARGO_BUILD_JOBS=8 cargo run --manifest-path "${REPO_ROOT}/Cargo.toml" --locked --release --jobs 8 -p purrdf-bench --bin lubm-check -- "$@"
}
native_admitted="$(native_check config "${SEED}" "${INDEX}" "${UNIVERSITIES}" "${ONTO}" "${DOC_BASE}")" ||
  die "invalid native configuration: LUBM_SEED='${SEED}' LUBM_INDEX='${INDEX}' LUBM_UNIVERSITIES='${UNIVERSITIES}' LUBM_ONTO='${ONTO}' LUBM_DOC_BASE='${DOC_BASE}'; no acquisition or generation occurred"
# A strict two-decimal, single-line boundary, produced only after Spec admission.
# No Bash arithmetic or second numeric parser touches native seed/index values.
[[ "${native_admitted}" =~ ^([0-9]+)$'\t'([0-9]+)$ ]] || die "native configuration admission returned an invalid seed/index record"
IFS=$'\t' read -r SEED INDEX <<<"${native_admitted}"
CHECK_BIN="$(native_check executable)" || die "could not resolve the freshly Cargo-built native checker"
lane_require_executable native-check 0 "${CHECK_BIN}" "the native graph checker"

mkdir_checked "${ARENA_ROOT}"
"${CHECK_BIN}" output "${ARENA_ROOT}" || die "LUBM_OUT='${OUT}' cannot retain external ontology/query output safely; use an ignored or outside-worktree directory"

# Milliseconds since the epoch. `bc` is not assumed present, so every duration is
# integer arithmetic over nanoseconds.
now_ms() {
  echo $(($(date +%s%N) / 1000000))
}

step "1/7 artifacts (external ontology and queries, fetched by digest)"
python3 "${REPO_ROOT}/scripts/benchmark-acquire.py" \
  --only queries-sparql.txt univ-bench.owl ||
  die "artifact acquisition failed -- stopping"
for required in univ-bench.owl queries-sparql.txt; do
  require_nonempty_file "${CACHE}/${required}" "${required}, which acquisition reported cached,"
done
verify_external_inputs() {
  for required in univ-bench.owl queries-sparql.txt; do
    require_nonempty_file "${CACHE}/${required}" "the retained external input ${required}"
  done
  # Existing acquisition owns digest/cache/ignore laws. Preconditions above make
  # this a verified cache-hit check, never a missing-input repair during a run.
  python3 "${REPO_ROOT}/scripts/benchmark-acquire.py" --only queries-sparql.txt univ-bench.owl ||
    die "retained external ontology/query cache failed its original digest or ignore proof"
}
external_ontology_sha="$(lane_sha256_file "${CACHE}/univ-bench.owl" "original external ontology")"
external_queries_sha="$(lane_sha256_file "${CACHE}/queries-sparql.txt" "original external queries")"

# ── 2. The purrdf binary ────────────────────────────────────────────────────────

step "2/7 purrdf CLI"
if ((BIN_FROM_KNOB == 0)); then
  echo "building purrdf (release)..." >&2
  BIN="$(CARGO_BUILD_JOBS=8 cargo build --manifest-path "${REPO_ROOT}/Cargo.toml" --locked --release --jobs 8 -p purrdf-cli --message-format=json-render-diagnostics | "${CHECK_BIN}" artifact purrdf)" ||
    die "cargo build -p purrdf-cli failed"
  validate_purrdf_bin "the binary this lane built, '${BIN}'" 0
fi
echo "purrdf: ${BIN}  (${PURRDF_VERSION})"

step "3/7 native generator (Cargo freshness, original first-party Rust)"
GENERATOR="$(CARGO_BUILD_JOBS=8 cargo build --manifest-path "${REPO_ROOT}/Cargo.toml" --locked --release --jobs 8 -p purrdf-bench --bin lubm-corpus --message-format=json-render-diagnostics | "${CHECK_BIN}" artifact lubm-corpus)" ||
  die "could not build the native university generator"
lane_require_executable native-generator 0 "${GENERATOR}" "the native university generator"
echo "generator: ${GENERATOR} profile=purrdf-lubm-native-v1"
generator_sha="$(lane_sha256_file "${GENERATOR}" "native generator executable")"
binary_sha="$(lane_sha256_file "${BIN}" "purrdf executable")"
checker_sha="$(lane_sha256_file "${CHECK_BIN}" "native checker executable")"

step "4/7 generate native LUBM(${UNIVERSITIES}, ${INDEX}) seed=${SEED}"
RUN_ROOT="$(mktemp -d "${ARENA_ROOT}/run.XXXXXXXX")" || die "could not create a fresh owned run directory under LUBM_OUT='${OUT}'"
echo "run artifacts: ${RUN_ROOT}"
WORK="${RUN_ROOT}/gen"
CONVERTED="${RUN_ROOT}/converted"
# Every run owns fresh paths. Previous success/failure artifacts are preserved.
mkdir_checked "${CONVERTED}"
t0="$(now_ms)"
"${GENERATOR}" --universities "${UNIVERSITIES}" --index "${INDEX}" --seed "${SEED}" \
  --ontology "${ONTO}" --document-base "${DOC_BASE}" --out "${WORK}" ||
  die "native generation failed; retained partial output is not a corpus"
gen_ms=$(( $(now_ms) - t0 ))
require_nonempty_file "${WORK}/receipt.json" "native generation receipt"

step "5/7 convert native N-Triples through purrdf and verify actual RDF graphs"
t0="$(now_ms)"
mapfile -t payloads < <(find "${WORK}" -maxdepth 1 -type f -name '*.nt' | sort)
((${#payloads[@]} > 0)) || die "native generator produced no department payloads"
declare -a nq_files=()
for file in "${payloads[@]}"; do
  name="$(basename "${file}" .nt)"
  output="${CONVERTED}/${name}.nq"
  "${BIN}" convert --from ntriples --to nquads "${file}" "${output}" ||
    die "purrdf failed converting native department ${file}"
  require_nonempty_file "${output}" "converted native department"
  nq_files+=("${output}")
done
DATA="${RUN_ROOT}/lubm-data.nq"
write_checked "${DATA}" "complete converted native corpus" cat "${nq_files[@]}"
ACCEPTANCE="${RUN_ROOT}/graph-acceptance.json"
lane_certify "${ACCEPTANCE}"
"${CHECK_BIN}" verify "${WORK}" "${CONVERTED}" "${DATA}" "${SEED}" "${INDEX}" "${UNIVERSITIES}" "${ONTO}" "${DOC_BASE}" "${ACCEPTANCE}" ||
  die "native receipt/graph acceptance failed; no query numbers are admissible"
require_nonempty_file "${ACCEPTANCE}" "complete native graph acceptance"
verify_external_inputs
EXTERNAL_ONTO_NQ="${RUN_ROOT}/external-ontology.nq"
"${BIN}" convert --from rdfxml --to nquads --base "${LUBM_DEFAULT_ONTO}" "${CACHE}/univ-bench.owl" "${EXTERNAL_ONTO_NQ}" ||
  die "purrdf failed converting the original external ontology"
require_nonempty_file "${EXTERNAL_ONTO_NQ}" "converted external ontology"
ONTO_NQ="${RUN_ROOT}/lubm-onto.nq"
write_checked "${ONTO_NQ}" "mechanically projected RDF schema" "${CHECK_BIN}" project "${ONTO}" <"${EXTERNAL_ONTO_NQ}"
require_nonempty_file "${ONTO_NQ}" "projected ontology"
conv_ms=$(( $(now_ms) - t0 ))
data_rows="$(wc -l <"${DATA}")"
data_bytes="$(wc -c <"${DATA}")"
data_sha="$(lane_sha256_file "${DATA}" "complete converted native corpus")"
receipt_sha="$(lane_sha256_file "${WORK}/receipt.json" "native receipt")"
acceptance_sha="$(lane_sha256_file "${ACCEPTANCE}" "native graph acceptance")"
projected_ontology_sha="$(lane_sha256_file "${ONTO_NQ}" "projected ontology")"
echo "native: ${#payloads[@]} department files; ${data_rows} converted statements"
echo "receipt sha256: ${receipt_sha}; graph acceptance sha256: ${acceptance_sha}"
echo "external ontology sha256: ${external_ontology_sha}; projected schema sha256: ${projected_ontology_sha}"

# ── 6. Normalise the queries ────────────────────────────────────────────────────

step "6/7 normalise the 14 published queries (mechanical rules, recorded)"
verify_external_inputs
QUERIES="${RUN_ROOT}/queries"
NAMESPACE="${ONTO}#"
python3 "${REPO_ROOT}/scripts/lubm-queries.py" --self-test ||
  die "the query normaliser failed its own self-test"
python3 "${REPO_ROOT}/scripts/lubm-queries.py" --namespace "${NAMESPACE}" --out "${QUERIES}" ||
  die "could not normalise the LUBM queries"

# A NORMALISER REPORTING SUCCESS IS NOT 14 QUERIES, and the artifacts it names
# are not evidence until they are checked for being artifacts. The report below
# counts what it executed; without these, the denominator it counts against was a
# typed literal and a partial query set would have read as "executed 3 of 14".
# ONE COPY OF THE NUMBER, read from the pin file, as the sibling lane already does.
EXPECTED_QUERIES="$(python3 "${REPO_ROOT}/scripts/benchmark-acquire.py" --lubm-query-count)" ||
  die "could not read the pinned LUBM published-query count"
lane_require_query_count "${QUERIES}" "${EXPECTED_QUERIES}" "LUBM_OUT='${OUT}'"
require_nonempty_file "${QUERIES}/regimes.tsv" "the per-query entailment regime index"
require_nonempty_file "${QUERIES}/provenance.txt" "the query normalisation record"

# Freeze both query bytes and their execution map in this run's fresh directory.
queries_sha="$(lane_query_set_digest "${QUERIES}")"
regimes_sha="$(lane_sha256_file "${QUERIES}/regimes.tsv" "query regime map")"
normalisation_sha="$(lane_sha256_file "${QUERIES}/provenance.txt" "query normalisation record")"
verify_query_set() {
  lane_verify_query_set "${QUERIES}" "${queries_sha}" "$1" "LUBM_OUT='${OUT}'"
  [[ "$(lane_sha256_file "${QUERIES}/regimes.tsv" "query regime map")" == "${regimes_sha}" &&
     "$(lane_sha256_file "${QUERIES}/provenance.txt" "query normalisation record")" == "${normalisation_sha}" ]] ||
    die "query regime map or normalisation provenance changed $1"
}

echo "provenance: ${QUERIES}/provenance.txt"
echo "sha256(queries) = ${queries_sha}"
echo "sha256(query regimes) = ${regimes_sha}"
echo "sha256(query normalisation) = ${normalisation_sha}"

# ASSERTED, not printed -- but only at the knob it depends on. The normalisation is
# a pure function of the pinned queries file and the target namespace, so at the
# default namespace the digest is a constant and printing it instead of checking it
# would be a known value left unchecked. A non-default namespace is a different
# query set, and asserting the default's digest against it would be an
# over-refusal, so that case says what it is doing instead.
if [[ "${ONTO}" == "${LUBM_DEFAULT_ONTO}" ]]; then
  expected_queries="$(lane_require_pin "${REPO_ROOT}" lubm.queries.sha256 \
    "query-set pin for the default LUBM namespace")"
  [[ "${queries_sha}" == "${expected_queries}" ]] ||
    die "the normalised LUBM query set does not match its recorded pin.
  expected ${expected_queries}
  found    ${queries_sha}
  The queries file matched its own digest, so the NORMALISATION changed. Every row
  below would be answered over a different query set than the one these rules were
  reviewed against."
  echo "  ^ matches the recorded pin for the default namespace"
else
  echo "  ^ NOT checked against a pin: LUBM_ONTO is not the default, so this is a"
  echo "    different query set and no pin is recorded for it."
fi

# ── 7. Run the queries ──────────────────────────────────────────────────────────

verify_native_graph() {
  verify_external_inputs
  [[ "$(lane_sha256_file "${BIN}" "purrdf executable")" == "${binary_sha}" &&
     "$(lane_sha256_file "${GENERATOR}" "native generator executable")" == "${generator_sha}" &&
     "$(lane_sha256_file "${CHECK_BIN}" "native checker executable")" == "${checker_sha}" &&
     "$(lane_sha256_file "${CACHE}/univ-bench.owl" "original external ontology")" == "${external_ontology_sha}" &&
     "$(lane_sha256_file "${CACHE}/queries-sparql.txt" "original external queries")" == "${external_queries_sha}" &&
     "$(lane_sha256_file "${ONTO_NQ}" "projected ontology")" == "${projected_ontology_sha}" ]] ||
    die "an executable or external/projected input identity changed during the native run"
  "${CHECK_BIN}" recheck "${WORK}" "${CONVERTED}" "${DATA}" "${SEED}" "${INDEX}" "${UNIVERSITIES}" "${ONTO}" "${DOC_BASE}" "${ACCEPTANCE}" ||
    die "native graph/receipt identity changed before or during query measurement"
  if [[ -n "${entail_full_sha:-}" ]]; then
    [[ "$(lane_sha256_file "${ENTAIL_FULL}" "full entailment rung")" == "${entail_full_sha}" &&
       "$(lane_sha256_file "${ENTAIL_FILE}" "one-file entailment rung")" == "${entail_file_sha}" &&
       "$(lane_sha256_file "${ENTAIL_SLICE_NQ}" "slice entailment rung")" == "${entail_slice_sha}" ]] ||
      die "an entailment rung changed before or during native query measurement"
  fi
}
verify_native_graph

step "7/7 run the queries, per regime"

# The entailment ladder. Materializing a closure has a FIXED internal ceiling that
# no flag raises, so a regime that cannot close over the whole dataset is offered
# progressively smaller rungs rather than being reported as unsupported. Each rung
# is a real dataset and every reported row count names the rung it came from, so a
# smaller rung never silently masquerades as a full-scale answer.
ENTAIL_FULL="${RUN_ROOT}/entail-full.nq"
ENTAIL_FILE="${RUN_ROOT}/entail-file.nq"
ENTAIL_SLICE_NQ="${RUN_ROOT}/entail-slice.nq"
FIRST_NQ="${nq_files[0]}"
# `${nq_files}` is non-empty by the guard at step 5, but the rungs are DATASETS
# that queries are answered over and reported against, so each one is checked
# for being one. The unchecked `cat "${FIRST_NQ}" ...` here is where the
# empty-corpus run finally died, at 7/7, on a bare `cat: '': No such file or
# directory` that named neither the lane, the knob, nor purrdf -- six steps and
# one published digest after the dataset was already known to be empty.
require_nonempty_file "${FIRST_NQ}" "the first converted LUBM file"

write_checked "${ENTAIL_FULL}" "the 'full' rung of the entailment ladder" \
  cat "${DATA}" "${ONTO_NQ}"
write_checked "${ENTAIL_FILE}" "the 'one-file' rung of the entailment ladder" \
  cat "${FIRST_NQ}" "${ONTO_NQ}"
slice_rung() {
  head -n "${ENTAIL_SLICE}" "${FIRST_NQ}"
  cat "${ONTO_NQ}"
}
write_checked "${ENTAIL_SLICE_NQ}" "the 'slice' rung of the entailment ladder" slice_rung
for rung_file in "${ENTAIL_FULL}" "${ENTAIL_FILE}" "${ENTAIL_SLICE_NQ}"; do
  require_nonempty_file "${rung_file}" "a rung of the entailment ladder"
done
entail_full_sha="$(lane_sha256_file "${ENTAIL_FULL}" "full entailment rung")"
entail_file_sha="$(lane_sha256_file "${ENTAIL_FILE}" "one-file entailment rung")"
entail_slice_sha="$(lane_sha256_file "${ENTAIL_SLICE_NQ}" "slice entailment rung")"

rows_of() { wc -l <"$1"; }

# Evaluate one query file against one dataset under one regime. Prints
# `status<TAB>rows<TAB>ms<TAB>detail`; never exits non-zero, because a query that
# cannot run is a RESULT this lane reports, not a reason to abandon the run.
run_query() {
  local query_file="$1" dataset="$2" regime="$3"
  local -a flags=(--data "${dataset}" --results-format json)
  [[ "${regime}" == "-" ]] || flags+=(--entailment "${regime}")

  # STDERR IS NOT RESULTS. Merging the two meant a binary that exits 0 while
  # writing anything at all to stderr -- a notice, a warning, a future governor
  # line -- prepended non-JSON to well-formed output, the parse failed, and the
  # lane reported "its results were not parseable SPARQL JSON". The results were
  # fine. That is a diagnosis the lane had not established, about the binary
  # under test, which is the misdiagnosis class the lane tests exist to stop.
  # READ THE QUERY BEFORE MEASURING, AND CHECK THAT THE READ WORKED. Inlining
  # `$(cat ...)` into the invocation put the read inside the `set +e` window, so a
  # read that failed -- a mode changed between the guard above and this line, a
  # filesystem error -- yielded the empty string, the engine was handed an empty
  # query, and its usage complaint became this lane's diagnosis. The guard cannot
  # close that window by itself; only checking the read can.
  local query_text
  query_text="$(cat "${query_file}")" ||
    die "could not read ${query_file} at the moment ${LANE} was about to run it.
  The engine has not been asked and is not at fault: an unread query becomes an
  empty query string, and the engine's complaint about that would be reported here
  as though the corpus or the binary were wrong."
  [[ -n "${query_text}" ]] ||
    die "${query_file} read as empty at the moment it was to be run, although it
  passed the non-empty check moments earlier. Something is changing the arena
  underneath this run."

  local start stop out rc errfile
  errfile="${LANE_TMP}/query.err"
  lane_reset_capture "${errfile}"
  start="$(now_ms)"
  set +e
  out="$("${BIN}" query "${flags[@]}" "${query_text}" 2>"${errfile}")"
  rc=$?
  set -e
  stop="$(now_ms)"

  local said
  said="$(lane_capture_stderr "${errfile}")"

  if ((rc != 0)); then
    printf 'CANNOT-EXECUTE\t-\t%s\t%s\n' "$((stop - start))" \
      "${said:-the binary exited ${rc} without saying anything}"
    return
  fi

  local count
  local -a oracle_flags=()
  if [[ "${dataset}" == "${DATA}" && ( "${4:-}" == "Q1" || "${4:-}" == "Q14" ) ]]; then
    oracle_flags=("${ACCEPTANCE}" "$4")
  fi
  lane_reset_capture "${LANE_TMP}/result-check.err"
  count="$(printf '%s' "${out}" | "${CHECK_BIN}" results "${oracle_flags[@]}" 2>"${LANE_TMP}/result-check.err")" || count=""

  if [[ -z "${count}" ]]; then
    local failure
    failure="$(lane_capture_stderr "${LANE_TMP}/result-check.err")"
    printf 'BAD-RESULTS\t-\t%s\t%s\n' "$((stop - start))" \
      "the engine exited 0 but native result/oracle acceptance failed: ${failure}${said:+; it also wrote: ${said}}"
    return
  fi
  printf 'OK\t%s\t%s\t-\n' "${count}" "$((stop - start))"
}

# Probe a regime ONCE per rung. The closure is a property of the dataset and the
# regime, not of the query, so probing per query would repeat an identical failure
# fourteen times and multiply the run time by the number of queries that share a
# regime.
probe_query="${LANE_TMP}/probe.rq"
write_checked "${probe_query}" "the regime probe query" \
  printf 'SELECT ?s WHERE { ?s ?p ?o } LIMIT 1\n'

declare -A REGIME_DATASET REGIME_RUNG REGIME_NOTE

resolve_regime() {
  local regime="$1"
  if [[ "${regime}" == "-" ]]; then
    REGIME_DATASET["${regime}"]="${DATA}"
    REGIME_RUNG["${regime}"]="full"
    REGIME_NOTE["${regime}"]="no closure needed"
    return
  fi
  local rung name dataset result status
  for rung in "full:${ENTAIL_FULL}" "one-file:${ENTAIL_FILE}" "slice:${ENTAIL_SLICE_NQ}"; do
    name="${rung%%:*}"
    dataset="${rung#*:}"
    result="$(run_query "${probe_query}" "${dataset}" "${regime}")"
    status="${result%%$'\t'*}"
    if [[ "${status}" == "OK" ]]; then
      REGIME_DATASET["${regime}"]="${dataset}"
      REGIME_RUNG["${regime}"]="${name}"
      REGIME_NOTE["${regime}"]="closure completed"
      printf '  regime %-8s rung %-9s %s rows -- CLOSURE OK\n' \
        "${regime}" "${name}" "$(rows_of "${dataset}")"
      return
    fi
    printf '  regime %-8s rung %-9s %s rows -- %s\n' \
      "${regime}" "${name}" "$(rows_of "${dataset}")" \
      "$(printf '%s' "${result}" | cut -f4)"
    REGIME_NOTE["${regime}"]="$(printf '%s' "${result}" | cut -f4)"
  done
  REGIME_DATASET["${regime}"]=""
  REGIME_RUNG["${regime}"]="none"
}

# The regimes to probe are DERIVED from the query set rather than listed here. A
# hardcoded triple is a second source of truth beside `lubm-queries.py`'s regime
# table, whose own self-test admits every CLI regime the binary offers: retagging
# one query to a regime not in this list is an edit that passes that self-test and
# then dies in this loop with a bare `REGIME_NOTE[...]: unbound variable`, naming
# neither the lane nor the knob nor the query.
mapfile -t probe_regimes < <(tail -n +2 "${QUERIES}/regimes.tsv" | cut -f3 | sort -u)
((${#probe_regimes[@]} > 0)) ||
  die "${QUERIES}/regimes.tsv names no entailment regimes; the normaliser wrote an
  index this lane cannot probe against."

echo "probing each regime's closure against the dataset ladder:"
for regime in "${probe_regimes[@]}"; do
  resolve_regime "${regime}"
done

echo ""
printf '%-4s %-36s %-8s %-9s %-15s %8s %8s\n' \
  ID REGIME CLI RUNG STATUS ROWS MS
printf '%s\n' "----------------------------------------------------------------------------------------------------"

query_total_ms=0
executed=0
unexecuted=0
nonempty=0
# COUNTING EXECUTIONS IS NOT COUNTING COMPARABLE ANSWERS. A row answered on a rung
# below 'full' is, by this lane's own rule below, NOT the published LUBM answer --
# it is an answer over a strict subset. A reader who quotes "14 of 14, not executed
# 0" from the summary concludes the workload was demonstrated; if eleven of those
# ran on a slice, almost none of it is comparable to anything published. So the
# summary carries the number that decides that, rather than leaving it to be
# reconstructed from fourteen table rows.
comparable=0
declare -a NOTES=()
declare -A ANSWERED=()

# THE THIRD CALL SITE, which the sibling had and this lane did not. The shared law is
# that the query set is re-verified BEFORE the first query, on a missing file, and
# after the last; this lane had only the last two, and the unguarded window is its
# most expensive phase -- three ladder rungs built by `cat` over the whole corpus and
# a probe query per regime, including an owl-rl closure over a hundred thousand
# triples. A concurrent run sharing LUBM_OUT rewrites all fourteen `.rq` files in that
# window, so every file is PRESENT, the per-file guard passes, and the substituted set
# is measured and printed row by row -- with the mismatch surfacing only after the
# table. A law that holds in one lane and not its sibling is not a law.
verify_query_set "between normalisation and the first query"
verify_native_graph

while IFS=$'\t' read -r id regime cli file; do
  [[ "${id}" != "id" ]] || continue
  dataset="${REGIME_DATASET[${cli}]:-}"
  rung="${REGIME_RUNG[${cli}]:-none}"
  if [[ -z "${dataset}" ]]; then
    printf '%-4s %-36s %-8s %-9s %-15s %8s %8s\n' \
      "${id}" "${regime}" "${cli}" "-" "CANNOT-EXECUTE" "-" "-"
    NOTES+=("${id}: no rung of the ladder could close ${cli} -- ${REGIME_NOTE[${cli}]:-no rung was probed for regime '${cli}'}")
    unexecuted=$((unexecuted + 1))
    continue
  fi
  # A missing file is almost always a concurrent run having just deleted this
  # directory, so ask that question FIRST: it gives the real diagnosis instead of
  # a filename that vanished for no stated reason.
  [[ -f "${QUERIES}/${file}" ]] || verify_query_set "while ${id} was about to run"
  # Then the artifact itself, on EVERY iteration rather than only when it is
  # missing: present-but-unreadable and present-but-empty both reach `cat` and
  # both become an empty query the engine is then blamed for rejecting.
  lane_require_query_file "${QUERIES}/${file}" "${id}" "LUBM_OUT='${OUT}'"
  result="$(run_query "${QUERIES}/${file}" "${dataset}" "${cli}" "${id}")"
  status="$(printf '%s' "${result}" | cut -f1)"
  rows="$(printf '%s' "${result}" | cut -f2)"
  ms="$(printf '%s' "${result}" | cut -f3)"
  detail="$(printf '%s' "${result}" | cut -f4)"
  printf '%-4s %-36s %-8s %-9s %-15s %8s %8s\n' \
    "${id}" "${regime}" "${cli}" "${rung}" "${status}" "${rows}" "${ms}"
  if [[ "${status}" == "OK" ]]; then
    executed=$((executed + 1))
    if [[ "${rung}" == "full" ]]; then
      comparable=$((comparable + 1))
      ANSWERED["${id}"]="${rows}"
    fi
    query_total_ms=$((query_total_ms + ms))
    ((rows == 0)) || nonempty=$((nonempty + 1))
  else
    unexecuted=$((unexecuted + 1))
    NOTES+=("${id}: ${detail}")
  fi
done <"${QUERIES}/regimes.tsv"

# The rows above are one measurement only if they were all answered over the same
# query set, and only if they are all of it. Both are checked after the fact,
# because that is what proves it rather than assumes it.
verify_query_set "while the 14 queries were running"
verify_native_graph
query_total=$((executed + unexecuted))
((query_total == EXPECTED_QUERIES)) ||
  die "read ${query_total} row(s) from ${QUERIES}/regimes.tsv, not ${EXPECTED_QUERIES}.
  The ${EXPECTED_QUERIES} .rq files were written and counted, so the index that drives
  this loop disagrees with them. No SUMMARY is printed for a run that measured part of the workload under
  the whole workload's name."

echo ""
if ((comparable == 0)); then
  echo "NOT ONE ROW ABOVE ESTABLISHES THE COMPLETE NATIVE-PROFILE WORKLOAD: every query that"
  echo "  executed did so on a rung BELOW 'full', which is a strict subset of the"
  echo "  corpus. The rows say the regimes WORK and what they cost on this machine."
  echo "  They are not results for LUBM(${UNIVERSITIES}, ${INDEX})."
  echo ""
fi
if ((${#NOTES[@]} > 0)); then
  echo "QUERIES THAT DID NOT EXECUTE, and exactly why:"
  for note in "${NOTES[@]}"; do
    echo "  ${note}"
  done
  echo ""
fi

# A LANE IN WHICH NOTHING RAN HAS MEASURED NOTHING WHILE LOOKING EXACTLY LIKE A
# FAST ENGINE, and this lane used to exit 0 from precisely that state: fourteen
# CANNOT-EXECUTE rows, a published digest above them, and a SUCCESS line for a
# dataset that was fifteen rows long. `watdiv-lane.sh` has had this guard since it
# was written; a law that holds in one lane and not its siblings is not a law.
((executed > 0)) ||
  die "not one of the 14 queries executed; this lane measured nothing.
  Every row above says why it could not run. A report whose every row is
  CANNOT-EXECUTE is a failed run, not a fast one."
((nonempty > 0)) || die "all executed queries were vacuous; this is not a successful benchmark"
for oracle in Q1 Q14; do
  [[ -n "${ANSWERED[${oracle}]:-}" ]] ||
    die "${oracle} did not execute with valid exact URI answers over the full native graph"
done
# The result reader compared complete sets while their full-data queries executed.
# Q1 may be zero at a nonzero university index; Q14 is graph-derived and positive.
echo "oracle: Q1 and Q14 exactly match independent parsed native graph sets"

campaign_qualification="PARTIAL: unsupported, invalid or subset rows do not establish the full workload"
if ((comparable == query_total)); then
  campaign_qualification="COMPLETE: every published query answered on the full corpus"
fi

cat <<REPORT
SUMMARY
  qualification      ${campaign_qualification}
  run artifacts      ${RUN_ROOT}
  binary             ${BIN} (${PURRDF_VERSION})
  dataset            LUBM(${UNIVERSITIES}, ${INDEX}) seed=${SEED}
  profile            purrdf-lubm-native-v1
  generator sha256   ${generator_sha}
  checker sha256     ${checker_sha}
  binary sha256      ${binary_sha}
  receipt sha256     ${receipt_sha}
  graph acceptance   ${acceptance_sha}
  ontology original  ${external_ontology_sha}
  queries original   ${external_queries_sha}
  ontology projected ${projected_ontology_sha}
  entailment full    ${entail_full_sha}
  entailment file    ${entail_file_sha}
  entailment slice   ${entail_slice_sha}
  generated          ${#payloads[@]} N-Triples department files, ${gen_ms} ms
  converted          ${data_rows} rows, ${data_bytes} bytes, ${conv_ms} ms
  sha256             ${data_sha}
  queries sha256     ${queries_sha}
  queries executed   ${executed} of ${query_total} (${query_total_ms} ms total)
  comparable rows    ${comparable} of ${query_total} (answered on rung 'full')
  matched nothing    $((executed - nonempty))
  not executed       ${unexecuted}

HOW TO READ THIS
  Every row names the REGIME it was answered under and the RUNG of the dataset
  ladder it was answered over. Compare two engines on a query ONLY when both
  answered it under the same regime and over the same data. LUBM never asserts
  Student, Professor or Chair, so an engine that applies no inference answers
  eleven of these queries 0 -- instantly, and wrongly.

  A ROW COUNT ON A RUNG BELOW 'full' IS NOT THE COMPLETE NATIVE-PROFILE ANSWER. It is the
  answer over that rung, which is a strict subset of the corpus, so a query whose
  matching individuals fall outside the subset legitimately reports 0. Those counts
  say the regime WORKS and what it costs; they are not comparable against another engine
  over these same complete native-profile bytes. Only 'full' rows are.

  A rung below 'full' appears when the 'full' attempt did not succeed. The usual
  cause is materializing that regime's closure passing a FIXED internal ceiling
  that no command-line flag raises, and the probe lines above carry whatever the
  engine said in full -- including the observed and permitted counts when that is
  the cause -- so the reason is read rather than inferred from a missing row. Any
  non-zero exit demotes the rung, so read the probe line rather than assuming the
  ceiling.

  Timing is report-only. Exact native graph, conversion and Q1/Q14 answer sets
  are acceptance checks. Historical UBA answer counts do not apply to this profile.

CITE
  Y. Guo, Z. Pan and J. Heflin, "LUBM: A Benchmark for OWL Knowledge Base
  Systems", Journal of Web Semantics 3(2).
REPORT
