// SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Native SSSOM (Simple Standard for Sharing Ontology Mappings) codec.
//!
//! This is the PyO3-free Rust replacement for the `sssom` PyPI package's
//! parse + validate behaviour. It carries the PurRDF mapping artifacts
//! (`generated/mappings/*.sssom.tsv`) in and out of an owned IR and adds a
//! native RDF serializer the Python toolkit never had (the SUBSUME/ENHANCE
//! deliverable).
//!
//! ## The SSSOM TSV format (as PurRDF writes it)
//!
//! A PurRDF SSSOM file is a YAML-ish `#`-prefixed metadata header followed by a
//! tab-separated mapping table:
//!
//! ```text
//! # mapping_set_id: https://…/mappings/accessibility
//! # mapping_set_version: 0.1.0
//! # license: https://creativecommons.org/licenses/by/4.0/
//! # comment: "Accessibility alignments …"
//! # curie_map:
//! #   ex: https://example.org/vocab/
//! #   skos:  http://www.w3.org/2004/02/skos/core#
//! # # generated by deterministic curation (set provenance, not a mapping)
//! subject_id  predicate_id  object_id  mapping_justification  confidence  comment
//! ex:Foo  skos:closeMatch  sosa:Observation  semapv:ManualMappingCuration  0.7  …
//! # preserved after-table comment extension
//! ```
//!
//! (The column header and data rows are tab-separated in the real file; spaces
//! stand in here only because doc comments forbid raw tabs.)
//!
//! Scalar header lines are `# key: value`; the nested `# curie_map:` block is a
//! set of indented `#   prefix: uri` lines. PurRDF *owns* this format, so the
//! header is parsed bespoke — no YAML library. (The Python `_sssom_for_validation`
//! shim only existed to satisfy sssom-py's YAML reader; the native codec needs no
//! such crutch.) Set-level comments are a typed document envelope: unambiguous
//! `# #…` provenance is emitted after metadata and before the table, while a
//! parsed after-table comment extension retains its exact raw line and placement.
//! Physical input line endings are normalized to deterministic LF output.
//!
//! ## Parity intent
//!
//! [`validate`] reproduces the *reachable* default checks of sssom-py 0.4.x
//! (`PrefixMapCompleteness` + `JsonSchema`; see
//! `tests/fixtures/lint-golden/sssom_validation.json`) and then deliberately
//! *extends* them with a `RequiredSlot` check. sssom-py silently drops rows with a
//! missing required slot during parsing, so they never reach its validators and
//! produce no diagnostic; that is a parity *gap in sssom-py's favour of silence*,
//! not a behaviour worth preserving (CONSTITUTION / no-compromises). The native
//! validator is a strict SUPERSET: every committed corpus file is clean under both
//! the parity checks and the enhancement, so flagging the missing-slot negatives
//! is an improvement with no corpus regression.

use std::collections::{BTreeMap, BTreeSet};

use crate::{RdfDiagnostic, RdfLiteral, RdfLocation, RdfQuad, RdfSeverity, RdfTerm};

// --------------------------------------------------------------------------- //
// Vocabulary
// --------------------------------------------------------------------------- //

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const OWL_AXIOM: &str = "http://www.w3.org/2002/07/owl#Axiom";
const OWL_ANNOTATED_SOURCE: &str = "http://www.w3.org/2002/07/owl#annotatedSource";
const OWL_ANNOTATED_PROPERTY: &str = "http://www.w3.org/2002/07/owl#annotatedProperty";
const OWL_ANNOTATED_TARGET: &str = "http://www.w3.org/2002/07/owl#annotatedTarget";
const XSD_DOUBLE: &str = "http://www.w3.org/2001/XMLSchema#double";

/// The `https://w3id.org/sssom/` metadata namespace.
const SSSOM_NS: &str = "https://w3id.org/sssom/";

/// The default check set sssom-py runs (`validation_types=None`), captured from
/// `sssom.validators.DEFAULT_VALIDATION_TYPES` into the frozen golden. The native
/// validator implements the two *reachable-through-parse* checks of this set
/// (`PrefixMapCompleteness`, `JsonSchema`); `StrictCurieFormat` is unreachable
/// because PurRDF never emits a pipe-bearing entity slot. Exposed so a consumer can
/// report the parity surface it covers.
pub const SSSOM_DEFAULT_VALIDATION_TYPES: &[&str] =
    &["JsonSchema", "PrefixMapCompleteness", "StrictCurieFormat"];

/// The canonical SSSOM column order PurRDF writes.
const SSSOM_ORDER: &[&str] = &[
    "subject_id",
    "subject_label",
    "predicate_id",
    "object_id",
    "object_label",
    "mapping_justification",
    "confidence",
    "comment",
];

/// The columns PurRDF always emits, even when blank for every row.
const SSSOM_ALWAYS: &[&str] = &[
    "subject_id",
    "predicate_id",
    "object_id",
    "mapping_justification",
    "confidence",
    "comment",
];

// --------------------------------------------------------------------------- //
// IR types
// --------------------------------------------------------------------------- //

/// The SSSOM metadata header.
///
/// The named scalars cover everything PurRDF writes; any other `# key: value`
/// scalar is preserved verbatim in [`extra`](SssomMeta::extra) so nothing is lost
/// (maximal information flow). The `comment` value is kept *as authored* — PurRDF
/// JSON-quotes it (`"…—…"`), which this codec round-trips byte-for-byte
/// rather than re-interpreting.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SssomMeta {
    /// `mapping_set_id` — the mapping set's identifying IRI.
    pub mapping_set_id: Option<String>,
    /// `mapping_set_version` — the mapping set's version string.
    pub mapping_set_version: Option<String>,
    /// `license` — the mapping set's license IRI.
    pub license: Option<String>,
    /// `mapping_tool` — the tool that produced the mappings.
    pub mapping_tool: Option<String>,
    /// `mapping_tool_version` — the producing tool's version.
    pub mapping_tool_version: Option<String>,
    /// `mapping_date` — when the mappings were produced.
    pub mapping_date: Option<String>,
    /// `comment` — free-text commentary, kept byte-for-byte as authored.
    pub comment: Option<String>,
    /// `prefix → namespace-IRI` for every declared CURIE prefix.
    pub curie_map: BTreeMap<String, String>,
    /// Any header scalar outside the named set, preserved losslessly.
    pub extra: BTreeMap<String, String>,
}

/// A single SSSOM mapping (one TSV data row).
///
/// The named columns cover PurRDF's `SSSOM_ORDER`; any other column is preserved
/// verbatim in [`extras`](SssomMapping::extras) so a non-PurRDF SSSOM file still
/// round-trips losslessly.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SssomMapping {
    /// `subject_id` — the mapped subject entity (CURIE or IRI).
    pub subject_id: String,
    /// `subject_label` — the subject's human-readable label.
    pub subject_label: Option<String>,
    /// `predicate_id` — the mapping relation (e.g. `skos:exactMatch`).
    pub predicate_id: String,
    /// `object_id` — the mapped object entity (CURIE or IRI).
    pub object_id: String,
    /// `object_label` — the object's human-readable label.
    pub object_label: Option<String>,
    /// `mapping_justification` — the `semapv:` justification for the mapping.
    pub mapping_justification: String,
    /// `confidence` — the mapping confidence in `[0, 1]`, when scored.
    pub confidence: Option<f64>,
    /// `comment` — free-text commentary on the row.
    pub comment: Option<String>,
    /// Any column outside the named set, in declaration order.
    pub extras: BTreeMap<String, String>,
}

/// Where a set-scoped SSSOM comment appears in the document envelope.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SssomCommentPlacement {
    /// After the YAML-like metadata and before the TSV column header.
    ///
    /// Only provenance comments with an unambiguous second `#` marker are valid
    /// here; a single-marker line would be parsed as metadata.
    BeforeTable,
    /// After the final TSV mapping row (or after the column header for a
    /// zero-row mapping set).
    AfterTable,
}

/// The lexical kind of a set-scoped SSSOM comment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SssomCommentKind {
    /// A single-marker `#...` comment.
    Ordinary,
    /// A second-marker `# #...` provenance comment.
    Provenance,
}

/// A typed set-comment construction failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SssomCommentError {
    /// A raw comment line did not start with `#`.
    MissingMarker,
    /// One logical comment line contained `\r` or `\n`.
    EmbeddedLineTerminator,
    /// A single-marker comment was assigned to the metadata region, where it
    /// would be ambiguous with a YAML key or value.
    AmbiguousBeforeTable,
    /// An ordinary-comment constructor received content beginning with `#`,
    /// which would silently change the resulting line to provenance kind.
    KindMismatch,
}

impl std::fmt::Display for SssomCommentError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingMarker => f.write_str("a raw SSSOM set comment must start with `#`"),
            Self::EmbeddedLineTerminator => {
                f.write_str("a SSSOM set comment must contain exactly one logical line")
            }
            Self::AmbiguousBeforeTable => f.write_str(
                "a before-table SSSOM set comment must use the unambiguous `# #` provenance marker",
            ),
            Self::KindMismatch => {
                f.write_str("ordinary SSSOM set-comment content must not begin with a `#` marker")
            }
        }
    }
}

impl std::error::Error for SssomCommentError {}

/// One validated, set-scoped comment in the SSSOM document envelope.
///
/// The exact Unicode line content is retained, excluding the physical line
/// terminator. Fields are private so invalid marker/placement combinations cannot
/// be constructed by assignment; use [`Self::from_raw`], [`Self::ordinary`],
/// [`Self::provenance`], or [`Self::provenance_after_table`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SssomSetComment {
    placement: SssomCommentPlacement,
    raw_line: String,
}

impl SssomSetComment {
    /// Validate and retain an exact raw comment line at `placement`.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] for a missing marker, an embedded line
    /// terminator, or a single-marker line placed before the table.
    pub fn from_raw(
        raw_line: impl Into<String>,
        placement: SssomCommentPlacement,
    ) -> Result<Self, SssomCommentError> {
        let raw_line = raw_line.into();
        let kind = classify_comment_line(&raw_line)?;
        if placement == SssomCommentPlacement::BeforeTable && kind == SssomCommentKind::Ordinary {
            return Err(SssomCommentError::AmbiguousBeforeTable);
        }
        Ok(Self {
            placement,
            raw_line,
        })
    }

    /// Construct an ordinary after-table comment from unprefixed content.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator or
    /// begins with `#` after leading whitespace.
    pub fn ordinary(content: impl Into<String>) -> Result<Self, SssomCommentError> {
        let content = content.into();
        validate_comment_content(&content)?;
        if content.trim_start().starts_with('#') {
            return Err(SssomCommentError::KindMismatch);
        }
        Self::from_raw(format!("# {content}"), SssomCommentPlacement::AfterTable)
    }

    /// Construct standard-compatible before-table provenance from unprefixed
    /// content. Empty content produces the exact line `# #`.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator.
    pub fn provenance(content: impl Into<String>) -> Result<Self, SssomCommentError> {
        let content = content.into();
        Self::provenance_at(&content, SssomCommentPlacement::BeforeTable)
    }

    /// Construct after-table provenance from unprefixed content. Empty content
    /// produces the exact line `# #`.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator.
    pub fn provenance_after_table(content: impl Into<String>) -> Result<Self, SssomCommentError> {
        let content = content.into();
        Self::provenance_at(&content, SssomCommentPlacement::AfterTable)
    }

    fn provenance_at(
        content: &str,
        placement: SssomCommentPlacement,
    ) -> Result<Self, SssomCommentError> {
        validate_comment_content(content)?;
        let raw_line = if content.is_empty() {
            "# #".to_owned()
        } else {
            format!("# # {content}")
        };
        Self::from_raw(raw_line, placement)
    }

    /// The comment's document placement.
    pub const fn placement(&self) -> SssomCommentPlacement {
        self.placement
    }

    /// The comment's kind, derived from its validated raw line.
    pub fn kind(&self) -> SssomCommentKind {
        classify_comment_line(&self.raw_line)
            .expect("SssomSetComment construction validates its raw line")
    }

    /// The exact Unicode comment line, excluding its physical line terminator.
    pub fn raw_line(&self) -> &str {
        &self.raw_line
    }
}

fn validate_comment_content(content: &str) -> Result<(), SssomCommentError> {
    if content.contains(['\r', '\n']) {
        Err(SssomCommentError::EmbeddedLineTerminator)
    } else {
        Ok(())
    }
}

fn classify_comment_line(raw_line: &str) -> Result<SssomCommentKind, SssomCommentError> {
    validate_comment_content(raw_line)?;
    let Some(after_marker) = raw_line.strip_prefix('#') else {
        return Err(SssomCommentError::MissingMarker);
    };
    if after_marker.trim_start().starts_with('#') {
        Ok(SssomCommentKind::Provenance)
    } else {
        Ok(SssomCommentKind::Ordinary)
    }
}

/// A validated TSV column declaration retained from a parsed SSSOM mapping set.
///
/// An empty layout means a programmatically constructed set should infer the
/// canonical columns from its mappings. A non-empty layout preserves parsed
/// column order, including optional or extension columns on zero-row sets.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SssomColumnLayout {
    columns: Vec<String>,
}

/// A declared SSSOM TSV column-layout construction failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SssomColumnLayoutError {
    /// A column name was empty.
    EmptyName,
    /// A column name contained a TSV or line delimiter.
    InvalidDelimiter(String),
    /// A column name appeared more than once.
    DuplicateName(String),
}

impl std::fmt::Display for SssomColumnLayoutError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyName => f.write_str("a SSSOM TSV column name must not be empty"),
            Self::InvalidDelimiter(name) => write!(
                f,
                "SSSOM TSV column name {name:?} contains a tab or line terminator"
            ),
            Self::DuplicateName(name) => {
                write!(f, "duplicate SSSOM TSV column name {name:?}")
            }
        }
    }
}

impl std::error::Error for SssomColumnLayoutError {}

impl SssomColumnLayout {
    /// Validate and retain a declared column sequence.
    ///
    /// # Errors
    ///
    /// Returns [`SssomColumnLayoutError`] for an empty, duplicate, tabbed, or
    /// multiline name.
    pub fn new<I, S>(columns: I) -> Result<Self, SssomColumnLayoutError>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        let mut retained = Vec::new();
        let mut seen = BTreeSet::new();
        for column in columns {
            let column = column.into();
            if column.is_empty() {
                return Err(SssomColumnLayoutError::EmptyName);
            }
            if column.contains(['\t', '\r', '\n']) {
                return Err(SssomColumnLayoutError::InvalidDelimiter(column));
            }
            if !seen.insert(column.clone()) {
                return Err(SssomColumnLayoutError::DuplicateName(column));
            }
            retained.push(column);
        }
        Ok(Self { columns: retained })
    }

    /// Declared columns in source order.
    pub fn columns(&self) -> &[String] {
        &self.columns
    }

    /// Whether the serializer should infer the canonical layout from mappings.
    pub fn is_inferred(&self) -> bool {
        self.columns.is_empty()
    }
}

/// A parsed SSSOM mapping set: header metadata, mappings, and document envelope.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SssomMappingSet {
    /// The `# `-prefixed YAML header metadata.
    pub meta: SssomMeta,
    /// The mapping rows, in file order.
    pub mappings: Vec<SssomMapping>,
    /// Parsed TSV column declaration, or an empty inferred layout for a set
    /// constructed through [`Self::new`].
    pub column_layout: SssomColumnLayout,
    /// Validated set-level comments in document order within each placement.
    pub set_comments: Vec<SssomSetComment>,
}

impl SssomMappingSet {
    /// Construct a mapping set whose serializer infers canonical columns.
    pub fn new(meta: SssomMeta, mappings: Vec<SssomMapping>) -> Self {
        Self {
            meta,
            mappings,
            column_layout: SssomColumnLayout::default(),
            set_comments: Vec::new(),
        }
    }

    /// Replace the inferred/parsed column layout with `column_layout`.
    #[must_use]
    pub fn with_column_layout(mut self, column_layout: SssomColumnLayout) -> Self {
        self.column_layout = column_layout;
        self
    }

    /// Append standard-compatible before-table mapping-set provenance.
    ///
    /// Mutation is atomic: an invalid value leaves the set unchanged.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator.
    pub fn append_provenance(
        &mut self,
        content: impl Into<String>,
    ) -> Result<(), SssomCommentError> {
        let comment = SssomSetComment::provenance(content)?;
        self.set_comments.push(comment);
        Ok(())
    }

    /// Append an ordinary after-table set comment.
    ///
    /// Mutation is atomic: an invalid value leaves the set unchanged.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator or
    /// begins with `#` after leading whitespace.
    pub fn append_after_table_comment(
        &mut self,
        content: impl Into<String>,
    ) -> Result<(), SssomCommentError> {
        let comment = SssomSetComment::ordinary(content)?;
        self.set_comments.push(comment);
        Ok(())
    }

    /// Append after-table mapping-set provenance.
    ///
    /// Mutation is atomic: an invalid value leaves the set unchanged.
    ///
    /// # Errors
    ///
    /// Returns [`SssomCommentError`] when `content` contains a line terminator.
    pub fn append_after_table_provenance(
        &mut self,
        content: impl Into<String>,
    ) -> Result<(), SssomCommentError> {
        let comment = SssomSetComment::provenance_after_table(content)?;
        self.set_comments.push(comment);
        Ok(())
    }
}

/// A single validation diagnostic, mirroring the sssom-py golden record shape
/// `{severity, type, message, instance, check}`. `code` carries the golden's
/// `type` string; `check` carries the originating check name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SssomDiagnostic {
    /// The finding's severity.
    pub severity: RdfSeverity,
    /// The golden record's `type` string (the machine-readable finding code).
    pub code: String,
    /// The human-readable finding message.
    pub message: String,
    /// The offending value, when the check can point at one.
    pub instance: Option<String>,
    /// The originating check name (e.g. `PrefixMapCompleteness`).
    pub check: String,
}

impl SssomDiagnostic {
    fn error(
        code: impl Into<String>,
        check: impl Into<String>,
        message: impl Into<String>,
        instance: Option<String>,
    ) -> Self {
        Self {
            severity: RdfSeverity::Error,
            code: code.into(),
            message: message.into(),
            instance,
            check: check.into(),
        }
    }
}

// --------------------------------------------------------------------------- //
// Parsing
// --------------------------------------------------------------------------- //

/// Parse a PurRDF SSSOM TSV document into an owned [`SssomMappingSet`].
///
/// The `#`-prefixed header (scalars + the nested `curie_map:` block) is parsed
/// bespoke; the TSV body is parsed with the `csv` crate (tab delimiter, flexible
/// column counts, by-name access). Unknown header scalars and unknown columns are
/// preserved verbatim. Unambiguous `# #…` provenance in the leading envelope
/// and comments in the trailing envelope are retained as typed set comments.
///
/// Returns `Err(RdfDiagnostic)` only on structurally unparsable input (no TSV
/// column-header row, a malformed `# key` line, or a body the TSV reader rejects):
/// semantic defects (unknown prefix, bad confidence, missing slot) are surfaced by
/// [`validate`], not here, so a caller can ingest-then-validate the way sssom-py's
/// `parse_tsv` → `validate` split does.
pub fn parse_tsv(text: &str) -> Result<SssomMappingSet, RdfDiagnostic> {
    let lines: Vec<&str> = text.lines().collect();

    // Locate the TSV column-header row: the first line that does not start with
    // '#'. Everything before it is the metadata header.
    let header_idx = lines.iter().position(|line| !line.starts_with('#'));
    let Some(header_idx) = header_idx else {
        return Err(RdfDiagnostic::error(
            "sssom-tsv-parse",
            "no TSV column-header row found (every line is a `#` comment)",
        ));
    };

    let (meta, mut set_comments) = parse_header(&lines[..header_idx])?;

    // Only the final comment suffix is a trailing document envelope. Comments
    // interleaved between mappings remain non-row annotations and are skipped,
    // preserving the existing row-diagnostic line mapping without incorrectly
    // moving them to the end during a subsequent serialization.
    let table_and_suffix = &lines[header_idx..];
    let suffix_start = table_and_suffix
        .iter()
        .rposition(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map_or(table_and_suffix.len(), |offset| offset + 1);

    // The body is the column-header row plus the data rows. `#` provenance
    // comments (PurRDF emits its trailer block right after the column header when
    // there are zero rows, or interleaved) and blank lines are not mappings; skip
    // them while recording each kept line's original 1-based source line number,
    // so a diagnostic reports the true line even when a comment is interleaved
    // between data rows (passing a flat offset shifted every later row's line).
    let mut body = String::new();
    let mut line_numbers: Vec<u32> = Vec::new();
    for (offset, line) in table_and_suffix.iter().enumerate() {
        if line.starts_with('#') {
            if offset >= suffix_start {
                let line_no = (header_idx + offset + 1) as u32;
                let comment = SssomSetComment::from_raw(
                    (*line).to_owned(),
                    SssomCommentPlacement::AfterTable,
                )
                .map_err(|error| {
                    RdfDiagnostic::error(
                        "sssom-tsv-parse",
                        format!("invalid trailing SSSOM set comment: {error}"),
                    )
                    .with_location(RdfLocation::default().with_line(line_no))
                })?;
                set_comments.push(comment);
            }
            continue;
        }
        if line.trim().is_empty() {
            continue;
        }
        line_numbers.push((header_idx + offset + 1) as u32);
        body.push_str(line);
        body.push('\n');
    }

    let (column_layout, mappings) = parse_body(&body, &line_numbers)?;
    Ok(SssomMappingSet {
        meta,
        mappings,
        column_layout,
        set_comments,
    })
}

/// Parse leading metadata and unambiguous provenance comments.
fn parse_header(lines: &[&str]) -> Result<(SssomMeta, Vec<SssomSetComment>), RdfDiagnostic> {
    let mut meta = SssomMeta::default();
    let mut set_comments = Vec::new();
    let mut in_curie_map = false;

    for (offset, raw) in lines.iter().enumerate() {
        let line_no = (offset + 1) as u32;
        // Strip the leading '#'. A bare '#' line is an empty comment; skip it.
        let body = raw.strip_prefix('#').unwrap_or(raw);
        if body.trim().is_empty() {
            continue;
        }
        // A `# #…` line is unambiguous set provenance: the second marker keeps it
        // distinct from a YAML scalar. It does not close an open curie_map block,
        // so further indented entries remain valid.
        if body.trim_start().starts_with('#') {
            let comment =
                SssomSetComment::from_raw((*raw).to_owned(), SssomCommentPlacement::BeforeTable)
                    .map_err(|error| {
                        RdfDiagnostic::error(
                            "sssom-tsv-parse",
                            format!("invalid leading SSSOM set comment: {error}"),
                        )
                        .with_location(RdfLocation::default().with_line(line_no))
                    })?;
            set_comments.push(comment);
            continue;
        }

        // `#   prefix: uri` (two+ leading spaces) inside a `curie_map:` block.
        // The block is "open" from the `# curie_map:` line until a non-indented
        // scalar (or end of header). PurRDF indents curie entries with three
        // spaces; accept any indent of one or more.
        let is_indented = body.starts_with(' ') && body.trim_start() != body;
        if in_curie_map && is_indented {
            let entry = body.trim();
            let (prefix, uri) = split_key_value(entry).ok_or_else(|| {
                RdfDiagnostic::error(
                    "sssom-tsv-parse",
                    format!("malformed curie_map entry: {entry:?}"),
                )
                .with_location(RdfLocation::default().with_line(line_no))
            })?;
            meta.curie_map.insert(prefix.to_owned(), uri.to_owned());
            continue;
        }

        // A non-indented line ends any open curie_map block.
        in_curie_map = false;

        let scalar = body.trim_start();
        let (key, value) = split_key_value(scalar).ok_or_else(|| {
            RdfDiagnostic::error(
                "sssom-tsv-parse",
                format!("malformed header line: {scalar:?}"),
            )
            .with_location(RdfLocation::default().with_line(line_no))
        })?;

        match key {
            "curie_map" => {
                // The nested-block opener: `# curie_map:` with an empty value.
                // A non-empty inline value (e.g. the broken `[unclosed` fixture)
                // is a malformed flow sequence PurRDF never emits — reject it the
                // way sssom-py's YAML reader does (it raised a FATAL parse error).
                if !value.is_empty() {
                    return Err(RdfDiagnostic::error(
                        "sssom-tsv-parse",
                        format!("inline curie_map value is not supported: {value:?}"),
                    )
                    .with_location(RdfLocation::default().with_line(line_no)));
                }
                in_curie_map = true;
            }
            "mapping_set_id" => meta.mapping_set_id = Some(value.to_owned()),
            "mapping_set_version" => meta.mapping_set_version = Some(value.to_owned()),
            "license" => meta.license = Some(value.to_owned()),
            "mapping_tool" => meta.mapping_tool = Some(value.to_owned()),
            "mapping_tool_version" => meta.mapping_tool_version = Some(value.to_owned()),
            "mapping_date" => meta.mapping_date = Some(value.to_owned()),
            "comment" => meta.comment = Some(value.to_owned()),
            other => {
                meta.extra.insert(other.to_owned(), value.to_owned());
            }
        }
    }
    Ok((meta, set_comments))
}

/// Split a `key: value` scalar at the first `": "` (or a trailing `":"`).
///
/// Returns `None` if there is no colon at all. The value is the remainder
/// verbatim (no YAML unquoting — PurRDF owns the format and the comment value is
/// kept as authored for byte-stable round-trips).
fn split_key_value(scalar: &str) -> Option<(&str, &str)> {
    let idx = scalar.find(':')?;
    let key = scalar[..idx].trim();
    if key.is_empty() {
        return None;
    }
    // Skip the colon and a single following space if present.
    let rest = &scalar[idx + 1..];
    let value = rest.strip_prefix(' ').unwrap_or(rest);
    Some((key, value.trim_end()))
}

/// Parse the TSV body (column-header row + data rows) into mappings.
///
/// `line_numbers` holds the original 1-based source line of each body line in
/// order: `line_numbers[0]` is the column-header row, and data row `i` is at
/// `line_numbers[i + 1]`. This keeps diagnostics anchored to the true source
/// position regardless of how many `#` comment lines were filtered out upstream.
fn parse_body(
    body: &str,
    line_numbers: &[u32],
) -> Result<(SssomColumnLayout, Vec<SssomMapping>), RdfDiagnostic> {
    if body.trim().is_empty() {
        return Err(RdfDiagnostic::error(
            "sssom-tsv-parse",
            "missing TSV column-header row",
        ));
    }

    let mut reader = csv::ReaderBuilder::new()
        .delimiter(b'\t')
        .flexible(true)
        .has_headers(true)
        .from_reader(body.as_bytes());

    // `csv` validates the header lazily; fetch it up front so a malformed header
    // is reported with the right line (the first body line).
    let header_line = line_numbers.first().copied().unwrap_or(1);
    let columns: Vec<String> = reader
        .headers()
        .map_err(|e| {
            RdfDiagnostic::error("sssom-tsv-parse", format!("unreadable TSV header: {e}"))
                .with_location(RdfLocation::default().with_line(header_line))
        })?
        .iter()
        .map(str::to_owned)
        .collect();
    let column_layout = SssomColumnLayout::new(columns.clone()).map_err(|error| {
        RdfDiagnostic::error(
            "sssom-tsv-parse",
            format!("invalid TSV column declaration: {error}"),
        )
        .with_location(RdfLocation::default().with_line(header_line))
    })?;

    let mut mappings = Vec::new();
    for (row_index, record) in reader.records().enumerate() {
        // The data row's true 1-based source line: line_numbers[0] is the column
        // header, so data row `row_index` is at line_numbers[row_index + 1].
        let line_no = line_numbers
            .get(row_index + 1)
            .copied()
            .unwrap_or(header_line);
        let record = record.map_err(|e| {
            RdfDiagnostic::error("sssom-tsv-parse", format!("malformed TSV row: {e}"))
                .with_location(RdfLocation::default().with_line(line_no))
        })?;
        mappings.push(parse_row(&columns, &record, line_no)?);
    }
    Ok((column_layout, mappings))
}

/// Map one TSV record onto a [`SssomMapping`] by column name.
fn parse_row(
    columns: &[String],
    record: &csv::StringRecord,
    line_no: u32,
) -> Result<SssomMapping, RdfDiagnostic> {
    let mut mapping = SssomMapping::default();
    for (col, value) in columns.iter().zip(record.iter()) {
        let value = value.to_owned();
        match col.as_str() {
            "subject_id" => mapping.subject_id = value,
            "subject_label" => mapping.subject_label = non_empty(value),
            "predicate_id" => mapping.predicate_id = value,
            "object_id" => mapping.object_id = value,
            "object_label" => mapping.object_label = non_empty(value),
            "mapping_justification" => mapping.mapping_justification = value,
            "confidence" => {
                if !value.is_empty() {
                    let parsed = value.parse::<f64>().map_err(|_| {
                        RdfDiagnostic::error(
                            "sssom-tsv-parse",
                            format!("non-numeric confidence: {value:?}"),
                        )
                        .with_location(RdfLocation::default().with_line(line_no))
                    })?;
                    mapping.confidence = Some(parsed);
                }
            }
            "comment" => mapping.comment = non_empty(value),
            other => {
                mapping.extras.insert(other.to_owned(), value);
            }
        }
    }
    Ok(mapping)
}

/// `None` for an empty string, `Some(value)` otherwise.
fn non_empty(value: String) -> Option<String> {
    if value.is_empty() { None } else { Some(value) }
}

// --------------------------------------------------------------------------- //
// Validation
// --------------------------------------------------------------------------- //

/// The required entity slots of a mapping (SSSOM core).
const REQUIRED_SLOTS: &[&str] = &[
    "subject_id",
    "predicate_id",
    "object_id",
    "mapping_justification",
];

/// Validate a mapping set, returning every ERROR-severity diagnostic.
///
/// Reproduces the *reachable* default sssom-py checks and extends them:
///
/// * **`PrefixMapCompleteness`** — every CURIE prefix used in `subject_id`,
///   `predicate_id`, `object_id`, or `mapping_justification` must be declared in
///   the `curie_map`. An undeclared prefix is an ERROR (`Missing prefix: <pfx>`).
/// * **`JsonSchema`** — `confidence`, when present, must lie in `[0.0, 1.0]`;
///   out-of-range is an ERROR (matching sssom-py's JSON-schema min/max).
/// * **`RequiredSlot`** *(enhancement)* — every required entity slot
///   (`subject_id`, `predicate_id`, `object_id`, `mapping_justification`) must be
///   present and non-empty. sssom-py *silently drops* such rows during parsing, so
///   they never reach its validators; the native codec flags them instead. This is
///   a deliberate strict-superset improvement, NOT a parity regression — every
///   committed corpus file populates all four slots, so the clean corpus is
///   unaffected.
///
/// The mapping-justification slot is checked for prefix completeness but its CURIE
/// shape is otherwise left to `RequiredSlot`/downstream: a non-CURIE justification
/// (no `:`) carries no prefix, so it neither trips nor satisfies the prefix check —
/// matching the corpus, where the justification is always a `semapv:` CURIE.
pub fn validate(set: &SssomMappingSet) -> Vec<SssomDiagnostic> {
    let mut diagnostics = Vec::new();

    for mapping in &set.mappings {
        validate_required_slots(mapping, &mut diagnostics);
        validate_prefixes(mapping, &set.meta, &mut diagnostics);
        validate_confidence(mapping, &mut diagnostics);
    }

    diagnostics
}

/// ENHANCEMENT check: every required slot is present and non-empty.
fn validate_required_slots(mapping: &SssomMapping, out: &mut Vec<SssomDiagnostic>) {
    let slots = [
        ("subject_id", mapping.subject_id.as_str()),
        ("predicate_id", mapping.predicate_id.as_str()),
        ("object_id", mapping.object_id.as_str()),
        (
            "mapping_justification",
            mapping.mapping_justification.as_str(),
        ),
    ];
    for (name, value) in slots {
        debug_assert!(REQUIRED_SLOTS.contains(&name));
        if value.trim().is_empty() {
            out.push(SssomDiagnostic::error(
                "required slot",
                "RequiredSlot",
                format!("Missing required slot: {name}"),
                mapping_instance(mapping),
            ));
        }
    }
}

/// Parity check: every CURIE prefix used is declared in the curie_map.
fn validate_prefixes(mapping: &SssomMapping, meta: &SssomMeta, out: &mut Vec<SssomDiagnostic>) {
    let entities = [
        mapping.subject_id.as_str(),
        mapping.predicate_id.as_str(),
        mapping.object_id.as_str(),
        mapping.mapping_justification.as_str(),
    ];
    for entity in entities {
        let Some(prefix) = curie_prefix(entity) else {
            continue;
        };
        if !meta.curie_map.contains_key(prefix) {
            out.push(SssomDiagnostic::error(
                "prefix validation",
                "PrefixMapCompleteness",
                format!("Missing prefix: {prefix}"),
                mapping_instance(mapping),
            ));
        }
    }
}

/// Parity check: `confidence`, when present, lies in `[0.0, 1.0]`.
fn validate_confidence(mapping: &SssomMapping, out: &mut Vec<SssomDiagnostic>) {
    if let Some(confidence) = mapping.confidence {
        if confidence < 0.0 {
            out.push(SssomDiagnostic::error(
                "jsonschema validation",
                "JsonSchema",
                format!("{confidence} is less than the minimum of 0.0"),
                mapping_instance(mapping),
            ));
        } else if confidence > 1.0 {
            out.push(SssomDiagnostic::error(
                "jsonschema validation",
                "JsonSchema",
                format!("{confidence} is greater than the maximum of 1.0"),
                mapping_instance(mapping),
            ));
        }
    }
}

/// The CURIE prefix of an entity reference, or `None` if it is not a CURIE.
///
/// A CURIE is `prefix:reference` with a non-empty prefix that is *not* a scheme of
/// an absolute IRI (`http://`, `https://`, …). PurRDF writes bare absolute URIs for
/// unregistered namespaces, which must not be mistaken for a `http`/`https` CURIE
/// prefix.
fn curie_prefix(entity: &str) -> Option<&str> {
    let idx = entity.find(':')?;
    let prefix = &entity[..idx];
    if prefix.is_empty() {
        return None;
    }
    // An absolute IRI: `prefix` is a scheme and the reference starts with `//`.
    if entity[idx + 1..].starts_with("//") {
        return None;
    }
    Some(prefix)
}

/// The instance handle a diagnostic points at: the offending row's `subject_id`
/// (or its first non-empty entity if the subject is itself missing), or `None`.
fn mapping_instance(mapping: &SssomMapping) -> Option<String> {
    for candidate in [
        mapping.subject_id.as_str(),
        mapping.object_id.as_str(),
        mapping.predicate_id.as_str(),
    ] {
        if !candidate.is_empty() {
            return Some(candidate.to_owned());
        }
    }
    None
}

// --------------------------------------------------------------------------- //
// TSV serialization
// --------------------------------------------------------------------------- //

/// Serialize a mapping set back to canonical PurRDF SSSOM TSV.
///
/// Emits the metadata header, before-table provenance, the retained or inferred
/// columns, rows sorted by `(subject_id, predicate_id, object_id)`, and the
/// after-table comment envelope. Parsed column order and exact comment-line
/// content are retained; newly introduced columns are appended deterministically.
/// Physical line endings are canonical LF. IDs are kept as authored (CURIEs are
/// not expanded).
pub fn serialize_tsv(set: &SssomMappingSet) -> String {
    let mut lines: Vec<String> = Vec::new();
    let meta = &set.meta;

    push_scalar(&mut lines, "mapping_set_id", meta.mapping_set_id.as_ref());
    push_scalar(
        &mut lines,
        "mapping_set_version",
        meta.mapping_set_version.as_ref(),
    );
    push_scalar(&mut lines, "license", meta.license.as_ref());
    push_scalar(&mut lines, "mapping_tool", meta.mapping_tool.as_ref());
    push_scalar(
        &mut lines,
        "mapping_tool_version",
        meta.mapping_tool_version.as_ref(),
    );
    push_scalar(&mut lines, "mapping_date", meta.mapping_date.as_ref());
    push_scalar(&mut lines, "comment", meta.comment.as_ref());
    for (key, value) in &meta.extra {
        lines.push(format!("# {key}: {value}"));
    }
    if !meta.curie_map.is_empty() {
        lines.push("# curie_map:".to_owned());
        for (prefix, uri) in &meta.curie_map {
            lines.push(format!("#   {prefix}: {uri}"));
        }
    }

    for comment in set
        .set_comments
        .iter()
        .filter(|comment| comment.placement() == SssomCommentPlacement::BeforeTable)
    {
        lines.push(comment.raw_line().to_owned());
    }

    let columns = serialization_columns(set);
    lines.push(columns.join("\t"));

    let mut sorted: Vec<&SssomMapping> = set.mappings.iter().collect();
    sorted.sort_by(|a, b| {
        (&a.subject_id, &a.predicate_id, &a.object_id).cmp(&(
            &b.subject_id,
            &b.predicate_id,
            &b.object_id,
        ))
    });
    for mapping in sorted {
        let row: Vec<String> = columns.iter().map(|col| cell(mapping, col)).collect();
        lines.push(row.join("\t"));
    }

    for comment in set
        .set_comments
        .iter()
        .filter(|comment| comment.placement() == SssomCommentPlacement::AfterTable)
    {
        lines.push(comment.raw_line().to_owned());
    }

    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// Choose retained or inferred columns, appending newly introduced data in a
/// deterministic order without discarding a parsed zero-row declaration.
fn serialization_columns(set: &SssomMappingSet) -> Vec<String> {
    let mut columns = if set.column_layout.is_inferred() {
        SSSOM_ORDER
            .iter()
            .copied()
            .filter(|column| {
                SSSOM_ALWAYS.contains(column)
                    || set
                        .mappings
                        .iter()
                        .any(|mapping| cell_is_populated(mapping, column))
            })
            .map(str::to_owned)
            .collect()
    } else {
        set.column_layout.columns().to_vec()
    };
    let mut seen: BTreeSet<String> = columns.iter().cloned().collect();

    // A caller may populate a known field that was absent from a retained source
    // layout. Append such fields in the canonical SSSOM order.
    for column in SSSOM_ORDER {
        if !seen.contains(*column)
            && set
                .mappings
                .iter()
                .any(|mapping| cell_is_populated(mapping, column))
        {
            let column = (*column).to_owned();
            seen.insert(column.clone());
            columns.push(column);
        }
    }

    // Extension columns absent from the retained declaration follow known
    // fields in lexical order. Presence in `extras` is itself a declared caller
    // intent, even when every current value is blank.
    let extra_columns: BTreeSet<&str> = set
        .mappings
        .iter()
        .flat_map(|mapping| mapping.extras.keys().map(String::as_str))
        .collect();
    for column in extra_columns {
        if !seen.contains(column) {
            let column = column.to_owned();
            seen.insert(column.clone());
            columns.push(column);
        }
    }
    columns
}

/// Whether a named SSSOM cell carries a value.
fn cell_is_populated(mapping: &SssomMapping, column: &str) -> bool {
    match column {
        "subject_id" => !mapping.subject_id.is_empty(),
        "subject_label" => mapping
            .subject_label
            .as_deref()
            .is_some_and(|value| !value.is_empty()),
        "predicate_id" => !mapping.predicate_id.is_empty(),
        "object_id" => !mapping.object_id.is_empty(),
        "object_label" => mapping
            .object_label
            .as_deref()
            .is_some_and(|value| !value.is_empty()),
        "mapping_justification" => !mapping.mapping_justification.is_empty(),
        "confidence" => mapping.confidence.is_some(),
        "comment" => mapping
            .comment
            .as_deref()
            .is_some_and(|value| !value.is_empty()),
        other => mapping
            .extras
            .get(other)
            .is_some_and(|value| !value.is_empty()),
    }
}

/// Push a `# key: value` header line when the scalar is present.
fn push_scalar(lines: &mut Vec<String>, key: &str, value: Option<&String>) {
    if let Some(value) = value {
        lines.push(format!("# {key}: {value}"));
    }
}

/// The serialized TSV cell for a named column, including any preserved extra.
fn cell(mapping: &SssomMapping, column: &str) -> String {
    match column {
        "subject_id" => mapping.subject_id.clone(),
        "subject_label" => mapping.subject_label.clone().unwrap_or_default(),
        "predicate_id" => mapping.predicate_id.clone(),
        "object_id" => mapping.object_id.clone(),
        "object_label" => mapping.object_label.clone().unwrap_or_default(),
        "mapping_justification" => mapping.mapping_justification.clone(),
        "confidence" => mapping
            .confidence
            .map(format_confidence)
            .unwrap_or_default(),
        "comment" => mapping.comment.clone().unwrap_or_default(),
        other => mapping.extras.get(other).cloned().unwrap_or_default(),
    }
}

/// Format a confidence as the shortest round-trip-stable decimal (`0.7`, not
/// `0.70`), matching the PurRDF writer.
fn format_confidence(value: f64) -> String {
    // Rust's default float formatting already drops trailing zeros and prints the
    // shortest decimal that round-trips, so `0.7_f64` → "0.7" and `1.0` → "1".
    // Preserve a decimal point for whole confidences so the column stays numeric.
    let text = value.to_string();
    if text.contains('.') {
        text
    } else {
        format!("{text}.0")
    }
}

// --------------------------------------------------------------------------- //
// RDF serialization (SUBSUME / ENHANCE — a capability sssom-py lacked here)
// --------------------------------------------------------------------------- //

/// Serialize a mapping set to the SSSOM RDF mapping-set form (owned quads).
///
/// Each mapping is emitted as a reified OWL axiom node (`a owl:Axiom`) with
/// `owl:annotatedSource`/`owl:annotatedProperty`/`owl:annotatedTarget` carrying
/// the (CURIE-resolved) subject/predicate/object, plus the SSSOM metadata
/// predicates `sssom:mapping_justification`, `sssom:confidence`, and
/// `sssom:comment` under the `https://w3id.org/sssom/` namespace. Confidence is an
/// `xsd:double` literal; everything else is an IRI or plain literal.
///
/// CURIEs are resolved through `meta.curie_map`; an already-absolute IRI is used
/// as-is. The reifier node is a blank node, one per mapping. This RDF form is a
/// NEW capability (the Python toolkit had no equivalent here) and is not under any
/// byte-parity gate; it is well-formed and tested but matches no committed file.
pub fn to_rdf(set: &SssomMappingSet) -> Vec<RdfQuad> {
    let mut quads = Vec::new();
    for (index, mapping) in set.mappings.iter().enumerate() {
        let node = RdfTerm::blank_node(format!("mapping{index}"));

        quads.push(RdfQuad::new(
            node.clone(),
            RDF_TYPE,
            RdfTerm::iri(OWL_AXIOM),
        ));
        quads.push(RdfQuad::new(
            node.clone(),
            OWL_ANNOTATED_SOURCE,
            resolve_iri(&mapping.subject_id, &set.meta),
        ));
        quads.push(RdfQuad::new(
            node.clone(),
            OWL_ANNOTATED_PROPERTY,
            resolve_iri(&mapping.predicate_id, &set.meta),
        ));
        quads.push(RdfQuad::new(
            node.clone(),
            OWL_ANNOTATED_TARGET,
            resolve_iri(&mapping.object_id, &set.meta),
        ));

        if !mapping.mapping_justification.is_empty() {
            quads.push(RdfQuad::new(
                node.clone(),
                format!("{SSSOM_NS}mapping_justification"),
                resolve_iri(&mapping.mapping_justification, &set.meta),
            ));
        }
        if let Some(confidence) = mapping.confidence {
            quads.push(RdfQuad::new(
                node.clone(),
                format!("{SSSOM_NS}confidence"),
                RdfTerm::literal(RdfLiteral::typed(confidence.to_string(), XSD_DOUBLE)),
            ));
        }
        if let Some(comment) = &mapping.comment {
            quads.push(RdfQuad::new(
                node.clone(),
                format!("{SSSOM_NS}comment"),
                RdfTerm::literal(RdfLiteral::simple(comment.clone())),
            ));
        }
        if let Some(label) = &mapping.subject_label {
            quads.push(RdfQuad::new(
                resolve_iri(&mapping.subject_id, &set.meta),
                format!("{SSSOM_NS}subject_label"),
                RdfTerm::literal(RdfLiteral::simple(label.clone())),
            ));
        }
        if let Some(label) = &mapping.object_label {
            quads.push(RdfQuad::new(
                resolve_iri(&mapping.object_id, &set.meta),
                format!("{SSSOM_NS}object_label"),
                RdfTerm::literal(RdfLiteral::simple(label.clone())),
            ));
        }
    }
    quads
}

/// Resolve an entity reference to a full-IRI [`RdfTerm`].
///
/// A CURIE whose prefix is in the curie_map expands to `<namespace><reference>`;
/// anything else (an already-absolute IRI, or a CURIE with an undeclared prefix)
/// is used verbatim. Prefix completeness is [`validate`]'s job, not the
/// serializer's — `to_rdf` emits the best-effort IRI regardless so a partially
/// valid set still produces inspectable RDF.
fn resolve_iri(entity: &str, meta: &SssomMeta) -> RdfTerm {
    if let Some(prefix) = curie_prefix(entity)
        && let Some(namespace) = meta.curie_map.get(prefix)
    {
        let reference = &entity[prefix.len() + 1..];
        return RdfTerm::iri(format!("{namespace}{reference}"));
    }
    RdfTerm::iri(entity.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal, clean in-memory SSSOM document.
    const CLEAN: &str = "\
# mapping_set_id: https://example.org/mappings/demo
# mapping_set_version: 0.1.0
# license: https://creativecommons.org/licenses/by/4.0/
# comment: \"demo set\"
# curie_map:
#   ex: https://example.org/vocab/
#   skos: http://www.w3.org/2004/02/skos/core#
#   semapv: https://w3id.org/semapv/vocab/
#   sosa: http://www.w3.org/ns/sosa/
subject_id\tpredicate_id\tobject_id\tobject_label\tmapping_justification\tconfidence\tcomment
ex:Foo\tskos:closeMatch\tsosa:Observation\tObservation\tsemapv:ManualMappingCuration\t0.7\ta note
";

    fn negative(rows: &str) -> String {
        format!(
            "\
# mapping_set_id: https://example.org/mappings/demo
# curie_map:
#   ex: https://example.org/vocab/
#   skos: http://www.w3.org/2004/02/skos/core#
#   semapv: https://w3id.org/semapv/vocab/
#   sosa: http://www.w3.org/ns/sosa/
subject_id\tpredicate_id\tobject_id\tmapping_justification\tconfidence\tcomment
{rows}"
        )
    }

    #[test]
    fn typed_set_comments_preserve_kind_placement_and_raw_content() {
        let before =
            SssomSetComment::provenance("curation —  exact  spacing ").expect("valid provenance");
        assert_eq!(before.placement(), SssomCommentPlacement::BeforeTable);
        assert_eq!(before.kind(), SssomCommentKind::Provenance);
        assert_eq!(before.raw_line(), "# # curation —  exact  spacing ");

        let ordinary = SssomSetComment::ordinary("plain note  ").expect("valid comment");
        assert_eq!(ordinary.placement(), SssomCommentPlacement::AfterTable);
        assert_eq!(ordinary.kind(), SssomCommentKind::Ordinary);
        assert_eq!(ordinary.raw_line(), "# plain note  ");

        let empty = SssomSetComment::provenance_after_table("").expect("empty provenance");
        assert_eq!(empty.placement(), SssomCommentPlacement::AfterTable);
        assert_eq!(empty.kind(), SssomCommentKind::Provenance);
        assert_eq!(empty.raw_line(), "# #");
    }

    #[test]
    fn typed_set_comments_hard_fail_ambiguous_or_multiline_values() {
        assert_eq!(
            SssomSetComment::from_raw("not a comment", SssomCommentPlacement::AfterTable),
            Err(SssomCommentError::MissingMarker)
        );
        assert_eq!(
            SssomSetComment::from_raw("# ordinary", SssomCommentPlacement::BeforeTable),
            Err(SssomCommentError::AmbiguousBeforeTable)
        );
        assert_eq!(
            SssomSetComment::ordinary("  # changes kind"),
            Err(SssomCommentError::KindMismatch)
        );
        assert_eq!(
            SssomSetComment::ordinary("two\nlines"),
            Err(SssomCommentError::EmbeddedLineTerminator)
        );
        assert_eq!(
            SssomSetComment::provenance("two\rlines"),
            Err(SssomCommentError::EmbeddedLineTerminator)
        );
        assert_eq!(
            SssomSetComment::provenance_after_table("two\r\nlines"),
            Err(SssomCommentError::EmbeddedLineTerminator)
        );
    }

    #[test]
    fn mapping_set_comment_append_is_atomic() {
        let mut set = SssomMappingSet::new(SssomMeta::default(), Vec::new());
        set.append_provenance("accepted").expect("valid provenance");
        let accepted = set.set_comments.clone();

        let err = set
            .append_after_table_comment("bad\ncomment")
            .expect_err("multiline comment must fail");
        assert_eq!(err, SssomCommentError::EmbeddedLineTerminator);
        assert_eq!(set.set_comments, accepted, "failed append must not mutate");
    }

    #[test]
    fn column_layout_retains_order_and_rejects_invalid_names() {
        let layout = SssomColumnLayout::new(["object_id", "subject_id", "x_extension"])
            .expect("valid declared columns");
        assert_eq!(
            layout.columns(),
            &["object_id", "subject_id", "x_extension"]
        );
        assert!(!layout.is_inferred());
        assert!(SssomColumnLayout::default().is_inferred());
        assert_eq!(
            SssomColumnLayout::new(["subject_id", "subject_id"]),
            Err(SssomColumnLayoutError::DuplicateName(
                "subject_id".to_owned()
            ))
        );
        assert_eq!(
            SssomColumnLayout::new([""]),
            Err(SssomColumnLayoutError::EmptyName)
        );
        assert_eq!(
            SssomColumnLayout::new(["bad\tcolumn"]),
            Err(SssomColumnLayoutError::InvalidDelimiter(
                "bad\tcolumn".to_owned()
            ))
        );
    }

    #[test]
    fn parse_minimal_doc_fields() {
        let set = parse_tsv(CLEAN).expect("parse");
        assert_eq!(
            set.meta.mapping_set_id.as_deref(),
            Some("https://example.org/mappings/demo")
        );
        assert_eq!(set.meta.mapping_set_version.as_deref(), Some("0.1.0"));
        // The comment value is kept as authored (JSON-quoted), not unquoted.
        assert_eq!(set.meta.comment.as_deref(), Some("\"demo set\""));
        assert_eq!(
            set.meta.curie_map.get("ex").map(String::as_str),
            Some("https://example.org/vocab/")
        );
        assert_eq!(set.mappings.len(), 1);
        let m = &set.mappings[0];
        assert_eq!(m.subject_id, "ex:Foo");
        assert_eq!(m.predicate_id, "skos:closeMatch");
        assert_eq!(m.object_id, "sosa:Observation");
        assert_eq!(m.object_label.as_deref(), Some("Observation"));
        assert_eq!(m.mapping_justification, "semapv:ManualMappingCuration");
        assert_eq!(m.confidence, Some(0.7));
        assert_eq!(m.comment.as_deref(), Some("a note"));
    }

    #[test]
    fn parse_preserves_unknown_header_and_columns() {
        let doc = "\
# mapping_set_id: https://example.org/x
# creator_id: orcid:0000
# curie_map:
#   ex: https://example.org/vocab/
#   skos: http://www.w3.org/2004/02/skos/core#
#   semapv: https://w3id.org/semapv/vocab/
subject_id\tpredicate_id\tobject_id\tmapping_justification\tmapping_cardinality
ex:A\tskos:exactMatch\tex:B\tsemapv:ManualMappingCuration\t1:1
";
        let set = parse_tsv(doc).expect("parse");
        assert_eq!(
            set.meta.extra.get("creator_id").map(String::as_str),
            Some("orcid:0000")
        );
        assert_eq!(
            set.mappings[0]
                .extras
                .get("mapping_cardinality")
                .map(String::as_str),
            Some("1:1")
        );
        assert_eq!(
            set.column_layout.columns(),
            &[
                "subject_id",
                "predicate_id",
                "object_id",
                "mapping_justification",
                "mapping_cardinality"
            ]
        );
    }

    #[test]
    fn serialize_preserves_unknown_columns_roundtrip() {
        // A non-PurRDF SSSOM file carrying an extra column must survive
        // parse → serialize_tsv (lossless round-trip), not be silently dropped
        // because the column set is built only from SSSOM_ORDER (H-1).
        let doc = "\
# mapping_set_id: https://example.org/x
# curie_map:
#   ex: https://example.org/vocab/
#   skos: http://www.w3.org/2004/02/skos/core#
#   semapv: https://w3id.org/semapv/vocab/
subject_id\tpredicate_id\tobject_id\tmapping_justification\tmapping_cardinality
ex:A\tskos:exactMatch\tex:B\tsemapv:ManualMappingCuration\t1:1
";
        let set = parse_tsv(doc).expect("parse");
        let serialized = serialize_tsv(&set);
        assert!(
            serialized.contains("mapping_cardinality"),
            "extra column dropped on serialize:\n{serialized}"
        );
        let reparsed = parse_tsv(&serialized).expect("reparse");
        assert_eq!(
            reparsed.mappings[0]
                .extras
                .get("mapping_cardinality")
                .map(String::as_str),
            Some("1:1"),
            "extra column value lost on round-trip"
        );
    }

    #[test]
    fn diagnostic_line_survives_interleaved_comment() {
        // A `#` provenance comment between data rows must not shift the reported
        // line of a later row's diagnostic. Before M-1, a
        // flat offset ignored the filtered comment and reported the wrong line.
        let doc = "\
# mapping_set_id: https://example.org/x
# curie_map:
#   ex: https://example.org/vocab/
#   skos: http://www.w3.org/2004/02/skos/core#
#   semapv: https://w3id.org/semapv/vocab/
subject_id\tpredicate_id\tobject_id\tmapping_justification\tconfidence
ex:A\tskos:exactMatch\tex:B\tsemapv:ManualMappingCuration\t0.7
# interleaved provenance comment
ex:C\tskos:exactMatch\tex:D\tsemapv:ManualMappingCuration\tNOTNUM
";
        let err = parse_tsv(doc).unwrap_err();
        assert_eq!(err.code, "sssom-tsv-parse");
        assert!(err.message.contains("confidence"), "{}", err.message);
        // The bad row is the 9th source line; the interleaved comment (line 8)
        // must not shift the reported line back to 8.
        assert_eq!(
            err.location.as_ref().and_then(|loc| loc.line),
            Some(9),
            "reported line should be the bad row's true source line",
        );
    }

    #[test]
    fn parse_retains_exact_after_table_comments() {
        let doc = format!(
            "{CLEAN}#\n# ordinary trailer\n# # REFUSED ex:Bar —  exact spacing  \n# # provenance note\n"
        );
        let set = parse_tsv(&doc).expect("parse");
        assert_eq!(set.mappings.len(), 1, "trailer comments are not mappings");
        assert_eq!(set.set_comments.len(), 4);
        assert_eq!(set.set_comments[0].raw_line(), "#");
        assert_eq!(set.set_comments[0].kind(), SssomCommentKind::Ordinary);
        assert_eq!(set.set_comments[1].raw_line(), "# ordinary trailer");
        assert_eq!(
            set.set_comments[2].raw_line(),
            "# # REFUSED ex:Bar —  exact spacing  "
        );
        assert_eq!(set.set_comments[2].kind(), SssomCommentKind::Provenance);
        assert!(
            set.set_comments
                .iter()
                .all(|comment| comment.placement() == SssomCommentPlacement::AfterTable)
        );
    }

    #[test]
    fn parse_distinguishes_metadata_from_before_table_provenance() {
        let doc = "\
# mapping_set_id: https://example.org/x
# # generated by deterministic curation
# curie_map:
#   ex: https://example.org/vocab/
# # retained without closing curie_map
#   skos: http://www.w3.org/2004/02/skos/core#
subject_id\tpredicate_id\tobject_id
";
        let set = parse_tsv(doc).expect("parse");
        assert_eq!(
            set.meta.mapping_set_id.as_deref(),
            Some("https://example.org/x")
        );
        assert_eq!(
            set.meta.curie_map.get("skos").map(String::as_str),
            Some("http://www.w3.org/2004/02/skos/core#")
        );
        assert_eq!(set.set_comments.len(), 2);
        assert_eq!(
            set.set_comments[0].raw_line(),
            "# # generated by deterministic curation"
        );
        assert_eq!(
            set.set_comments[1].raw_line(),
            "# # retained without closing curie_map"
        );
        assert!(
            set.set_comments
                .iter()
                .all(|comment| comment.placement() == SssomCommentPlacement::BeforeTable)
        );
    }

    #[test]
    fn parse_retains_zero_row_layout_and_trailing_envelope() {
        let doc = "\
# mapping_set_id: https://example.org/empty
object_id\tx_extension\tsubject_id
# empty mapping-set note
";
        let set = parse_tsv(doc).expect("parse");
        assert!(set.mappings.is_empty());
        assert_eq!(
            set.column_layout.columns(),
            &["object_id", "x_extension", "subject_id"]
        );
        assert_eq!(set.set_comments.len(), 1);
        assert_eq!(set.set_comments[0].raw_line(), "# empty mapping-set note");
        assert_eq!(
            set.set_comments[0].placement(),
            SssomCommentPlacement::AfterTable
        );
    }

    #[test]
    fn parse_rejects_duplicate_columns_at_header_line() {
        let doc = "\
# mapping_set_id: https://example.org/x
subject_id\tsubject_id\tobject_id
";
        let err = parse_tsv(doc).expect_err("duplicate columns must fail");
        assert_eq!(err.code, "sssom-tsv-parse");
        assert!(err.message.contains("duplicate"), "{}", err.message);
        assert_eq!(err.location.as_ref().and_then(|loc| loc.line), Some(2));
    }

    #[test]
    fn parse_rejects_headerless_doc() {
        let err = parse_tsv("# only: comments\n# more: comments\n").unwrap_err();
        assert_eq!(err.code, "sssom-tsv-parse");
    }

    #[test]
    fn parse_rejects_inline_curie_map_flow_sequence() {
        // The `unparseable-bad-yaml-curie-map` negative: an inline `[unclosed`
        // value sssom-py reported as a FATAL parse error.
        let doc = "\
# mapping_set_id: https://example.org/broken
# curie_map: [unclosed
subject_id\tpredicate_id\tobject_id
ex:A\tskos:exactMatch\tex:B
";
        let err = parse_tsv(doc).unwrap_err();
        assert_eq!(err.code, "sssom-tsv-parse");
    }

    #[test]
    fn roundtrip_serialize_is_stable() {
        let set = parse_tsv(CLEAN).expect("parse");
        let serialized = serialize_tsv(&set);
        let reparsed = parse_tsv(&serialized).expect("reparse");
        assert_eq!(set, reparsed, "parse ∘ serialize must be stable");
        // And serializing the reparse is byte-identical (fixed point).
        assert_eq!(serialized, serialize_tsv(&reparsed));
    }

    #[test]
    fn serialize_preserves_mixed_envelope_and_normalizes_crlf() {
        let doc = concat!(
            "# mapping_set_id: https://example.org/empty\r\n",
            "# # curated —  exact spacing  \r\n",
            "object_id\tx_extension\tsubject_id\r\n",
            "#\r\n",
            "# #\r\n",
            "# mapping_set_version: trailer prose, not metadata\r\n",
            "# duplicate\r\n",
            "# duplicate\r\n",
        );
        let expected = concat!(
            "# mapping_set_id: https://example.org/empty\n",
            "# # curated —  exact spacing  \n",
            "object_id\tx_extension\tsubject_id\n",
            "#\n",
            "# #\n",
            "# mapping_set_version: trailer prose, not metadata\n",
            "# duplicate\n",
            "# duplicate\n",
        );

        let set = parse_tsv(doc).expect("parse CRLF envelope");
        assert_eq!(set.meta.mapping_set_version, None);
        assert_eq!(set.set_comments.len(), 6);
        assert_eq!(serialize_tsv(&set), expected);

        let reparsed = parse_tsv(expected).expect("reparse canonical LF");
        assert_eq!(set, reparsed);
        assert_eq!(serialize_tsv(&reparsed), expected);
    }

    #[test]
    fn typed_append_apis_emit_canonical_envelope_positions() {
        let meta = SssomMeta {
            mapping_set_id: Some("https://example.org/programmatic".to_owned()),
            ..SssomMeta::default()
        };
        let mapping = SssomMapping {
            subject_id: "ex:A".to_owned(),
            predicate_id: "skos:exactMatch".to_owned(),
            object_id: "ex:B".to_owned(),
            mapping_justification: "semapv:ManualMappingCuration".to_owned(),
            ..SssomMapping::default()
        };
        let mut set = SssomMappingSet::new(meta, vec![mapping]);
        set.append_provenance("origin — deterministic")
            .expect("valid before-table provenance");
        set.append_after_table_comment("plain trailer")
            .expect("valid ordinary trailer");
        set.append_after_table_provenance("tail provenance")
            .expect("valid trailer provenance");

        let expected = concat!(
            "# mapping_set_id: https://example.org/programmatic\n",
            "# # origin — deterministic\n",
            "subject_id\tpredicate_id\tobject_id\tmapping_justification\tconfidence\tcomment\n",
            "ex:A\tskos:exactMatch\tex:B\tsemapv:ManualMappingCuration\t\t\n",
            "# plain trailer\n",
            "# # tail provenance\n",
        );
        assert_eq!(serialize_tsv(&set), expected);
    }

    #[test]
    fn retained_layout_appends_new_fields_deterministically() {
        let doc = concat!(
            "# mapping_set_id: https://example.org/layout\n",
            "object_id\tx_extension\tsubject_id\n",
            "ex:B\toriginal\tex:A\n",
        );
        let mut set = parse_tsv(doc).expect("parse retained layout");
        let mapping = &mut set.mappings[0];
        mapping.predicate_id = "skos:exactMatch".to_owned();
        mapping.comment = Some("new comment".to_owned());
        mapping.extras.insert("z_added".to_owned(), String::new());
        mapping
            .extras
            .insert("a_added".to_owned(), "first".to_owned());

        let serialized = serialize_tsv(&set);
        let mut table_lines = serialized.lines().filter(|line| !line.starts_with('#'));
        assert_eq!(
            table_lines.next(),
            Some("object_id\tx_extension\tsubject_id\tpredicate_id\tcomment\ta_added\tz_added")
        );
        assert_eq!(
            table_lines.next(),
            Some("ex:B\toriginal\tex:A\tskos:exactMatch\tnew comment\tfirst\t")
        );
    }

    #[test]
    fn set_comments_are_validation_and_rdf_inert() {
        let base = parse_tsv(CLEAN).expect("parse");
        let expected_diagnostics = validate(&base);
        let expected_quads = to_rdf(&base);

        let mut commented = base;
        commented
            .append_provenance("audit provenance")
            .expect("valid provenance");
        commented
            .append_after_table_comment("human note")
            .expect("valid comment");

        assert_eq!(validate(&commented), expected_diagnostics);
        assert_eq!(to_rdf(&commented), expected_quads);
    }

    #[test]
    fn validate_clean_doc_has_no_errors() {
        let set = parse_tsv(CLEAN).expect("parse");
        assert!(validate(&set).is_empty());
    }

    #[test]
    fn validate_flags_unknown_prefix() {
        let set = parse_tsv(&negative(
            "nope:Foo\tskos:closeMatch\tsosa:Observation\tsemapv:ManualMappingCuration\t0.7\tx\n",
        ))
        .expect("parse");
        let diags = validate(&set);
        let prefix: Vec<_> = diags
            .iter()
            .filter(|d| d.check == "PrefixMapCompleteness")
            .collect();
        assert_eq!(prefix.len(), 1);
        assert_eq!(prefix[0].code, "prefix validation");
        assert_eq!(prefix[0].message, "Missing prefix: nope");
        assert_eq!(prefix[0].severity, RdfSeverity::Error);
    }

    #[test]
    fn validate_flags_confidence_too_high() {
        let set = parse_tsv(&negative(
            "ex:A\tskos:closeMatch\tsosa:Observation\tsemapv:ManualMappingCuration\t1.5\tx\n",
        ))
        .expect("parse");
        let diags = validate(&set);
        let js: Vec<_> = diags.iter().filter(|d| d.check == "JsonSchema").collect();
        assert_eq!(js.len(), 1);
        assert_eq!(js[0].code, "jsonschema validation");
        assert!(
            js[0].message.contains("greater than the maximum of 1.0"),
            "{}",
            js[0].message
        );
    }

    #[test]
    fn validate_flags_confidence_negative() {
        let set = parse_tsv(&negative(
            "ex:A\tskos:closeMatch\tsosa:Observation\tsemapv:ManualMappingCuration\t-0.5\tx\n",
        ))
        .expect("parse");
        let diags = validate(&set);
        let js: Vec<_> = diags.iter().filter(|d| d.check == "JsonSchema").collect();
        assert_eq!(js.len(), 1);
        assert!(
            js[0].message.contains("less than the minimum of 0.0"),
            "{}",
            js[0].message
        );
    }

    #[test]
    fn validate_flags_missing_required_slot() {
        // ENHANCEMENT: sssom-py silently drops this row; we flag it.
        let set = parse_tsv(&negative(
            "\tskos:closeMatch\tsosa:Observation\tsemapv:ManualMappingCuration\t0.7\tx\n",
        ))
        .expect("parse");
        let diags = validate(&set);
        let req: Vec<_> = diags.iter().filter(|d| d.check == "RequiredSlot").collect();
        assert_eq!(req.len(), 1);
        assert_eq!(req[0].code, "required slot");
        assert!(req[0].message.contains("subject_id"), "{}", req[0].message);
    }

    #[test]
    fn to_rdf_emits_owl_reification_for_a_mapping() {
        let set = parse_tsv(CLEAN).expect("parse");
        let quads = to_rdf(&set);
        assert!(!quads.is_empty());

        let has = |pred: &str, obj: &str| {
            quads.iter().any(|q| {
                q.predicate == pred && matches!(&q.object, RdfTerm::Iri(iri) if iri == obj)
            })
        };
        // CURIEs are resolved to full IRIs via the curie_map.
        assert!(has(RDF_TYPE, OWL_AXIOM));
        assert!(has(OWL_ANNOTATED_SOURCE, "https://example.org/vocab/Foo"));
        assert!(has(
            OWL_ANNOTATED_PROPERTY,
            "http://www.w3.org/2004/02/skos/core#closeMatch"
        ));
        assert!(has(
            OWL_ANNOTATED_TARGET,
            "http://www.w3.org/ns/sosa/Observation"
        ));
        // Confidence is an xsd:double literal.
        assert!(quads.iter().any(|q| {
            q.predicate == format!("{SSSOM_NS}confidence")
                && matches!(
                    &q.object,
                    RdfTerm::Literal(l) if l.datatype.as_deref() == Some(XSD_DOUBLE)
                )
        }));
    }

    #[test]
    fn corpus_accessibility_parses_and_validates_clean() {
        // The committed corpus file is the parity anchor: parse must succeed and
        // validate must yield zero ERRORs (full 66-file parity is covered by the
        // Python parity test, Task 7). Path is resolved relative to this crate's
        // manifest dir up to the repo root.
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../generated/mappings/gmeow-accessibility.sssom.tsv"
        );
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read corpus file {path}: {e}"));
        let set = parse_tsv(&text).expect("corpus parse");
        assert!(
            set.mappings.len() >= 10,
            "corpus rows: {}",
            set.mappings.len()
        );
        let diags = validate(&set);
        assert!(
            diags.iter().all(|d| d.severity != RdfSeverity::Error),
            "corpus must validate clean, got: {diags:?}"
        );
    }
}
